### ISSUE TITLE
Add async calls inside custom ExpandRow renderer

### ISSUE THREAD

**Issue by ronaiza-cardoso** [react-bootstrap-table/react-bootstrap-table2#1001]
There's a way of making async calls inside custom expand row renderer?

**Comment by jendamozna** [comment]
Hi, try using this:
onExpand={this.handleOnExpand}
expandRenderer={this.expandRenderer}

    handleOnExpand= (row, isExpand, rowIndex, e) => {
        if (
            isExpand &&
            this.state.expands.filter(a => a.id === row.id).length === 0
        ) {
            this.loadDetails(row.id);
        }
    };

    expandRenderer = row => {
        const hit = this.state.expands.filter(a => a.id === row.id);
        if (hit.length === 0) {
            return Loading
        }
       return hit.anything
}

**Comment by ronaiza-cardoso** [comment]
Here?

**Comment by AllenFang** [comment]
@jendamozna good sharing

**Comment by CACDX** [comment]
Hi ! There are other way? Because I use functional component, and I make a request for each row for get data, I tried with hook and figure out in a loop infinite, never finish and throw a request limit.

**Comment by fffaria** [comment]
> Hi ! There are other way? Because I use functional component, and I make a request for each row for get data, I tried with hook and figure out in a loop infinite, never finish and throw a request limit.

Did you manage to solve this problem?
