### ISSUE TITLE
Sort test failing on master branch

### ISSUE THREAD

**Issue by james-s-turner** [react-bootstrap-table/react-bootstrap-table2#1002]
FYI - Just checked out latest master branch and ran tests. I see the following failure in a sort test.

<img width="688" alt="Screenshot 2019-07-09 at 10 53 01" src="https://user-images.githubusercontent.com/1702747/60878758-48842980-a238-11e9-99c4-a17fd9d9f3cb.png">

**Comment by AllenFang** [comment]
@james-s-turner it's work for me in my local env.


bellow is newest commit everything is green:

<img width="1077" alt="螢幕快照 2019-07-13 下午1 32 44" src="https://user-images.githubusercontent.com/5351390/61167515-eba7ac80-a572-11e9-885c-2a32b2ca5504.png">
