### ISSUE TITLE
Cell Edit default saves value as string how do I  save a number?

### ISSUE THREAD

**Issue by bcobra** [react-bootstrap-table/react-bootstrap-table2#1004]
When I edit a number cell and add a new number the value is saved as a string to my state. is there a way to save as a number by default?

**Comment by AllenFang** [comment]
@bcobra so far we don't allow you to save value with other type, I will implement it soon, thank you

**Comment by bcobra** [comment]
thanks for your support and dedication to this awesome product.

**Comment by AllenFang** [comment]
@bcobra upgrade `react-bootstrap-table-next` and `react-bootstrap-table2-editor` to newest version and you can use [`column.type`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columntype-string) to specify the type after saving cell
