### ISSUE TITLE
Filters in a separate row for better styling

### ISSUE THREAD

**Issue by nordicbondpricing** [react-bootstrap-table/react-bootstrap-table2#1005]
Hi

I think it would be nice if filters could have their own row, as it would make styling/positioning nicer. This is how it looks in our old version, where we use https://datatables.net/. 

![image](https://user-images.githubusercontent.com/16350531/61106717-3f849980-a47e-11e9-84b4-375b84546f57.png)

Notice that the textboxes are in a separate row. This means that, even if the titles wrap over multiple lines, all the textboxes align nicely.

Here is the same section implemented in react-bootstrap table

![image](https://user-images.githubusercontent.com/16350531/61106894-c0dc2c00-a47e-11e9-8d12-1ebc6863c34d.png)

As you can see the textbox for the second column is not aligned with the rest. 

The jQuery datatables plugin uses a tfoot section for the filter row.

![image](https://user-images.githubusercontent.com/16350531/61107015-1adcf180-a47f-11e9-9796-77f032de25a9.png)

just an idea. Do you think it would require a lot of work?

**Comment by jendamozna** [comment]
did you try header formatter an display flex?

**Comment by nordicbondpricing** [comment]
Hi @jendamozna . Do you mean something like this?

![image](https://user-images.githubusercontent.com/16350531/61125877-3f4ec300-a4ab-11e9-9fa3-ee1e70cdf395.png)

**Comment by AllenFang** [comment]
`headerFormatter` is a way to custom the header, I think it's not a good solution for @nordicbondpricing 's  requirement. So far we don't have this feature and it's minor for me to implement it, so PR is welcome.

**Comment by ptah23** [comment]
Has anyone picked this up? if not, i can give it a go

**Comment by nordicbondpricing** [comment]
Hi @ptah23 , that would be awesome! I haven't had the time to look at it unfortunately

**Comment by AllenFang** [comment]
@ptah23 PR is welcome

**Comment by aliogaili** [comment]
I think this is really good to have, the clutter in the table header when the filters are enabled make the filters not very usable.

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/11/09/version-bump.html)

Now you can apply `filterPosition` on `BootstrapTable` -> https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#filterposition-string

**Comment by nordicbondpricing** [comment]
Tanks a bunch @aliogaili  and @AllenFang. Much appreciated!
