### ISSUE TITLE
column sort icons dont appear when use with bootstrap4

### ISSUE THREAD

**Issue by amjad489** [react-bootstrap-table/react-bootstrap-table2#1008]
Hi,

I'm facing issue where bootstrap table doesn't show up the sort icon on the table when using with bootstrap4. however it works when I use bootstrap3.

Following is the code.
```html
<div>
                    <Header/>
                    <div className="container-fluid">
                        <br></br>
                        <div>
                            <BootstrapTable
                                bootstrap4
                                striped
                                hover
                                keyField='InstanceId'
                                data={ this.state.inventory }
                                columns={ this.state.columns }
                                filter={ filterFactory() }
                                pagination={ paginationFactory() }/>
                        </div>
                    </div>
                </div>
```

**`Screenshot`**:
![image](https://user-images.githubusercontent.com/20831862/61128018-efc7c180-a4c1-11e9-9bb6-7abce54d3d42.png)

**`package.json`**:
```
 "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1",
    "react-router-dom":"^5.0.1",
    "reactstrap":"^8.0.1",
    "bootstrap":"^4.3.1",
    "jquery": "^3.4.1",
    "popper.js":"^1.15.0",
    "react-bootstrap-table-next":"^3.1.5",
    "react-bootstrap-table2-filter":"^1.1.10",
    "react-bootstrap-table2-paginator":"^2.0.7"
```

**Comment by AllenFang** [comment]
hello @amjad489 in live [demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Bootstrap%204&selectedStory=Sort%20table%20with%20bootstrap%204&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) it's work with newest version. 

In addition, I also test for `bootstrap@4.3.1` and everything work well.  Please check again in your project and if the issue still remain, just create a online example on `codesandbox` to reproduce it, thanks

**Comment by AmjadHussainSyed** [comment]
Hi @AllenFang,

thanks for responding. I have reproduced the issue. please check the sandbox link
https://codesandbox.io/embed/ecstatic-napier-8xjxf

I really appreciate the work you're doing and taking time to contribute.

Thanks in advance.
Amjad

**Comment by amjad489** [comment]
Hi @AllenFang,

thanks for responding. I have reproduced the issue. please check the `codesandbox` link
https://codesandbox.io/embed/ecstatic-napier-8xjxf

I really appreciate the work you're doing and taking time to contribute.

Thanks in advance.
Amjad

**Comment by amjad489** [comment]
here's another simple `codesandbox` and the sort column icons missing here.
https://codesandbox.io/embed/affectionate-antonelli-d7rht

Please check there seems to be something missing where its working for you and not for me :).
**`dependencies`**
```
"dependencies": {
    "bootstrap": "4.3.1",
    "react": "16.8.6",
    "react-bootstrap-table-next": "3.1.5",
    "react-dom": "16.8.6",
    "react-scripts": "3.0.1"
  },
```
