### ISSUE TITLE
Question: How do I reset the search filter programatically?

### ISSUE THREAD

**Issue by djlsw** [react-bootstrap-table/react-bootstrap-table2#1009]
@AllenFang First off thank you for the awesome work you have done. I am trying to reset the search filter text programatically and have been struggling. I am successfully using a ref to retrieve the table object (shown below). I have also read on several posts to call the handleSearch('') function but I cannot figure out how to do that. Is that still the recommended way? Any help would be appreciated.

![image](https://user-images.githubusercontent.com/5903093/61171576-a1f59c80-a547-11e9-9003-9de4d39bde72.png)

**Comment by djlsw** [comment]
Hi again,
I figured out how to do this. Finally realized I needed to get a Ref to the SearchBar to get access to the props and then call OnSearch() from there. Thank you!

**Comment by AllenFang** [comment]
@djlsw sorry for lately reply and your finding is correct

I put some reference here in case someone have the same question:
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Text%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

thanks
