### ISSUE TITLE
column sort icons dont appear when use with bootstrap4

### ISSUE THREAD

**Issue by amjad489** [react-bootstrap-table/react-bootstrap-table2#1010]
this issue is in regards to the reference https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1008

I'm still facing the issue and able to reproduce.

following are the example sandbox to see the issue.
https://codesandbox.io/embed/affectionate-antonelli-d7rht
another sandbox
https://codesandbox.io/embed/ecstatic-napier-8xjxf
Please check there seems to be something missing where its working for you and not for me :).
**`dependencies`**

```"dependencies": {
    "bootstrap": "4.3.1",
    "react": "16.8.6",
    "react-bootstrap-table-next": "3.1.5",
    "react-dom": "16.8.6",
    "react-scripts": "3.0.1"
  }```

**Comment by mouerrr** [comment]
Hi @amjad489 please also yo need to import:
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css'

**Comment by amjad489** [comment]
@mouerrr thanks is working perfectly.
