### ISSUE TITLE
Change sizePerPage's position

### ISSUE THREAD

**Issue by ronaklalwaniii** [react-bootstrap-table/react-bootstrap-table2#1011]
Hello, how can i move sizePerPage filter on top and keep pagination on bottom like in attached image ?
![question](https://user-images.githubusercontent.com/44769573/61199245-d52c5d00-a6fa-11e9-8b35-6e7855e0a06c.PNG)

**Comment by AllenFang** [comment]
@ronaklalwaniii sorry for lately reply, I think standalone component will help you:

check [docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#41-use-standalone-component)

[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20SizePerPage%20Dropdown&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) are couple pagination examples
