### ISSUE TITLE
Force column re rendering

### ISSUE THREAD

**Issue by AntoineCAMILLE** [react-bootstrap-table/react-bootstrap-table2#1012]
Hello, i'm trying to implement a fixed header and scrollable body. The whole thing is that i change the width of each columns compared to the width of the window (xs, sm, md, lg. Same as bootstrap works)
It works well except when the window width changes, the header re render but not the columns it leads to alignment problem between the header and the body
Is there a way to force re rendering of column ?
(Sorry my english isn't perfect, hope that you understand the problem)

**Comment by Extazx2** [comment]
New to react, but I guess you could just trigger a render with 
https://developer.mozilla.org/fr/docs/Web/API/Window/onresize ?

**Comment by AntoineCAMILLE** [comment]
@Extazx2 I already do like that it's not the problem
i catch the resize event but when i order to my columns to resize (in function of the screen size) only the header is taking the new size
The columns don't render again, i have to trigger a page change to make the columns taking the right size

**Comment by AllenFang** [comment]
@AntoineCAMILLE sorry for lately reply, I still don't have enough time to implement the fixed header feature. Any PR is welcome.

If the issue still remain, please post your code on codesandbox then I can help you to debug, thanks
