### ISSUE TITLE
Pagination & total 

### ISSUE THREAD

**Issue by Extazx2** [react-bootstrap-table/react-bootstrap-table2#1013]
Hello,

I have trouble understanding how the pagination works.
I work with firebase and to avoid many useless reads, I want to implement custom "page change".

I have a counter (at the time of my example : 39) in my database, that i collect, telling me how many docs I have, and i go through them 20 by 20 on each page (supposedly) instead of loading the whole firebase collection and let the table do the pagination itself.

Here is my table : 
![image](https://user-images.githubusercontent.com/9135968/61218635-c2258700-a712-11e9-80ab-0f5a2c23a233.png)

Here is the screen of my react dev tools
![pagination_react_dev_tools](https://user-images.githubusercontent.com/9135968/61218802-28aaa500-a713-11e9-9f0b-d809647451e2.png)

Here is my code : 
```javascript
        let options = {
            totalSize: nbCandidates,
            showTotal: true,
        };
        console.log(typeof nbCandidates);
        console.log(options);
        console.log(paginationFactory(options));
        if(candidates){
            return (<BootstrapTable keyField='cid'
                                    data={candidates}
                                    columns={columns}
                                    pagination={paginationFactory({...options})}/>);
        }
```

The thing is : if in the options, i change `totalSize: nbCandidates` to `totalSize: 39` I will have 4 pages in my list (which is ok, because there is 10 rows per pages, 39 rows total.

output of `console.log(typeof nbCandidates);` is "number"

**Comment by AllenFang** [comment]
@Extazx2 I can't understand what kind of issue you faced, would you please clearify this your question again?  It will be better to put your example code to codesandbox and keep it simple and minimal so that I can reproduce your issue, thanks

I will reopen it when I can identify this issue.

**Comment by AllenFang** [comment]
@Extazx2 I think it's gonna be happen and I can not reproduce it. So If ok, please give me an example on codesandbox so that I can reproduce it. 

BTW, in you case, actually you don't need to set the `totalSize`, you can check the doc: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationtotalsize-number

**Comment by Extazx2** [comment]
@AllenFang as my back end is connected to firebase, i'll try to open a new sample project and do this.

**Comment by Tana00** [comment]
@Extazx2 I have this same issue. Please how did you resolve it?
