### ISSUE TITLE
Body columns not updated when hideSelectColumn value changes

### ISSUE THREAD

**Issue by danAtAllworx** [react-bootstrap-table/react-bootstrap-table2#1014]
To reproduce:

Implement a simple table with selectRow.hideSelectColumn set based on React state data.

What should be:

When state changes, the table should update to show or hide the select column.

What is:

When state changes, the header of the table updates, but the body doesn't. Clicking on the individual rows and repeatedly hiding / showing the select column produces very strange behavior.

Live example: https://codesandbox.io/s/react-codesandbox-dbf6w

**Comment by AllenFang** [comment]
@danAtAllworx  please upgrade all packages to newest version and you will get the patch, thanks
