### ISSUE TITLE
Pass rowIndex to expandedArea

### ISSUE THREAD

**Issue by imtmh** [react-bootstrap-table/react-bootstrap-table2#1015]
Sorry, first of all, this is not an issue.

I would like to know if there is a way to pass the row index to the expandedArea renderer.
P.S. I tried adding the index to the data before passing the data prop to ToolkitProvider, but it doesn't work when I sort the table. It will work on the first load but not after sorting.

**Comment by AllenFang** [comment]
@imtmh I can add it to the function of `expandRow.renderer`:

```js
const expandRow = {
  renderer: (row, rowIndex) => (
    ...
  )
};
```

**Comment by AllenFang** [comment]
@imtmh please upgrade all packages to newest version and you will get the patch, thanks

**Comment by imtmh** [comment]
Thanks for the fix, I will upgrade the packages and check it.
