### ISSUE TITLE
Can nextPageText or prePageText be replaced with custom icon?

### ISSUE THREAD

**Issue by sujitykulkarni** [react-bootstrap-table/react-bootstrap-table2#1017]
Currently nextPageText and prevPageText are limited to string values. 

Would like to know if there's a way of using any custom icon (e.g. font-awesome's chevron-left/right or a custom SVG icon) ?

**Comment by AllenFang** [comment]
@sujitykulkarni so far we didn't provide a good way to just replace the text as an icon or something else.  But there's a workaround is using `pageButtonRenderer` to custom the page button 


https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationpagebuttonrenderer-function

Let me know if it's not helpful to u, thanks
