### ISSUE TITLE
How to use an icon (custom html) in column header text?

### ISSUE THREAD

**Issue by allencoded** [react-bootstrap-table/react-bootstrap-table2#1018]
I am needing to use an icon as my column text and not just plain text.

`columns = [{ dataField: 'required', text: '<i className="custom-icon" /> ', sort: true }]`

How does one use html in columns headers I couldn't find anything in the docs?

**Comment by sujitykulkarni** [comment]
You can use `formatter` function. It has ability to return a JSX element, so in your case you can return the `<i className="custom-icon" />` and use it.

Docs:
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function

**Comment by AllenFang** [comment]
thanks @sujitykulkarni !
