### ISSUE TITLE
Selecting a single row selects all rows

### ISSUE THREAD

**Issue by greygatch** [react-bootstrap-table/react-bootstrap-table2#1019]
Using the most [basic Storybook example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Multiple%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), and the component doesn't work.

Other "solutions" to similar issues are nonsensical.

```
const selectRow = {
  mode: 'radio',
  clickToSelect: true
};

<BootstrapTable
  keyField='id'
  data={ search.results }
  columns={ columns }
  selectRow={ selectRow }
/>
```

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#keyfield-required-string

here we mention it should be required and it might not very clear about "unique", I will enhance the docs, thanks
