### ISSUE TITLE
How can we style expanded row with a class??? 

### ISSUE THREAD

**Issue by maxsilvauk** [react-bootstrap-table/react-bootstrap-table2#1020]
I cant seem to style a clicked row or an expanded row with a class? How is this possible?

**Comment by AllenFang** [comment]
I think upgrade to newest version and you can use [`parentClassName `](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowparentclassname-string-function)

**Comment by maxsilvauk** [comment]
Thank-you @AllenFang
