### ISSUE TITLE
Warning: Failed prop type: The prop `column.text` is marked as required in `HeaderCell`, but its value is `undefined`.

### ISSUE THREAD

**Issue by liordino** [react-bootstrap-table/react-bootstrap-table2#1022]
Hi folks,

I recently started using your component and so for it worked like a charm and was very easy to integrate into my code. Thanks and keep up the good work!

Now, today I faced the following issue: I'm using react-bootstrap-table2 along with reactstrap, inserting a table into a modal to edit some stuff, in a master-slave fashion. The edits are made in the table itself, and in a field that should be numeric, greater than 0 and smaller or equal to 1 I've added a validator. Problem is: if I try to edit a cell where this validator is applied and set an invalid value  (for example, 2, or 'a'), it closes the modal just after showing the error message, and gives me the following error in the console:

>Warning: Failed prop type: The prop `column.text` is marked as required in `HeaderCell`, but its value is `undefined`.
>    in HeaderCell (created by Header)
>    in Header (created by BootstrapTable)
>    in table (created by BootstrapTable)
>    in div (created by BootstrapTable)
>    in BootstrapTable (created by Context.Consumer)
>    in PaginationDataProvider (created by Context.Consumer)
>    in SortProvider (created by Context.Consumer)
>    in SearchProvider (created by Context.Consumer)
>    in DataProvider (created by BootstrapTableContainer)
>    in BootstrapTableContainer (at Forms.js:171)
>    in div (at Forms.js:166)
>    in ToolkitProvider (created by Toolkitprovider)
>    in Toolkitprovider (at Forms.js:159)
>    in div (at Forms.js:155)
>    in Forms (created by Route)
>    in Route (at App.js:18)
>    in div (at Layout.js:13)
>    in div (at Layout.js:11)
>    in Layout (at App.js:16)
>    in App (at src/index.js:18)
>    in Router (created by BrowserRouter)
>    in BrowserRouter (at src/index.js:17)
Here's the relevant code:
```javascript
const weightValidator = (newValue, row, column) => {
    if (isNaN(newValue)) {
        return {
            valid: false,
            message: 'Peso deve ser numérico'
        };
    }
    if (newValue <= 0) {
        return {
            valid: false,
            message: 'Peso deve ser maior do que 0'
        };
    }
    if (newValue > 1) {
        return {
            valid: false,
            message: 'Peso deve ser menor ou igual a 1'
        };
    }

    return true;
}

const formsItemsColumns = [
    { dataField: 'number', text: '#', sort: true, editable: false },
    { dataField: 'description', text: 'Descrição' },
    { dataField: 'weight', text: 'Peso', validator: weightValidator },
    { dataField: 'actions', formatter: formsItemsActionsFormatter, editable: false },
];

<Modal centered={true} size="lg" isOpen={this.state.modalAddEdit} className={this.props.className}>
    <ModalHeader toggle={this.toggleAddEdit} close={closeBtn}>Formulário</ModalHeader>
    <ModalBody>
        <Form>
            <FormGroup row>
                <Label for="formName" sm={2}>Nome</Label>
                <Col sm={10}>
                    <Input name="form" id="formName" />
                </Col>
            </FormGroup>
            <FormGroup row>
                <Label for="formCode" sm={2}>Código</Label>
                <Col sm={10}>
                    <Input name="code" id="formCode" />
                </Col>
            </FormGroup>
            <div className="d-sm-flex align-items-center justify-content-between mb-4">
                <h3 className="h3 mb-0 text-gray-800">Items</h3>
            </div>
            <Button className="float-right btn btn-success btn-circle btn-sm mb-1">
                <i className="fas fa-plus" />
            </Button>
            <BootstrapTable
                BootstrapTable
                bootstrap4
                bordered={false}
                hover
                condensed
                keyField='id'
                columns={formsItemsColumns}
                data={forms[0].items}
                expandRow={expandFormsItemsRow}
                noDataIndication="Não há dados"
                cellEdit={cellEditFactory({ mode: 'dbclick' })} />
        </Form>
    </ModalBody>
    <ModalFooter>
        <Button color="success">Salvar</Button>
        <Button color="danger" onClick={this.toggleAddEdit}>Cancelar</Button>
    </ModalFooter>
</Modal>
```
I tried to create a custom input field but got the same error (just without the error message from the validator).

Any help would be greatly appreciated!

Cheers!

**Comment by AllenFang** [comment]
@liordino sorry for lately reply,

```js
const formsItemsColumns = [
    { dataField: 'number', text: '#', sort: true, editable: false },
    { dataField: 'description', text: 'Descrição' },
    { dataField: 'weight', text: 'Peso', validator: weightValidator },
    { dataField: 'actions', formatter: formsItemsActionsFormatter, editable: false },
];
```
i think this issue is irrelevant to cell editing, but is just missing [`column.text`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columntext-required-string) for last column, because it is required.

Do let me know if above answer can not help you


BTW, the last column in your table is just a action column, so I encourage to set `column. isDummyField` as true

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnisdummyfield-bool

[`online example`](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Dummy%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by liordino** [comment]
Hi @AllenFang ! Thanks for your reply!

I tried your suggestion, and while the error that was being logged in the console doesn't occur anymore (in fact no errors are displayed in the console as off now) the behaviour is still the same: after setting an invalid value in a field that has an associated validator it shows the error message and shortly after that closes the modal. If I set a valid value, the model keeps opened. Here's a GIF showing what happens (first the behaviour with a valid value, and them with an invalid one):

![Alt text](https://media.giphy.com/media/hvdrUpPXQ6BDh04M8f/giphy.gif)

Notice that as soon as the error appears bellow the input, the modal in which the table resides is closed.

I'm new to web development, but could this be happening because of a form submission anywhere?

Thanks again!

**Comment by AllenFang** [comment]
@liordino I think it's not a bug directly with `react-bootstrap-table` but if ok, would you please give me a simple and minimal example on codesandbox so that I can help you to debug, thanks.

[here](https://codesandbox.io/s/k5750vzzvv) is an example you can start, but just remember to change the dependency version, thanks

**Comment by liordino** [comment]
Hi @AllenFang !

It was indeed a form submission, so nothing directly related to `react-bootstrap-trable`. Thank you so much for your help!
