### ISSUE TITLE
Expand header cell size is 30px

### ISSUE THREAD

**Issue by mbystryantsev** [react-bootstrap-table/react-bootstrap-table2#1024]
Chrome 75.0.3770.142 (64-bit)
react-bootstrap-table-next 3.1.7

Expand row header cell has attribute `data-row-selection="true"` that limited it size to 30px.
```
.react-bootstrap-table th[data-row-selection] {
  width: 30px; }
```

```
const expandRow = {
	renderer: row => (
		<div>Test</div>
	),
	showExpandColumn: true,
	expandByColumnOnly: true,
	onlyOneExpanding: true,
	expandColumnPosition: 'right',
	expandColumnRenderer: ({ expanded, rowKey, expandable }) => (
		<>Show</>
	),
	expandHeaderColumnRenderer: ({ isAnyExpands }) => (
		<>Log</>
	)
}
```

![image](https://user-images.githubusercontent.com/1485514/61725235-11edf900-ad78-11e9-80cc-9c3516d5f349.png)

**Comment by AllenFang** [comment]
@mbystryantsev do you want to ... have more space for expand column?

**Comment by gilgenbergg** [comment]
@AllenFang not sure about the author of this issue, but I have such problem :) is this possible to  make expand column wider? Because I`ve tried to customize expandHeaderColumnRenderer returning the <div> block with inline style={{width: *some percentage*}} and it is still the size of "plus" sign... Thanks in advance!

**Comment by emresimsk** [comment]
@mbystryantsev 

table.react-bootstrap-table tbody tr td:nth-child(last index) {
  width: 30px
}

you can try it

**Comment by AllenFang** [comment]
thanks @emresimsk  ,,, @mbystryantsev do let me know if this issue still remain, thanks

**Comment by kevindekemele** [comment]
@emresimsk  this doesn't work. I've even added it to index.css in a create-react-app.
I would also like to increase the width
