### ISSUE TITLE
Styling entire sorted column

### ISSUE THREAD

**Issue by chikeorjih** [react-bootstrap-table/react-bootstrap-table2#1026]
I see that there are ways to style and add classes the <th> of a sorted column. Is there a way to do this for all the <td>s in that column. I think it would be beneficial from a UX standpoint

**Comment by AllenFang** [comment]
> Is there a way to do this for all the s in that column

I can not understand this....

**Comment by chikeorjih** [comment]
Sorry i meant to say all the TD's. The tablet headers have a class but I think it would be be beneficial to apply that class to all the <td>'s in the Same calumn

**Comment by AllenFang** [comment]
@chikeorjih I think you can use [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnclasses-string-function) to add custom class on column
