### ISSUE TITLE
get rows returned as search result

### ISSUE THREAD

**Issue by lorenzoface** [react-bootstrap-table/react-bootstrap-table2#1031]
Hello, 

I want to display near the table the sum / max /min values for a column. These values should get recalculated whenever a search is performed, counting the records contained in all the pages.
Is there an easy way to retrieve the records returned by a search?

Thanks

**Comment by AllenFang** [comment]
```

// get search data
this.table.searchContext.getSearched();

<BootstrapTable ref={ n => this.table = n }.../>
```
