### ISSUE TITLE
Unable to save value of edited cell

### ISSUE THREAD

**Issue by premkiran7** [react-bootstrap-table/react-bootstrap-table2#1036]
I could not edit cells in the column **Values** which can be seen in the code sandbox URL given below. I am new to ReactJS and react-bootstrap-table2. I went through the documentation but could not find out where I am going wrong. Any help would be appreciated.
[Code Sandbox Reference](https://codesandbox.io/embed/ecstatic-tharp-gdecb)

**Getting the following error**
Uncaught TypeError: dataOperator.typeConvert is not a function

**Comment by AllenFang** [comment]
@premkiran7 line:65 is wrong, it should be

`if (row.key === rowId) {`

**Comment by cervmi** [comment]
I received this error message as well. I debugged bootstrap-table javascript and found that  typeConvert function in dataOperator was missing. After restarting whole dev environment including OS helped and next time this error was not there.  I don't know exact reason.

**Comment by AllenFang** [comment]
[there](https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1044) are a similar  issue which caused by new `column.type` support, I will fix it in next version but not sure if it is relevant with this issue.

**Comment by AllenFang** [comment]
I fixed in newest version, please upgrade to newest version, thanks
[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/10/version-bump.html) is release note

**Comment by ImSolitude** [comment]
@AllenFang I am getting the issue again, Not sure what's wrong this time even though I have it all updated, This is my [ToolkitProvider](https://codesandbox.io/s/html-css-3bfkj?fontsize=14&hidenavigation=1&module=%2Ftable.js&theme=dark)
