### ISSUE TITLE
Can we do remote pagination with sorting/filtering on current page?

### ISSUE THREAD

**Issue by sushreedash** [react-bootstrap-table/react-bootstrap-table2#1040]
**Question**
A clear and concise description of you question. In addition, please search issues before you open a question to make sure there's no any duplicated questions.

**Screenshots**

**codesandbox**
Please give a simple and minimal example on https://codesandbox.io so that we can reproduce it easily.

**Comment by AllenFang** [comment]
@sushreedash sort and filter is cross page. but if you are in the remote mode, you can do anything by yourself(Like sorting/filtering on current page). Because in non remote mode, filter/sort is cross page.  But in remote mode, you can arrange/sort/filter/slice you data as you want

**Comment by gyerzh** [comment]
@AllenFang , the question was is it possible to use default react-bootstrap-table2 sorting within one page if the option remote = { pagination: true } 
So far I see that sorting stops working when at least one option in remote property pagination is true. Looks like a bug.
