### ISSUE TITLE
Error edit cell

### ISSUE THREAD

**Issue by leonardyrj** [react-bootstrap-table/react-bootstrap-table2#1041]
Uncaught TypeError: dataOperator.typeConvert is not a function

**Comment by premkiran7** [comment]
#1036

**Comment by leonardyrj** [comment]
I'm having problem on this line

` var newValueWithType = dataOperator.typeConvert(column.type, newValue);`

**Comment by AllenFang** [comment]
#1036 is a bug cause by example code itself,  "PLEASE FOLLOW CORRECT WAY TO REPORT A BUG"  thanks
