### ISSUE TITLE
Disable select row onClick for one column of row

### ISSUE THREAD

**Issue by mirl72** [react-bootstrap-table/react-bootstrap-table2#1042]
Hello,

I need to turn off the onClick for row selection on a single column of a row.

One of the columns in my table contain buttons for the user to interact with. I do not want the clicking of these buttons to trigger the select row, but clicking any other column should. (See image below)

Is there a way to achieve this with the latest build?

Thanks!
p.s. I love your table component and have really been able to use it for ALL of my requirements to this point. Great work and please keep it up!

![rowSelectionByColumn](https://user-images.githubusercontent.com/53577960/62373177-163fb200-b4ee-11e9-9a39-de5a7dc5b89f.png)

**Comment by AllenFang** [comment]
@mirl72  I think you can try to call `e.stopPropagation()` when handling the click event of your custom buttons.

**Comment by mirl72** [comment]
Perfect, thanks for the speedy response @AllenFang it worked like a charm!

**Comment by AllenFang** [comment]
👍

**Comment by Mvijaysai** [comment]
Hello,

I need to turn off the onClick for row selection on a single column of a row.

One of the columns in my table contain buttons for the user to interact with. I do not want the clicking of these buttons to trigger the select row, but clicking any other column should. (See   code below)@AllenFang

![Screen Shot 2020-01-21 at 5 47 31 PM](https://user-images.githubusercontent.com/54619232/72804588-b218d200-3c76-11ea-8ddb-221e560564a3.png)

i do not  want **edit modal** when clicking on other columns except edit column (at last column)
onRowClick = (cell, row) => {
    if (row != undefined) {
      this.openModal("open", cell);
    }
  };

**Comment by MahiBaghel** [comment]
i also having same issue @AllenFang  please help with example.

**Comment by Tzvetelin88** [comment]
As this event is for the hole ROW, we need to exclude last one, as we have different events there. You can exclude no matter which one, even pass it as parameter (index in this case)

```
onClick: (e, row, rowIndex) => {
    let getCurrentCellIndex = e.target.cellIndex;
    let getLastCellIndex = document.querySelector('table tr:last-child td:last-child').cellIndex
  
    if (getCurrentCellIndex !== getLastCellIndex && getCurrentCellIndex !== undefined) {
        console.log(`----> ${JSON.stringify(row)} |||| ${rowIndex}`)
    }
}
```

Basically this: (getCurrentCellIndex !== getLastCellIndex ) is controlling the current ROW event, but when click on the action button inside the Cell, you do not have cellIndex, so (getCurrentCellIndex !== undefined) is helping here. 
In that case you control the hole CELL + the Action Button Inside

**Comment by kyou-ennbunn** [comment]
> 👍

how to use e.stopPropagation() in react bootstraap table column?

**Comment by Huzaifaahmed20** [comment]
in your column in which you don't want event trigger , do this in that column

```
 events: {
        onClick: (e, column, columnIndex, row, rowIndex) => {
          e.stopPropagation();
        },
},
```

**Comment by viomjeet** [comment]
const selectRow = {
            mode: 'checkbox',
            // clickToSelect: true,

**Comment by robocon321** [comment]
> @mirl72 I think you can try to call `e.stopPropagation()` when handling the click event of your custom buttons.

Thank you very much. It's save my day

**Comment by sumitkp11** [comment]
This is how I got with easy solution:
Suppose the table is:
`<tr onclick="viewDetails()> <td>Col 1</td> <td ><button onclick="submitBtn()>Submit</button></td></tr>`

Step 1: Add id to the button.
`<button id="submit-btn" onclick="submitBtn()>Submit</button>`

Step 2: in viewDetails() function, pass event
`<tr onclick="viewDetails(event)>`

Step 3: in viewDetails function, check for submit-btn and return otherwise do your view details stuff

`const viewDetails = (event) => { if(event.target.id === 'submit-btn') return }`
