### ISSUE TITLE
Search multiple columns in combination

### ISSUE THREAD

**Issue by twiddler** [react-bootstrap-table/react-bootstrap-table2#1043]
Hi! :)

I have a table with multiple columns. Right now, when using the basic search from the [storybook](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Basic%20Search%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) examples, queries seem to be only compared with a single cell. It is not possible to search for "some word", and retrieve all rows where "some" appears in one column and "word" in another.

I did not find an example in the storybook that explains such a search. Ideally, I would also like to filter rows based on further information. I think a function that gets called per row and returns whether that row should show up in the search results would be optimal.

Can someone tell me whether this is already featured in the current release, or hint me at a workaround? The only possibility so far seems to make a custom search field and filter the data myself before passing it to the table, but ideally I would rather not go for that.

Best

**Comment by AllenFang** [comment]
@twiddler yeah, we don't have this feature so far and i will not to implement this very advanced feature for this component, I think the only way to achieve your requirement is like you said, you have to custom the mechanism of searching.

Thanks
