### ISSUE TITLE
How to get overall row index when pagination using editorRenderer

### ISSUE THREAD

**Issue by vollmerr** [react-bootstrap-table/react-bootstrap-table2#1045]
Hello,

I am using the editorRenderer column property to render a custom field (such as [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Custom%20Editor&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)) and I am needing the overall row index of the row when there is pagination.

I can currently access the rowIndex, but it is only for the given page. For example, on the first and second page the first item both have rowIndex of 0 instead of 0 and 10 (if page size is 10).

Is there a way to access the overall index of the row, or context to the pagination to compute it from within the editorRenderer function?

**Comment by AllenFang** [comment]
@vollmerr you are correct, rowindex always starts from 0 for first item in every page. So far we don't have this feature but would you please give me ant example about why you need the rowindex cross pagination?  thanks

**Comment by thebradisrad** [comment]
Hello, is there a way to get rowindex cross pagination yet? Need the row index to be correct to do an onChange on that row. When I do onChange on rows on page 2, the onChange would affect rows on page 1. 

I have tried to use row.id, but that doesn't work because the id are not in order of row index.
