### ISSUE TITLE
reload react-bootstrap-table2 when there is sort, filter, pagination

### ISSUE THREAD

**Issue by aguskianto** [react-bootstrap-table/react-bootstrap-table2#1046]
I am trying to use remote on react-bootstrap-table2.

The problem is: I need to call the API based on the parameter used in react-bootstrap-table2, such as: state, page, sizePerPage, filters, sortField, sortOrder. The problem is: I need props addition: token, url.

How can I add these two props inside onTableChange?

handleTableChange(type, { page, sizePerPage, filters, sortField, sortOrder }, **url, token**) {
        // how to pass props: url, token
}

**Comment by aguskianto** [comment]
I've found the way using remote-resolver.js. Is there anyway to reload react-bootstrap-table2?

**Comment by aguskianto** [comment]
Now, I can change the data inside react-bootstrap-table2, but I can't rerender the table.

Is the way I am changing the data wrong? Or, the way I update the data that is not fixed yet?

handleTableChange(type, { page, sizePerPage, filters, sortField, sortOrder, link, token, parent_state, data }) {
        let new_link = link + "?page=" + page + "&length=" + sizePerPage + "&order_by=" + sortField + "&order=" + sortOrder;

        setTimeout(() => {
             axios.get(new_link, {
                headers: {
                    Authorization: 'Bearer ' + token
                }
            })
            .then(res => {
                if(res.data.success) {
                    parent_state = data = res.data.data; **// I change the data here, but no rerender happens.**

                    this.forceUpdate();
                } else {
                    console.log(res.data.message);
                }
            }).catch(err => {
                console.log(err);
            });
        }, 2000);
    }

**Comment by aguskianto** [comment]
Is it possible to handleTableChange and setState at the same time? I want to handle sort, filter using API call and this API call will update the state and at last force react-bootstrap-table2 to rerender.

Is it possible?

**Comment by aguskianto** [comment]
Already found the answer... Just need more tweaking.

**Comment by 2xSamurai** [comment]
> Already found the answer... Just need more tweaking.

Can you please tell me how you handled this.
I am also facing a similar issue. 
I have a delete button action in all the rows. 

I am not sure how to solve the following issue. I have been banging my head for a few days now.

If I have 2 pages. And I am currently on the last page. It has only one row(entry). I delete that entry.
How do I re-render the table so that the first page(previous page) gets selected?

Any help would be much appreciated. 
Thank you.

**Comment by nayanahurix** [comment]
> Already found the answer... Just need more tweaking.

Can please tell me how you reload the table?
