### ISSUE TITLE
Pagination elements not on same row/line 

### ISSUE THREAD

**Issue by Amritpd** [react-bootstrap-table/react-bootstrap-table2#1051]
**Describe the bug**
When using the PaginationFactory() attribute in a Table, the pagination elements are not on the same row, specifically the # rows/per page dropdown and the prev/next page buttons, etc. 

**To Reproduce**
Simply look at the example on the demo site: 
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel 

**Screenshots**
![image](https://user-images.githubusercontent.com/9814488/62756451-d163d000-ba45-11e9-8613-7de8275e0813.png)

**codesandbox**
N/A

**Comment by AllenFang** [comment]
@Amritpd I fixed in newest version, please upgrade to newest version, thanks
[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/10/version-bump.html) is release note
