### ISSUE TITLE
Set property "options"  using a function in select filter

### ISSUE THREAD

**Issue by vagofrank** [react-bootstrap-table/react-bootstrap-table2#1054]
Set property "**options**"  using a function in select filter

To allow fill the options using the STATE
Something like

getOptions(() => this.state.dynamicFilter

**Comment by AllenFang** [comment]
Fixed in newest version:

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/25/version-bump.html

check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-filter.html#function-as-options)
