### ISSUE TITLE
Clear Row Selections

### ISSUE THREAD

**Issue by premkiran7** [react-bootstrap-table/react-bootstrap-table2#1055]
I am unable to clear the selected rows even after modifying the state variable responsible for storing the selected row ids on a button click event. Please help

Code Sandbox
[![Edit gifted-carson-ktpl5](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-carson-ktpl5?fontsize=14)

**Comment by AllenFang** [comment]
hello @premkiran7 I can clear selected row, please give the step to reproduce your issue. I will reopen it when I know how to reproduce it. thanks

**Comment by premkiran7** [comment]
hello @AllenFang, in the sample code which can be found in the above code sandbox, this issue can be reproduced. When a row is clicked the button "Mark" appears. On clicking the button "Mark" I want to clear the row that was selected previously. This was not happening. Please do correct me if there is something wrong in the code that I have written

**Comment by mayawen** [comment]
I am having the same problem here, is there a way to bind the selected list back to the table?

**Comment by Avhishek05** [comment]
Same issue here
