### ISSUE TITLE
Export to PDF 

### ISSUE THREAD

**Issue by maxsilvauk** [react-bootstrap-table/react-bootstrap-table2#1057]
Really need an export to PDF feature for this, is this being worked on also is it possible to combine multiple tables I notice export to csv say we had 3 tables on one page but they used different Bootstrap tables there is no way to combine them in one export to CSV download?

                        <BootstrapTable
                          hover
                          keyField={keyField}
                          {...props.baseProps}
                          expandRow={expandRow()}
                          headerClasses="report-header"
                          footerClasses="report-footer"
                          noDataIndication={`Showing '0' ${name} rows.`}
                          pagination={paginationFactory(getPagination(rows))}
                        />

                <BootstrapTable
                  hover
                  data={row.expandData}
                  keyField={subKeyField}
                  columns={subDataColumns}
                  noDataIndication={noDataIndicicationMsg}
                  classes="subTable"
                />

**Comment by fastertabla** [comment]
It will be helpful if we get export pdf

**Comment by AllenFang** [comment]
@maxsilvauk so far we don't have this feature and I think I will not implement this feature. However, If you really want to export multiple tables, I will recommend you to use `file-saver` to export any data you want.  `react-bootstrap-table2-toolkit` use it to achieve this. 

Thanks
