### ISSUE TITLE
Export to CSV multiple tables in one export please?

### ISSUE THREAD

**Issue by maxsilvauk** [react-bootstrap-table/react-bootstrap-table2#1058]
Really need the ability to export multiple tables in one 'Export To CSV' download?

Is there any way of doing this instead of having them in separate downloads? 

Thanks 

Max @AllenFang

**Comment by AllenFang** [comment]
hello @maxsilvauk I think it's impossible to implement it in current design but there's a workaround is use the exposed API:

```js

handleExportAll () {
const data = [...dataOfTable1, ...dataOfTable2];
  this.table1.handleExportCSV(data);
}

<button onClick={ handleExportAll }>Export All</button>
<ToolkitProvider ref={ n => this.table1 = n }... >
<ToolkitProvider ref={ n => this.table2 = n }... >

```

Let me know if you have any questions, thanks
