### ISSUE TITLE
onFilter hook is broken

### ISSUE THREAD

**Issue by webskin** [react-bootstrap-table/react-bootstrap-table2#1060]
Hello,

The example here :
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Filter%20Hooks&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

is broken

![image](https://user-images.githubusercontent.com/1107719/62979835-2e37ff80-be25-11e9-9e0e-7c1baca0a559.png)

I have tried this hook in my own project and I have the same error.

![image](https://user-images.githubusercontent.com/1107719/62980184-1c0a9100-be26-11e9-8ea3-96a2337eff03.png)

Best Regards.

**Comment by webskin** [comment]
I found the problem : it is not a hook but a customFilter :)

We must take the filtered data in second parameter and return a filtered collection :

```javascript
onFilter: (filterVal, data) {
  return data.filter(elmt => elmt.includes(filterVal))
}
```

To conclude it is just a matter of documentation :)

**Comment by webskin** [comment]
One remark : onFilter is not called when the text in the input is deleted.

Is it normal ?

**Comment by jendamozna** [comment]
For me it seems like bug. According to docs it does not require return value. "...called when column filter being triggered. If you return..." https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/filter-props.html#textfilter

I was using it as a handler without return value to update some app state when user changes filter. Now i cant find a solution as onTableChange works only in remote mode.

**Comment by webskin** [comment]
hum...
![image](https://user-images.githubusercontent.com/1107719/62982595-e6b57180-be2c-11e9-8112-cf75952d760b.png)

This is why `onFilter` is not called when manually clear filter

**Comment by webskin** [comment]
> For me it seems like bug. According to docs it does not require return value. "...called when column filter being triggered. If you return..." https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/filter-props.html#textfilter
> 
> I was using it as a handler without return value to update some app state when user changes filter. Now i cant find a solution as onTableChange works only in remote mode.

Yes Ideally it has to filter

**Comment by webskin** [comment]
@jendamozna The workaround to listen input change is to use the `onInput` Event Attribute because `onChange` is already used.

https://www.w3schools.com/tags/ev_oninput.asp

```javascript
textFilter({
  dataField: 'id',
  text: 'id',
  onInput: function(e) {
    // our code here
  }
});
```

**Comment by jendamozna** [comment]
Thanks, `onInput` is working fine. Applicable also on `selectFilter()`.

**Comment by AllenFang** [comment]
it's a regression issue from last version, I will fix it soon

**Comment by AllenFang** [comment]
Fixed in newest version:

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/25/version-bump.html
