### ISSUE TITLE
weird column toggle behavior

### ISSUE THREAD

**Issue by flc** [react-bootstrap-table/react-bootstrap-table2#1062]
consider this example:
https://codesandbox.io/s/frosty-ellis-17cun
everything works fine.

now change
```
    {
        dataField: "name",
        text: "Name"
      }
```
to
```
    {
        dataField: "namex",
        text: "Name"
      }
```
and start toggling the columns. weird things start to happen, values start to appear in wrongs cells.
any idea on why is this happening? i know i use a dataField that is not in the data but i have a use case where i need to define dataField that is not a field of a row.

**Comment by AllenFang** [comment]
@flc I will check this out, thank you

**Comment by AllenFang** [comment]
Fixed in newest version 

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/08/25/version-bump.html
