### ISSUE TITLE
Mark a cell mandatory based on condition.

### ISSUE THREAD

**Issue by mustafa-taheri** [react-bootstrap-table/react-bootstrap-table2#1065]
**Question**
Is there any way i can make a cell mandatory on the basis of a particular condition. 

**Screenshots**
![Screenshot from 2019-08-20 12-40-56](https://user-images.githubusercontent.com/20725410/63325510-ed217d00-c347-11e9-82fb-b75f82dba860.png)

The scenario is if SelfDemo is selected Demo Person and Phone Number cell should be mandatory and NOT Empty and if By Company is selected Company Login ID  field should be mandatory and NOT Empty. Is there anything I can do it directly using React-Bootstrap-Table-2 or I have loop every item and check it before save..?

**Comment by AllenFang** [comment]
@mustafa-taheri sorry for lately reply. so far we don't have this feature. the workaround is like you said, you have to do the checking by yourself before saving the cell.  thanks
