### ISSUE TITLE
State problem when using events within the table

### ISSUE THREAD

**Issue by bbuchanan** [react-bootstrap-table/react-bootstrap-table2#1066]
**Describe the bug**
This is a bit hard to describe, but I have a table that is initially populated from a store. The user can add and delete new rows. If I have initially populated with 1 row from the database and the user adds 2 rows, now the state reflects 3 rows. Great. However, if the user clicks the delete button on row 2 and I query the state from the button click event, it states there are only 2 rows. This is all very confusing and I did not suspect the table for the longest time, but I believe I have isolated it and have included a link to a code sandbox to demonstrate this problem.

**To Reproduce**
1. Go to https://codesandbox.io/s/vigorous-taussig-39noc
2. Click on "Add milestone" 2 or more times.
3. Click on the "Get Milestone Count" button which will display to the console the correct number of rows.
4. Click on the delete button in row #2. The number of milestones logged to the console is 2. That's not right.
5. Click on the delete button for row 3, reports that there are now 3 milestones (correct).

Note: nothing is actually deleted. This is creating chaos because if user deletes row 2, everything added below row 2 is gone, so work is lost.

Also, I'm going to try and identify this issue myself, but hoping you might have some ideas to clue me in. Thank you.

**Screenshots**
<img width="616" alt="Screen Shot 2019-08-20 at 09 53 57" src="https://user-images.githubusercontent.com/315135/63353459-c9067180-c330-11e9-909a-aabdc345a945.png">

**codesandbox**
https://codesandbox.io/s/vigorous-taussig-39noc

**Comment by bbuchanan** [comment]
<img width="878" alt="Screen Shot 2019-08-20 at 13 23 08" src="https://user-images.githubusercontent.com/315135/63369436-ef86d580-c34d-11e9-8135-4d0260db61b8.png">

Just came across this in the docs. So maybe this is why I'm having so much trouble. How should I handle what I'm trying to accomplish?

**Comment by AllenFang** [comment]
please pass state via `formatExtraData`


```
import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import BootstrapTable from "react-bootstrap-table-next";
import { Button } from "react-bootstrap";

import "./styles.css";
import "react-bootstrap-table-next/dist/react-bootstrap-table2.min.css";

function App() {
  const [milestones, setMilestones] = useState([]);
  useEffect(() => {
    setMilestones([{ Id: 1, Name: "Milestone 1" }]);
  }, []);

  const editButton = (cell, row) => {
    return <Button onClick={() => editMilestone(row.Id)}>Edit</Button>;
  };

  const deleteButton = (cell, row, rowIndex, extra) => {
    return (
      <Button onClick={() => deleteMilestone(row.Id, extra)}>Delete</Button>
    );
  };

  const columns = [
    {
      dataField: "Id",
      text: "Milestone ID"
    },
    {
      dataField: "Name",
      text: "Milestone Name"
    },
    { dataField: "Edit", text: "Edit", sort: false, formatter: editButton },
    {
      dataField: "Delete",
      text: "X",
      sort: false,
      formatter: deleteButton,
      formatExtraData: {
        currentLength: milestones.length
      }
    }
  ];

  const addMilestone = () => {
    setMilestones([
      ...milestones,
      {
        Id: milestones.length + 1,
        Name: `Milestone ${parseInt(milestones.length + 1, 10)}`
      }
    ]);
    //   milestones.concat({
    //     Id: milestones.length + 1,
    //     Name: "Milestone " + parseInt(milestones.length + 1, 10)
    //   })
    // );
  };

  const editMilestone = Id => {
    console.log(`Editing milestone ${Id}`);
    getMilestones();
  };

  const deleteMilestone = (Id, extra) => {
    >>>>>> console.log(extra.currentLength);
    //getMilestones();
  };

  const getMilestones = () => {
    console.log(`Milestone count = ${milestones.length}`);
  };

  return (
    <div className="App">
      <Button onClick={getMilestones}>Get Milestone Count</Button>
      <Button onClick={addMilestone}>Add Milestone</Button>
      {milestones == null ? (
        ""
      ) : (
        <BootstrapTable keyField="Id" data={milestones} columns={columns} />
      )}
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

**Comment by AllenFang** [comment]
BTW, I encourage to enable `isDummyField` when you column is meaningless(For actions)

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnisdummyfield-bool

**Comment by muthurajameq** [comment]
i use   BootstrapTable from "react-bootstrap-table-next". i have 25 columns in this table. in 25 th column has button. When button clicks that the modal will open. everything is ok. but i have to scroll for 25th column. its ok but after button click the table moved to initial position(left most position). in case i want to second time click the button , then i have to scroll again. how to fix. i want any event occurs then the table dont go to initial position. what can i do? anyone please help me?
