### ISSUE TITLE
Custom search on predefined columns

### ISSUE THREAD

**Issue by 7DeGe** [react-bootstrap-table/react-bootstrap-table2#1067]
Is there a possibility to exclude certain columns from the search scope? I would like to only search rows based on a single column. The default setting always searches for matches in all columns.

**Comment by AllenFang** [comment]
I will add a new props: `column.searchable` for this requirement, thanks

**Comment by AllenFang** [comment]
@7DeGe you can give false to `column.searchable`.  BTW, I found I missing the docs and story for this, I will also add it, thanks!

**Comment by AllenFang** [comment]
patched docs: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnsearchable-bool
