### ISSUE TITLE
You seem to pass e, column, columnIndex, row, rowIndex in events { } but not headerEvents{ }

### ISSUE THREAD

**Issue by maxsilvauk** [react-bootstrap-table/react-bootstrap-table2#1077]
**Question**
I need access to newly added attributes when a column header is clicked. I would love access via 

       headerEvents: {
            onClick: (e, column, columnIndex, row, rowIndex) => {
                console.log('colunn',  column);
               // I could manipulate column to get my attribute which i could pass to 'headerOnClick()' 
                headerOnClick();
            },
        },

Can we have this please is there something I am missing I have even tried,.

console.dir(e.target.attributes.getNamedItem('date').value);

but I cant seem to assign this to a constant to be used?

**Comment by AllenFang** [comment]
hi @maxsilvauk I can only add `column` and `columnIndex` for onClick event in headerEvent, because when clicking on a header column, there's no row perspective.

**Comment by maxsilvauk** [comment]
Hi @AllenFang. Thanks for your speedy reply so column should give me access to the headerAttrs {} as I can see column gives access to this information for events: { }. 

Also when are you planning to release release-2019-q2-9. Many thanks in advance @maxsilvauk

**Comment by maxsilvauk** [comment]
@AllenFang Can you also pass column and columnIndex for onClick for footerEvent as-well?

**Comment by AllenFang** [comment]
Sorry, I am busy recently lol 

> Can you also pass column and columnIndex for onClick for footerEvent as-well?

I will try.

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/09/08/version-bump.html)

This issue was fixed, please upgrade all the packages listed in above
