### ISSUE TITLE
Sort by different value than formatter returns

### ISSUE THREAD

**Issue by fabianbloching** [react-bootstrap-table/react-bootstrap-table2#1082]
Hello,

Is it somehow possible to change the sorted value of a column ? I use a column formatter which returns html but need to sort for a specific value inside of that. Something similar to filterValue option (sortValue) would be awesome.
```
{
          dataField: 'versionList',
          text: 'Versionen',
          formatter: (cellContent, row) => {
                 return <div>sortedText .... <p>..</p><div> ;
           },
           sort: true
}

**Comment by AllenFang** [comment]
@fabianbloching I will implement it soon, thanks!

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/09/08/version-bump.html)

This issue was fixed, please upgrade all the packages listed in above 

Now, you can use `sortValue`
react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnsortvalue-function

**Comment by fabianbloching** [comment]
:heart: thank you

**Comment by avindra** [comment]
`formatter` is meant to change the output the data.

It seems un-intuitive to me that it also mangles the actual internal data that is being passed around in the library. 

As a user, I would expect that `formatter` doesnt mangle my data. Why should I have to add another `sortValue`? This solution seems unintuitive, and it does not scale. If I have to add `sortValue` to any sortable column that has custom formatting, that that means I have to do it for _almost everything_, as `formatter` is quite frequently used.
