### ISSUE TITLE
Pagination break downs after delete the last element on active page

### ISSUE THREAD

**Issue by dailymp** [react-bootstrap-table/react-bootstrap-table2#1085]
**Error when deleting last element on active page**
When deleting the last element of an active page, the table doesn't re-render properly, instead throw the following error: 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/14187188/64418591-9633db80-d09b-11e9-9320-7b2f8ef313bf.png)

**To Reproduce**
1. Go to last page
2. Delete the last element on page
3. See error

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/14187188/64418678-c1b6c600-d09b-11e9-8239-c66ded2d2ac5.png)

**Comment by dailymp** [comment]
Added a PR: https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/1086

**Comment by AllenFang** [comment]
@dailymp thanks this bug report and your contribution, I will check this out and find the root cause, thank!

**Comment by AllenFang** [comment]
@dailymp I try this case in [official demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Pagination%20with%20Dynamic%20Data&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) but it work!

Any thoughts?

**Comment by dailymp** [comment]
Hello @AllenFang  maybe could be the versions I used
Here are the versions I use:
![image](https://user-images.githubusercontent.com/14187188/64526569-f88f1500-d303-11e9-8f68-6b8d2e212139.png)
What do you think?
Thanks in advance!!! :)

**Comment by AllenFang** [comment]
@dailymp I think it's not about to the version. Please give me a simple and minimal example on codesandbox.io so that I can reproduce it, thanks!

**Comment by AllenFang** [comment]
@dailymp Though I still can not understand the root cause of this issue, but I will add a short circuit to avoid this error.

**Comment by AllenFang** [comment]
@dailymp please all the packages to newest version. Let me know if the issue still remain, thanks

**Comment by dailymp** [comment]
Hello @AllenFang I have updateted now to "react-bootstrap-table-next": "3.2.1", and the error is gone. Thanks a lot!
