### ISSUE TITLE
Dynamic Data not updating properly

### ISSUE THREAD

**Issue by Anandks1993** [react-bootstrap-table/react-bootstrap-table2#1089]
**Describe the bug**
Dynamic data not updating properly, Data gets updated only on 3rd occurrence of API call. API call is happening through formatter option of column. Atleast in my actual application the formatter column toggles between properly after 1st 3rd occurrence of the API call, But when I tried to reproduce the issue on codesandbox, the occurrence continued.

**codesandbox**
https://codesandbox.io/s/react-bootstrap-table-next-issue-sample-ccq1q

In the example, Please click Yes/No in completed column, to see the issue happening, Value updating only on the 3rd occurrence.

**Note:** When I tried to debug, `this.props.row` and `nextProps.row` are going as same (i.e both `this.props.row` and `nextprops.row` are the updated one) to this function `shouldUpdatedByNormalProps` and after 2 times, the value differs (i.e old value for `this.props.row` and new value for `nextprops.row`). This happens for boolean field, and if I edit any non-boolean field first, then try to change boolean, it works properly.

Maybe I am doing it wrong, I don't know what causes to this issue.

**Comment by AllenFang** [comment]
@Anandks1993 sorry for lately reply,  Please follow the way of immutable to update data in the world of react

```
statusUpdate = (data) => {
    fetch(`https://jsonplaceholder.typicode.com/todos/${data.id}`, {
      method: 'PUT',
      body: JSON.stringify({ ...data, completed: !data.completed }),
      headers: {
        'Content-type': 'application/json; charset=UTF-8'
      }
    })
      .then(response => response.json())
      .then((json) => {
        const newdata = this.state.users.map((item) => {
          if (json.id === item.id) {
            // item[index] = json;
            return json;
          }
          return item;
        });
        this.setState({
          users: newdata,
          requesting: false
        });
      });
  }
```

**Comment by Anandks1993** [comment]
@AllenFang Thank you very much, My bad.
