### ISSUE TITLE
. notation keys in datafield don't work

### ISSUE THREAD

**Issue by dstone1983** [react-bootstrap-table/react-bootstrap-table2#1091]
`{
            text: 'Assignee Name',
            dataField: 'assignee.combo_name'
        }`

I am reading data directly from the backend api. They keys in the JSON are as like they are in the sample above. No errors are given in the console, just a bunch of blank <td>'s.

I tried it with a key that I had no intention of using and it worked fine. _id

These type of keys use to work in the original bootstrap table.

I know I could remap that keys myself, but I think a better solution would to not have to do that in the UI code if it can be avoided. I also can't control the way it is presented to me from the back end (external api).

**Comment by AllenFang** [comment]
@dstone1983 ***please follow the instruction to report a question or a bug***.  [demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Display%20Nested%20Data&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) work well.
