### ISSUE TITLE
row span feature

### ISSUE THREAD

**Issue by dstone1983** [react-bootstrap-table/react-bootstrap-table2#1092]
Everything seems to be old and not sure if it is being worked on.

Original bootstrap allowed for 2nd level headers to give titles to a group of other headers. It was a very nice feature that I currently am using in a project. The problem I have is that some of the old items in the original bootstrap table are slowly becoming deprecated and it would be great to have the same features.

It is honestly the only thing preventing me from moving to bootstrap table 2.

**Comment by AllenFang** [comment]
@dstone1983 so far i don't have enough time to implement column span. sorry about that. Anyway PR is welcome and close it due to duplicated issues
