### ISSUE TITLE
expandRow.parentClassName only works when expanded

### ISSUE THREAD

**Issue by williamkmlau** [react-bootstrap-table/react-bootstrap-table2#1095]
expandRow.parentClassName only works when IsExpanded is true.

You can see this directly from the Storybook example by inspecting the element.

The IsExpanded parameter is useless because the class name will always be empty when IsExpanded is false.

**Comment by AllenFang** [comment]
@williamkmlau I will check this out, thanks!

**Comment by AllenFang** [comment]
@williamkmlau I won't fix this issue. In my opinion, you can custom row via `rowClasses` for any cases, but when you want to custom row when it is expanded, you can use `expandRow.parentClassName`
