### ISSUE TITLE
Table th tabIndex cant be unset

### ISSUE THREAD

**Issue by jendamozna** [react-bootstrap-table/react-bootstrap-table2#1099]
Column headerAttrs param can't be used to unset default tabIndex behaviour
`column.headerAttrs: () => ({ tabIndex: false })`
does not work.

Line 44 `tabIndex: 0` should be moved before headerAttrs in following code
https://github.com/react-bootstrap-table/react-bootstrap-table2/commit/4ec02b294afa876155088fc7140c2f13ec2b0aa2

**Comment by AllenFang** [comment]
@jendamozna I will fix it soon

**Comment by AllenFang** [comment]
@jendamozna please upgrade `react-bootstrap-table-next` to newest version so that you can set `tabIndex`.  As default, `tabIndex` is still `0`

**Comment by jendamozna** [comment]
thanks
