### ISSUE TITLE
Blur To Save for Custom Editor - Reopen for issue NO. 1093

### ISSUE THREAD

**Issue by hyphen1370** [react-bootstrap-table/react-bootstrap-table2#1100]
Hello, 

Since Github doesn't allow to reopen issue that closed by contributor, I open this issue referencing the issue No. 1093 because I made an update over there. I am not sure the contributor will check the close issue or not. 

I apologize for the inconvenience.

**Comment by AllenFang** [comment]
@hyphen1370  sorry for lately reply, the `rest` object contain a property is `onBlur`, You **have to** render this property to an input or select element or both of them.
