### ISSUE TITLE
Selected rows  will be deleted after click on review form button. Submitted

### ISSUE THREAD

**Issue by kammasuresh** [react-bootstrap-table/react-bootstrap-table2#1102]
Hi , I am using your plugin..simply ..good..my requirement is I am using your table , on top of the table review button..I  want to review the selected rows.. after selected the rows, I click on review button ,it will be open one pop up and ask the question and answers and clicked on submit button on pop up, then I will come back to the table and selected rows will be deleted..and write dB for updates as reviewed(this I will make it for dB..I knew this..)’problem is how do I do  delete rows qfter  child pop up component submitted.’really stucked to be deleted rows..I saw your documentation..old version has.. deleted rows option..currently I am using latest version ..shall I switch to old version or will look into another table plugin

**Comment by AllenFang** [comment]
@kammasuresh no need to switch to old version, it's irrelevant and definitely not a bug. How do your submit button work?  is it trigger a page refresh?

If ok, please create a simple and minimal example on codesandbox, so that I can help you, thanks
