### ISSUE TITLE
Master checkboxes are broken when using a nested keyField

### ISSUE THREAD

**Issue by dwichelo** [react-bootstrap-table/react-bootstrap-table2#1104]
Hi,

It seems the row selection behaviour does not work correctly in combination with nested a `keyField`. When that key is nested, the master checkbox is not checked as intended. See screenshot.

![image](https://user-images.githubusercontent.com/7196191/65390022-9d294200-dd5b-11e9-8f05-51d0591c2e46.png)

Note that both tables use a unique field as `keyField`. The above table incorporates a nested `keyfield`, while the below one does not. When in this broken state, the master checkbox is not able to deselect rows.

 As soon as the nested key is replaced by a top layer key, the checkboxes act as expected.

**Comment by AllenFang** [comment]
@dwichelo sorry for lately reply, I will fix it soon

**Comment by AllenFang** [comment]
Fixed it!! please upgrade  `react-bootstrap-table-next` to newest version

**Comment by dwichelo** [comment]
Thank you.
