### ISSUE TITLE
Implement React-Router-Dom <Link /> to the row

### ISSUE THREAD

**Issue by sg27950** [react-bootstrap-table/react-bootstrap-table2#1105]
Hi, I'm new to react-bootstrap-table2 
I already got a list of products to display on the table fetching all data from external API with JSON format. I want to make some sort of button or double click on that row is fine too. After the click, It will take to another page that has all the product details.
Any thoughts on how to implement react-router to the table? 
Appreciate your help and suggestion.

Thank you!

**Comment by AllenFang** [comment]
Hello @sg27950 sorry for lately reply, I think it depends on how you want to make redirect happen.

So far we only have column formatter but no row formatter. You can check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) to see how to custom a column to render anything you want in the cell.

Or there's a dummy column you can use: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnisdummyfield-bool

Please check our docs and [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Welcome&selectedStory=react%20bootstrap%20table%202%20&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) to explore more detail and let me know if you have any question when you are implementing. thanks

**Comment by CurlyJoe71** [comment]
I've found a quick work around for my table data. As the data object is being fetched, I run it through a function that will put each whichever field value I choose into its own div which will contain an "a" element linked to a url. This new element takes the place of the old string value for that field. React renders it in the table like it would any other JSX element. Neato Torpedo!

`const path = https://wherever;`
`dataObject.forEach(d => {
d.dataField = <><a href={path}>{d.dataFieldValue}</a></>
});`
