### ISSUE TITLE
Drop down editor: Table Displays Value instead of Label

### ISSUE THREAD

**Issue by rchaser** [react-bootstrap-table/react-bootstrap-table2#1106]
Hello
I suppose it is a wrong behavior,
Check this out please
https://codesandbox.io/embed/react-bootstrap-table-next-basic-example-u168d

![DropdownEditor](https://user-images.githubusercontent.com/1940857/65445970-0d0ef980-de3c-11e9-8197-fdd5d6344677.gif)

There was the same issue that was imho unfairly closed #934

**Comment by AllenFang** [comment]
@rchaser it's not an issue and actually depends on your case. In you case you should also use `column.formatter` to render **Product Type** with actual display value instead of raw value. ex:

```js
const ProductList = props => {
  const columns = [
    {
      dataField: "id",
      text: "Product ID"
    },
    {
      dataField: "name",
      text: "Product Name"
    },
    {
      dataField: "productTypeValue",
      text: "Product Type",
      formatter: (cell, row) => {
        return productTypes.find(x => x.value == cell).label;
      },
      editor: {
        type: Type.SELECT,
        options: productTypes
      }
    },
    {
      dataField: "price",
      text: "Product Price"
    }
  ];

  return (
    <div style={{ padding: "20px" }}>
      <h1 className="h2">Products</h1>
      <BootstrapTable
        keyField="id"
        data={products}
        columns={columns}
        cellEdit={cellEditFactory({ mode: "click", blurToSave: true })}
      />
    </div>
  );
};
```

**Comment by rohit8080** [comment]
I am getting error>> TypeError: Cannot read property 'label' of undefined

**Comment by jankes44** [comment]
Anybody have fix for that? I'm getting the same error.

**Comment by rahulsemwal** [comment]
@AllenFang, Thanks it's working for me.

**Comment by rahulsemwal** [comment]
> @rchaser it's not an issue and actually depends on your case. In you case you should also use `column.formatter` to render **Product Type** with actual display value instead of raw value. ex:
> 
> ```js
> const ProductList = props => {
>   const columns = [
>     {
>       dataField: "id",
>       text: "Product ID"
>     },
>     {
>       dataField: "name",
>       text: "Product Name"
>     },
>     {
>       dataField: "productTypeValue",
>       text: "Product Type",
>       formatter: (cell, row) => {
>         return productTypes.find(x => x.value == cell).label;
>       },
>       editor: {
>         type: Type.SELECT,
>         options: productTypes
>       }
>     },
>     {
>       dataField: "price",
>       text: "Product Price"
>     }
>   ];
> 
>   return (
>     <div style={{ padding: "20px" }}>
>       <h1 className="h2">Products</h1>
>       <BootstrapTable
>         keyField="id"
>         data={products}
>         columns={columns}
>         cellEdit={cellEditFactory({ mode: "click", blurToSave: true })}
>       />
>     </div>
>   );
> };
> ```
@AllenFang , Thanks it's working for me.
