### ISSUE TITLE
Column formatter not formatting Export CSV columns

### ISSUE THREAD

**Issue by devevignesh** [react-bootstrap-table/react-bootstrap-table2#1111]
**Question**
Hey @AllenFang, I'm formatting a column like below but this is not working in Export CSV column. I'm getting `null` instead of `-` for Progress Date. 
```
const columns = [
{
    dataField: "progress.date",
    text: "Progress Date",
    sort: true,
    formatter: col => (col ? col : "-"),
    style: { textAlign: "center" },
    headerAlign: "center"
}
]
```
Should I include `csvFormatter` to achive this?
```
const columns = [
{
    dataField: "progress.date",
    text: "Progress Date",
    sort: true,
    formatter: col => (col ? col : "-"),
    csvFormatter: col => (col ? col : "-"),
    style: { textAlign: "center" },
    headerAlign: "center"
}
]
```

**Comment by AllenFang** [comment]
@devevignesh you should use `csvFormatter` because a lots of developer they custom cell with a complicated jsx, react element, it's impossible to export to CSV(Not make sense)

**Comment by tiarahardiy** [comment]
I already using csvFormatter but still can not working,

here my codes 
`{
    dataField: 'region_name',
    text: 'Region Group',
    sort: false,
    csvExport: true,
    headerStyle: () => {
      return { width: '200px' }
    },
    csvHeaderStyle: { backgroundColor: 'lightblue', color: 'white' },
    csvFormatter: (cell, row) => {
      return cell + ' '.repeat(200 - cell.length)
    },
  },
`
