### ISSUE TITLE
How to add linkout to cells of a column

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [react-bootstrap-table/react-bootstrap-table2#1116]
![Screen Shot 2019-10-04 at 4 04 41 PM](https://user-images.githubusercontent.com/22722805/66245160-d7ca9d00-e6c0-11e9-9e9c-faea2be609c1.png)

For the cells of accession column I would like each cell have  a link-out to an external url

Any tips on how to do this would be helpful.

Thanks!

**Comment by Ymbere** [comment]
Hi, you can use a `formatter` in order to achieve that result.

```jsx
const columns = [
  ...
  {
    dataField: "accessions",
    text: "Accessions",
    formatter: (rowContent, row) => {
      return (
        <>
          rowContent
          <a href="#">Link</a>
        </>
      )
    }
  }
  ...
]
```

[![Edit wonderful-wind-h0yl0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-wind-h0yl0?fontsize=14)

**Comment by Parul-Kudtarkar** [comment]
@Ymbere perfect! Thank you so much, that works!

**Comment by stuartabrown** [comment]
Just wanted to also say thanks for this solution @Ymbere - it really helped me out!
