### ISSUE TITLE
Tie editing to row key

### ISSUE THREAD

**Issue by guldfisk** [react-bootstrap-table/react-bootstrap-table2#1120]
Current behavior:
When a user begins editing a cell, what is being edited is based on the index, so if the table is updated while the user is editing, they are now editing a different cell.

Desired behavior:
The cell being edited should be tied to the key of the row the cell belongs to. So if a cell is inserted or removed on a lower index, the user is still editing the same cell. If the row with the key the user is editing is removed, the editing dialog should close.

[Sandbox](https://codesandbox.io/embed/vibrant-kapitsa-o51dm). Try editing a value for a key while new rows are being inserted.

**Comment by AllenFang** [comment]
it's minor for me, PR is welcome, thanks
