### ISSUE TITLE
I added a custom column with add and minus buttons to every row and I want onClick each + buttons, counter will be updated for that particular row only not every row? 

### ISSUE THREAD

**Issue by dashName** [react-bootstrap-table/react-bootstrap-table2#1123]
<img width="83" alt="Screen Shot 2019-10-08 at 11 18 20 AM" src="https://user-images.githubusercontent.com/56317909/66426658-2b8dfc80-e9c7-11e9-8770-85b607f931fb.png">

code:
 const dataFormatter = (cell, row, rowIndex, formatExtraData) => {
       
            return (
                <div>
                    <div onClick={() => addToCart(rowIndex)}>
                        <img src={plus} style={{backgroundColor: '#2a4252'}}/>
                    </div>
                    <div id='text-val'> {formatExtraData} </div>
                    <div onClick={() => removeFromCart(rowIndex)}>
                        <img src={minus} style={{backgroundColor: '#2a4252'}}/>
                    </div>
                </div>
            );
        };

and
...
formatExtraData: this.state.counter,
...

 const addToCart = (index) => {
                    this.setState({counter: this.state.counter + 1});
                }

...

**Comment by Ymbere** [comment]
Hi, you want that when a `+` button is clicked the counter increase just for that specific row of the button clicked? Is that correct?

**Comment by dashName** [comment]
yes

**Comment by dashName** [comment]
> Hi, you want that when a `+` button is clicked the counter increase just for that specific row of the button clicked? Is that correct?

Yes

**Comment by Ymbere** [comment]
Could you provide the code for that component so I can help you more efficiently?

**Comment by dashName** [comment]
> Could you provide the code for that component so I can help you more efficiently?
........
constructor(props) {
        super(props);
        this.state = {
            counter: 0
        };
    }
......
const columns = [{
{
    dataField: '',
    text: 'Qty',
    formatter: dataFormatter,
    formatExtraData: this.state.counter,
    headerStyle: () => {
        return {width: '15%', textAlign: 'center', fontSize: '12px', color: '#7F7F7F'};
    },
}];
.......

const dataFormatter = (cell, row, rowIndex, formatExtraData) => {

        return (
            <div>
                <div onClick={() => addToCart(rowIndex)}>
                    <img src={plus} style={{backgroundColor: '#2a4252'}}/>
                </div>
                <div id='text-val'> {formatExtraData} </div>
                <div onClick={() => removeFromCart(rowIndex)}>
                    <img src={minus} style={{backgroundColor: '#2a4252'}}/>
                </div>
            </div>
        );
    };

..........

const addToCart = (index) => {
console.log(index)
this.setState({counter: this.state.counter + 1});
}

.....

**Comment by Ymbere** [comment]
The problem is in the state, all the rows of the table are receiving the same state variable, so when you update one row the state is the same for all the others.
In order to make each row increase the counter individually, you need to have one counter for each row.

**Comment by dashName** [comment]
> The problem is in the state, all the rows of the table are receiving the same state variable, so when you update one row the state is the same for all the others.
> In order to make each row increase the counter individually, you need to have one counter (state) for each row.

can we do something with rowIndex?If not how we are gonna have counters for each row?can you please suggest the best way to achieve this?

**Comment by Ymbere** [comment]
The items to be displayed in the table are received as props in the component?

**Comment by dashName** [comment]
> The items to be displayed in the table are received as props in the component?

yes

**Comment by Ymbere** [comment]
> > The items to be displayed in the table are received as props in the component?
> 
> yes

My approach is the following after you receive your table data as props you can iterate through then, this way you add a default counter for each row.

```jsx
  state = {
    tableCounters: []
  };
  componentDidMount() {
    const tableCounters = [];
    const tableData = this.props.myTableData;

    tableData.forEach(() => {
      tableCounters.push({ counter: 0 });
    });

    this.setState({ tableCounters });
  }

```
After that, you can implement the method getCounter and pass it to your `formatExtraData`

```jsx
  getCounter = rowIndex => {
    if (this.state.tableCounters[rowIndex] !== undefined) {
      return this.state.tableCounters[rowIndex].counter;
    }
  };
```

And your `dataFormatter` will look like this

```jsx
const dataFormatter = (cell, row, rowIndex, formatExtraData) => {
  return (
    <div>
      <div onClick={() => addToCart(rowIndex)}>
        <img src={plus} style={{ backgroundColor: "#2a4252" }} />
      </div>
      <div id="text-val"> {formatExtraData(rowIndex)} </div>
      <div onClick={() => removeFromCart(rowIndex)}>
        <img src={minus} style={{ backgroundColor: "#2a4252" }} />
      </div>
    </div>
  );
};
```

With that done you need to update your `addToCart` in order to update the counter for the specific row index

**Comment by dashName** [comment]
> > > The items to be displayed in the table are received as props in the component?
> > 
> > 
> > yes
> 
> My approach is the following after you receive your table data as props you can iterate through then, this way you add a default counter for each row.
> 
> ```js-jsx
>   state = {
>     tableCounters: []
>   };
>   componentDidMount() {
>     const tableCounters = [];
>     const tableData = this.props.myTableData;
> 
>     tableData.forEach(() => {
>       tableCounters.push({ counter: 0 });
>     });
> 
>     this.setState({ tableCounters });
>   }
> ```
> 
> After that, you can implement the method getCounter and pass it to your `formatExtraData`
> 
> ```js-jsx
>   getCounter = rowIndex => {
>     if (this.state.tableCounters[rowIndex] !== undefined) {
>       return this.state.tableCounters[rowIndex].counter;
>     }
>   };
> ```
> 
> And your `dataFormatter` will look like this
> 
> ```js-jsx
> const dataFormatter = (cell, row, rowIndex, formatExtraData) => {
>   return (
>     <div>
>       <div onClick={() => addToCart(rowIndex)}>
>         <img src={plus} style={{ backgroundColor: "#2a4252" }} />
>       </div>
>       <div id="text-val"> {formatExtraData(rowIndex)} </div>
>       <div onClick={() => removeFromCart(rowIndex)}>
>         <img src={minus} style={{ backgroundColor: "#2a4252" }} />
>       </div>
>     </div>
>   );
> };
> ```
> 
> With that done you need to update your `addToCart` in order to update the counter for the specific row index

Hey I tried like below but does not seem to work.
....
 this.state = {
            counter: 0,
            tableCounters: []
        };
....

    componentDidUpdate(prevProps, prevState) {
        const tableCounters = [];
        const tableData = this.props.data;
        tableData.forEach(() => {
            tableCounters.push({counter: 0});
        });
        if (this.props.data !== prevProps.data) {
            this.setState({tableCounters: tableCounters});
        }
    }

    getCounter = rowIndex => {
        if (this.state.tableCounters[rowIndex] !== undefined) {
            return this.state.tableCounters[rowIndex].counter;
        }
    };
....

const dataFormatter = (cell, row, rowIndex, formatExtraData) => {
            return (
                <div>
                    <div onClick={() => addToCart(rowIndex)}>
                        <img src={plus} style={{backgroundColor: '#2a4252'}}/>
                    </div>
                    <div style={{backgroundColor: '#fff', padding: '2px 5px', outline: 'none'}}
                         id='text-val'> {formatExtraData(rowIndex)} </div>
                    <div onClick={() => removeFromCart()}>
                        <img src={minus} style={{backgroundColor: '#2a4252'}}/>
                    </div>
                </div>
            );
        };
........
  const addToCart = (index) => {
           this.setState({counter: this.state.tableCounters[index].counter + 1});
}

**Comment by Ymbere** [comment]
Hi @dashName , your state should be like this

```jsx
  state = {
    tableCounters: []
  };
```

And your `addToCart` method should loop through the array of state counters and then update the state counter for the specific row, the way that you implemented it will do not work because it is setting the state on the "global" counter.

I think this will do the trick

```jsx
  addToCard = rowIndex => {
    this.setState(prevState => ({
      tableCounters: prevState.tableCounters.map((item, index) => {
        if (index === rowIndex) {
          return { counter: item.counter + 1 };
        }
        return item;
      })
    }));
  }
```

And the `componentDidUpdate` should be `componentDidMount`

**Comment by dashName** [comment]
> Hi @dashName , your state should be like this
> 
> ```js-jsx
>   state = {
>     tableCounters: []
>   };
> ```
> 
> And your `addToCart` method should loop through the array of state counters and then update the state counter for the specific row, the way that you implemented it will do not work because it is setting the state on the "global" counter.
> 
> I think this will do the trick
> 
> ```js-jsx
>   addToCard = rowIndex => {
>     this.setState(prevState => ({
>       tableCounters: prevState.tableCounters.map((item, index) => {
>         if (index === rowIndex) {
>           return { counter: item.counter + 1 };
>         }
>         return item;
>       })
>     }));
>   }
> ```
> 
> And the `componentDidUpdate` should be `componentDidMount`

ComponentDidMount was returning props value as undefined so i used componentDidMount..Thanks a lot for the solution..it works..really appreciate

**Comment by Ymbere** [comment]
> > Hi @dashName , your state should be like this
> > ```
> >   state = {
> >     tableCounters: []
> >   };
> > ```
> > 
> > 
> > And your `addToCart` method should loop through the array of state counters and then update the state counter for the specific row, the way that you implemented it will do not work because it is setting the state on the "global" counter.
> > I think this will do the trick
> > ```
> >   addToCard = rowIndex => {
> >     this.setState(prevState => ({
> >       tableCounters: prevState.tableCounters.map((item, index) => {
> >         if (index === rowIndex) {
> >           return { counter: item.counter + 1 };
> >         }
> >         return item;
> >       })
> >     }));
> >   }
> > ```
> > 
> > 
> > And the `componentDidUpdate` should be `componentDidMount`
> 
> ComponentDidMount was returning props value as undefined so i used componentDidUpdate..Thanks a lot for the solution..it works..really appreciate

No problem

**Comment by dashName** [comment]
> > > Hi @dashName , your state should be like this
> > > ```
> > >   state = {
> > >     tableCounters: []
> > >   };
> > > ```
> > > 
> > > 
> > > And your `addToCart` method should loop through the array of state counters and then update the state counter for the specific row, the way that you implemented it will do not work because it is setting the state on the "global" counter.
> > > I think this will do the trick
> > > ```
> > >   addToCard = rowIndex => {
> > >     this.setState(prevState => ({
> > >       tableCounters: prevState.tableCounters.map((item, index) => {
> > >         if (index === rowIndex) {
> > >           return { counter: item.counter + 1 };
> > >         }
> > >         return item;
> > >       })
> > >     }));
> > >   }
> > > ```
> > > 
> > > 
> > > And the `componentDidUpdate` should be `componentDidMount`
> > 
> > 
> > ComponentDidMount was returning props value as undefined so i used componentDidUpdate..Thanks a lot for the solution..it works..really appreciate
> 
> No problem

On above context:

 <div contentEditable='true' suppressContentEditableWarning={true} id='text-val'> {formatExtraData(rowIndex)} </div>

Currently it takes {formatExtraData(rowIndex)}  data as the value but I want to support userInput as well , i.e make the div editable so is it possible to support both features?
 
I tried with cell property but it is undefined

**Comment by Ymbere** [comment]
Hi, you can change the div that contains the number to a input so you can attach `onChange` method to it and support user input.

```jsx
  const dataFormatter = (cell, row, rowIndex, formatExtraData) => {
    return (
      <div>
        <div onClick={() => addToCart(rowIndex)}>
          <img src={plus} style={{ backgroundColor: "#2a4252" }} />
        </div>
        <input
          id="input-quantity"
          value={formatExtraData(rowIndex)}
          onChange={// Custom on change goes here}
        />
        <div onClick={() => removeFromCart(rowIndex)}>
          <img src={minus} style={{ backgroundColor: "#2a4252" }} />
        </div>
      </div>
    );
  };
```

**Comment by dashName** [comment]
> Hi, you can change the div that contains the number to a input so you can attach `onChange` method to it and support user input.
> 
> ```js-jsx
>   const dataFormatter = (cell, row, rowIndex, formatExtraData) => {
>     return (
>       <div>
>         <div onClick={() => addToCart(rowIndex)}>
>           <img src={plus} style={{ backgroundColor: "#2a4252" }} />
>         </div>
>         <input
>           id="input-quantity"
>           value={formatExtraData(rowIndex)}
>           onChange={// Custom on change goes here}
>         />
>         <div onClick={() => removeFromCart(rowIndex)}>
>           <img src={minus} style={{ backgroundColor: "#2a4252" }} />
>         </div>
>       </div>
>     );
>   };
> ```

I tried the same thing before but it won't update the value at all

**Comment by Ymbere** [comment]
@dashName, you can send your custom `onChange` method, so I can see if is there any problem?

**Comment by dashName** [comment]
> @dashName, you can send your custom `onChange` method, so I can see if is there any problem?

     const handleChange = (e) => {
            console.log(e.currentTarget.value,row)
            this.setState(prevState => ({
                tableCounters: prevState.tableCounters.map((item, index) => {
                        return { counter: e.currentTarget.value };
                })
            }));

        };
it is updating the value

**Comment by Ymbere** [comment]
Your `onChange` method is not actually changing the counter for a specific row, you need to pass along with the event the row index that you want to change the counter.

Like this

```jsx
onChange={e => onChange(rowIndex, e)}
```

Your `onChange` method will look like this

```jsx
  handleChange = (rowIndex, e) => {
    this.setState(prevState => ({
      tableCounters: prevState.tableCounters.map((item, index) => {
        if (index === rowIndex) {
          return { counter: e.currentTarget.value };
        }
        return item;
      })
    }));
  };
```

**Comment by dashName** [comment]
> Your `onChange` method is not actually changing the counter for a specific row, you need to pass along with the event the row index that you want to change the counter.
> 
> Like this
> 
> ```js-jsx
> onChange={e => onChange(rowIndex, e)}
> ```
> 
> Your `onChange` method will look like this
> 
> ```js-jsx
>   handleChange = (rowIndex, e) => {
>     this.setState(prevState => ({
>       tableCounters: prevState.tableCounters.map((item, index) => {
>         if (index === rowIndex) {
>           return { counter: e.currentTarget.value };
>         }
>         return item;
>       })
>     }));
>   };
> ```

yes you are right.Thanks

**Comment by Ymbere** [comment]
Hi @dashName, it worked properly?

**Comment by dashName** [comment]
> Hi @dashName, it worked properly?

seems to be working perfectly.Thanks

**Comment by dashName** [comment]
> > Hi @dashName, it worked properly?
> 
> seems to be working fine.But only thing is handleChange Triggers on Click on add to cart button as well so cart gets messed up

@Ymbere I see that onChange value doesn't update in formatExtraData.

**Comment by Ymbere** [comment]
Hi, I didn't understand, can you explain in more details?

**Comment by dashName** [comment]
> Hi, I didn't understand, can you explain in more details?

so in the below logic: handleChange = (rowIndex, e) => {
    this.setState(prevState => ({
      tableCounters: prevState.tableCounters.map((item, index) => {
        if (index === rowIndex) {
          return { counter: e.currentTarget.value };
        }
        return item;
      })
    }));
  };

the tableCounters should update to user input as well as formatExtraData(rowIndex) right..but it doesn't

**Comment by Ymbere** [comment]
I think you are missing the `e` on the `formatExtraData`, it should be

```jsx
formatExtraData(rowIndex, e)
```

**Comment by dashName** [comment]
> I think you are missing the `e` on the `formatExtraData`, it should be
> 
> ```js-jsx
> formatExtraData(rowIndex, e)
> ```

I think it seems to be working.I actually added defaultValue={formatExtraData(rowIndex)} to avoid the warning:Input elements should not switch from uncontrolled to controlled thats why the value was not updating.

**Comment by Ymbere** [comment]
> > I think you are missing the `e` on the `formatExtraData`, it should be
> > ```
> > formatExtraData(rowIndex, e)
> > ```
> 
> I think it seems to be working.I actually added defaultValue={formatExtraData(rowIndex)} to avoid the warning:Input elements should not switch from uncontrolled to controlled thats why the value was not updating.

You add a default value to the `input` tag?

**Comment by dashName** [comment]
> > > I think you are missing the `e` on the `formatExtraData`, it should be
> > > ```
> > > formatExtraData(rowIndex, e)
> > > ```
> > 
> > 
> > I think it seems to be working.I actually added defaultValue={formatExtraData(rowIndex)} to avoid the warning:Input elements should not switch from uncontrolled to controlled thats why the value was not updating.
> 
> You add a default value to the `input` tag?

yes

**Comment by dashName** [comment]
> > > I think you are missing the `e` on the `formatExtraData`, it should be
> > > ```
> > > formatExtraData(rowIndex, e)
> > > ```
> > 
> > 
> > I think it seems to be working.I actually added defaultValue={formatExtraData(rowIndex)} to avoid the warning:Input elements should not switch from uncontrolled to controlled thats why the value was not updating.
> 
> You add a default value to the `input` tag?

let say i want to reset the value of formatExtraData to 0 when add to cart is clicked so how can we do that?

**Comment by dashName** [comment]
Hey @Ymbere I know its been long since this discussion but just was curious if there is a way to sort the field.let say i incremented the quantity and sort one of the column so accordingly this quantity column should also be sorted accordingly right.
