### ISSUE TITLE
noDataIndication: throws a warning when providing an object which is not a string

### ISSUE THREAD

**Issue by Stefan-Reimer** [react-bootstrap-table/react-bootstrap-table2#1124]
The description of the API says:
> noDataIndication should be a callback function which return anything that will be showed in the table when data is empty.

But if i set `noDataIndication={<div>test</div>}` it will give the warning:
> Warning: Failed prop type: Invalid prop `noDataIndication` supplied to `BootstrapTable`.

It will still be shown correctly and as far as I understand a div should be included in 'anything' ;-)
So my guess is that the warning has to be removed. Or it is desired that only text is used. Than the API text has to be adjusted. 

(PS 'return' in the description should be 'returns')

**Comment by AllenFang** [comment]
@Stefan-Reimer I will fix this, thanks :)

**Comment by AllenFang** [comment]
fixed in newest version -> https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/11/09/version-bump.html
