### ISSUE TITLE
SearchBar error- Cannot read property 'searchable' of undefined

### ISSUE THREAD

**Issue by senthilmca90** [react-bootstrap-table/react-bootstrap-table2#1126]

**Comment by JEEVANJGA** [comment]
Hi got following error on using the search feature.

Need pointers on how to fix this.

![image](https://user-images.githubusercontent.com/8213715/66997959-0305b100-f0f1-11e9-818c-45b183d278c0.png)

**Comment by JEEVANJGA** [comment]
@senthilmca90 , you raised this issue right?
Could you please share information on this if you have found any fix.

**Comment by senthilmca90** [comment]
@JEEVANJGA first `stop` the server. then try to clear the cache use the below comment comment

`npm cache verify`

you upgrade all versions.

```
 "react-bootstrap-table-next": "^3.2.1",
    "react-bootstrap-table2-overlay": "^2.0.0",
   "react-bootstrap-table2-toolkit": "^2.1.0",
```
then start your server.  If you want clear idea you follow this storybook [ example link](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Basic%20Search%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
