### ISSUE TITLE
show data in table

### ISSUE THREAD

**Issue by nirkrumer** [react-bootstrap-table/react-bootstrap-table2#1127]
Hey there,
Im new to this component. As first stage im trying to put example string in my table.
For some reason it doesnt show me that.
What do I miss?
Thanks!

![image](https://user-images.githubusercontent.com/38032506/66685412-1e9e3100-ec85-11e9-9ddc-df5aefb63267.png)

![image](https://user-images.githubusercontent.com/38032506/66685426-2958c600-ec85-11e9-8398-e1c12aaa9b04.png)

**Comment by josh08h** [comment]
From the `columns` given I'd expect your `data` array to look like the following:

```
[
  { processName: 'process1', atomName: 'atom1', executionType: 'ex1', startTime: '2019-10-12T15:04:45+00:00', status: 'complete' }
]
```

**Comment by nirkrumer** [comment]
Hey, Thanks for the quick reply. It worked :)

Now I wanted to ask: 
Let's say I want to put image as a cell value (and not string).
For example, if the value of status == 'Completed' , the user will see green mark and so on.

**Comment by josh08h** [comment]
I suggest you look here https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel at column formatters

**Comment by nirkrumer** [comment]
Great, looks good.
I'll dive into that.

Thx!

**Comment by josh08h** [comment]
@AllenFang This can be closed.

**Comment by AllenFang** [comment]
HI guys sorry for lately reply.  Thanks @josh08h, your answer is perfect :)
