### ISSUE TITLE
Expanded table layout changed after navigating to a specific route then navigating back

### ISSUE THREAD

**Issue by thelonglqd** [react-bootstrap-table/react-bootstrap-table2#1129]
I have a table with with children expanded row (The row with caret is parent row and below it are its children) like the image below:
![table-ordered_censored](https://user-images.githubusercontent.com/13036097/66711547-362a0680-edb8-11e9-9ef1-45abb74d229a.jpg)

In this image, the dots (regardless green or red) of parent rows and children rows are in ordered. But, after navigating to a specific route (call it anotherRoute) on my React app and navigate back to this route, the table looks like this:
![table-chaos_cencorsed](https://user-images.githubusercontent.com/13036097/66711558-58238900-edb8-11e9-92fe-9eaf3454017e.jpg)

In the anotherRoute, I also have a table and I realize, after removing out the code for rendering table on that route, this weird bug is gone.

Is there any possiblity the reason for that weird bugs are from caching or rendering something of the table ?

P/s: Link for thí question on SOF: https://stackoverflow.com/questions/58360636/table-layout-changed-after-navigating-to-a-specific-route-then-navigating-back

**Comment by AllenFang** [comment]
@thelonglqd I don't have too much idea about this issue. But I guess it's not related to `react-bootstrap-table`. Let close it first until I got enough cases.
