### ISSUE TITLE
Hiding/Omitting Header Row

### ISSUE THREAD

**Issue by ddouglas** [react-bootstrap-table/react-bootstrap-table2#1130]
**Question**
I scoured the documentation and could not find what I was looking for, but I do apologize if I missed it.

I have a few scenarios where I need a table to display data but it is not necessary to display a header because the information that is being displayed is blatantly obvious.

So, is there a way to hide the header row and just display the data?

**Screenshots**
N/A
**codesandbox**
N/A

**Comment by Ymbere** [comment]
Hi, in the columns that you want the header to be hiding you can use the `header Classes`, with that you can use a custom CSS to omit the header.

[![Edit quizzical-grass-0o3dy](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-grass-0o3dy?fontsize=14)

**Comment by Ymbere** [comment]
After some research, I found another approach that may be slightly better, it did not require any custom CSS.

In the column that you want the header to be hidden just use this property.

```jsx
...
    headerAttrs: {
      hidden: true
    }
...
```

**Comment by ddouglas** [comment]
You my friend are a saint. I am not in a position to test this right now, but i will post as soon as I can.

Did I miss this in the documentation some where?

**Comment by Ymbere** [comment]
I don't think that you missed, actually is not like explicit that you can hide the header.
I checked for the `column.headerAttrs` in the documentation and after that, I looked for wich Attrs it accepts.

Here is the link for the documentation page where I found it, in case you want to check

[column.headerAttrs](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnheaderattrs-object-function)

**Comment by ddouglas** [comment]
Sorry this took so long to config. Work was hectic this week and I haven't been able to work the project that I created this issue for. I have confirmed that this is working. Thank You so much @Ymbere
