### ISSUE TITLE
Clear search text programatically

### ISSUE THREAD

**Issue by josh08h** [react-bootstrap-table/react-bootstrap-table2#1132]
**Is this feature requested before?**
No

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To be able to clear the search text programatically.

**Describe alternatives you've considered**
The alternative is to use the clear search button. This doesn't really fit my use case.

**Additional context**
Ideally I'd like to be able to clear the search text when I do some background data fetches. Currently you can only provide default search text, maybe we should allow the user to pass in their own search text as a prop.

**Comment by AllenFang** [comment]
@josh08h I have few questions about this requirement:

1. if I exposed an API to you to clear text, is it ok for you
2. when text being clear,  I think we should trigger a search(reset) on table, did you agree it?

**Comment by josh08h** [comment]
1) I guess the API (following React conventions) would be allowing the user to provide their own search text down to the child component?

2) Yes, if the search text is cleared then the results shown on the table should be reset

Is this a good beginner issue to tackle?

**Comment by AllenFang** [comment]
> I guess the API (following React conventions) would be allowing the user to provide their own search text down to the child component?

yes, just a react exposed api to achieve it.

I think it's an easy feature to implement, I will fix it soon, thank you

**Comment by AllenFang** [comment]
hello, the exposed API I mentioned is like:
```
// somewhere you can call  this.toolkit.onClear() . to clear text


<ToolkitProvider
  keyField="id"
  data={ products }
  columns={ columns }
  ref={ n => this.toolkit = n }
  search
>
  {
    props => (
      .....
    )
  }
</ToolkitProvider>
```

You can try above use case, it's implemented in any version. is it a solution for you?

**Comment by josh08h** [comment]
That would work, yes. Thanks
