### ISSUE TITLE
Make sorting trigger only on the sort caret when using custom header with other clickable elements

### ISSUE THREAD

**Issue by jhhr** [react-bootstrap-table/react-bootstrap-table2#1133]
**Problem**
When sorting is enabled on a column, clicking anywhere within the header element triggers sorting. If the header contains clickable elements like buttons or checkboxes, clicking these also triggers sorting.

**codesandbox**
https://codesandbox.io/s/brave-mccarthy-e4oed

This behaviour seems unintended when the headerFormatter is meant for adding pretty much anything into the header, including other elements that respond to clicks.

**No workarounds**
The onSort function is attached to the <th> element's onClick attribute so there doesn't seem to be any workaround possible with version 3.2.1.
See https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/be916d81a3c4e0a54aae8e7c622174ea8f94bac6/packages/react-bootstrap-table2/src/header-cell.js#L76

**Suggested fix**
Perhaps an additional optional property given to columns like `sortOnCaretOnly` which moves the executing of `onSort` to the `onClick` attribute on the `sortSymbol`? This would also add the additional requirement of giving the `sortCaret` function `onSort` as a third argument which the user then needs to handle, if they're using `sortCaret` on a column.

**Comment by AllenFang** [comment]
@jhhr you can just call `e.stopPropagation();` to avoid sorting happen when clicking on your custom button.
