### ISSUE TITLE
Set custom class on disabled/non-selectable rows (for selectRow)

### ISSUE THREAD

**Issue by mdeeter** [react-bootstrap-table/react-bootstrap-table2#1135]
I've looked through the API and cannot find a way to set a class (or style) on the rows that are non-selectable.

I'd like to grey out the text on those rows.

**Comment by Ymbere** [comment]
Hi, @mdeeter.
Looks like It really doesn't have an API to set the non-selectable rows a custom class, but you can make a workaround using the `rowClasses` property.

## Example
[![Edit Custom color for disabled rows](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/change-table-value-on-select-fork-noio6?fontsize=14)

**Comment by AllenFang** [comment]
@mdeeter we have this enhancement in newest release -> https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/11/16/version-bump.html

you can just learn how to custom the non-selectable row via [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Not%20Selectabled%20Rows%20Style&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Not%20Selectabled%20Rows%20Class&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

btw, thanks @Ymbere 's contribution, he made this become true.
