### ISSUE TITLE
Remote Panigation not working

### ISSUE THREAD

**Issue by subhamchatterjee** [react-bootstrap-table/react-bootstrap-table2#1137]
Remote pagination is not working as _onPageChange_ function is not allowing setState, to update the page. Please provide a solution or a way out of this problem.

`<BootstrapTable data={this.state.results} columns={columns} pagination={paginationFactory({page: this.state.page, sizePerPage: this.state.sizePerPage, totalSize: this.state.totalSize, onPageChange: this.onPageChange, onSizePerPageChange: this.onSizePerPageChange}) }`

**Comment by AllenFang** [comment]
@subhamchatterjee hello, sorry for lately reply, if you enable remote, please update state in `onTableChange`

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-remote.html#table-data-change
