### ISSUE TITLE
how to disable the frame when click the th cell

### ISSUE THREAD

**Issue by rdsuncn** [react-bootstrap-table/react-bootstrap-table2#1142]
**Question**
There is a deep frame when click the header of table。How to make it invisible?

**Screenshots**
![image](https://user-images.githubusercontent.com/30366045/68111396-0048ef80-ff2a-11e9-8c49-0cee3dcb0364.png)

**Comment by thimo1** [comment]
You can easily disable it with CSS

`
th:focus {
    outline: 0;
}
`

**Comment by AllenFang** [comment]
@thimo1  perfect answer.
