### ISSUE TITLE
global custom sortCaret

### ISSUE THREAD

**Issue by stilllife00** [react-bootstrap-table/react-bootstrap-table2#1144]
**Is this feature requested before?**
There was this PR but it got closed https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/407

**Is your feature request related to a problem? Please describe.**
The `sortCaret` is customizable on a per-column basis while generally we need an unique customization of the caret for all our tables and columns

**Describe the solution you'd like**
While the problem can somehow be solved via CSS overrides, the strict DOM structure (order, caret) does not allow a good customization. In our case we would like to keep both carets (up and down) even when there is one active.

**Describe alternatives you've considered**
Setting the same `sortCaret` in every column, but it creates more code boilerplate and IMHO is counterintuitive. Is like we would have to set global styles on every columns.

**Additional context**
![image](https://user-images.githubusercontent.com/3191603/68280039-05ff1c00-0075-11ea-9066-b96bb5fa6a63.png)
⬆️ Carets are hard to customize

**Comment by AllenFang** [comment]
hello @stilllife00 thanks for this suggestion, would you please give me some example to describe how will you like to custom the sort, it will also be better to show me which part of DOM you feel is not good on customization, I want to consider more and know the root cause of bad customization on sorting.  Because so far I still feel `sortCaret` can solve at least 90% sort customization but anyway, I'm not the real user, so your any idea is very welcome.  Thanks!!

**Comment by stilllife00** [comment]
Sorry I didn't have time to prepare a codesandbox. sortCaret works but it must be specified for every table and every column we have. Imagine a project with 10 tables and 5 columns each, it means 50 rows of code used just to to include the custom caret. Caret are generally global props of a project so configured only once. 

I can do the config in a common Table component with custom settings but it is a bit more complex given the fact that columns are specific to each table (but the caret is not).

So if possible it would be good imho to have a sortCaret prop at TABLE level instead of at column level.

**Comment by AllenFang** [comment]
> So if possible it would be good imho to have a sortCaret prop at TABLE level instead of at column level. If it is not clear I will explain better with a codepen comparison.

I agree, I will spend some time to enhance it. thanks this idea.!

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/12/07/version-bump.html)

Now you can configure `sort` prop on `BootstrapTable`:
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#one-time-sorting-configuration
