### ISSUE TITLE
Add class to expanded column

### ISSUE THREAD

**Issue by clarkbrent** [react-bootstrap-table/react-bootstrap-table2#1146]
When I went through the documentation, I did not see any props that allowed classes to be directly assigned to the `showExpandColumn` header column. By default it has no ID or classes assigned to it which makes adding styling to it somewhat difficult out of the box. This can be seen on a [few of the expanded row storybooks](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Only%20Expand%20by%20Indicator&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

Would it be potentially feasible to add a `showExpandColumn` column class prop similar to other column class props?

**Comment by AllenFang** [comment]
Hello @clarkbrent sorry for lately reply, I think I will give a classname on the `td` element so that you can custom it. It's just a quick solution, if I have time, I will implement a props way for customizing the style/class,

**Comment by AllenFang** [comment]
fixed in `react-bootstrap-table-next@3.3.1`

upgrade to newest version and there will be some default class :)
