### ISSUE TITLE
New filterPosition prop causes react "unique key" error in console

### ISSUE THREAD

**Issue by elmoro666** [react-bootstrap-table/react-bootstrap-table2#1157]
**Describe the bug**
When the newly introduced filterPosition prop is set to "top", I get the "Each child in a list should have a unique key prop",  in the console. I haven't tested with "bottom", but it is probably the same.

**To Reproduce**
1. Just set filterPosition to "top" and check console

**Screenshots**
![image](https://user-images.githubusercontent.com/15340253/68526620-4f9e6f80-02de-11ea-98e6-e76dd4e65dc5.png)

The new FilterCell row is missing key
![image](https://user-images.githubusercontent.com/15340253/68526635-7f4d7780-02de-11ea-8dfe-1ee4ac431650.png)

**codesandbox**
I will make a codesandbox if you need one. This should be very simple to reproduce

**Comment by AllenFang** [comment]
@elmoro666 I will fix it in next version, thanks for issue report

**Comment by AllenFang** [comment]
fixed in `react-bootstrap-table-next@3.3.1`

**Comment by elmoro666** [comment]
Thanks Allen!

**Comment by Ryota201** [comment]
> fijo en`react-bootstrap-table-next@3.3.1`

@AllenFang  We are in version 4.0.3 and the problem continues
