### ISSUE TITLE
React Table mobile view

### ISSUE THREAD

**Issue by nirkrumer** [react-bootstrap-table/react-bootstrap-table2#1159]
I try to see the table on mobile view.
I see it wrong..
![image](https://user-images.githubusercontent.com/38032506/68587626-2cb3bd00-0490-11ea-939b-a4ba6f5344bc.png)

Is there any configuration to set this up for adjusted mobile version? 

Thanks,
Nir
![mobile_view](https://user-images.githubusercontent.com/38032506/68587738-71d7ef00-0490-11ea-994b-cd1ef915f47d.PNG

**Comment by AllenFang** [comment]
so far we don't have better responsive solution. I have some idea but need time lol . I think the only way is try to add the some styles or class to make the cell content change line or truncate etc.
