### ISSUE TITLE
Issues with dynamically added row events

### ISSUE THREAD

**Issue by niyaza3** [react-bootstrap-table/react-bootstrap-table2#1161]
I initialised the bootsrap table with 2 rows and added the 3rd and 4th row dynamically with custom action

`
const data = [{name: 'test', id:1}, {name: 'test2', id:2}]
const columns =  [
 {
            dataField: '',
            text: '',
            sort: false,
            formatter: function (value, row) {
                return (
                    <span className="btn-row-remove">
                        <i className="fa fa-times" onClick={() => console.log(data)} />
                    </span>
                )
            },
        }
]
`
the onclick handler prints always the initialised data  [{name: 'test', id:1}, {name: 'test2', id:2}], how can i make it  print ( i have a scenario to delete newly added row)[{name: 'test', id:1}, {name: 'test2', id:2}, , {name: 'test3', id:3}, , {name: 'test4', id:4}]

**Comment by AllenFang** [comment]
@niyaza3 would you please put your example code to codesandbox? that will be easy for me to reproduce the issue you faced.  thanks

**Comment by Graig123git** [comment]
@niyaza3 did you resolve this ? i am facing the same issue
