### ISSUE TITLE
Dynamic checkbox 

### ISSUE THREAD

**Issue by rohit8080** [react-bootstrap-table/react-bootstrap-table2#1162]
I want to show a check box, like my api is returning array of objects, which have boolen values, I want to show the checkbox is checked when the value is true, and uncheck for false.

I tried to implement it with the formattor at column level for the above  scenario as below
{
   dataField: "IsBikeShelterAvailable",
   text: "Bike Shelter",
   formatter: (value) => {
   (value === true) ?
     return <input type="checkbox" defaultValue={value} checked />
     : <input type="checkbox" defaultVale={value} />
   }
   }
 }

The above code supports initial render, but as soon as I check/uncheck any checkbox, the event is not getting captured, or it is not maintaining the state. Is there any other way to handel the scenario?

Check to Uncheck ====> off
Uncheck to check =====> on

On and off values are getting stored in the array in the afterSaveCell event

**Comment by AllenFang** [comment]
@rohit8080 `afterSaveCell` only work if you enable cell editing. I didn't know if you enable it or not. but ket me guess you didn't. In you case you can just disable cell editing but just add `onClick` or `onChange` handler to your checkbox component and handle the changes. It's quite simple solution
