### ISSUE TITLE
SizePerPageDropdownStandalone not keyboard accessible

### ISSUE THREAD

**Issue by justinjamesp1988** [react-bootstrap-table/react-bootstrap-table2#1163]
I am not able to select the result per page drop down using the keyboard, and noticed the tab index is -1, have updated the tab index. but still not able to select.

**Comment by AllenFang** [comment]
I will enhance this, thanks

**Comment by AllenFang** [comment]
@justinjamesp1988 I can press `tab` key to navigate to size per page dropdown, any idea?

**Comment by AllenFang** [comment]
close it due to no response
