### ISSUE TITLE
Nested data and select filter: I want "logical" value to be a number and a "display" value to be a string? Possible?

### ISSUE THREAD

**Issue by Popov85** [react-bootstrap-table/react-bootstrap-table2#1165]
Is it possible to distinguish between "logical" and "display" value for a nested column? Sorry but I didn't find any mentioning of it in the [docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html)
Say, I have 
```
 {
            dataField: 'position.name',
            text: 'Position',
            sort: true,
            filter: selectFilter({
                options: getPositions(users)
            }),
            editable: true
        }
}
```
Where getPositions return a map like this:
```
{
  1: 'Head',
  2: 'Staff',
  3: 'User'
};
```

If I put 

> dataField: 'position.name'

, I am forced to use names as map key, hence getPositions should return:
```
{
  'Head': 'Head',
  'Staff': 'Staff',
  'User': 'User'
};
```

If I put 

> dataField: 'position.id'

, user will see only IDs.. which is not acceptable;

Any fiddling with [formatters](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) to achieve what I just described failed..

Smth. like this might be to achieve it:

```
 {
            dataField: 'position',
            logicalValue: 'position.id',
            displayValue: 'position.name'
            text: 'Position',
            sort: true,
            filter: selectFilter({
                options: getPositions(users)
            }),
            editable: true
        }
}
```

**P.S.** The reason I want number as a key is that for **remote** cell editing, it is much simpler to work with numeric ID then with strings as identifiers" to send update request to server. (Server usually operates longs/integers as main IDs)

**Comment by Popov85** [comment]
OK, I got it working.
Here is the how:
```
 {
            dataField: 'position.posId',
            text: 'Position',
            sort: true,
            editable: true,
            filter: selectFilter({
                options: positions.forFilter
            }),
            formatter: cell => positions.forFilter[cell],
            editor: {
                type: Type.SELECT,
                options: positions.forEdit
            }
        },
```
Here I maintain multiple formats for the same data to feed it to the table: actual, for filter and for edit;

**Actual** position object:
```
 {
        "posId": 1,
        "name": "Head"
    }
```
**For filter it is:**

```
const forFilter = {
    1: "Head",
    2: "Staff",
    3: "User"
}
```

**For edit it is:**
```
const forEdit = [
    {
        value: 1,
        label: 'Head'
    },
    {
        value: 2,
        label: 'Staff'
    },
    {
        value: 3,
        label: 'User'
    }
]

```
Now it works as expected, but if it could be done simpler I would really appreciate!

**Comment by AllenFang** [comment]
@Popov85 filter also accept an array

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Preserved%20Option%20Order%20on%20Select%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/641
