### ISSUE TITLE
table Search and export to csv

### ISSUE THREAD

**Issue by nirkrumer** [react-bootstrap-table/react-bootstrap-table2#1167]
Hey , I'm trying to configure the elements under ToolKitProvider.
I see the elements in the page, but nothing happens. What is missing??
I attach also my code. (I write in typescript - .tsx file)

![image](https://user-images.githubusercontent.com/38032506/68992635-a4aa2a80-0876-11ea-9e60-85f963151b62.png)

[toolkitprovider.txt](https://github.com/react-bootstrap-table/react-bootstrap-table2/files/3854130/toolkitprovider.txt)

**Comment by nirkrumer** [comment]
By the way, I tried the native component and also the customized way
Same results

**Comment by AllenFang** [comment]
```js
<ToolkitProvider
  keyField="id"
  data={ products }
  columns={ columns }
  exportCSV
   ......
>
  {
    props => (
      <div>
         ......
        <BootstrapTable { ...props.baseProps } /> .  /// .  <<<<<<< here, you forget to put baseProps to BootstrapTable
      </div>
    )
  }
</ToolkitProvider>
```

**Comment by nirkrumer** [comment]
Great it works :)
I created my own custom search bar
Now, I want to create a custom clear button. What is the command to erase the values from the customized searchbar?

Attached my tries

![image](https://user-images.githubusercontent.com/38032506/69477115-e6911e80-0dea-11ea-989a-c9ed9997b988.png)

**Comment by nirkrumer** [comment]
hey , any thoughts?
Thanks
