### ISSUE TITLE
Column toggle hidden column expanded row colspan incorrect

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [react-bootstrap-table/react-bootstrap-table2#1168]
**Describe the bug**
When click on row to expend, new expended row have wrong colspan. Colspan of new row will not consider columns hidden by default (column toggle)

**To Reproduce**
open codesandbox https://codesandbox.io/s/rough-sound-q2bcb
1. click on Address button (on top) to show the hidden address column
2. Click on any row to open expended row
3. Observe the expended row div (which have black border)
4. Colspan of expended row is only 2 (Two is the count of columns which was not hidden)
5. It is not considering the hidden column (when visible) to calculate colspan

**Screenshots**
![Screenshot from 2019-11-16 12-01-40](https://user-images.githubusercontent.com/34174422/68992844-0a8fb580-0869-11ea-8b89-0dc2303b3de5.png)

**codesandbox**
Added above in reproduce steps.

**packages**
Latest packages available of today
"react-bootstrap-table-next": "^3.3.1",
"react-bootstrap-table2-paginator": "^2.1.0",
 "react-bootstrap-table2-toolkit": "^2.1.0",

**Similar issue (closed)**
Expanded row column span does not update #836

**Comment by AllenFang** [comment]
@rizwan-ishtiaq  I will fix it ASAP, thanks !!

**Comment by AllenFang** [comment]
fixed in `react-bootstrap-table-next@3.3.2`, [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/12/02/version-bump.html)
