### ISSUE TITLE
filterPosition property does not work with rowSelect

### ISSUE THREAD

**Issue by elmoro666** [react-bootstrap-table/react-bootstrap-table2#1169]
**Describe the bug**
When filterPosition is set to 'top', and rowSelect is enabled, it places the filterboxes in the wrong columns. Codesandbox should make it fairly easy to spot the problem. Just toggle the buttons on top

**codesandbox**
https://codesandbox.io/s/react-bootstrap-filterposition-pnfxn

**Comment by AllenFang** [comment]
@elmoro666 I will fix it soon, thanks!

**Comment by AllenFang** [comment]
fixed in `react-bootstrap-table-next@3.3.2`, [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/12/02/version-bump.html)
