### ISSUE TITLE
Storybook logger not working

### ISSUE THREAD

**Issue by AllenFang** [react-bootstrap-table/react-bootstrap-table2#117]
@Chun-MingChen I tried story book logger a while ago, but seems like there's something wrong and I still got fail, I hope all of the stories's `console.log` can be output to storybook logger panel, thanks

**Comment by Chun-MingChen** [comment]
@AllenFang 

Sure that's would be fantastic if log message on the storybook panel. I'll give a try :)

**Comment by AllenFang** [comment]
Thanks
