### ISSUE TITLE
How to display multiple items in single cell of each row?

### ISSUE THREAD

**Issue by dashName** [react-bootstrap-table/react-bootstrap-table2#1172]
I have this array of data: Products:Array(102)
>0:{id:’1’,productDetail:Array(5) > 0:{title:’item-1’,code:’11’}1:{title:’item-2’,code:’12’}}
>1:{id:’2’,productDetail:Array(4) > 0:{title:’item-1-1’,code:’11’}…..so on}
…..
…..
…..

I want to display in my table one column header as items and display

<img width="130" alt="Screen Shot 2019-11-19 at 9 51 09 AM" src="https://user-images.githubusercontent.com/56317909/69172230-4ff2f380-0ab2-11ea-8b3d-96b28b309b8c.png">

**Comment by Ymbere** [comment]
Hi, could you send a sample of your **Products** array? Don't need to be the full array only 10 records are fine, with that I can try to reproduce the behavior that you expect.

**Comment by dashName** [comment]
> Hi, could you send a sample of your **Products** array? Don't need to be the full array only 10 records are fine, with that I can try to reproduce the behavior that you expect.

{
  "data": [
    {
      "id": "string",
      "product": [
        {
          "title": "string",
        },
        {
          "title": "string",
        },
        {
          "title": "string",
        }
      ],
    },
    {
      "id": "string",
      "product": [
        {
          "title": "string",
        },
        {
          "title": "string",
        }
      ],
    },
    {
      "id": "string",
      "product": [
        {
          "title": "string",
        },
        {
          "title": "string",
        }
      ],
    },{
      "id": "string",
      "product": [
        {
          "title": "string",
        },
        {
          "title": "string",
        }
      ],
    }
    {
      "id": "string",
      "product": [
        {
          "title": "string",
        },
        {
          "title": "string",
        },
        {
          "title": "string",
        }
      ],
    },

    
  ]
}

**Comment by dashName** [comment]
> > Hi, could you send a sample of your **Products** array? Don't need to be the full array only 10 records are fine, with that I can try to reproduce the behavior that you expect.
> 
> {
> "data": [
> {
> "id": "1",
> "product": [
> {
> "title": "book-1",
> },
> {
> "title": "book-2",
> },
> {
> "title": "book-3",
> }
> ],
> },
> {
> "id": "2",
> "product": [
> {
> "title": "note-1",
> },
> {
> "title": "note-1",
> }
> ],
> },
> {
> "id": "3",
> "product": [
> {
> "title": "pen-1",
> },
> {
> "title": "pen-2",
> }
> ],
> },{
> "id": "4",
> "product": [
> {
> "title": "copy-1",
> },
> {
> "title": "copy-2",
> },
> {
> "title": "copy-1",
> },
> {
> "title": "copy-2",
> },
> {
> "title": "copy-1",
> },
> {
> "title": "copy-2",
> }
> ],
> }
> {
> "id": "5",
> "product": [
> {
> "title": "name-1",
> },
> {
> "title": "name-2",
> },
> {
> "title": "name-3",
> }
> ],
> },
> 
> ]
> }
> 
> id item
> 
> <img alt="Screen Shot 2019-11-19 at 5 11 45 PM" width="253" src="https://user-images.githubusercontent.com/56317909/69200394-d843b980-0aef-11ea-84a2-51e3b5933bc0.png">
> 
> will this work?
> @Ymbere

I am trying something like below:

 const productInfoFormatter =(cell) => {
            console.log(cell);
            if(cell.length === 1){
                return (
                    cell[0].title
                )
            }else {
                cell.map(x => {
                    console.log(x.title)
                    return (
                        x.title
                    )
                })
            }

        };

it works when cell.length is 1 but not for multiple

**Comment by Ymbere** [comment]
Hi @dashName, could you create a [Code Box](https://codesandbox.io/s/) with your code?
With that, it's easier to help you.

**Comment by dashName** [comment]
> Hi @dashName, could you create a [Code Box](https://codesandbox.io/s/) with your code?
> With that, it's easier to help you.

https://codesandbox.io/s/pedantic-allen-i2u7e
@Ymbere

**Comment by Ymbere** [comment]
Hi, @dashName your implementation is correct you just forgot a `return` statement, your code will look like this.
```jsx
  const productInfo = (cell, row, rowIndex, formatExtraData) => {
    console.log(cell);
    if (cell.length === 1) {
      return cell[0].title;
    } else {
      // Return here was missing
      return cell.map(x => {
        console.log(x.title);
        return x.title;
      });
    }
  };
```
Although you can make the code more clean removing the first  `if` statment

```jsx
  const productInfo = (cell, row, rowIndex, formatExtraData) => {
    console.log(cell);
    return cell.map(x => {
      console.log(x.title);
      return x.title;
    });
  };
```

**Comment by dashName** [comment]
> Hi, @dashName your implementation is correct you just forgot a `return` statement, your code will look like this.
> 
> ```js-jsx
>   const productInfo = (cell, row, rowIndex, formatExtraData) => {
>     console.log(cell);
>     if (cell.length === 1) {
>       return cell[0].title;
>     } else {
>       // Return here was missing
>       return cell.map(x => {
>         console.log(x.title);
>         return x.title;
>       });
>     }
>   };
> ```
> 
> Although you can make the code more clean removing the first `if` statment
> 
> ```js-jsx
>   const productInfo = (cell, row, rowIndex, formatExtraData) => {
>     console.log(cell);
>     return cell.map(x => {
>       console.log(x.title);
>       return x.title;
>     });
>   };
> ```

<img width="253" alt="69200394-d843b980-0aef-11ea-84a2-51e3b5933bc0" src="https://user-images.githubusercontent.com/56317909/69392551-2f31c600-0c8b-11ea-9655-4360b61fe9c8.png">


to display something like like can we add a condition to check the length of array and if the length is > 2 can display + rest of items?

**Comment by dashName** [comment]
> > Hi, @dashName your implementation is correct you just forgot a `return` statement, your code will look like this.
> > ```
> >   const productInfo = (cell, row, rowIndex, formatExtraData) => {
> >     console.log(cell);
> >     if (cell.length === 1) {
> >       return cell[0].title;
> >     } else {
> >       // Return here was missing
> >       return cell.map(x => {
> >         console.log(x.title);
> >         return x.title;
> >       });
> >     }
> >   };
> > ```
> > 
> > 
> > Although you can make the code more clean removing the first `if` statment
> > ```
> >   const productInfo = (cell, row, rowIndex, formatExtraData) => {
> >     console.log(cell);
> >     return cell.map(x => {
> >       console.log(x.title);
> >       return x.title;
> >     });
> >   };
> > ```
> 
> <img alt="69200394-d843b980-0aef-11ea-84a2-51e3b5933bc0" width="253" src="https://user-images.githubusercontent.com/56317909/69392551-2f31c600-0c8b-11ea-9655-4360b61fe9c8.png">
> 
> to display something like like can we add a condition to check the length of array and if the length is > 2 can display + rest of items?

Yes I am able to do this thanks
