### ISSUE TITLE
Why No visible columns detected error is showing. how to resolve this ?

### ISSUE THREAD

**Issue by srikanthpathlavath** [react-bootstrap-table/react-bootstrap-table2#1176]

**Comment by AllenFang** [comment]
You can't fix it. because no visible column for a table is meaningless, avoid to render table when there's no any column visible is best idea.

**Comment by AshwinTayson** [comment]
This is not the right way to handle it. There should be default handler like No data found for columns as well.

**Comment by Tzahi12345** [comment]
Can someone expand on what this error means? Does it mean that no data was put into the table, or that no columns were defined (or both)?

Thanks!

EDIT: I got it! It means no columns were defined :)

**Comment by Aranguez** [comment]
Just pass [ { dataField: "", text: "" } ] to the columns prop and should be no problem

**Comment by ahujahbti** [comment]
> Just pass [ { dataField: "", text: "" } ] to the columns prop and should be no problem

Thanks this worked for me.
