### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by UbaidRajputt** [react-bootstrap-table/react-bootstrap-table2#1177]
Hi there, below is the link to codesandbox for the demo of my code, I am using react bootstrap table 2, everything is working perfectly fine but when I add text filter to my columns and use the filters, the tables crash, but search is also implemented and it works absolutely fine, but when i input some data into filter field it crashes, please ca you help me with this issue?
https://codesandbox.io/s/ubaid-rajputt-ixv90

**Comment by AllenFang** [comment]
@UbaidRajputt I don't see any content in the codesandbox, would you please check it again? thanks

**Comment by UbaidRajputt** [comment]
![Capture](https://user-images.githubusercontent.com/43198235/69958191-11cfe800-1526-11ea-9957-f5626ddd9519.PNG)

**Comment by UbaidRajputt** [comment]
See it is working, open the link and switch the button to the top right to current module view

**Comment by AllenFang** [comment]
Hello @UbaidRajputt please don't use `react-bootstrap-table2-overlay` which has some critical bug and can't be solve in near future. sorry about that, when you remove the `overlay` prop from `BootstrapTable`, everything will be fine.
