### ISSUE TITLE
Forcefully Avoid Filter Clean, Pagination Defaulting to first Page and Sort Clear

### ISSUE THREAD

**Issue by virasatkhan** [react-bootstrap-table/react-bootstrap-table2#1180]
**Question**

Q1) How can I forecefully avoid a condition where my filters that are getting auto-reseted when I perform some action on my table like expand Row.

Q2) How can I forecefully avoid same condition with pagination where the pagination is getting auto resetted to page1 of my results table when I expand Row.

Q3) Similar condition with Sort where the sort is getting auto resetted when I perform expandRow.

**Comment by virasatkhan** [comment]
Hello Allen - If you can tell me the complete variable list of (Pagination,Filter & Sort), I can try to work around this with setState. I was thinking to read for example the filterValue (if that is what the variable is) and maintain it through out. Same with pagination and Sort.

**Comment by virasatkhan** [comment]
I think I cannot use the filterVal outside your component, the only way for me is to maintain the states of (filter, pagination, sort), still figuring out a way to maintain states. If you know an easy way, please propose.

**Comment by virasatkhan** [comment]
My usage of BootstrapTable is like this and I have a different component to expandRow


       <BootstrapTable keyField={'id'} columns={columns} data={this.state.resultdata}
        striped={false} hover={true} tabIndexCell={true} condensed={true}
        bootstrap4={true} classes="react-bootstrap-table2" bordered={false}
        expandRow={ expandRow } options={options1}
        pagination={ paginationFactory() } filter={ filterFactory() } 
        />





    const expandRow = {
      onlyOneExpanding: true,      
      renderer: row => {
        let id = row.apicall.split('~#~')[3]        
        let formatted = this.state.statusmsg[id]
        let status = ""
        let summary = ""
        let summary1 = ""
        let bgClr = ""        
        console.log(this.state)
        if(id in this.state.statusmsg){
          if(formatted.indexOf('; Summary') > -1) {
            bgClr = formatted.substring(formatted.indexOf('$ ')+2)  // Virasat added bgColor of the expand cell coming form python view.
            status = formatted.substring(0, formatted.indexOf('; Summary'));
            summary1 = formatted.substring(formatted.indexOf('; Summary') + 2); // temp summary with bgClor
            summary = summary1.substring(0, summary1.indexOf('$ ')) // final summary slicing off bgclr
          }
          return(
            <span className="help-text text-left" style={{backgroundColor: bgClr}}>{ status }<br /><br />{summary}</span>
          )

        } 
        else {
          this.setState({
            nonExpandable: [parseInt(id)],
            expanded: [],
  
      
          })
        }        
      },
      nonExpandable: this.state.nonExpandable,
      expanded: this.state.expanded
    }

**Comment by virasatkhan** [comment]
And I have a button against each row to populate that expandRow <division>, My problem is when i click on that button, my filter, pagination and sort is getting auto-resetted to none.

**Comment by virasatkhan** [comment]
I was able to prevent the pagination defaulting to page#1 with states and currentPage. Can someone help with the Filter and Sort that is getting reset to null when I click that button against each row to populate my expandRow?

All that I want to know, is there a way to perform some stateSet onFilter or something similar with Sort?

**Comment by AllenFang** [comment]
@virasatkhan sorry boss, I'm too late to reply your issue.

about sorting, so far we don't have a way to manage the sort, the only way is configure `defaultSort`: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-sort.html#default-sort

about filter, i think it's same situation, no directly solution, but the workaround is you can use `onFilter` to listen the filtering change and keep it in somewhere, then perform the programmatically filter when you need

[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Text%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) show you how to manually filter and [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/filter-props.html#textfilteronfilter-function) is `onFilter` docs

Please let me know if the problem still there. thanks

**Comment by virasatkhan** [comment]
yeah I used onFilter to get a workaround filters.
Regarding Filters, when i use onSort like below I don't see any change in the table content when I click the sort carets. I believe it's always defaulting to 'desc', is there a way to allow it to get changed as per what my users will click on the table header for sort?

        **onSort: (field,order) => {           
          this.setState({
            sortOrder: order,
            sortName: field
          })
        },**

**Comment by AllenFang** [comment]
@virasatkhan sorry like I mentioned above, we don't support the sorting management, But I can tr y to implement it asap.  thanks

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/12/07/version-bump.html)

[ONLINE DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Sort%20Table&selectedStory=Sort%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

[DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#manage-sorting-state)
