### ISSUE TITLE
Hide columns (no toogling)

### ISSUE THREAD

**Issue by theocerutti** [react-bootstrap-table/react-bootstrap-table2#1181]
Hello,

I would like to hide completely a column if a user is not admin.
I know there is an option to 'hide' it (hidden) but the problem is that we can show it with the toogler...
For example:

We have a table of sales:
```
| Products | Prices      |  
|------------------------|  
|  Cap     |   30€       |  
|------------------------|  
|  .....   |   ...       |  
|------------------------|  
```

Default Users (not admin) can just see these columsn (products and prices)

However Administrator can see:

```
| Products | Prices      |   Admin Tools
|------------------------| -----------------------|
|  Cap     |   30€       |  Delete product        |
|------------------------| -----------------------|
|  .....   |   ...       |  ....                  |
|------------------------| -----------------------|
```

Is it possible ??

**Comment by Devkutt** [comment]
Maybe you can generate the columns in your render method and only add the column if the user is an admin.
```javascript
render() {
[...]
const columns = user.isAdmin ? [Products, Prices, Admin Tools] : [Products, Prices];
[...]
<BootstrapTable columns={columns} [...] />
}
```

**Comment by virasatkhan** [comment]
or maintain the state of a bool variable based on isAdmin and set it a true/false and use that in your table as hidden: {this.state.isAdmin}. Just a thought, never tried and I am just learning react.

**Comment by AllenFang** [comment]
I think above solution is all good. the other workaround is turn off the column toggle for regular user  or just exclude the admin columns when user is non-admin.
