### ISSUE TITLE
How Do I include the Footer in the ExportCSVButton

### ISSUE THREAD

**Issue by tommydev** [react-bootstrap-table/react-bootstrap-table2#1188]
**Question**
I have added a footer to the columns of my table but its not showing in the CSV file when exporting.  I am using the ExportCSVButton.

There seems to be an option in the old version setting a property of footer=true, however, I don't see that option in react-bootstrap-table2

Please help!

Thanks

**Comment by AllenFang** [comment]
@tommydev so far we didn't allow to export the content of footer to csv, I will implement it ASAP, thanks

**Comment by tommydev** [comment]
Thank you. 

Do you have an ETA.  Just asking because we are hoping to goto production on 12/16.

Thanks again.

**Comment by AllenFang** [comment]
@tommydev wow, seriously I'm busy on my job, I will try to find some time in this weekend. but I can't tell you the ETA, sorry about that.

**Comment by tommydev** [comment]
Im sorry Allen I didn't mean to be pushy i was just curious so I could plan ahead.  Thanks again

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/12/07/version-bump.html)

```js
<ToolkitProvider
  keyField="id"
  data={ products }
  columns={ columns }
  exportCSV={ {
    ignoreFooter: false
  } }
>
```

**Comment by tommydev** [comment]
Allen, Thanks for getting this out.  I am seeing an issue though when exporting the footer using footerFormatter the footer columns are rending [object.object]
![Screen Shot 2019-12-11 at 12 08 57 PM](https://user-images.githubusercontent.com/1158137/70643792-a534a780-1c0f-11ea-9663-0ef4449ec351.png)
