### ISSUE TITLE
react "unique key" error in console

### ISSUE THREAD

**Issue by Yuki-Zhao** [react-bootstrap-table/react-bootstrap-table2#1192]
Use the react-bootstrap-table-next": "^3.3.2
There is an error in console. i
![image](https://user-images.githubusercontent.com/22816207/70195988-3b655b00-1742-11ea-8c67-b0842159e712.png)

**Comment by AllenFang** [comment]
@Yuki-Zhao it's not an issue, because we use `keyField` as key on each row, this error will be throw when you have same key in data.

**Comment by Yuki-Zhao** [comment]
but the type of keyField is string. how to set different ?
![image](https://user-images.githubusercontent.com/22816207/70299725-ac833c00-1830-11ea-824b-eb0a48f99871.png)

**Comment by Yuki-Zhao** [comment]
![image](https://user-images.githubusercontent.com/22816207/70299875-113e9680-1831-11ea-8d1e-992f4763c4ec.png)

**Comment by AllenFang** [comment]
`keyField` is specified to a column which is unique, for ex: `id`

so in your data, `id` field should be unique:
```js
[{
  id: 1,
  name: "xxxx"
}, {
  id: 2,
  name: "yyy"
}]
```

If you don't have any column can be unique, you can just transform them to generate a sequence key before render table.

**Comment by Yuki-Zhao** [comment]
I got it ! thanks

**Comment by Ryota201** [comment]
> `keyField` se especifica en una columna que es única, por ejemplo: `id`
> 
> por lo que en sus datos, el campo debe ser único:`id`
> 
> ```js
> [{
>   id: 1,
>   name: "xxxx"
> }, {
>   id: 2,
>   name: "yyy"
> }]
> ```
> 
> Si no tiene ninguna columna que pueda ser única, puede transformarlas para generar una clave de secuencia antes de la tabla de procesamiento.

Hello @AllenFang  how can I generate a sequence key before the processing table if I don't have a unique column? Could you show me an example please!
