### ISSUE TITLE
How to load an icon after editing another cell

### ISSUE THREAD

**Issue by kilofafeure** [react-bootstrap-table/react-bootstrap-table2#1193]
**Question**
I would like to know if it's possible to load an icon in a cell after edit another cell. I've been able to edit a cell but after that I can't load an icon on the next one

**Screenshots**
![image](https://user-images.githubusercontent.com/27411445/70247156-3079ed00-1779-11ea-9763-56805590b516.png)
![image](https://user-images.githubusercontent.com/27411445/70247186-3ec80900-1779-11ea-96e2-dc4843dcc109.png)

Thanks advance!
Best regards!

**Comment by AllenFang** [comment]
1. use [`cellEdit.afterSaveCell`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/cell-edit-props.html#celleditaftersavecell-function) listener to know when the cell being saved
2. in this listener, you can modify your data to generate a icon for a specified column
3. render component by setState or foreceupdate etc.
