### ISSUE TITLE
row height

### ISSUE THREAD

**Issue by MaheshYTech** [react-bootstrap-table/react-bootstrap-table2#1199]
please let me know how to set row height of rct-bs-tbl-next.
what i following
class Itable extends Component {
    rowStyle = (row, rowIndex) => {
        // row.index = rowIndex;
        // const style = {};
        // style.height = '15px';
        // return style;
        return {height: '10px'}
    }
  render(){
   return(
     <div>
                <BootstrapTable 
                    keyField='id' 
                    data={ products } 
                    columns={ columns } 
                    hover
                    rowStyle = {this.rowStyle}
                    bordered={true}
                    selectRow={ { mode: 'radio', clickToSelect: true } }
                />
     </div>
)
}

but i cannot set  row height .

earliest reply will be appreciated
}

**Comment by Ymbere** [comment]
Hi @MaheshYTech you can use `rowStyle={{ height: '100px'}}`.
### Here is a working example
[![Edit dreamy-pasteur-hce4v](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-pasteur-hce4v?fontsize=14&hidenavigation=1&theme=dark)

**Comment by AllenFang** [comment]
Thanks @Ymbere

**Comment by MaheshYTech** [comment]
Thanks Xavier

**Comment by kyou-ennbunn** [comment]
rowStyle={{ height: '100px'}}. I tried this,but it didnt work
