### ISSUE TITLE
TableHeader width not matching column width

### ISSUE THREAD

**Issue by tylerkeesling** [react-bootstrap-table/react-bootstrap-table2#120]
<img width="929" alt="screen shot 2017-10-26 at 3 19 04 pm" src="https://user-images.githubusercontent.com/26422129/32077560-0abc38ba-ba61-11e7-97c6-580960863384.png">

I can't figure out how to get the TableHeader to match the size of the column. The 'name' column (of which I did not show) is also twice as large as it needs to be. I realize I can hard code in width's, but even still the Title's do not much the data columns.

Also, how do I get rid of the separation from of the Titles and the first row of data?

**Comment by tylerkeesling** [comment]
Got it.

**Comment by jennybean** [comment]
@tylerkeesling what was your solution?
