### ISSUE TITLE
Selection radio with bootstrap4 not centered

### ISSUE THREAD

**Issue by osnofa** [react-bootstrap-table/react-bootstrap-table2#1206]
**Describe the bug**
A selectable table with the 'bootstrap4' will not have the radio buttons centered, they're aligned to the left side of the column.
To better understand, I think its easier to see the screenshots.

**To Reproduce**
. Add the property 'boostrap4' to a selectable table

**Screenshots**
Normal selectable table:
![Screenshot_2019-12-19 PMed - Atestado](https://user-images.githubusercontent.com/24547517/71168067-dafc1080-224d-11ea-926b-2c502b2aaeff.png)
The same table but with the 'bootstrap4' property:
![Screenshot_2019-12-19 PMed - Atestado(1)](https://user-images.githubusercontent.com/24547517/71168077-df282e00-224d-11ea-989f-69b3b565d6d8.png)

**Comment by AllenFang** [comment]
it work great in online demo https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Bootstrap%204&selectedStory=Row%20selection%20table%20with%20bootstrap%204&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

@osnofa if you feel something wrong, there's a workaround is tweak this rule `.react-bootstrap-table th > .selection-input-4, .react-bootstrap-table td > .selection-input-4`
