### ISSUE TITLE
Custom searchBar + eraseButton

### ISSUE THREAD

**Issue by nirkrumer** [react-bootstrap-table/react-bootstrap-table2#1209]
Hey,
I created custom search bar and custom clear button.
Till now I could make my erase button to erase the text from the search bar,
but the filter remains.
How can I code it correctly? Thx

**handler**
 const Clearbutton = (props: any) => {
            
            const clearhandleClick = () => {
                props.onSearch(inputs.value).onClear(); // (I tried also obviously props.onClear();)
            }
            return (
                <button className="btn btn-default"
                    onClick={clearhandleClick}>Clear</button>
            )
        }
I tried also obviously props.onClear();

**ToolkitProvider**
    (props: { csvProps: JSX.IntrinsicAttributes; searchProps: {onClear:JSX.IntrinsicAttributes}; baseProps: JSX.IntrinsicAttributes;}) => (
                        <div>
                            <MySearch {...props.searchProps} id="SearchBar" />
                            <br></br>
                            <Clearbutton {...props.searchProps.onClear} />
                            <br></br>
                            <br></br>
                            <BootstrapTable  {...props.baseProps} keyField='id' data={products} columns={columns} noDataIndication="Table is Empty"
                              defaultSorted={defaultSorted} filter={filterFactory()}
                            />
                        </div>
                    )

WHAT IS MISSING? 
Thanks!

**Comment by nirkrumer** [comment]
Hey,
Any thoughts?
thx

**Comment by nirkrumer** [comment]
Hey guys ,
I really need your help on this
What do u think?

**Comment by AllenFang** [comment]
@nirkrumer sorry for lately reply, I just give answer [here](https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1253). So close it.
