### ISSUE TITLE
Support Bootstrap 4  for paginator

### ISSUE THREAD

**Issue by pravin-d** [react-bootstrap-table/react-bootstrap-table2#1214]
**Question**
Paginator does not use Bootstrap4 classes even though it is enabled on Bootstrap table. How do I enable bootstrap 4 classes for the paginator ?

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/bootstrap4.html

it work great boss, https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Bootstrap%204&selectedStory=Pagination%20table%20with%20bootstrap%204&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
