### ISSUE TITLE
How to get footer value in other fields

### ISSUE THREAD

**Issue by cindy-li-qa** [react-bootstrap-table/react-bootstrap-table2#1217]
**Question**
I want to have a table like below
![image](https://user-images.githubusercontent.com/44219522/71613657-b22b3200-2be2-11ea-8804-1a4bbbc000db.png)

I need to use the total_feature_tickets/total_ticket to get feature ticket percentage value, but have no idea on how to get them.

In bootstrap table, I can use **rows** to get values in other fields, but it doesn't work in react-bootstrap-table2
`footerFormatter: function (rows) {
         var total = 0;
         var feature = 0;
         for (var i = 0; i < rows.length; i++) {
               total += rows[i].total_ticket
               feature += rows[i].feature_ticket
         };
         return '<b>' + ((feature / total) * 100).toFixed(0) + '%</b>';
   }`

**Comment by cindy-li-qa** [comment]
Find other ways to get the value I want

**Comment by abehm22** [comment]
@cindy-li-qa What was your solution? I am also looking to do something similar.

I would like to take the total calculated from the footer and render it in a jsx object like you would in the footerFormatter. Is this possible @AllenFang ?

```
footer: columnData => columnData.reduce((acc, item) => (Number(acc) + Number(item)).toFixed(2), 0),
footerFormatter: (column, colIndex) => {
                        return (<>
                            <div className='text-right' style={{ fontWeight: 'bold', fontSize: '0.9rem'}}>
                                Total Fees:
                                <div className='d-inline-block form-group ml-2'>
                                    <Input disabled={true} bsSize='md' className='text-right form-control-md form-control' value={{columnData??}} style={{width: '120px'}} />
                                </div>
                            </div>
                        </>);
                    }
```

**Comment by abehm22** [comment]
ahh nm.
I just combined the jsx in the footer and it did what I wanted.
`footer: columnData => {
                        const total = columnData.reduce((acc, item) => (Number(acc) + Number(item)).toFixed(2), 0);
                        return (<>
                            <div className='text-right' style={{ fontWeight: 'bold', fontSize: '0.9rem'}}>
                                Total Fees:
                                <div className='d-inline-block form-group ml-2'>
                                    <Input disabled={true} bsSize='md' className='text-right form-control-md form-control' value={total} style={{width: '120px'}} />
                                </div>
                            </div>
                        </>);
                    },`
