### ISSUE TITLE
Can't exit edit mode if table is in remote mode

### ISSUE THREAD

**Issue by uc2pac** [react-bootstrap-table/react-bootstrap-table2#1218]
**Describe the bug**
When BootstrapTable is in remote mode and I click table cell to edit, I can not exit edit mode. 

BootstrapTable configuration
```
<BootstrapTable
      bootstrap4
      bordered={false}
      hover
      remote
      selectRow={ selectRow }
      onTableChange={ onTableChange }
      cellEdit={ cellEditFactory({ 
           mode: 'click',
           blurToSave: true
      }) }
      { ...toolkitprops.baseProps }
      { ...paginationTableProps }
/>
```

I've noticed that `completeEditing` is not used in remote mode
`react-bootstrap-table2-editor.js`
```
if (isRemoteCellEdit()) {
    handleCellChange(rowId, column.dataField, newValue);
} else {
    dataOperator.editCell(data, keyField, rowId, column.dataField, newValue);
     if (_.isFunction(afterSaveCell)) afterSaveCell(oldValue, newValue, row, column);
     this.completeEditing(); 
}
```

**To Reproduce**
1. Use `BootstrapTable` configuration from above
2. Click on editing cell
4. Click outside of cell

**Comment by AllenFang** [comment]
@uc2pac I believe something wrong in your code base. [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Cell%20Editing&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is work great!

**Comment by DinaKotliar** [comment]
> @uc2pac I believe something wrong in your code base. [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Cell%20Editing&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is work great!

I have the same problem as @uc2pac. The example doesn't work at all. The values do not change according to handleTableChange method.

I want to use remote method for change values, but I can not exit edit mode after changing.

**Comment by dinakotliar** [comment]
I have the same problem as @uc2pac. 
The point is that I add a cancel button if the user does not want to save changes. In this case, I do not want to update the table, but I just want to remove the editable field. Now I have to find the old value and still update it to remove edit field. 
How can I just remove editing without saving?
