### ISSUE TITLE
[HELP WANTED] onRowDoubleClick

### ISSUE THREAD

**Issue by tylerkeesling** [react-bootstrap-table/react-bootstrap-table2#122]
For the onRowDoubleClick(row) function, is there a way to call another function that is mentioned in the { options }? 

I would like to change the state of the component onRowDoubleClick using this.setState({}), but that doesn't seem to be supported.

**Comment by AllenFang** [comment]
Hi @tylerkeesling would you please give me an example, I think it's possible to change state when onRowDoubleClick is triggered.

**Comment by Ar2r** [comment]
You can call function this way:
```
const rowEvents = {
  onClick: (e) => {
    alert('click on row');
  }
};

<BootstrapTable keyField='id' data={ products } columns={ columns } rowEvents={ rowEvents } />
```

OR

```
    const columns = [
      {
        dataField: 'phone',
        text: localize.phoneNumber,
        filter: textFilter(),
        events: {
          onDoubleClick: (row: any) => alert('clicker')
        }
      },
];
<BootstrapTable keyField='id' data={ products } columns={ columns } rowEvents={ rowEvents } />
```

**Comment by AllenFang** [comment]
Close it due to no response, I think @Ar2r already give right answer
