### ISSUE TITLE
Maximum depth update issue while custom select filter

### ISSUE THREAD

**Issue by iamjayantchauhan** [react-bootstrap-table/react-bootstrap-table2#1220]
The maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

This issue I am getting when I apply same filter on a large dataset. If I use same code it works for a lower number of rows. When rows increase it stops working. 

`index.js:1375 The above error occurred in the <DataProvider> component:
    in DataProvider (created by BootstrapTableContainer)`

**Comment by iamjayantchauhan** [comment]
@AllenFang Any update for this issue? It works for low data When my data size increases it stops working. I have checked filters my code is everything as documented.

**Comment by Johan-dutoit** [comment]
I get the same error, however mine mentions this

```
The above error occurred in the <SelectFilter> component:
    in SelectFilter (created by HeaderCell)
```

**Comment by AllenFang** [comment]
hi here, sorry for lately reply, @iamjayantchauhan would you please give me a simple and minimal code on codesandbox so that I can help you, thanks!

**Comment by niallpatrickryan** [comment]
Hi,

If it helps anyone else who has this issue. I had a similar issue with a basic text filter resulting in a max update depth issue. Mine was due to having a sort & a filter on the same column. 

Removing the sort eliminated the problem. I didn't dig too deep into the issue but it looked like each filter call triggered the sort function as well.

**Comment by AllenFang** [comment]
lol example please. all the online demos or my local example are work. Please fill another github issue with codesandbox or clear code.

**Comment by GaneshSinghPapola** [comment]
any solution to this?
I am getting maximum depth exceeded issue while searching on two text-filters together (on Header)
or sometime erasing one filter text..
