### ISSUE TITLE
SelectFilter onFilter hook is not fired when filter value is reset

### ISSUE THREAD

**Issue by Popov85** [react-bootstrap-table/react-bootstrap-table2#1221]
onFilter hook perfectly works when a value in select filter is selected and returns proper value, but when I reset it manually - this event is not fired!

The reason why I need it to get fired is that I wanna implement a feature when one column filter **depends** on another in such the way when I select a filter value in one column, the list of values in the next column filter shortens.

Without being able to detect the filter reset event - I cannot return the original list of the linked column.
Probably for this functionality there is another solution, please suggest!

Also, I noticed that if I have multiple columns and onFilter hook is set only in one column, the event is fired all the time another column's filter changes without any changes to the target column filter!
I feels like a wrong behavior.
![Issue04012020](https://user-images.githubusercontent.com/14125796/71764176-0557fa00-2eed-11ea-9851-afccd63af9c1.png)

On the picture, I consecutively set 3 filters from the left to the right in different columns and the hook onFilter of Organisation's column is fired 3 times!
Here is code snippet: 
```
   {
            dataField: 'faculty.organisation.orgId',
            text: 'Organisation',
            sort: true,
            filter: selectFilter({
                options: organisations,
                onFilter: filterVal => console.log(`Filter value: ${filterVal}`),
            }),
            formatter: cell => organisations[cell]
        },
```

**Comment by buacula** [comment]
happens to me too! onFilter not fired when clearing the filter

**Comment by AllenFang** [comment]
@Popov85  please update all the packaged listed in [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/03/07/version-bump.html)

for the id issue you mentioned above, please assign an unique `id` prop on each `BootstrapTable` component
