### ISSUE TITLE
Is it possible to pass a class name to the parent cell (td)?

### ISSUE THREAD

**Issue by agushurst** [react-bootstrap-table/react-bootstrap-table2#1222]
I need to style the background of cells in a column contextually based on the status, e.g., red, green, yellow, etc. I can create a div within the cell that includes the appropriate background color, but then this interferes with filtering the column, e.g., values like "running", "completed", "failed" are not filtered properly (presumably due to the div content), I'd like to be able to pass a className to the parent <td> so that it is styled appropriately. Is there a way to do this such that the column sorting and filtering works as expected?

**Comment by AllenFang** [comment]
docs: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnclasses-string-function

example: https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Customize%20Column%20Style&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
