### ISSUE TITLE
RowIndex Increase Across Pagination

### ISSUE THREAD

**Issue by thebradisrad** [react-bootstrap-table/react-bootstrap-table2#1224]
Hello, is there a way to get rowindex cross pagination yet? Need the row index to be correct to do an onChange on that row. When I do onChange on rows on page 2, the onChange would affect rows on page 1.

I'm using the basic pagination, if I could somehow get the current page, then I would be able to use that to increment the row index, but I don't know how.

**Comment by thebradisrad** [comment]
I was able to get the page number and set that to currentPage then use that in the column, but setting state inside onPageChange causes pagination to stop working. Clicking on the next page always return the first page.    

const options = {
      onPageChange: (page, sizePerPage) => {
        this.setState({ currentPage: page });
        console.log(page);
      }
    };

///
        dataField: '#',
        text: '#',
        formatter: (cell, row, rowIndex) => {
          let rowNumber = this.state.currentPage * (rowIndex + 1);
          return <span>{rowNumber}</span>;
        },

**Comment by thebradisrad** [comment]
Ok, I figured it out. I forgot to assigned page to the currentPage state.

    const options = {
      onPageChange: page => {
        this.setState({ currentPage: page });
      },
      page: this.state.currentPage
    };

// for the column
        dataField: '#',
        text: '#',
        formatter: (cell, row, rowIndex) => {
          let rowNumber = (this.state.currentPage - 1) * 10 + (rowIndex + 1);
          return <span>{rowNumber}</span>;
        },

**Comment by dextel2** [comment]
hello @thebradisrad, can you please share your solution on codesandbox?
