### ISSUE TITLE
Render pagination page-size dropdown above the table

### ISSUE THREAD

**Issue by stevej2608** [react-bootstrap-table/react-bootstrap-table2#1228]
Hi, I'd like to be able to show the page-size dropdown, top-left, above 
the table itself. I've looked at the documentation on customising the paginator and I can
see how to change its aperence but not how to relocate it.

I can see one possibe solution would be to use `hideSizePerPage` property to hide the default 
page-size dropdown. I then re-render the table with a new page-size when my custom page-size component value is changes. This all seems a bit clunky.

Any advice would be much apreciated.

Cheers, Steve

**Comment by AllenFang** [comment]
@stevej2608  use standalone component https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#41-use-standalone-component

sample: https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20SizePerPage%20Dropdown&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by Nhiphat** [comment]
@AllenFang Can we resolve stevej2608's issue without using PaginationProvider?
