### ISSUE TITLE
Warning: Failed prop type: The prop `column.dataField` is marked as required in `HeaderCell`, but its value is `undefined`.

### ISSUE THREAD

**Issue by psfir** [react-bootstrap-table/react-bootstrap-table2#1232]
Is it normal to receive a Warning: Failed prop type when rendering data from an asynchronous call with either a native react fetch or an axios fetch.  As far as I can tell its normal? Is there anyway to avoid this?

**Comment by AllenFang** [comment]
I think the message is clear enough, it's abnormal in my opinion, please the value of `column.dataField`. It's required value

**Comment by psfir** [comment]
Yes, I get that it's clear and the column.,datafield needs to be valued and
it is in actual fact. It's a timing thing where the table renders initially
displays the message because it hasn't received the data. I'm using an
async function to get a json object from a rest service and using await to
wait for the response before calling setState in my React object. Once the
response is received the table renders fine but there looks to be an
initial render that has no data, therefore, I get the error in the console.

**Comment by AllenFang** [comment]
@psfir if the step is initial, you shouldn't render table component, right? If you didn't when `react-bootstrap-table2`, you will not get this issue anymore.

**Comment by dsudasinghe-virtusa** [comment]
This is because one of the column's dataField is undefined or null. Make sure to assign a unique dataField value in your formatter. Check all formatters
