### ISSUE TITLE
Columns initially hidden when using ToolKitProvider and columns array changes

### ISSUE THREAD

**Issue by seare-kidane** [react-bootstrap-table/react-bootstrap-table2#1233]
Relates to #723 

When using `ToolKitProvider` with `ColumnToggle`, if you first initialize the `keyField` & `columns` array to some value and later update it to a different `columns` array with it's respective `keyField`, the columns will be hidden.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a React component with `ToolkitProvider` that contains `ColumnToggle` and `BootstrapTable` inside it
2. Initialize the the properties as follows
    ```js
    keyField='id',
    columns=[{
        dataField: 'id',
        text: 'ID Column'
    }]
    ```
3. And then update the properties: e.g.
    ```js
    keyField='first',
    columns=[{
        dataField: 'first',
        text: 'First Column'
    },
    {
        dataField: 'second',
        text: 'Second Column'
    }]
    ```
4. See the both columns initially become hidden

I suspect this happens due to the `ToolKitProvider` context initializing the `columnToggle` state on the constructor rather than doing it on the _render_.
I'm referring specifically to `ToolkitProvider` class constructor
```js
constructor(props) {
    ...
    if (props.columnToggle) {
      state.columnToggle = props.columns
        .reduce((obj, column) => {
          obj[column.dataField] = !column.hidden;
          return obj;
        }, {});
    }
    state.searchText = typeof props.search === 'object' ? (props.search.defaultSearch || '') : '';
    ...
}
```

**Suggestion**
Since the `columnToggle` & `searchText` states are dependent on the updated columns & `defaultSearch` properties respectively; and also since this properties can be updated at any given time, I suggest we move the above two state updates to the render method.

Doing this should fix `ToolKitProvider` column toggle from initially hidden the columns and correctly reflects columns hidden property changes.

**Comment by jonathanhamel4** [comment]
+1

**Comment by seare-kidane** [comment]
> +1
> 
> @seare-kidane Have you found any workaround yet?

The temporary workaround it to ether re-render the entire `ToolKitProvider` using
either `ReactDom` or **IIFE**
```js
const toolKitElement = (
  <ToolKitProvider>
    ...
  </ToolKitProvider>
);
ReactDOM.render(toolKitElement, document.getElementById('root'));
```
or
```js
(() => {
  return (
    <ToolKitProvider>
      ...
    </ToolKitProvider>
})();
```

**Comment by AllenFang** [comment]
sorry for lately reply, I will take a look on this, thanks for issue report.

**Comment by AllenFang** [comment]
@seare-kidane fixed this in newest version: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/02/09/version-bump.html

**Comment by seare-kidane** [comment]
> @seare-kidane fixed this in newest version: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/02/09/version-bump.html

@AllenFang Thanks for the quick fix, I verified columns aren't initialised hidden anymore!
