### ISSUE TITLE
Page list requires two clicks to open

### ISSUE THREAD

**Issue by mfleonhardt** [react-bootstrap-table/react-bootstrap-table2#1235]
**Question**
I created a wrapper for react-bootstrap-table2 for a common use case I have.  I can't explain why but in this implementation, the first click does not open the page list dropdown.  The drop down works as expected in other contexts such as the story book examples.

What happens is in the span element around the page list button.  On the first click, it only gets the "open" class.  After that, further onClick events remove the "open" class and toggle the "show" class, which succeeds in displaying/hiding the dropdown contents.  To compare with the storybook, both the "open" and "show" classes are toggled together.

**codesandbox**

```jsx
import React from 'react';
import BootstrapTable from 'react-bootstrap-table-next';
import paginationFactory from 'react-bootstrap-table2-paginator';

import 'react-bootstrap-table-next/dist/react-bootstrap-table2.css';
import 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.css';
import 'myTableStyle.scss';

class PaginatedTable extends React.Component {

    getData = () => {  /** read sort&page config, get remote data, update state.data **/  };

    handleTableChange = (type, changes) => {
        this.setState(changes, this.getData);
    };

    render = () => {

        const {keyField, columns, route, collection, parameters, ...otherProps} = this.props;
        const {data, totalSize, sizePerPage, page} = this.state;

        return <BootstrapTable
            remote
            bootstrap4
            keyField={keyField}
            data={data}
            columns={columns}
            pagination={paginationFactory({page, sizePerPage, totalSize})}
            onTableChange={this.handleTableChange}
            {...otherProps}/>;
    };
}

export default PaginatedTable;

```

**Comment by AllenFang** [comment]
hi @mfleonhardt I really can't reproduce this issue lol. If ok, please create codesandbox example online so that I can help, thanks
