### ISSUE TITLE
How to style selectRow checkbox?

### ISSUE THREAD

**Issue by bernarddoci** [react-bootstrap-table/react-bootstrap-table2#1237]
How can I style selectRow checkbox? I am trying to make checkbox 50 px wide and height with a green background color.

**Comment by AllenFang** [comment]
please read docs and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Custom%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an online example
