### ISSUE TITLE
Can i add dynamic options coming from API to filter?

### ISSUE THREAD

**Issue by dashName** [react-bootstrap-table/react-bootstrap-table2#1239]
**Question**
A clear and concise description of you question. In addition, please search issues before you open a question to make sure there's no any duplicated questions.

**Screenshots**

**codesandbox**
Please give a simple and minimal example on https://codesandbox.io so that we can reproduce it easily.

**Comment by AllenFang** [comment]
So far we don't support this feature directly, but I think you can try.
