### ISSUE TITLE
Placing Pagination arrows to the sides of the table instead of page numbers.

### ISSUE THREAD

**Issue by Dev442** [react-bootstrap-table/react-bootstrap-table2#1240]
I have to move my pagination left and right arrow option to both the sides of the bootstrap-table-next from the bottom. And I don't want the numbers, just the arrows. I am using React,React-Bootstrap-table-next for front end. I have simply render the pagination option in my table . I have searched a lot but couldn't find anything satisfying my query. Here is part of my code for pagination.

```
    <BootstrapTable keyField="Date"  
                            data={this.state.posts} 
                            columns={columns} 
                            filter={ filterFactory() }
                            filterPosition="bottom"
                            pagination={ paginationFactory() }
            />
```

Is there any other option along with pagination to achieve this?

Bootstrap table next

**Comment by AllenFang** [comment]
If you only need the left and right arrow button in a customization place, it's better to custom the pagination list completely by yourself

```js
import BootstrapTable from 'react-bootstrap-table-next';
import paginationFactory, { PaginationProvider } from 'react-bootstrap-table2-paginator';

const columns = [{
  dataField: 'id',
  text: 'Product ID'
}, {
  dataField: 'name',
  text: 'Product Name'
}, {
  dataField: 'price',
  text: 'Product Price'
}];

const options = {
  custom: true,
  totalSize: products.length
};

<PaginationProvider
  pagination={ paginationFactory(options) }
>
  {
    ({
      paginationProps,
      paginationTableProps
    }) => (
      <div>
        <BootstrapTable
          keyField="id"
          data={ products }
          columns={ columns }
          { ...paginationTableProps }
        />
       // render left and right arrow button here
      </div>
    )
  }
</PaginationProvider>
```

When user click on right and left button, `PaginationProvider` context provide you a way to change page, please read docs: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#42-customization-everything

BTW, please discover the online example: https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html
