### ISSUE TITLE
Detachable custom filter, or programmatic custom filter

### ISSUE THREAD

**Issue by stilllife00** [react-bootstrap-table/react-bootstrap-table2#1241]
**Is this feature requested before?**
Nope

**Is your feature request related to a problem? Please describe.**
Our business need, is to have all the filters in a separate lightbox and to be able to add multiple filters even on the same column. Right now it is possible to customize the filter component but it gets rendered anyways in the table header or row and this is not as flexible as we need.
It is also possible to filter programmatically but I fail to understand if we can pass filter values programmatically coming from a separated component.

**Describe the solution you'd like**
Be able to pass filter values to the table, not matter the filter rendering logic. AKA a complete separation between the filter position and the filter action.

**Describe alternatives you've considered**
Using a Portal in the filter custom component to be able to render it in a separate position, not sure it will work properly.

**Additional context**
Maybe this is not a necessary feature, I just need information on how to be able to achieve this using custom components and programmatic filtering.

**Comment by AllenFang** [comment]
> Be able to pass filter values to the table, not matter the filter rendering logic. AKA a complete separation between the filter position and the filter action.

@stilllife00 sorry for lately reply, I still confuse about your requirement and solution, it's better to describe by some pseudo code.  :p

**Comment by stilllife00** [comment]
I was able to obtain this with a programmatic custom filter for every column.

https://codesandbox.io/embed/react-bootstrap-table2-clear-search-bar-and-filter-5kqtu?fontsize=14&hidenavigation=1&theme=dark

I just feel this is more laborious because it is not possible to use any of the filters provided by the library if we want to render them **outside** of the table. I think this is an important requirement for who has a specific design to follow, where filters inputs are not in the columns but as in my case, on a separate "Filters" page.
