### ISSUE TITLE
Roll-back cell edit - is that possible?

### ISSUE THREAD

**Issue by mazzalab** [react-bootstrap-table/react-bootstrap-table2#1242]
Hi,
is it possible to roll-back cell edit by storing the old value of an edited cell somewhere 

```
handleEditCell = (oldValue, newValue, row, column) => {
        if(column.dataField === "date_movement"){
            this.old_date_movement = oldValue;
        }
        ...
    };
```
and re-setting it upon triggering of an event?
Is the only viable way that of re-rendering the component?

I pass data to be rendered in the table as props:

```
<BootstrapTable
                    keyField="id"
                    data={this.props.data}
                    ...
```

Should I ask to the parent of this component to resend props to this child component containing the "BootstrapTable", even if **props** are now actually changed (since I've decided to roll-back changes)?

Hope it is not confusing to you.
thanks

**Comment by AllenFang** [comment]
> Is the only viable way that of re-rendering the component?

yes, I think I will not implement this feature on `react-bootstrap-table2`, the only solution just like you said, keep the old value then restore it by rerender table component by triggering some actions.

Feel free to let me know if the problem still remain, thanks

**Comment by mazzalab** [comment]
Hi Allen,
Actually, it seems it is possible to access props.data inside a cellCentext and modify it. I managed to do it after a triggering event:

`this.table.cellEditContext.props.data[rowIndex]['columns_name_here'] = 'a_value'`

I don't know if this is an unwanted feature or a bug, but cell content can be modified programmatically also in this way.

regards
