### ISSUE TITLE
Accessibility Issue: Sortable table headers not read by sceen reader

### ISSUE THREAD

**Issue by Michael-Hanley** [react-bootstrap-table/react-bootstrap-table2#1247]
**Describe the bug**
- Table headers, when sortable, are not described by screen readers as sortable.
- When sorted, are not described by screen readers as sorted with their direction.
- When sort is changed, screen readers do not describe new sort configuration

**To Reproduce**
- Requires a screen reader such as [NVDA](https://www.nvaccess.org/download/)

1. Go to a sortable example in the storybook
2. Click just above the table
3. Tab into headers
4. Headers will not be described as sortable

**Comment by AllenFang** [comment]
@Michael-Hanley thanks your PR, great job for this issue. I will release by this weekend. :)

**Comment by Michael-Hanley** [comment]
Awesome! Thank you!

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/02/16/version-bump.html

upgrade to `react-bootstrap-table-next` to newest version
