### ISSUE TITLE
CSV export resulting in error for .xlsx

### ISSUE THREAD

**Issue by g-akshay** [react-bootstrap-table/react-bootstrap-table2#1249]
Getting the following error when trying to use `.xlsx` extension.

> Excel cannot open the file 'ManageRides (1).xlsx' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file.

I am using the following code: (commented ones are also being tried)
`exportCSV={{
                        fileName: 'filename.xlsx',
                        blobType: "data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8"
                        //blobType: "data:text/csv;charset=utf-8"
                        //blobType: "data:text/csv;charset=UTF-8,%EF%BB%BFs"
                    }}`

**Screenshots**
![image](https://user-images.githubusercontent.com/8638426/74140877-ec451600-4c1b-11ea-8034-e44d1f544e7a.png)

On using the `.xls` extension, whole row data is shown in the first cell and no column segregation happens.

![image](https://user-images.githubusercontent.com/8638426/74141104-51007080-4c1c-11ea-810f-2987bef6b9a5.png)
![image](https://user-images.githubusercontent.com/8638426/74141176-73928980-4c1c-11ea-98ab-3fc070a39e38.png)

Whats  `blobType` is supported for `.xls` or `.xlsx` extension?

**Comment by AllenFang** [comment]
actually, I'm not sure about your question, we used `file-saver` to save file and they just provide a way to customize the blob type. I think you have to ask this question in their repository https://github.com/eligrey/FileSaver.js/ . 


You can open another issue if they or you still think this issue is about `react-bootstrap-table2`

**Comment by malsioufi** [comment]
@g-akshay I have the same issue. How did you solve it?

**Comment by fjperini** [comment]
@g-akshay @malsioufi I have applied some changes in react-bootstrap-table2-toolkit to export in xlsx, it works perfectly. I hope it will be of help to those who need to use the format #1666
