### ISSUE TITLE
Custom searchbar & erase button

### ISSUE THREAD

**Issue by nirkrumer** [react-bootstrap-table/react-bootstrap-table2#1250]
Hey,
I created a custom search bar and custom clear button.
I succeed just to clear the search on the table. 
How can i add more commands - for example to clear the text from the input.

Tried to pass two methods to the onclick - doesnt work
or another way create custom button with the relevant handlers- doesnt work
Do you recommend me to do?
![image](https://user-images.githubusercontent.com/38032506/74154457-5c06d100-4c1b-11ea-8259-fb07089d081b.png)

Thanks

**Comment by AllenFang** [comment]
Hi I found two issue here:
1. should be `props.searchProps.onClear()`
2. I found use custom the search bar(search input) by yourself, which mean you can to clear the test when user hit the clear button. in this case, `react-bootstrap-table2` can only help you to re-render table with correct data but we can not control your component.

Please open an issue if you still don't know how to do it. Thanks!!

**Comment by nirkrumer** [comment]
hey
I get now an error on the client
