### ISSUE TITLE
Date type support for column data

### ISSUE THREAD

**Issue by jzelos** [react-bootstrap-table/react-bootstrap-table2#1251]
**Describe the bug**
The Date type isn't supported for column data. Calling toDateString() on the dates and using as string is fine. 

I've checked the latest version 3.3.4 and the problem persists. I've also tried setting the type column attribute to date without success.

The error is reported as:
Error
Objects are not valid as a React child (found: Thu Dec 12 2013 00:00:00 GMT+0000 (Greenwich Mean Time)). If you meant to render a collection of children, use an array instead.
    in td (created by Cell)
    in Cell (created by RowPureContent)
    in RowPureContent (created by SimpleRow)
    in tr (created by SimpleRow)
    in SimpleRow (created by Body)
    in tbody (created by Body)
    in Body (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by Context.Consumer)
    in DataProvider (created by BootstrapTableContainer)
    in BootstrapTableContainer (at src/index.js:33)
    in div (at src/index.js:32)
    in App (at src/index.js:39)

**To Reproduce**
1. Create data with Date type
2. Wire up to table

See below for simple reproduction.

**codesandbox**
https://codesandbox.io/s/react-bootstrap-table-next-date-type-not-handled-dcj9z

**Comment by AllenFang** [comment]
hey @jzelos please use [column.formatter](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) to handle this. We don't support the native date rendering is because I don't what kind of format your want to be rendered. So you have to deal with it by yourself.
