### ISSUE TITLE
Remote datatable with exportCSV

### ISSUE THREAD

**Issue by owen-stellar** [react-bootstrap-table/react-bootstrap-table2#1255]
Is there a way to get exportCSV (all and onlyExportFiltered) to work with remote datatables? It seems like the export call isn't making a call back to my API when pressed on a datatable that is setup as remote.

**Comment by AllenFang** [comment]
@owen-stellar `exportCSV` only work in local. I mean it rely on `fileSaver` to download the file from browser. We offered some options to configure the content of CSV file, but so far we don't have feature to export from an API. Any thought on this? You can share what you expect, I can help if I have time lol

**Comment by owen-stellar** [comment]
Understood. I think from an expectation perspective simply having a property where we can pass in a function that should be called to retrieve the data that returns the dataset to the datatable might be good enough. That would provide the flexibility to get all, or visible. Ideally it gets passed in any exportCSV configurations that have been set.

**Comment by AllenFang** [comment]
@owen-stellar there's a workaround but not sure if you can accept it:


```js
class Test extends React.Component {
  handleBtnClick = (onExport) => (e) => {
    // get your data from remote or some where
    const data = .....;  
    onExport(data); // you can call onExport function when your data is ready!
  }

  render() {
    return (
      <div>
        <ToolkitProvider
          keyField="id"
          data={ products }
          columns={ columns }
          exportCSV
        >
          {
            props => (
              <div>
                <ExportCSVButton { ...props.csvProps } onClick={ this.handleBtnClick(props.csvProps.onExport) }>Export CSV!!</ExportCSVButton>
                <hr />
                <BootstrapTable { ...props.baseProps } />
              </div>
            )
          }
        </ToolkitProvider>
      </div>
    );
  }
}
```

Please open another issue if you have any other question, thank!!

**Comment by owen-stellar** [comment]
Thanks @AllenFang. We're moving forward with a custom component where file generation will be handled on the server. I appreciate the workaround though!
