### ISSUE TITLE
Update react-transition-group dependency

### ISSUE THREAD

**Issue by Moki-19** [react-bootstrap-table/react-bootstrap-table2#1260]
`react-bootstrap-table-next` depends on a old version of `react-transition-group` (2.5.3) that triggers a react deprecation warning :

```
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Transition
```

So a nice improvement would be to update `react-transition-group` to its last version in the next release.

Thanks

**Comment by AllenFang** [comment]
@Moki-19  please update all the packaged to newest 
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/03/07/version-bump.html

**Comment by hauhuynh1208** [comment]
@AllenFang could you please upgrade react-transition-group to the newest (4.4.2 I think) because 4.2.0 still trigger a react deprecation warning

**Comment by junreyd** [comment]
@AllenFang I have the same issue, any updates on this?

**Comment by epicsoftwaredev-anton-petrov** [comment]
@AllenFang please update `react-transition-group` package

**Comment by itsmepetrov** [comment]
@AllenFang please update react-transition-group package
