### ISSUE TITLE
SizePerPageDropdownStandalone Button is submitting form

### ISSUE THREAD

**Issue by owen-stellar** [react-bootstrap-table/react-bootstrap-table2#1261]
**Describe the bug**
I want to use the datatable inside of a form, however the pageDropDown button that is created for selecting how many items per page to view is submitting the form as a type isn't set for that button. Can you please set the type="button" on the button or allow us to pass this into the SizePerPageDropdownStandalone component as an option?

Also, I want to use the SizePerPageDropdownStandalone multiple times on the page (once above and once below the table) however it has an id on the button that seems to be hard coded to 'pageDropDown' which causes a warning on my browser (especially when I have two or more datatables on the same page). If that could be fixed in some way it would be great.

Thank you!!

**Comment by AllenFang** [comment]
@owen-stellar will do, thanks!

**Comment by AllenFang** [comment]
@owen-stellar please update all the packaged listed in [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/03/07/version-bump.html)

for the id issue you mentioned above, please assign an unique `id` prop on each `BootstrapTable` component

**Comment by owen-stellar** [comment]
Thanks Allen!
