### ISSUE TITLE
unexpected column toggle behavior

### ISSUE THREAD

**Issue by flc** [react-bootstrap-table/react-bootstrap-table2#1262]
**codesandbox**
https://codesandbox.io/s/blissful-voice-8c3xj

Instructions to reproduce problem:
1. Turn off K1 column by clicking the 'K1' button
2. Values belong to the K1 column now appear at the K2 column, K2 values are disappear.
3. Turn off the K2 column as well. Then turn on K2, than K1. The result is that both K1 and K2 columns show the values of K2.

If the column definitions that are commented out are used then it works fine.

**Comment by AllenFang** [comment]
@flc it's not a bug, you have to use `dot` to describe the nest data instead of `__`
`dataField: extra_data__k1` -> `dataField: extra_data.k1`.

**Comment by flc** [comment]
What about the cases when in remote mode a different query parameter (and not `dataField`) has to be used for server side API calls?
For example `a__b` instead of `a.b`  Do you have a suggestion how to handle these cases?
