### ISSUE TITLE
Column toggle state gets reset with selectRow

### ISSUE THREAD

**Issue by amaline** [react-bootstrap-table/react-bootstrap-table2#1266]
**Question**
When I click on a row that has a selectRow function defined (which sets state on another component) the state of the column toggle gets reset to the original and the table gets reset to the original columns. Do I need to be doing something in my selectRow method to keep the column toggle state?

It seems like during rendering the packages/react-bootstrap-table2-toolkit/context.js UNSAFE_componentWillReceiveProps method seems to get called again resetting the state.  Is this an indication that I am doing something wrong?

**Comment by AllenFang** [comment]
````js
const selectRow = {
  mode: 'checkbox',
  clickToSelect: true
};

export default () => (
  <div>
    <ToolkitProvider
      keyField="id"
      data={ products }
      columns={ columns }
      columnToggle
    >
      {
        props => (
          <div>
            <ToggleList { ...props.columnToggleProps } />
            <hr />
            <BootstrapTable
              selectRow={ selectRow }
              { ...props.baseProps }
            />
          </div>
        )
      }
    </ToolkitProvider>
  </div>
);
```

@amaline I try above code on my end but everything is fine. Would you please share your code?

> "Please keep you code simple and minimal so that we can reproduce issue that is enough!"

**Comment by amaline** [comment]
I solved my issue by using a custom onColumnToggle method

```
  const myColumnToggle = (df) => {
    var newTableColumns = tableColumns.map( (val) => {
       if( val.dataField === df) {
         val.hidden = !val.hidden
       }
       return val;
    });
    setTableColumns(newTableColumns);
  }

  useFetch(URL);

  const CustomToggleList = ({
    columns,
    onColumnToggle,
    toggles
  }) => (
    <div className="btn-group btn-group-toggle btn-group-vertical" data-toggle="buttons">
      {
        columns
          .map(column => ({
            ...column,
            toggle: toggles[column.dataField]
          }))
          .map(column => (
            <button
              type="button"
              key={ column.dataField }
              className={ `btn btn-warning ${column.toggle ? 'active' : ''}` }
              data-toggle="button"
              aria-pressed={ column.toggle ? 'true' : 'false' }
              onClick={ () => onColumnToggle(column.dataField) }
            >
              { column.text }
            </button>
          ))
      }
    </div>
  );

  return (
    <Jumbotron fluid style={{backgroundColor:"#ffffff"}}>
      <Row style={{width:"2000px",height:"800px", margin:"20px auto"}} className="mediaPlaceHolder">

            { loading ? ( <div>Loading...</div>) : <OrgDiagram centerOnCursor={true} config={orgChart} /> }
      
      </Row>
      { loading ? 
        ( <Row>Loading...</Row>) : 
        ( 
            <ToolkitProvider
                  keyField="id"
                  data={ orgChart.items }
                  columns={ tableColumns }
                  boostrap4={true} 
                  columnToggle
                  search
                >
                  {
                    props => (
                      <Row>
                        <Col xs={1} >
                          <CustomToggleList  { ...props.columnToggleProps } onColumnToggle={ myColumnToggle } />
                        </Col>
                        <Col lg={10} style={{marginLeft:"10px"}}>
                          <SearchBar { ...props.searchProps } />
                          <BootstrapTable pagination={ paginationFactory() } filter={ filterFactory() } selectRow={ selectRow } { ...props.baseProps } />
                        </Col>
                        </Row>
                    )
                  }
            </ToolkitProvider>
        )
      }
    </Jumbotron>
  );
```

**Comment by AllenFang** [comment]
💯

**Comment by amitsetty** [comment]
Can this be reopened? There is a big issue with this that now every time a column is toggled the entire table is rerendered. This is bad for performance reasons when the table has a lot of data.

**Comment by shaunlabang** [comment]
> I solved my issue by using a custom onColumnToggle method
> 
> ```
>   const myColumnToggle = (df) => {
>     var newTableColumns = tableColumns.map( (val) => {
>        if( val.dataField === df) {
>          val.hidden = !val.hidden
>        }
>        return val;
>     });
>     setTableColumns(newTableColumns);
>   }
> 
>   useFetch(URL);
> 
>   const CustomToggleList = ({
>     columns,
>     onColumnToggle,
>     toggles
>   }) => (
>     <div className="btn-group btn-group-toggle btn-group-vertical" data-toggle="buttons">
>       {
>         columns
>           .map(column => ({
>             ...column,
>             toggle: toggles[column.dataField]
>           }))
>           .map(column => (
>             <button
>               type="button"
>               key={ column.dataField }
>               className={ `btn btn-warning ${column.toggle ? 'active' : ''}` }
>               data-toggle="button"
>               aria-pressed={ column.toggle ? 'true' : 'false' }
>               onClick={ () => onColumnToggle(column.dataField) }
>             >
>               { column.text }
>             </button>
>           ))
>       }
>     </div>
>   );
> 
>   return (
>     <Jumbotron fluid style={{backgroundColor:"#ffffff"}}>
>       <Row style={{width:"2000px",height:"800px", margin:"20px auto"}} className="mediaPlaceHolder">
> 
>             { loading ? ( <div>Loading...</div>) : <OrgDiagram centerOnCursor={true} config={orgChart} /> }
>       
>       </Row>
>       { loading ? 
>         ( <Row>Loading...</Row>) : 
>         ( 
>             <ToolkitProvider
>                   keyField="id"
>                   data={ orgChart.items }
>                   columns={ tableColumns }
>                   boostrap4={true} 
>                   columnToggle
>                   search
>                 >
>                   {
>                     props => (
>                       <Row>
>                         <Col xs={1} >
>                           <CustomToggleList  { ...props.columnToggleProps } onColumnToggle={ myColumnToggle } />
>                         </Col>
>                         <Col lg={10} style={{marginLeft:"10px"}}>
>                           <SearchBar { ...props.searchProps } />
>                           <BootstrapTable pagination={ paginationFactory() } filter={ filterFactory() } selectRow={ selectRow } { ...props.baseProps } />
>                         </Col>
>                         </Row>
>                     )
>                   }
>             </ToolkitProvider>
>         )
>       }
>     </Jumbotron>
>   );
> ```

is it possible to share "setTableColumns(newTableColumns);"?

**Comment by minhkhoa719** [comment]
> I solved my issue by using a custom onColumnToggle method
> 
> ```
>   const myColumnToggle = (df) => {
>     var newTableColumns = tableColumns.map( (val) => {
>        if( val.dataField === df) {
>          val.hidden = !val.hidden
>        }
>        return val;
>     });
>     setTableColumns(newTableColumns);
>   }
> 
>   useFetch(URL);
> 
>   const CustomToggleList = ({
>     columns,
>     onColumnToggle,
>     toggles
>   }) => (
>     <div className="btn-group btn-group-toggle btn-group-vertical" data-toggle="buttons">
>       {
>         columns
>           .map(column => ({
>             ...column,
>             toggle: toggles[column.dataField]
>           }))
>           .map(column => (
>             <button
>               type="button"
>               key={ column.dataField }
>               className={ `btn btn-warning ${column.toggle ? 'active' : ''}` }
>               data-toggle="button"
>               aria-pressed={ column.toggle ? 'true' : 'false' }
>               onClick={ () => onColumnToggle(column.dataField) }
>             >
>               { column.text }
>             </button>
>           ))
>       }
>     </div>
>   );
> 
>   return (
>     <Jumbotron fluid style={{backgroundColor:"#ffffff"}}>
>       <Row style={{width:"2000px",height:"800px", margin:"20px auto"}} className="mediaPlaceHolder">
> 
>             { loading ? ( <div>Loading...</div>) : <OrgDiagram centerOnCursor={true} config={orgChart} /> }
>       
>       </Row>
>       { loading ? 
>         ( <Row>Loading...</Row>) : 
>         ( 
>             <ToolkitProvider
>                   keyField="id"
>                   data={ orgChart.items }
>                   columns={ tableColumns }
>                   boostrap4={true} 
>                   columnToggle
>                   search
>                 >
>                   {
>                     props => (
>                       <Row>
>                         <Col xs={1} >
>                           <CustomToggleList  { ...props.columnToggleProps } onColumnToggle={ myColumnToggle } />
>                         </Col>
>                         <Col lg={10} style={{marginLeft:"10px"}}>
>                           <SearchBar { ...props.searchProps } />
>                           <BootstrapTable pagination={ paginationFactory() } filter={ filterFactory() } selectRow={ selectRow } { ...props.baseProps } />
>                         </Col>
>                         </Row>
>                     )
>                   }
>             </ToolkitProvider>
>         )
>       }
>     </Jumbotron>
>   );
> ```

is it possible to share where you use "setTableColumns"?
