### ISSUE TITLE
Toggle filters

### ISSUE THREAD

**Issue by Liteolika** [react-bootstrap-table/react-bootstrap-table2#1267]
Is there any way to toggle the filters for a table?
The only way i could think of to do this right now, is to show/hide a certain row in the table.

**Comment by AllenFang** [comment]
hi @Liteolika boss, sorry that we don't have any mechanism to toggle the filters now. But you can still custom it by yourself, for example, when user click something, you remove the `filter` props from a specific column then rerender.

Please let me know if you have any other questions or issues. thanks
