### ISSUE TITLE
Set id for filter explicitly instead of id={ `text-filter-column-${text}` }

### ISSUE THREAD

**Issue by buacula** [react-bootstrap-table/react-bootstrap-table2#1269]
**Is your feature request related to a problem? Please describe.**
It's fine if only one table is rendered, but if you render several tables with the same column text of exp. 'User', then there would be a lot of non-unique id warnings.

**Describe the solution you'd like**
Also to pass id props to text, number, date, select, multiselect filter.

Thanks very much!

**Comment by AllenFang** [comment]
@buacula I will handle this, thanks

**Comment by AllenFang** [comment]
@buacula  please update all the packaged to newest 
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/03/07/version-bump.html
