### ISSUE TITLE
Table does not render new cells when adding columns to table

### ISSUE THREAD

**Issue by ottosson** [react-bootstrap-table/react-bootstrap-table2#1270]
**Describe the bug**
When I add columns to my columns object the new cells won't render properly until I activate edit cell for every row.

**Screenshots**
![image](https://user-images.githubusercontent.com/3355320/75265628-77640580-57f1-11ea-91f2-11ce27d93215.png)

**codesandbox**
https://codesandbox.io/s/frosty-wind-94u38

**Comment by AllenFang** [comment]
@ottosson it;'s not an issue, the problem is you can't mutate the any props data, particular in React world:

```js
// . DONT DO THIS AGAIN
data.forEach(row => {
   row[newColName] = "-";
});

// DO THIS
setData(
      data.map(d => ({
        ...d,
        [newColName]: "-"
      }))
    );
```

After you adopt above change, the table will render correctly.  in addition, you can't also mutate columns as well.
