### ISSUE TITLE
Missing types...

### ISSUE THREAD

**Issue by kgonzale** [react-bootstrap-table/react-bootstrap-table2#1271]
```
//@ts-ignore
import filterFactory from "react-bootstrap-table2-filter";
//@ts-ignore
import paginationFactory from "react-bootstrap-table2-paginator";
//@ts-ignore
import BootstrapTable from "react-bootstrap-table-next";
```

Has there been any updates on the types associated with the library? I keep having //@ts-ignore
anything related to the library because typescript screams at me.

I'm on typescript 3.7.3 if that helps any.

**Comment by AllenFang** [comment]
@kgonzale I don't support the TS officially. sorry about this.

you can make a type or reference https://gitlab.com/fluidattacks/integrates/-/tree/master/front/src/typings
