### ISSUE TITLE
when selecting time in the table the time isn't changing 

### ISSUE THREAD

**Issue by avichaigrunseid** [react-bootstrap-table/react-bootstrap-table2#1272]
when selecting a time in the table the time isn't changing.
I'm using the date picker.
when I'm changing the time outside the table it is working.

herby by screenshots:

Not working:

![image](https://user-images.githubusercontent.com/53261178/75321326-2dbefd80-5879-11ea-9e96-297a611e7e7f.png)

working:

![image](https://user-images.githubusercontent.com/53261178/75270904-0548ec00-5804-11ea-96dd-93d4bb35a9d2.png)

**Comment by avichaigrunseid** [comment]
Hi @AllenFang 

Any update?

Thanks

**Comment by AllenFang** [comment]
hi @avichaigrunseid boss, your information is not enough foe me to debug or reproduce. Please follow the instruction to open a valid ticket to that I can help you effective.  (Give clear steps and a codesandbox example to reproduce your issue(Keep example minimal and simple))
