### ISSUE TITLE
SizePerPageDropdownStandalone custom style

### ISSUE THREAD

**Issue by haqim007** [react-bootstrap-table/react-bootstrap-table2#1275]
How to customize SizePerPageDropdownStandalone style? Thank you

**Comment by AllenFang** [comment]
You can use `className` prop to add custom class name on dropdown component. so far we don't support the `style`. BTW, there're few props you may be interesting: `btnContextual`, `variation`

docs: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#41-use-standalone-component
