### ISSUE TITLE
Standalone Pagination components need to support 'bootstrap4' prop

### ISSUE THREAD

**Issue by GamertagsRLame** [react-bootstrap-table/react-bootstrap-table2#1276]
If the PaginationProvider component is used along with any of the standalone Pagination components (SizePerPageDropdownStandalone, PaginationTotalStandalone, PaginationListStandalone) and the PaginationProvider wraps the BootstrapTable component (as in the examples), it is not possible to 'configure' the standalone Pagination components with the 'bootstrap4' prop.  Specifying it on the BootstrapTable only affects the table.

Seems like PaginationProvider needs to behave like ToolkitProvider and support the 'bootstrap4' property... or do I have to wrapper BootstrapTable and the standalone Pagination components with a ToolkitProvider, and then wrapper all of that with the PaginationProvider?

**Comment by AllenFang** [comment]
@GamertagsRLame it's not an issue, standalone component support bootstrap4

Take below code to explain:

```js
<PaginationProvider
      bootstrap4  // add bootstrap4 prop
      pagination={ paginationFactory(options) }
    >
      {
        ({
          paginationProps,
          paginationTableProps
        }) => (
          <div>
            <PaginationListStandalone
              { ...paginationProps }  // actually, paginationProps contain bootstrap4 prop
            />
            <BootstrapTable
              keyField="id"
              data={ products }
              columns={ columns }
              { ...paginationTableProps }
            />
            <SizePerPageDropdownStandalone
              { ...paginationProps }  // actually, paginationProps contain bootstrap4 prop 
              btnContextual="btn btn-primary"
            />
          </div>
        )
      }
    </PaginationProvider>
```

at above case, `paginationProps` contain `bootstrap4` prop and you have to pass them down to standalone component and all of the standalone component take `bootstrap4` prop to do the corresponding handling. I just prove bootstrap 4 is work well in my local by above example.

Please open another issue ticket if the problem still remain.
