### ISSUE TITLE
How do I turn off tooltips on hovering over pagination items?

### ISSUE THREAD

**Issue by paroxyzm** [react-bootstrap-table/react-bootstrap-table2#1278]
Hello!

I'm struggling with disabling tooltips on hovering over pagination items.

This can be seen in examples for pagination:
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20Pagination%20Total&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

When you hover over any item the tooltip appears showing either the number of the page, or the Title for Next/Previous/First/Last items.

Is there a way to disable it?
What options should I provide to make this happen?

I tried augmenting options with for example `nextPageText: null` with no luck
```
 const options = {
  custom: true,
  totalSize: products.length,
  nextPageText: null,
  prePageText: null,
};
```

**Comment by AllenFang** [comment]
@paroxyzm I will add a prop to allow developer to disable the title on the button, thanks!

**Comment by AllenFang** [comment]
@paroxyzm [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/03/16/version-bump.html)

Please upgrade `react-bootstrap-table2-paginator` to `2.1.2` and add `disablePageTitle` as true in pagination config.

Thanks

**Comment by paroxyzm** [comment]
Thank you!
