### ISSUE TITLE
Make hidePageListOnlyOnePage work on PaginationListStandalone

### ISSUE THREAD

**Issue by kevinashworth** [react-bootstrap-table/react-bootstrap-table2#1279]
**Is this feature requested before?**
I don't see this requested before.

**Is your feature request related to a problem? Please describe.**

https://codesandbox.io/s/vigilant-tdd-owuxk
Load the sandbox, then select any page size over 10, and you'll see a pagination list that says "1", even though `hidePageListOnlyOnePage: true`.

**More info on what I see in the code**
TLDR: The same classes and HTML tags do not get generated when it's standalone. 

In the codesandbox source view, I see class `react-bootstrap-table-page-btns-ul` on a `ul` tag for PaginationListStandalone.

Looking in the main repo for a default, non-standalone pagination list, I see variable `pageListClass` applied to a `div` and it is modified by the `hidePageListOnlyOnePage` flag:

https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/02cdbb5338e438c4b748143a3a9494a34aa5b04d/packages/react-bootstrap-table2-paginator/src/pagination.js#L38-L42

Apparently, there is no such code that gets called in the standalone pagination list, thus `hidePageListOnlyOnePage` does not work on `PaginationListStandalone`. 

**Describe the solution you'd like**
Have the same logic, classes and tags on the pagination list whether it's standalone or non-standalone, so that `hidePageListOnlyOnePage` works in both cases.

**Comment by AllenFang** [comment]
@kevinashworth I will fix it in next version, thanks

**Comment by AllenFang** [comment]
@kevinashworth [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/03/16/version-bump.html)

Please upgrade `react-bootstrap-table2-paginator` to `2.1.2`

Thanks

**Comment by kevinashworth** [comment]
Great!
