### ISSUE TITLE
Resetting all filters while using a customFilter()

### ISSUE THREAD

**Issue by LRode** [react-bootstrap-table/react-bootstrap-table2#1286]
Hi there, I've been loving using this library, but I've just run into a snag.

It's just been requested that I add a 'Reset all filters' button to my tables, however I have quite a complex table setup using a lot of `customFilter()`s. I set it up following the example [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Clear%20All%20Filters&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), however I've now realized that the `customFilter()` filter doesn't accept the `getFilter` prop, so the reset for many of my columns will not work :( 

Is there any way I can implement resetting all filters while using custom ones? Here is a snippet of my columns + clearing logic

```
let statusF, firstNameF, lastNameF, emailF, rolesF;

const clearFilter = () => {
        statusF('');
        firstNameF('');
        lastNameF('');
        rolesF('');
        emailF('');
    };

const columns = [
        {
            dataField: 'status',
            text: 'Status',
            sort: true,
            filter: customFilter({
                getFilter: (filter) => { // This is what does not work
                    statusF = filter;
                }
            }),
            filterRenderer: (onFilter, column) => (
                <DropdownFilter
                    column={column}
                    options={[
                        { value: 'Active', label: 'Active' },
                        { value: 'Archived', label: 'Archived' }
                    ]}
                    onFilter={onFilter} />
            )
        },
        {
            dataField: 'firstName',
            text: 'First Name',
            sort: true,
            filter: textFilter({
                getFilter: (filter) => { // This does work
                    firstNameF = filter;
                }
            })
        },
        ...
];
```

Any advice on a way I can achieve this would be very helpful! Thanks so much!

**Comment by AllenFang** [comment]
@LRode add below code in your `DropdownFilter`:

```js
componentDidMount() {
    // check getFilter is existing or not
    if (this.props.column.filter.props.getFilter) {
      this.props.column.filter.props.getFilter((filterVal) => {
        this.props.onFilter(filterVal);
      });
    }
  }
```

Following is my example:

```js
class PriceFilter extends React.Component {
  static propTypes = {
    column: PropTypes.object.isRequired,
    onFilter: PropTypes.func.isRequired
  }
  constructor(props) {
    super(props);
    this.filter = this.filter.bind(this);
    this.getValue = this.getValue.bind(this);
  }
  componentDidMount() {
    if (this.props.column.filter.props.getFilter) {
      this.props.column.filter.props.getFilter((filterVal) => {
        this.props.onFilter(filterVal);
      });
    }
  }
  getValue() {
    return this.input.value;
  }
  filter() {
    this.props.onFilter(this.getValue());
  }
  render() {
    return [
      <input
        key="input"
        ref={ node => this.input = node }
        type="text"
        placeholder="Input price"
      />,
      <button
        key="submit"
        className="btn btn-warning"
        onClick={ this.filter }
      >
        { `Find ${this.props.column.text}` }
      </button>
    ];
  }
}
```

**Comment by LRode** [comment]
It works! Thank you so much @AllenFang!

**Comment by appasaheb4** [comment]
> Hi there, I've been loving using this library, but I've just run into a snag.
> 
> It's just been requested that I add a 'Reset all filters' button to my tables, however I have quite a complex table setup using a lot of `customFilter()`s. I set it up following the example [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Clear%20All%20Filters&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), however I've now realized that the `customFilter()` filter doesn't accept the `getFilter` prop, so the reset for many of my columns will not work :(
> 
> Is there any way I can implement resetting all filters while using custom ones? Here is a snippet of my columns + clearing logic
> 
> ```
> let statusF, firstNameF, lastNameF, emailF, rolesF;
> 
> const clearFilter = () => {
>         statusF('');
>         firstNameF('');
>         lastNameF('');
>         rolesF('');
>         emailF('');
>     };
> 
> const columns = [
>         {
>             dataField: 'status',
>             text: 'Status',
>             sort: true,
>             filter: customFilter({
>                 getFilter: (filter) => { // This is what does not work
>                     statusF = filter;
>                 }
>             }),
>             filterRenderer: (onFilter, column) => (
>                 <DropdownFilter
>                     column={column}
>                     options={[
>                         { value: 'Active', label: 'Active' },
>                         { value: 'Archived', label: 'Archived' }
>                     ]}
>                     onFilter={onFilter} />
>             )
>         },
>         {
>             dataField: 'firstName',
>             text: 'First Name',
>             sort: true,
>             filter: textFilter({
>                 getFilter: (filter) => { // This does work
>                     firstNameF = filter;
>                 }
>             })
>         },
>         ...
> ];
> ```
> 
> Any advice on a way I can achieve this would be very helpful! Thanks so much!

same issue facing you got solution?
