### ISSUE TITLE
exclude cell from selectRow

### ISSUE THREAD

**Issue by vtarelkin-comprehend** [react-bootstrap-table/react-bootstrap-table2#1288]
Good day. Thank you for your work!

I tried to implement onRowClick with the help of options but with no luck (maybe because I hover the table rows?) so I choose to use selectRow approach.

I've got a table with 
`
                selectRow={{
                    onSelect: handleClickSelectRow,
                    hideSelectColumn: true,
                    clickToSelect: true,
`
params and I have and icon in the cell. made via
`           dataField: 'iconField',
            isDummyField: true,
            formatter: iconsFieldFormatter,
            events: {
                onClick: (e, column, columnIndex, row, rowIndex) => {
                    iconHandleClick(rowIndex);
                },`

I set a click on icon (actually on a cell, can I reduce the size of a click area to make sure click was only on icon). 
So with those 2 events the selectRow is triggered always, but I want to exclude cell from it ( or a icon area, if possible). How that can be achieved? 

Thank you!

**Comment by AllenFang** [comment]
You can consider to use `stopPropagation`, https://developer.mozilla.org/zh-TW/docs/Web/API/Event/stopPropagation

**Comment by vtarelkin-comprehend** [comment]
thank you! 
cool, works like a charm ;-)
