### ISSUE TITLE
Is it possible to do custom checkbox style?

### ISSUE THREAD

**Issue by vtarelkin-comprehend** [react-bootstrap-table/react-bootstrap-table2#1290]
I spent many hours, but I couldn't find a way to customize the apperance of checkbox to be and behave like the checkbox on the pic.
Is it possible? 
I've found https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1237
but I really can't get it. Could you please provide an example with changing bgColor?
And if it possible to remove annoying "-" in checkbox header? 
![ch](https://user-images.githubusercontent.com/46703134/76691530-b355f200-665c-11ea-87a0-54eecf439529.png)

Thank you!

**Comment by AllenFang** [comment]
Custom checkbox on the header
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowselectionheaderrenderer-function

Custom cell style on the header
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowheadercolumnstyle-object-function

Custom cell style on the body
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowselectcolumnstyle-object-function

Custom checkbox
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowselectionrenderer-function

**Comment by vtarelkin-comprehend** [comment]
Thank you, but I've read this. I need only checkboxes, there is no examples, but 
```
selectRow.selectionRenderer - [Function]
Provide a callback function which allow you to custom the checkbox/radio box. This callback only have one argument which is an object and contain following properties:

const selectRow = {
  mode: 'checkbox',
  selectionRenderer: ({ mode, checked, disabled }) => (
    // ....
  )
};
```

Well, my code is 
```
                    selectionHeaderRenderer: ({mode, checked, indeterminate}) => {
                        if (checked) {
                            return {
                                backgroundColor: '#05AFF4',
                                color: '#FFFFFF'
                            };
                        }
                    }
```
doesn't work for me - it doesn't even shows a checkbox. What am I doing wrong?

**Comment by vtarelkin-comprehend** [comment]
@AllenFang ? please could you provide some code ?

**Comment by bmmpt** [comment]
@vtarelkin selectionRenderer and selectionHeaderRenderer must return JSX:

```
    selectionRenderer: (props) => (
        <input
            type={props.mode}
            checked={props.checked}
        />
    )
```

**Comment by AhsanNissar** [comment]
Is it possible to empty the checkboxes? I am trying to empty the checkboxes in a modal close function. I am using functional component and on accessing the useRef that is defined in table header I only am able to get the ref name and nothing else. How can I clear the selected checkboxes then?
