### ISSUE TITLE
Need to redirect to first page

### ISSUE THREAD

**Issue by MahiBaghel** [react-bootstrap-table/react-bootstrap-table2#1295]
How can i redirect to first page whenever i change sizeperpage

**Comment by Avasam** [comment]
@MahiBaghel By using [pagination.onSizePerPageChange](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationonsizeperpagechange-function) and [pagination.page](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationpage-number)

**Comment by AllenFang** [comment]
@Avasam thanks. use `onSizePerPageChange` you can know the size per change is change and assign to first page by `page` props.

**Comment by MahiBaghel** [comment]
Thanks its working now
