### ISSUE TITLE
Editing cells inside the table

### ISSUE THREAD

**Issue by nirkrumer** [react-bootstrap-table/react-bootstrap-table2#1298]
Hey,
I'm trying to configure table columns as editable
The issue is that the new value isn't been saved in a stable way.
For now, just the first row of the table is been saved.
When I change the values in the second row, it's not being saved, and then it rewrites these values (of the second row change) to the first row.

As Allen requested: 
@nirkrumer I can't run your code and it's hard to reproduce it. PLEASE CREATE A CODESANDBOX EXAMPLE SO THAT WE CAN HELP YOU EASILY. PLEASE KEEP IT SIMPLE AND MINIMAL.
___________________________________________________________________________
I attach the very minimal example.
Pay attention in order to test it, my class extends FlowPage 
(outer library for me, to show it on my 3 party UI application).

Also, I remarked the afterSaveCell attribute (I prefer not using that, cause this changes the logics of checkboxes in the original table and original values).
![image](https://user-images.githubusercontent.com/38032506/77071567-f3b6c680-69f4-11ea-8bc5-92a48c25ce12.png)

Hope everything is clear.
Thanks!

[schdueling.zip](https://github.com/react-bootstrap-table/react-bootstrap-table2/files/4354687/schdueling.zip)

**Comment by nirkrumer** [comment]
Hey guys,
Any thoughts?
Thx

**Comment by nirkrumer** [comment]
@AllenFang :)

**Comment by AllenFang** [comment]
@nirkrumer sorry.. I'm busy recently. actually, you don't need the `afterSaveCell`. it's just kind of post function for developer can know which cell been updated and it's not used for u to update the raw data.
