### ISSUE TITLE
Cant get selectRow to work

### ISSUE THREAD

**Issue by boomdrak** [react-bootstrap-table/react-bootstrap-table2#1299]
**Work perfectly without selectRow**
Have tryd with and without bootstrap4 option and all removing other props.
Any hints or tips? :)

```
import {
  Card, CardHeader, CardBody, Button,
} from 'reactstrap';
import BootstrapTable from 'react-bootstrap-table-next';
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';
import paginationFactory from 'react-bootstrap-table2-paginator';

  render() {
    const selectRow = {
      mode: 'checkbox',
      clickToSelect: true,
    };
 <BootstrapTable 
            bootstrap4 
            striped 
            hover 
            keyField="user_id" 
            data={this.state.tableData} 
            columns={columns} 
            selectRow={selectRow} 
            pagination={ paginationFactory() }
 />
```

Error:
> webpack:///./node_modules/react-bootstrap-table-next/lib/src/row-selection/row-consumer.js
> 
> row-consumer.js:31 Uncaught TypeError: _utils2.default.contains is not a function
>     at renderWithSelection (row-consumer.js:31)
>     at row-consumer.js:76
>     at updateContextConsumer (react-dom.development.js:15484)
>     at beginWork (react-dom.development.js:15672)
>     at performUnitOfWork (react-dom.development.js:19312)
>     at workLoop (react-dom.development.js:19352)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:149)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
>     at invokeGuardedCallback (react-dom.development.js:256)
>     at replayUnitOfWork (react-dom.development.js:18578)
> renderWithSelection @ row-consumer.js:31
> (anonymous) @ row-consumer.js:76
> updateContextConsumer @ react-dom.development.js:15484
> beginWork @ react-dom.development.js:15672
> performUnitOfWork @ react-dom.development.js:19312
> workLoop @ react-dom.development.js:19352
> callCallback @ react-dom.development.js:149
> invokeGuardedCallbackDev @ react-dom.development.js:199
> invokeGuardedCallback @ react-dom.development.js:256
> replayUnitOfWork @ react-dom.development.js:18578
> renderRoot @ react-dom.development.js:19468
> performWorkOnRoot @ react-dom.development.js:20342
> performWork @ react-dom.development.js:20254
> performSyncWork @ react-dom.development.js:20228
> requestWork @ react-dom.development.js:20097
> scheduleWork @ react-dom.development.js:19911
> enqueueSetState @ react-dom.development.js:11169
> ./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:325
> (anonymous) @ UserEdit.js:113
> Promise.then (async)
> updateData @ UserEdit.js:112
> componentDidMount @ UserEdit.js:87
> commitLifeCycles @ react-dom.development.js:17334
> commitAllLifeCycles @ react-dom.development.js:18736
> callCallback @ react-dom.development.js:149
> invokeGuardedCallbackDev @ react-dom.development.js:199
> invokeGuardedCallback @ react-dom.development.js:256
> commitRoot @ react-dom.development.js:18948
> (anonymous) @ react-dom.development.js:20418
> unstable_runWithPriority @ scheduler.development.js:255
> completeRoot @ react-dom.development.js:20417
> performWorkOnRoot @ react-dom.development.js:20346
> performWork @ react-dom.development.js:20254
> performSyncWork @ react-dom.development.js:20228
> requestWork @ react-dom.development.js:20097
> retryTimedOutBoundary @ react-dom.development.js:19789
> wrapped @ scheduler-tracing.development.js:207
> Promise.then (async)
> (anonymous) @ react-dom.development.js:18027
> commitWork @ react-dom.development.js:18019
> commitAllHostEffects @ react-dom.development.js:18680
> callCallback @ react-dom.development.js:149
> invokeGuardedCallbackDev @ react-dom.development.js:199
> invokeGuardedCallback @ react-dom.development.js:256
> commitRoot @ react-dom.development.js:18913
> (anonymous) @ react-dom.development.js:20418
> unstable_runWithPriority @ scheduler.development.js:255
> completeRoot @ react-dom.development.js:20417
> performWorkOnRoot @ react-dom.development.js:20346
> performWork @ react-dom.development.js:20254
> performSyncWork @ react-dom.development.js:20228
> requestWork @ react-dom.development.js:20097
> retryTimedOutBoundary @ react-dom.development.js:19789
> wrapped @ scheduler-tracing.development.js:207
> Promise.then (async)
> (anonymous) @ react-dom.development.js:18027
> commitWork @ react-dom.development.js:18019
> commitAllHostEffects @ react-dom.development.js:18680
> callCallback @ react-dom.development.js:149
> invokeGuardedCallbackDev @ react-dom.development.js:199
> invokeGuardedCallback @ react-dom.development.js:256
> commitRoot @ react-dom.development.js:18913
> (anonymous) @ react-dom.development.js:20418
> unstable_runWithPriority @ scheduler.development.js:255
> completeRoot @ react-dom.development.js:20417
> performWorkOnRoot @ react-dom.development.js:20346
> performWork @ react-dom.development.js:20254
> performSyncWork @ react-dom.development.js:20228
> requestWork @ react-dom.development.js:20097
> scheduleWork @ react-dom.development.js:19911
> enqueueSetState @ react-dom.development.js:11169
> ./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:325
> (anonymous) @ App.jsx:41
> Promise.then (async)
> componentWillMount @ App.jsx:39
> callComponentWillMount @ react-dom.development.js:11421
> mountClassInstance @ react-dom.development.js:11514
> updateClassComponent @ react-dom.development.js:14688
> beginWork @ react-dom.development.js:15644
> performUnitOfWork @ react-dom.development.js:19312
> workLoop @ react-dom.development.js:19352
> renderRoot @ react-dom.development.js:19435
> performWorkOnRoot @ react-dom.development.js:20342
> performWork @ react-dom.development.js:20254
> performSyncWork @ react-dom.development.js:20228
> requestWork @ react-dom.development.js:20097
> scheduleWork @ react-dom.development.js:19911
> scheduleRootUpdate @ react-dom.development.js:20572
> updateContainerAtExpirationTime @ react-dom.development.js:20600
> updateContainer @ react-dom.development.js:20657
> ./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20953
> (anonymous) @ react-dom.development.js:21090
> unbatchedUpdates @ react-dom.development.js:20459
> legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
> render @ react-dom.development.js:21155
> ./adminpanel/index.jsx @ index.jsx:28
> __webpack_require__ @ bootstrap:774
> fn @ bootstrap:129
> 9 @ events.js:448
> __webpack_require__ @ bootstrap:774
> (anonymous) @ bootstrap:953
> (anonymous) @ bootstrap:953
> 10react_devtools_backend.js:6 The above error occurred in the <Context.Consumer> component:
>     in WithSelectionRowConsumer (created by Body)
>     in tbody (created by Body)
>     in Body (created by BootstrapTable)
>     in table (created by BootstrapTable)
>     in div (created by BootstrapTable)
>     in BootstrapTable (created by Context.Consumer)
>     in SelectionProvider (created by Context.Consumer)
>     in PaginationDataProvider (created by Context.Consumer)
>     in DataProvider (created by BootstrapTableContainer)
>     in BootstrapTableContainer (created by UserEdit)
>     in div (created by CardBody)
>     in CardBody (created by UserEdit)
>     in div (created by Card)
>     in Card (created by UserEdit)
>     in div (created by UserEdit)
>     in UserEdit (created by ConnectFunction)
>     in ConnectFunction (created by Context.Consumer)
>     in Route (created by DefaultLayout)
>     in Switch (created by DefaultLayout)
>     in div (created by Container)
>     in Container (created by DefaultLayout)
>     in main (created by DefaultLayout)
>     in div (created by DefaultLayout)
>     in div (created by DefaultLayout)
>     in DefaultLayout (created by ConnectFunction)
>     in ConnectFunction (created by Context.Consumer)
>     in Route (created by App)
>     in Switch (created by App)
>     in Suspense (created by App)
>     in Router (created by HashRouter)
>     in HashRouter (created by App)
>     in div (created by App)
>     in App (created by ConnectFunction)
>     in ConnectFunction
>     in Provider
> 
> Consider adding an error boundary to your tree to customize error handling behavior.
> Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

**Comment by AllenFang** [comment]
HI @boomdrak  Did u use `underscore` in your codebase?

**Comment by AllenFang** [comment]
@boomdrak please open another issue to attach an example on codesandbox(Keep it simple and minimal) so that I can reproduce it. thanks. Let's close this
