### ISSUE TITLE
please give me some reference for add new row functionality

### ISSUE THREAD

**Issue by PriyaSahi** [react-bootstrap-table/react-bootstrap-table2#1304]
HI,

Please provide me some sample code to add new row functionality as am not getting anywhere by searching with react bootstrap table2. As am new to react js am not able to debug it properly. Please help me.

Thnk you in advance

**Comment by avindra** [comment]
@PriyaSahi maybe the editor sub-package can fulfill your use case: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-celledit.html

**Comment by AllenFang** [comment]
@PriyaSahi we don't have add row feature. you have to add new data and render the table.
