### ISSUE TITLE
Is there a way to set up defaultValue in customFilter

### ISSUE THREAD

**Issue by xiaoleATRI** [react-bootstrap-table/react-bootstrap-table2#1306]
**Question**
Hi, there:
I was trying to create a custom filter by using react-select. The idea is that the defaultValue is set up in react-select once the component is mounted. In the meantime, the defaultValue will be passed to onFilter function so that the table contents will be changed accordingly.

The problem I'm having now is that there is no way for me to set up a defaultValue in the custom filter to trigger onFilter function. Do you have any thoughts to solve this problem?
Thank a lot

**Comment by AllenFang** [comment]
@xiaoleATRI so far in custom filter, you have to figure a way to pass the default value.  <<< I think it shouldn't be a big problem

then you can trigger `onFilter` by yourself in `componentDidMount` or something else.

**Comment by AllenFang** [comment]
Please open another issue if you still have any issue or questions, thanks
