### ISSUE TITLE
Select Table Row On Right Click

### ISSUE THREAD

**Issue by amitsetty** [react-bootstrap-table/react-bootstrap-table2#1307]
I'm implementing a context menu over the table and want to select table rows on right click. Would appreciate a feature for this to be added - or if there's a workaround for this that would also be great

**Comment by AllenFang** [comment]
I guessI will not implement this feature. but there's a workaround is

1. use `rowEvents` to custom your right click event and you can get which row get right click
2. when above event happen, change the state for `selectRow.selected`


For the second step you can learn more from https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

this is a demo to show u how to select/unselect without default row clicking


For first step, you can learn from https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Rows&selectedStory=Row%20Event&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel to see how to custom a row event
