### ISSUE TITLE
onAuxClick event

### ISSUE THREAD

**Issue by dacevedo12** [react-bootstrap-table/react-bootstrap-table2#1312]
**Describe the solution you'd like**
Add support to onAuxClick as a rowEvent so that middle clicks can be handled

**Describe alternatives you've considered**
onClick doesn't trigger using the middle click so its not really an alternative since chrome 55

Edit: It triggers but the row object isn't passed as argument. It probably needs to be wrapped

**Comment by AllenFang** [comment]
@dacevedo12 no problem

**Comment by AllenFang** [comment]
Fixed. https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2020/04/18/version-bump.html
