### ISSUE TITLE
In onClick Row event . Can you please add a feature that change the color of the row when onclick is trigger.

### ISSUE THREAD

**Issue by archit1510130** [react-bootstrap-table/react-bootstrap-table2#1315]
I know there is already a workaround with that by USING SELECT ROW PROPS. but there is bug or restriction in that is when we select a row using selectrow prop then previous row color would not be automatically set to default .that means it makes user to feel that there are multiple rows are selected at one time .

So what I cconcisely want that if a USER click on a particular row then its background color should get changed and previous selected should get unselected(means background color set to default)

if there is any workaround for that Kindly let me know ALLEN because its a emergency type of stuff I want.

**Comment by waynebrantley** [comment]
Doesnt this already do it?
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Hide%20Selection%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by AllenFang** [comment]
thanks @waynebrantley
