### ISSUE TITLE
Same key warning when using pagination

### ISSUE THREAD

**Issue by bhupesh-sf** [react-bootstrap-table/react-bootstrap-table2#1319]
When I am using pagination its giving me following error

`Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in ul (created by PaginatonList)
    in PaginatonList (created by PaginationListAdapter)
    in PaginationListAdapter (created by Pagination)
    in div (created by Pagination)
    in div (created by Pagination)
    in Pagination (created by PaginationHandler)
    in PaginationHandler (created by PaginationDataProvider)
    in PaginationDataProvider (created by Context.Consumer)
    in DataProvider (created by BootstrapTableContainer)
    in BootstrapTableContainer (at DataTable/index.js:136)
    in div (at DataTable/index.js:135)
    in DataTable (at Users/index.js:266)
    in div (created by CardBody)
    in CardBody (at PageLayout.js:39)`

Following is the code 
`<BootstrapTable
        bordered={false}
        hover
        remote
        classes={'dataTable'}
        keyField={'id'}
        data={(data) || []}
        columns={this.state.columns}
        rowClasses={rowClasses}
        selectRow={selectRow}
        onTableChange={this.handleTableChange}
        pagination={pagination ? paginationFactory(options) : null}
        noDataIndication={this._setTableOption((isLoading || !data))}
        expandRow={expandRow}`

If I comment out pagination it starts working.

**Comment by bhupesh-sf** [comment]
And pagination is not working as well. Its showing me page numbers but nothing happens on click

**Comment by AllenFang** [comment]
Hi @bhupesh-sf you code is not enough for me to reproduce, please follow the instruction to create an issue and put a example on codesandbox so that I can help i efficiently.

thanks
