### ISSUE TITLE
Column's font size is not adjusting to the width columns 

### ISSUE THREAD

**Issue by joseph-vedadi** [react-bootstrap-table/react-bootstrap-table2#1320]
![image](https://user-images.githubusercontent.com/17168374/78600677-3572aa00-7808-11ea-910f-d18e7457d14b.png)

some of my tables have a lot of columns. and the result is as you see. :(

**Comment by AllenFang** [comment]
thanks @gosticks's answer

**Comment by nairsandeep** [comment]
Hi, I am new to this space. Apologies if it's trivial. 

Which prop should I use to have my columns auto-adjust to the size of the data? I have pasted by code below.

<BootstrapTable
                                    {...props.baseProps}
                                    bordered={false}
                                    defaultSorted={defaultSorted}
                                    pagination={paginationFactory({ sizePerPage: 5 })}
                                    wrapperClasses="table-responsive"
                                    selectRow={selectRow}
                                />
