### ISSUE TITLE
How to get the filtered json data after filtering by react-bootstrap-table2-filter

### ISSUE THREAD

**Issue by jackiehamchen** [react-bootstrap-table/react-bootstrap-table2#1323]
**Question**
I have 2 rows in json data
[{ "row1":"a"},{"row2":"b"}]

after filtering these rows by row number, the filtered json is now as below:
[{"row1":"a"}]

My question is that how to get the currently filtered json data. If get {data}, it will be the original json which is not filtered.

<ToolkitProvider
                                    keyField="_id"
                                    data={ submittedData } << this is not filtered,
/>
I would like to get filtered son as json string or object for further operation. Please suggest. 

Thank you very much.

**Screenshots**

**codesandbox**
Please give a simple and minimal example on https://codesandbox.io so that we can reproduce it easily.

**Comment by AllenFang** [comment]
> If get {data},
How do you get data?

and how do you filter data? 

Sorry, this question missing too many information. Please open another one and follow the instruction to create an issue so that I can help u efficiently
thanks
