### ISSUE TITLE
This lib is bugged!

### ISSUE THREAD

**Issue by sernovelli** [react-bootstrap-table/react-bootstrap-table2#1325]
**Describe the bug**
This lib is bugged! It's very simple to implement, but don't execute... the docs is very bad. What's error in my implementation, please?

**Screenshots**
![datatable1](https://user-images.githubusercontent.com/1108252/79124256-4f653d00-7d72-11ea-9ee8-5f79d6a3e6ff.png)
![datatable2](https://user-images.githubusercontent.com/1108252/79124258-50966a00-7d72-11ea-8096-be616c677ada.png)
![datatable3](https://user-images.githubusercontent.com/1108252/79124420-a79c3f00-7d72-11ea-8543-f953fd0ce132.png)

**Comment by vtarelkin-comprehend** [comment]
obviously you have wrong data coming into continentes

**Comment by sernovelli** [comment]
OK! But this code worked correctly with other components. Thank you!
