### ISSUE TITLE
Is there a way to use multiple filters on react-bootstrap-table2 table?

### ISSUE THREAD

**Issue by proasian42** [react-bootstrap-table/react-bootstrap-table2#1326]
It is my first time using a new version of the react-bootstrap-table. I am trying to use multiple filters on some header columns. For example, I want the user to select one or more fruits or to search for fruit on the same column. The react-bootstrap-table2 has both filters, multiSelectFilter, and textFilter.

I couldn't find a way to combine those filters together. It looks like filter function only accepts one, not two or more. I would like to know if there is a way to do that. Thank you!

`{
   dataField: "fruit",
   text: "Fruit",
   filter: multiSelectFilter({
     options: selectFruit
   }),
  filter: textFilter()            // A compiler will throw error since it doesn't accept dupilcated filter
}...`

**Comment by AllenFang** [comment]
@proasian42 I'm sorry we don't have this feature so far and maybe I won't implement this in near future. In term of you case, I will encourage u to custom the filter for your case. Sorry about that.
