### ISSUE TITLE
react-bootstrap-table2 with pagination and axios could not partially fetch data

### ISSUE THREAD

**Issue by vtarelkin-comprehend** [react-bootstrap-table/react-bootstrap-table2#1329]
good day.

I've asked this on SO, but there are no answers(

I really really got tired of trying to make things to work.

I have a component called Device and in useEffect i fetch the data for the first time for my component called DevicesTable where all the devices are.

The code below is in Device.js where I fetch data and send them to reducer. Data are parsed in reducer and are received by DevicesTable.js.

```
useEffect(() => {
    axios
        .get('http://**/ '?size=1000')
        .then(response => {
            dispatch(fetchData(response.data));
        }).catch(err => console.log(err));
}, []);
```
Backend actually allows me to fetch data by 1000 but I want to import only 20 for the first time. Then, after a clicking on pagination button in another component, I want to fetch another 20 and so on. Is it good approach?

Anyway, I can't get this to work.

In my DevicesTable component I've got paginationFactory with options
```

const paginationOptions = {
    paginationSize: 3,
    pageStartIndex: 0,
    firstPageText: '<<',
    prePageText: '<',
    nextPageText: '>',
    lastPageText: '>>',
    onPageChange: onPageChangeHandler,
    hideSizePerPage: true,
    totalSize: 27,
    totalPages: 2,
    sizePerPage: 20,
    hidePageListOnlyOnePage: true,

};
```
Of course, I can receive the amount of pages, total data size from the server, but here I've hardcoded it just to test how it works. As you see I have a handler onPageChangeHandler where I am dispatching the variable with the page number selected to send it to my first component named Device.

```
const onPageChangeHandler = (page, sizePerPage) => {
console.log( "I WAS HERE");
    dispatch(deviceTablePageChanged(page));
};
```
And here comes troubles. I declare a variable in Device component from the redux and my URI gets look like this

```
useEffect(() => {
    axios
        .get('http://**/ '?page=' + pageSelected)
        .then(response => {
            dispatch(fetchData(response.data));
        }).catch(err => console.log(err));
}, []);
```
and when I run this the first part of data is loading ok. I have 27 items on server, I want to get them by 20 (that is what server does by default). Some of those 20 items may be broken, so in my reducer I decided not to show them (they are nulls), so first page shows me only 13 items. That is acceptable, or it can be added more to 20 automatically? How can I do this? Well, this is not the main case, anyway.

When I click on the second page it seems (in console) that

there is a warning Warning: Cannot update a component from inside the function body of a different component.

My handler is called 2 times! the label "I WAS HERE" displayed 2 times! In console I see that it fetches right data for the 2 page and them for the 1 page. And if I watch over page variable it seems like I've clicked second page and then like I've clicked the first page. Of course I've made only one click, and the selected page becomes 1 and the data are shown from the first page.

That is the main issue I can't win. If I remove dispatch in handler, then I can switch between pages normally, however the second page is empty and useless. Please, any advices are appreciated

**Comment by vtarelkin-comprehend** [comment]
used another approach

**Comment by oahccc** [comment]
> used another approach

Hi @vtarelkin-comprehend,

Do you mind to share your approach? Really interested to know as I'm working on a similar partial-fetching function. Thank you in advance!

**Comment by sowmiyaseshadriii** [comment]
Hi @vtarelkin-comprehend ,
May i know how you resolved, facing same kind of problem, really will be helpful,
thanks.
