### ISSUE TITLE
Get final result from filter table as an Object 

### ISSUE THREAD

**Issue by AhmadYoussef** [react-bootstrap-table/react-bootstrap-table2#1332]
Hello, 
I am calculating a  sum of a column, but I am facing a problem when I use the filter that I can't know what is the final result when the user used a filter to re-calculate the sum 
I am using " ToolkitProvider   from   react-bootstrap-table2-toolkit".

I would like to know if there is a way to get the result of the filtering table as an Array

**Comment by AllenFang** [comment]
there're two way:

use `afterFitler` hook to know when a filter is done and you can collect the data that you want.
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/filter-props.html#afterfilter

or use expose API:
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html

>>> `this.node.filterContext.getFiltered`. 
The benefit is you can get the filtered data anytime when you want.
