### ISSUE TITLE
User can change column width

### ISSUE THREAD

**Issue by Akaren13** [react-bootstrap-table/react-bootstrap-table2#1339]
It would be usefull if user could adjust column width by himselves. Sometimes the data are too long and user could choose what he wants to see.

**Comment by AllenFang** [comment]
@Akaren13 so far I don't have plan to implement this feature. sorry about this.

**Comment by Akaren13** [comment]
Ok, but can you at least advice me if there is any way how to do it? Maybe setings column class or?
