### ISSUE TITLE
Text Filter broken ? 

### ISSUE THREAD

**Issue by salimkanoun** [react-bootstrap-table/react-bootstrap-table2#1345]
Hi there,

Thanks for this amazing library that I'm using for few months for the first time,

I upgraded to the last release and now my table which were working properly now have a bug when I inject data in it.
I have the following message 

```
TypeError: Cannot read property 'afterFilter' of undefined
FilterProvider.doFilter
C:/Users/kanoun_s/vsCode/ImageFetcher/ImageFetcher/FrontEnd/node_modules/react-bootstrap-table2-filter/lib/src/context.js:140
```

Is there  a breaking change in the last version of the filter ? 
In this table I'm just using the default textFilter() of react-bootstrap-table2-filter to filter some text input.

Best regards,

Salim

**Comment by brittlewis12** [comment]
Hey folks we're experiencing this as well it seems from 1.3.1 -> 1.3.2

**Comment by middleBoss** [comment]
Hey, salimkanoun have you found a way to solve this problem?

**Comment by middleBoss** [comment]
> Hey folks we're experiencing this as well it seems from 1.3.1 -> 1.3.2
> 
> EDIT: looks like your builds are aware of the error: https://travis-ci.org/github/react-bootstrap-table/react-bootstrap-table2/jobs/677223226#L382

Hey, brittlewis12 have you found a way to solve this problem?

**Comment by salimkanoun** [comment]
@middleBoss  Just downgrad the filter librairie to 1.3.1

**Comment by klapouchy** [comment]
@salimkanoun I had the same issue - downgrade to 1.3.1 helped.

**Comment by simcoles** [comment]
> @salimkanoun I had the same issue - downgrade to 1.3.1 helped.
I have downgraded to version 1.3.1 but still facing the same issue, any update on this please?
Issue resolved had a cached newer version.

**Comment by thiagoconnectcom** [comment]
o Problema esta na versão 1.3.1 > 1.3.2

Para resolver vá ao package.json e troque "react-bootstrap-table2-filter": "^1.3.1", para apenas "react-bootstrap-table2-filter": "1.3.1".

- rode npm i 
- npm start.

**Comment by kgrech** [comment]
I've also faced the same issue. In my case I was able to solve it by updating the react-bootstrap-table-next dependency to recently released v4.0.3:
```
"react-bootstrap-table-next": "^4.0.3",
"react-bootstrap-table2-filter": "^1.3.3",
```

**Comment by jbailey2954** [comment]
Seems like a patch release shouldn't introduce a breaking change. Is anyone working on a fix?

**Comment by khoand10** [comment]
> I've also faced the same issue. In my case I was able to solve it by updating the react-bootstrap-table-next dependency to recently released v4.0.3:
> 
> ```
> "react-bootstrap-table-next": "^4.0.3",
> "react-bootstrap-table2-filter": "^1.3.3",
> ```

work for me!

**Comment by nextglabs** [comment]
> I've also faced the same issue. In my case I was able to solve it by updating the react-bootstrap-table-next dependency to recently released v4.0.3:
> 
> ```
> "react-bootstrap-table-next": "^4.0.3",
> "react-bootstrap-table2-filter": "^1.3.3",
> ```

Works for me too 👍

**Comment by vodnokoki** [comment]
Faced with same issue, updating react-bootstrap-table-next dependency to recently released v4.0.3 fixed issue for me.

Thanks.

**Comment by lewismacdonald** [comment]
> I've also faced the same issue. In my case I was able to solve it by updating the react-bootstrap-table-next dependency to recently released v4.0.3:
> 
> ```
> "react-bootstrap-table-next": "^4.0.3",
> "react-bootstrap-table2-filter": "^1.3.3",
> ```

this fixed prob for me too!

**Comment by BenBirldland** [comment]
> I've also faced the same issue. In my case I was able to solve it by updating the react-bootstrap-table-next dependency to recently released v4.0.3:
> 
> ```
> "react-bootstrap-table-next": "^4.0.3",
> "react-bootstrap-table2-filter": "^1.3.3",
> ```

Worked for me as well!

**Comment by salimkanoun** [comment]
Thanks for feedback I close that issue since we all see that is has been fixed

**Comment by josephkannatraj** [comment]
Hi there, 
I am facing an issue on 'react-bootstrap-table-next'

I'm using recent versions


TypeError: can't access property "filter", props.columns is undefined
BootstrapTableContainer
              .../node_modules/react-bootstrap-table-next/lib/src/contexts/index.js:96

            93 |   props.registerExposedAPI(exposedAPIEmitter);
            94 | }
            95 | 
            > 96 | if (props.columns.filter(function (col) {
               | ^  97 |   return col.sort;
            98 | }).length > 0) {
            99 |   _this.SortContext = (0, _sortContext2.default)(_operators2.default, _this.isRemoteSort, _this.handleRemoteSortChange);
