### ISSUE TITLE
Can we add react-bootstrap button in the column's cell of react-bootstrap-table2?

### ISSUE THREAD

**Issue by sakshivicesoftware** [react-bootstrap-table/react-bootstrap-table2#1349]
Can we add react-bootstrap button in the column's cell of react-bootstrap-table2?
I want my last column to have button for every row so how will we do it?
@AllenFang or anybody from your team if you can guys can help me with this as it is really important.
Thanks

**Comment by sakshivicesoftware** [comment]
I found the solution.

**Comment by Vitagliano** [comment]
Can you provide the solution? @sakshivicesoftware

**Comment by Ymbere** [comment]
@Vitagliano you can use a formatter to achieve that result, I have an example here that uses it.

[![Edit Button Counter](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/button-counter-5y6w6?fontsize=14&hidenavigation=1&theme=dark)
