### ISSUE TITLE
Manage expanded row

### ISSUE THREAD

**Issue by aZolo77** [react-bootstrap-table/react-bootstrap-table2#1353]
Can I somehow get access to expanded row "td"-element? I need to fix its auto colspan value.
There is function "onExpand", but I guess it is called before new row is rendered..

**Comment by AllenFang** [comment]
@aZolo77 you can use react ref or just get element by id. In `react-bootstrap-table2`, we give developer to render the content of expand row, so I guess you can decide how to access the row by yourself.
