### ISSUE TITLE
Issue with formatExtraData for multiple values in a single column

### ISSUE THREAD

**Issue by sidthekidder** [react-bootstrap-table/react-bootstrap-table2#1357]
Hi, I am trying to access data from 2 different columns in a single column, tried to use formatExtraData, but formatExtraData doesn't seem to pick up the dataField from other columns. It just passed the string directly. Of the 4 arguments passed into the formatter, the 1st arg doesn't contain the other variables of the row, the 2nd arg is an index, the 3rd arg is an object with sortElement and filterElement keys(I am wrapping the table in ToolkitProvider for searching) and the 4th arg is undefined. 

My formatter code is this -
```
let columns = [{
      dataField: 'Product.official_id',
      text: 'Name',
      headerFormatter: productFormatter,
      formatExtraData: {
        name: 'Product.name',
        name: 'Product.image_url',
      }
    }, {
      dataField: 'Product.price',
      text: 'Price',
      sort: true
    }]

function productFormatter(cell, row, rowIndex, formatExtraData) {
    console.log("In productformatter")
    console.log(cell)
    console.log(row)
    console.log(rowIndex)
    console.log(formatExtraData)

    return (
      <h5><strong>{ cell.text }</strong></h5>
    )
  }
```
And I get this in the console -
<img width="711" alt="scc" src="https://user-images.githubusercontent.com/3611800/80460680-cc0f2400-88f9-11ea-9640-5c3f69f16128.png">

**Comment by AllenFang** [comment]
I think the snd argument is a row object which must contain any other properties. So it's enough for your use case, no need to leverage `formatExtra`
