### ISSUE TITLE
Cancel EditCell on Pagination

### ISSUE THREAD

**Issue by zoldbogar** [react-bootstrap-table/react-bootstrap-table2#1364]
Hello Allen,

My previous report was closed and there was no new answer in the past 3+ weeks, so I thought I'd open a new question for https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1316

As I stated in my last response I created a sandbox project using your code, where the behavior I am talking about is consistently reproducing: https://codesandbox.io/s/adoring-almeida-egdqm?file=/src/App.js 

Open an editor on the first page and then move to the second page. I would expect the editor to be closed, but when going to the second page the editor on the same row number will still be open.

Please let me know how I could work around this.

Thanks

**Comment by AllenFang** [comment]
@zoldbogar add `autoFocus` on your input element.

**Comment by zoldbogar** [comment]
thank you very much, 
although I have no idea how `autoFocus` affects pagination, how this solution works or how would I have identified this fix without your kind help: it really works as expected.
Thanks again!
