### ISSUE TITLE
Return filtered and searched data only

### ISSUE THREAD

**Issue by Mikeez** [react-bootstrap-table/react-bootstrap-table2#1365]
**Question**
I am using ToolkitProvider and BootstrapTable and I have column filtering and a global search. How can I get the filtered data after searching and filtering?

I want to set the filtered data to a new state to be able to export for PDF.

I tried:

Using the option in BootstrapTable and having a callback function, did not work.
I used the onFiltering and I tried to setState
Is there a more efficient way, I read the documentation concerning the filtering. Nothing jumps out to me

**Comment by Mikeez** [comment]
I read a lot of people were able to go around this, any suggestion?

**Comment by AllenFang** [comment]
@Mikeez for column filter, we got [`afterFilter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/filter-props.html#afterfilter), [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Filter%20Hooks&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an online example.

However, for the searching, we don't have this function yet. However, there's another solution is using the [exposed API](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html#get-current-display-rows) but it's not a listener solution.

Anyway, I will implement a `afterSearch` hook for u, thanks

**Comment by AllenFang** [comment]
Please upgrade packages to newest and you will have `afterSearch`.

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/search-props.html#searchaftersearch-function
