### ISSUE TITLE
Add headerAttr for selectionRow header renderer

### ISSUE THREAD

**Issue by paypay43** [react-bootstrap-table/react-bootstrap-table2#1371]
Hi, I have a need to add scope="col" to the selection header column...

headerAttrs = {
      scope: 'col',
    }; 

this works for a column header, but there's no way to do this for the checkbox column header <th> 

thanks

**Comment by AllenFang** [comment]
@paypay43 we don't have this feature for developer to attach the custom attribute to the selection header, please use `selectionHeaderRenderer` to custom the selection header as a workaround. [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Custom%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example you can take and it's very easy.

I will implement this feature when I got time. thanks! 🙏

**Comment by paypay43** [comment]
i need it on the <th> not on the element inside of it

**Comment by mchuttani18** [comment]
Hi, were you able to find a way to add scope="col" on the <th> element using selectionHeaderRenderer?

**Comment by paypay43** [comment]
no but i found a work a round if u want help and i can
