### ISSUE TITLE
data.filter is not a function

### ISSUE THREAD

**Issue by iAnthonyCoder** [react-bootstrap-table/react-bootstrap-table2#1372]
**Describe the bug**
I din't know if this is a bug or not compatibility with the currect react create app but when i try to use the search feature included in the toolkit i always receive this error.

data.filter is not a function

i used a code that i made like 1 year ago and 1 year ago it worked but now te return that error

**To Reproduce**
Only enable search feature and error will appear

key: 'search',
        value: function search(props) {
          var data = props.data,
              columns = props.columns;

          var searchText = props.searchText.toLowerCase();
          return data.filter(function (row, ridx) {     <--------bug here
            for (var cidx = 0; cidx < columns.length; cidx += 1) {
              var column = columns[cidx];

It is like if the function is fired when page is rendered and of course, or something with the async?

**Comment by AllenFang** [comment]
I never see this bug, would you please reopen an issue but please attach an online example by codesandbox so that I can help u more efficient? thanks!

**Comment by GokulSuresh27** [comment]
@AllenFang Did you find any solution for this ?
