### ISSUE TITLE
how to display array values inside an array

### ISSUE THREAD

**Issue by kislayaaakash** [react-bootstrap-table/react-bootstrap-table2#1374]
dataField: 'categories[0].categoryName',
        text: 'associated categories',
        editable: false,
        headerFormatter: this.boldHeader,
        formatter: this.edit3,
        headerAlign: 'center',
        align: 'center',
        editor: {
          type: Type.TEXTAREA
        }

my aim is to show all the categoryName but I am unable to do so, I am only able to show the category name for particular index of categories array.
Please help it's urgent.

**Comment by AllenFang** [comment]
use [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function)

**Comment by natan7366** [comment]
What should be inside the for loop if I want to display the array items line by line ?
