### ISSUE TITLE
How does Remote concept work(pagination, sorting, filter) ?

### ISSUE THREAD

**Issue by anjaligupta1404** [react-bootstrap-table/react-bootstrap-table2#1375]
**Describe the bug**
A clear and concise description of what the bug is. In addition, please search issues before you open a report to make sure there's no any duplicated report

I have to integrate API in react and perform remote sorting, pagination, filter. But I am not getting any clarity in terms of execution. What steps should I do 

**To Reproduce**

**Screenshots**

**codesandbox**
Please give a simple and minimal example on https://codesandbox.io so that we can reproduce it easily and handle it effectively

**Comment by anjaligupta1404** [comment]
I checked documentation but its not much helpful for me. So can you please help me

**Comment by AllenFang** [comment]
@anjaligupta1404 remote mode means for pagination, filter or sorting means you have to do the paging, filter and sorting in outside(In your codebase). [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Sort&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an online example to show u how to use remote mode with sorting, and we also have enough online example for remote paging, filtering, searching etc. Please read it. 

Anyway, I don't have too much time to teach u to write a remote mode code and I believe above example and docs should be enough. Please open another issue when u have any bug or issue. thanks
