### ISSUE TITLE
Update a check box post load in a read only column

### ISSUE THREAD

**Issue by nishanthkothuru** [react-bootstrap-table/react-bootstrap-table2#1376]
Hi,
I am working on a project where I need to update a check box in the table depending on the events happening outside of the table. The table itself cannot be edited manually. Changing the value in the data set behind the table is not updating it.

Here is my code to format the field
format = (cell) => <input type="checkbox" checked={cell} readOnly/>

and the code to update the value
records.forEach(x => {
    if (x.LotSerialNo === element) {
        x['PO Ver\'d'] = !x['PO Ver\'d']
        console.log(x['PO Ver\'d'])
    }
})

I can see that the data set is updating properly by logging the value to console, but the display on the screen is where I have trouble

Please help!!!

Thanks,
Nishanth

**Comment by AllenFang** [comment]
@nishanthkothuru don't mutate the state or props, it's king rule in react. We will compare the current prop and next props to decide whether or not we should update the cell or row.

**Comment by nishanthkothuru** [comment]
Hi @AllenFang, Thanks for your response!
