### ISSUE TITLE
Table fails to render data containing dots in key names

### ISSUE THREAD

**Issue by avindra** [react-bootstrap-table/react-bootstrap-table2#1381]
**Describe the bug**
The table fails to render data that has dots in the keys.

This was already reported on #1302 which was closed and never reopened so I am filing a new issue w/ the relevant code sandbox that @AllenFang  wanted.

**To Reproduce**
Pass `data` to the Table that contains dots inside of the object keys.

**Screenshots**
![image](https://user-images.githubusercontent.com/126848/82575479-87705480-9b56-11ea-9513-64231b255d92.png)

**codesandbox**

https://codesandbox.io/s/xenodochial-faraday-t7y2v?file=/src/App.js

**Comment by AllenFang** [comment]
@avindra please upgrade `react-bootstrap-table-next` to newest and open another issue if the issue still remain, thanks

**Comment by avindra** [comment]
Thanks @AllenFang . Nominally, the latest version seems to fix the issue:

https://codesandbox.io/s/inspiring-water-fw1pc?file=/src/index.js
