### ISSUE TITLE
Lodash for underscore - _utils2.default.contains is not a function

### ISSUE THREAD

**Issue by boomdrak** [react-bootstrap-table/react-bootstrap-table2#1384]
**Error when using rowSelect with lodash 4.+** 

When using current version of react-boostrap-table2 i get an error when using the rowSelect function. Loading the datatable crashes and the following error is prompted: 

node_modules\react-bootstrap-table-next\lib\src\row-selection\row-consumer.js
line 31,32,33 : _utils2.default.contains is not a function

As this post states, .contain has been swapped for .includes in lodash 4+
https://github.com/mgonto/restangular/issues/1298#issuecomment-171945302

Simply renaming .contains with .includes in row-consumer.js seems to work and removes the error.

**To Reproduce**

1. Use the following packages
"react-bootstrap-table-next": "^4.0.2",
"lodash": "^4.17.15",
"underscore": "^1.9.2",
"webpack": "4.41.0",

2. In webpack.config i have the following setup:
  resolve: {
    extensions: [ '.js', '.jsx' ],
    modules: [
      path.resolve('./js'),
      path.resolve('./es6'),
    ],
    alias: {
      // Make backbone use lodash instead of underscore
      **underscore: 'lodash/'**
    }
  },

3. Create a datatable with prop:
selectRow={selectRow}

4. See error in your browser
row-consumer.js
line 31,32,33 : _utils2.default.contains is not a function

**Edited..**
I see that alot of other files uses .contains function also..
So not sure if there is a better fix?

**Screenshots**
<img width="676" alt="lodash_contains" src="https://user-images.githubusercontent.com/4997449/82894221-83777480-9f52-11ea-9ac1-63ba6cd02579.png">

<img width="788" alt="contains" src="https://user-images.githubusercontent.com/4997449/82894564-0ef10580-9f53-11ea-905e-68405fc211c5.png">

**Comment by boomdrak** [comment]
I see that alot of other files uses .contains function also..
So not sure if there is a better fix?

**Comment by AllenFang** [comment]
@boomdrak it's an edge case for me actually, but I guess I have a simplest solution. Let me fix it and see if it is work or not.

**Comment by AllenFang** [comment]
@boomdrak upgrade `react-bootstrap-table-next` to newest. Please open another issue if the issue still remain, thanks

**Comment by boomdrak** [comment]
Thank you so much, @AllenFang 👍 
Works perfectly!
