### ISSUE TITLE
React Bootstrap Table 2 default sort ignored.

### ISSUE THREAD

**Issue by reposman33** [react-bootstrap-table/react-bootstrap-table2#1402]
I have a table with several columns, I want the table to be sorted on te 1st column on initial display. While I follow the docs it seems that the default sort is ignored.

This is my column definition:

```
	// define the columns for the table
	getColumns = () => [
		{ dataField: "id", text: "#", headerStyle: { width: "4%" }, sort: true },
		{
			dataField: "date",
			formatter: (cell, row, rowIndex) => this.Utils.dateFormat.format(cell),
			headerStyle: { width: "15%" },
			sort: true,
			sortFunc: this.Utils.dateSortFunction,
			text: this.I18n.get("EXPENSES.TABLE.HEADERS.DATE"),
		},
		{
			dataField: "company",
			formatter: (cell, row, rowIndex) => <span className={componentStyles.textOverflow}>{cell}</span>,
			headerStyle: { width: "25%" },
			text: this.I18n.get("EXPENSES.TABLE.HEADERS.COMPANY"),
			sort: true,
		},
		{
			dataField: "amount",
			headerStyle: { width: "10%" },
			formatter: (cell, row) => this.Utils.currencyFormat.format(cell),
			sort: true,
			text: this.I18n.get("EXPENSES.TABLE.HEADERS.AMOUNT"),
		},
		{
			dataField: "actions",
			text: this.I18n.get("INVOICES.TABLE.HEADERS.ACTIONS"),
			isDummyField: true,
			formatter: () => (
				<span className={ReactBootstrapTableStyles.actionIcons}>
					<FontAwesomeIcon icon='print' />
					<FontAwesomeIcon icon='edit' />
				</span>
			),
			headerStyle: { width: "10%" },
		},
	];
```

I want to sort on the 1st column:

```
	table = {
		defaultSorted: [
			{
				dataField: "id",
				order: "desc",
			},
		],
		defaultSortDirection: "desc",
	};
```
This is how I configure the table component in the component

```
				<BootstrapTable
					bootstrap4
					data={this.state.rowData}
					classes={ReactBootstrapTableStyles.ReactBootstrapTable}
					columns={this.getColumns()}
					table={this.table}
					keyField='ID'
					rowEvents={{ onClick: this.onRowClick }}
					pagination={paginationFactory(this.paginationConfig)}></BootstrapTable>
```
This is a screenshot of initial display

![image](https://user-images.githubusercontent.com/3200870/85163093-9f74ea00-b262-11ea-8a89-fa5124f4ea8a.png)

You can see that the 1st column (id / #) is not sorted. A data snippet from this.state.rowData:

![image](https://user-images.githubusercontent.com/3200870/85163476-2b871180-b263-11ea-838c-ad1b38b8eafc.png)

shows that id is a numeric value.

Am I missing something?

**Comment by saule1508** [comment]
Hello

I think the defaultSorted property does not do what you expected. The property does not tell the component to do the sorting, it says to the component on which field the data is (already) sorted, so that the component can put the small visual indicator in the column header (i.e. the arrow). But  the data provided must be sorted on this key.

Pierre

**Comment by aieshgit** [comment]
Hi [reposman33]. Were you able to resolve this ?
I am in a similar situation.
If you were able to resolve this, can you please guide me in the correct direction ?
