### ISSUE TITLE
Drawing bug when setting column width using headerStyle

### ISSUE THREAD

**Issue by sudravi** [react-bootstrap-table/react-bootstrap-table2#1405]
**Describe the bug**
When I add headerStyle to a column, I see a drawing bug. There's a small blue rectangle below the selected column header.

**To Reproduce**
1. Go to CodeSandbox, link below
2. Click on any of the column headers, e.g. ProductID
3. See drawing bug in the cell below the selected column header

**Screenshots**
<img width="580" alt="Screen Shot 2020-06-23 at 5 56 15 PM" src="https://user-images.githubusercontent.com/38792186/85487236-0f47e500-b581-11ea-8683-f45afad609f7.png">

**codesandbox**
https://codesandbox.io/s/react-bootstrap-table-2-q9ldo?file=/src/Table.js:688-715

**Comment by unllamas** [comment]
Apply in your style.css
`*{ outline: none! !important }`
It happens that the arrows take them as buttons and add an outline

**Comment by sudravi** [comment]
@jonallamas thanks, that works! There was an extra exclamation after none, but otherwise worked great.
