### ISSUE TITLE
unselect row

### ISSUE THREAD

**Issue by alperg** [react-bootstrap-table/react-bootstrap-table2#1406]
**Question**
In 'radio' mode, how do you unselect a row, if it's already selected?

this is my setup:

```javascript
selectRow={{
  mode: 'radio',
  clickToSelect: true,
  hideSelectColumn: true,
  classes: 'selected-row'
}}
```

**Comment by smeet2804** [comment]
@AllenFang @alperg 
Hello,
What's the solution for this? I want the same thing. Can you please help?
