### ISSUE TITLE
How do I pass multiple state variables to the formatExtraData?

### ISSUE THREAD

**Issue by jspin77** [react-bootstrap-table/react-bootstrap-table2#1411]
Trying to use a <Link> within in the table.  The issue is that I am trying to pass some state variables through that link.... 
          formatter: (cell, row) => {
                    return <Link
                              to={{
                                pathtext: `search/${row.id}`,
                                dataSetIds: this.state.dataSetIds,
                                searchText: this.state.searchText,
                              }}
                            >
                              {row.title}
                            </Link>
          }

So then I saw that I cannot pass data through the formatter and needed to use the formatExtraData.  But the examples only show how to pass one state variable. 

How would I populate the formatExtraData with the information that is above?

**Comment by chilobe** [comment]
formatExtraData can be an object, with as many values as you want, e.g. 

formatExtraData: {value1: someValue, value2:anotherValue} 

e.t.c

then just access them in formatter via

formatter: (cell, row, index, extraData) = > 
{
extraData.value1
} 

e.t.c

**Comment by AllenFang** [comment]
@chilobe's answer is correct, the `formatExtraData` can be anything
