### ISSUE TITLE
Filter on more than one value using a select dropdown 

### ISSUE THREAD

**Issue by msueping** [react-bootstrap-table/react-bootstrap-table2#1412]
**Question**
Using the example at the link below, is it possible to have both the "good" and the "unknown" rows included if "good" is selected in the drop down filter list. Same for if "bad" was selected; both "bad" and "unknown" would be included (but not "good").

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Select%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by AllenFang** [comment]
@msueping you can filter one more value via a single selection, but you can adopt [multi select filter](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-filter.html#multiselect-filter)
