### ISSUE TITLE
Search Formatter for Specific Cell (Phone Number)

### ISSUE THREAD

**Issue by AdamJakiela** [react-bootstrap-table/react-bootstrap-table2#1414]
**Question**
Hello,
I have a table with a column that contains a phone number. Since the data is stored unformatted, column uses a formatter to properly format the phone number. So for example 14632222408 -> 1 (463) 222-1408. 

For this table, `searchFormatted` is set to `true` to search over the formatted data. However, I have noticed that users search for phone numbers in many ways:

14632222408
1 (463) 222-1408
1-463-222-1408
1-(463)-222-1408
+14632222408

Is there a way I can change the search value for the column to only compare the raw data? So for example, if the user searches 1 (463) 222-1408 it should remove all non numeric characters and only search against the raw value. Keep in mind this is the only column where the value would be compared like this `searchFormatted` needs to be enabled for the rest of the table. I have tried `onColumnMatch` but have not had any luck. 

I appreciate any assistance with this.

**Screenshots**
<img width="150" alt="Screen Shot 2020-07-02 at 2 55 04 PM" src="https://user-images.githubusercontent.com/9663892/86399085-a3e2cf00-bc74-11ea-8c3f-1a00a3b0b0e7.png">

**codesandbox**
Please give a simple and minimal example on https://codesandbox.io so that we can reproduce it easily.

**Comment by AllenFang** [comment]
hi @AdamJakiela boss, try this: https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Custom%20match%20function&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

I just found the custom search didn't documented. will patch it... sorry
