### ISSUE TITLE
Expand should work only when we click on the expand indicator

### ISSUE THREAD

**Issue by SandeepKapalawai** [react-bootstrap-table/react-bootstrap-table2#1420]
**Describe the bug**
Hi I am using the custom expand indicator to implement the collapse only functionality  in the  expandHeaderColumnRenderer

as per the storybook example i have implemented the custom indictors to show the collapse all (...) when i click on that and i gave the other condition as null  (not to perform expand)

`  expandHeaderColumnRenderer: ({ isAnyExpands }) => {
      if (isAnyExpands) {
        return <b>-</b>;
      }
      return null;
    },`

As per the above condition i will not see any indication to expand all., which is correct But  the issue is when i click on that area which null i am seeing  the expand is working, which should not be the case in this scenario. Is there any way I can restrict only expand functionality in such a case.

Apologies if this is not a bug
**Screenshots**

**codesandbox**
https://codesandbox.io/s/react-bootstrap-table-next-basic-example-3fkwz?file=/src/index.js:969-1107

@AllenFang  @chimericdream

**Comment by AllenFang** [comment]
@sonusandeep if you want to expand the row by clicking expand indicator, you should enable [`expandByColumnOnly `](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowexpandbycolumnonly-bool)

Please open another issue if the problem still remain, thanks

**Comment by SandeepKapalawai** [comment]
Thank you so much @AllenFang , for the reply, i dont need the expand to be performed in table header, all i need is only the collapse should be performed, for that i have the indicator for only the collapse case and the other case i  gave it as null. But when in case an empty indicator if I click on the expand column, the rows are expanding, in my case i don't need to perform  the expand, is there any way i can restrict this. Thank you once again. #1422
