### ISSUE TITLE
Expand all is happening even if i click in the empty are/ when i dont display any indicator

### ISSUE THREAD

**Issue by SandeepKapalawai** [react-bootstrap-table/react-bootstrap-table2#1422]
**Describe the bug**
Hi I am using the custom expand indicator to implement the collapse only functionality( i dont need to have expand all )  in the expandHeaderColumnRenderer

as per the storybook example, i have implemented the custom indictors to show the collapse all (...) when i click on that and i gave the other condition as null  , so as(not to perform expand)
 
Here is my code :  as suggested by @AllenFang  in #1420 , i have added **expandByColumnOnly: true,** but this doesn't seem working for me.

`const expandRow = {
    renderer: row => (
      <div>
        <p>{`This Expand row is belong to rowKey ${row.id}`}</p>
        <p>
          You can render anything here, also you can add additional data on
          every row object
        </p>
        <p>
          expandRow.renderer callback will pass the origin row object to you
        </p>
      </div>
    ),
    showExpandColumn: true,
    expandByColumnOnly: true,
    expandHeaderColumnRenderer: ({ isAnyExpands }) => {
      if (isAnyExpands) {
        return <b>-</b>;
      }
      return null; //it means i should not perform any expand
    },
    expandColumnRenderer: ({ expanded }) => {
      if (expanded) {
        return <b>-</b>;
      }
      return <b>...</b>;
    }
  };
`
expandHeaderColumnRenderer: ({ isAnyExpands }) => { if (isAnyExpands) { return <b>-</b>; } return null; },

As per the above condition, I will not see any indicator for expand all., which is correct But the issue is when I click on that area which is null/ empty I am seeing the expand is still happening, which should not be the case in this scenario. Is there any way I can restrict only expand functionality in such a case

Please find the code sandbox link in below:

@AllenFang  request you to please review this, Thank you

**codesandbox**
https://codesandbox.io/s/react-bootstrap-table-next-basic-example-zsu58?file=/src/index.js

**Comment by AllenFang** [comment]
HI @sonusandeep  boss, so far we can't do this((for your requirement, but I got an idea.. ugly idea.. lol

Make the empty element to full cover the `th` element:
First, make it cover the `th` element:
```js
expandHeaderColumnRenderer: ({ isAnyExpands }) => {
  if (isAnyExpands) {
    return <b>-</b>;
  }
  const style = {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    bottom: 0,
    width: '100%'

  }
  return <div style={ style } onClick={e => e.stopPropagation()} />; 
},
```

Second: change it's parent(`th`) as position relative:

```css
.react-bootstrap-table > table > thead > tr:first-child > th:first-child {
  position: relative;
}
```

I tested it and work perfect. Let me know if above isn't work.

**Comment by AllenFang** [comment]
it's my link:
https://codesandbox.io/s/react-bootstrap-table-next-basic-example-z3qde?file=/src/index.js

**Comment by SandeepKapalawai** [comment]
Awesome boss @AllenFang , working perfect :)
