### ISSUE TITLE
Column classes callback function columnIndex ignore hidden columns

### ISSUE THREAD

**Issue by marcRobertHabib** [react-bootstrap-table/react-bootstrap-table2#1425]
I don't know if it is a bug or not, but from my experience when there are columns like this:
  column0 -> hidden = true
  column1  -> classes = callback(cell, row, rowIndex, colIndex)

colIndex value in callback is 0.
If  column0 is not hidden, colIndex is 1.

**Comment by AllenFang** [comment]
@marcRobertHabib actually the hidden column didn't render on HTML so it's expected behavior in my opinion. Please open another issue if you have another use case, I will consider to enhance it. 

thanks
