### ISSUE TITLE
How to draw table with complex data where each object from array contain another level of array of objects.

### ISSUE THREAD

**Issue by manojsharma20** [react-bootstrap-table/react-bootstrap-table2#1426]
I have a simple requirement where I have to draw a table with complex data where each object from array contain another level of array of objects. Something like below structure:

 "data": [
            {
                "uuid": "616509f786a",
                "emailId": "test@test.com",
                "password": "cvdfgfgdfvsdjgsdhgjkdsbgdjkbgvd",
                "firstName": "TEST",
                "middleName": "Tester",
                "lastName": "test",
                "mobile": "7684674986",
                "roles": [
                    {
                        "id": 1,
                        "roleName": "ROLE_1",
                        "roleDesc": "Role 1",
                        "privileges": [
                            {
                                "id": 1,
                                "privilegeName": "PRIVILEGE_1",
                                "privilegeDesc": Privilege 1",
                                "createdAt": "2020-06-25T14:11:49.000+0000",
                                "createdBy": "SYSTEM",
                                "updatedAt": null,
                                "updatedBy": null,
                                "deletedAt": null,
                                "deletedBy": null,
                                "flag": 0
                            }
                        ],
                        "createdAt": "2020-06-25T14:11:49.000+0000",
                        "createdBy": "SYSTEM",
                        "updatedAt": null,
                        "updatedBy": null,
                        "deletedAt": null,
                        "deletedBy": null,
                        "flag": 0
                    }
                ],
                "privileges": [
                    {
                        "id": 1,
                        "privilegeName": "PRIVILEGE_1",
                        "privilegeDesc": "Privilege 1 desc.",
                        "createdAt": "2020-06-25T14:11:49.000+0000",
                        "createdBy": "SYSTEM",
                        "updatedAt": null,
                        "updatedBy": null,
                        "deletedAt": null,
                        "deletedBy": null,
                        "flag": 0
                    }
                ],
                "registeredAt": "2020-06-25T14:11:49.000+0000",
                "registeredBy": "SYSTEM",
                "updatedAt": "2020-07-11T11:41:26.000+0000",
                "updatedBy": null,
                "deletedAt": "2020-07-11T11:41:26.000+0000",
                "deletedBy": null,
                "flag": 0,
                "isAccountNonExpired": true,
                "isAccountNonLocked": true,
                "isCredentialsNonExpired": true,
                "isEnabled": true
            }
        ],
        "pageable": {
            "sort": {
                "sorted": false,
                "unsorted": true,
                "empty": true
            },
            "offset": 0,
            "pageSize": 20,
            "pageNumber": 0,
            "unpaged": false,
            "paged": true
        },
        "last": true,
        "totalElements": 1,
        "totalPages": 1,
        "size": 20,
        "number": 0,
        "sort": {
            "sorted": false,
            "unsorted": true,
            "empty": true
        },
        "numberOfElements": 1,
        "first": true,
        "empty": false
    }

Now, how would i print data something like below:
![image](https://user-images.githubusercontent.com/9690516/87697910-60c64700-c7b0-11ea-8abb-c07fde4f56f6.png)

In the table I will have a few link / button which can open another page or popup to edit/delete/ view specific record. The role and privilege may may contain may not be or may be more than 1 record into an array. Please tell me how can I achieve this functionality with this library or I should go with a regular table.

**Comment by AllenFang** [comment]
@manojsharma20  use [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function). 

[some example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
