### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pawelkalbrun** [react-bootstrap-table/react-bootstrap-table2#143]
The last commit seemed to be back in Aug. Looks like development is not really active. Will you shed some light with regards to roadmap?

**Comment by prajapati-parth** [comment]
@pawelkalbrun Currently all the development work is done in the 'develop' branch and we are working on react-bootstrap-table2 features listed in this(https://github.com/react-bootstrap-table/react-bootstrap-table2/projects/1?) roadmap. 

Thanks.

**Comment by pawelkalbrun** [comment]
ok that great. when are you hoping to have a first drop released?

**Comment by AllenFang** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop . is our dev branch,

I can tell you when I can drop first release, it's hard to said, maybe ned of this year or first month in 2018.  But I need to say, I can't complete all the features on legacy `react-bootstrap-table` when first release. But I'll make those feature works on `react-bootstrap-table2` ASAP.

Thanks.

**Comment by pawelkalbrun** [comment]
ok thanks for clarifying
