### ISSUE TITLE
Unselect / Select Table Checkbox in Code

### ISSUE THREAD

**Issue by CoryCovino** [react-bootstrap-table/react-bootstrap-table2#1438]
Hello.  Is there any way to unselect a checkbox in react-bootstrap-table-next programmatically?  Like in this [link](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)?

I've copied and pasted the code exactly and each time I click the button, nothing happens to the checkbox selections.  I can see the state array changing in logs on each click, but the table row checkbox remains unselected.  

I see that there's a reference to 

<Code>{ sourceCode }</Code> in the table that may or may not make a difference.  

"react-bootstrap-table-next": "^4.0.3",
"react-bootstrap-table2-editor": "^1.4.0",

**Comment by parag-coditation** [comment]
Hi, I'm also going through same issues if possible can you please share what did you tried to solve this issue and what made it work. Help appreciated.
