### ISSUE TITLE
Selection (Self-)Management + Pagination

### ISSUE THREAD

**Issue by kylegoetz** [react-bootstrap-table/react-bootstrap-table2#1453]
Summary:

**I am manage my own selections with `selectRow` but also use pagination. `selectAll` should select just what's in the current page but there is no way to do this as far as I can tell.**

Lengthy explanation:

I have to manage my own selections because other parts of the UI depend on selection state (if some rows are selected, special UI appears to delete/edit/save/etc. the selected data). So I have currently in my `<BootstrapTable>` the following:

```
selectRow={{mode:'checkbox', /* ... */, onSelectAll}}
```

`onSelectAll` is a function that changes my component's state so I can render the other components in my page like "delete all" and such. The logic is easy: state has a list of all `data:Data[]` and `selectedRows:Data[]` and and then `onSelectAll` update `selectedRows` accordingly: `this.setState({selectedRows:[...data.map(getKey)]})`.

The problem is now I need to add pagination. Right now, with pagination, selectAll will select all data, not just the data on the current page! To fix this, I need access to what is the current page, and how many items are displayed per page (or, alternatively, a list of items currently displayed).

There does not appear to be any such callback for when you change page or change rows-per-page. How can I accomplish this?

It looks like pagination will do this automatically, *but only if you aren't self-managing the selections*.

**Comment by kylegoetz** [comment]
I don't see a way to delete this issue. So I'm closing it. The answer is on the `onSelectAll` callback, a second parameter, `rows`, is an array of only the rows displayed on the current page.

**Comment by pyronlaboratory** [comment]
@kylegoetz do you mind sharing a small snippet of your solution?
