### ISSUE TITLE
Remote pagination From REST API using React hooks

### ISSUE THREAD

**Issue by mrArray** [react-bootstrap-table/react-bootstrap-table2#1464]
please i'm looking for a way to add remote pagination using react hook, i already have my data from API  and i can use it with 
react-bootstrap-table2-paginator,
my issue is that if i want to use remote pagination within react hooks with existing Endpoint ,how can i ?

**Comment by mrArray** [comment]
Resolved

**Comment by yumyo** [comment]
It would be useful to know how did you solve this.
