### ISSUE TITLE
Column with hidden prop still visible

### ISSUE THREAD

**Issue by AntoineCAMILLE** [react-bootstrap-table/react-bootstrap-table2#1482]
Hello, i've made a wrapper around your component to add a selector to select which columns are visible and which are not
but i'm facing a problem
i've made 2 components using my wrapper
Both have the same logic but different columns and data 
On one it works the columns are hidden but on the other one it's not working 
I really don't understand why, when i'm checking in the react debugger the column has the hidden property but it's rendered regardless of the value of hidden in the column
When i check with the debugger the value of hidden in the specific column it's at true but still visible

Sorry for my average english level :)

**Comment by ogaston** [comment]
Can you reproduce this behavior in a new project isolated? If so, share with us to see what's happening.
