### ISSUE TITLE
ToolkitProvider search is not working on formatted cells

### ISSUE THREAD

**Issue by iamsajithsasi** [react-bootstrap-table/react-bootstrap-table2#1496]
function docFormatter(cell, row, rowIndex) {
    return (
        <a href={`${row.doc.doclink}`}>
          {row.doc.docname}
        </a>
    );
  }

const columns = [
    { dataField: "sno", text: "S.No" },
    {
      dataField: "doc",
      text: "Document Name",
      formatter: docFormatter,
      filterValue: docFormatter,
    },
  ];

I have a customer formatter and that returns a anchor tag with a text. the search is not working on this. 

I looked document https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-search.html#search-on-formatted-data

..., {
  dataField: 'type',
  text: 'Job Type',
  formatter: (cell, row) => types[cell],
  filterValue: (cell, row) => types[cell] // we will search the value after filterValue called
}

I did'nt understand how to implement this by referencing this. Please help me on this. Thanks

**Comment by iamsajithsasi** [comment]
function docFormatter(cell, row, rowIndex) {
      return (
        <a href={${row.doc.doclink}}>
           {row.doc.docname}
    
        );
      }

    function docFormatterFilter(cell, row) {
      return cell.docname;
    }
    
    const columns = [
      { dataField: "sno", text: "S.No" },
      {
        dataField: "doc",
        text: "Document Name",
        formatter: docFormatter,
        filterValue: (cell, row) => docFormatterFilter(cell, row),
      },
    ];

**Comment by reppard** [comment]
> ```
> function docFormatter(cell, row, rowIndex) {
>   return (
>     <a href={${row.doc.doclink}}>
>        {row.doc.docname}
> 
>     );
>   }
> 
> function docFormatterFilter(cell, row) {
>   return cell.docname;
> }
> 
> const columns = [
>   { dataField: "sno", text: "S.No" },
>   {
>     dataField: "doc",
>     text: "Document Name",
>     formatter: docFormatter,
>     filterValue: (cell, row) => docFormatterFilter(cell, row),
>   },
> ];
> ```

@iamsajithsasi did this actually work for you?  If I return any kind of template for my for my formatter, filterValue doesn't work.  I have something very similar to this and I can't seem to get it to function properly.

**Comment by iamsajithsasi** [comment]
> > ```
> > function docFormatter(cell, row, rowIndex) {
> >   return (
> >     <a href={${row.doc.doclink}}>
> >        {row.doc.docname}
> > 
> >     );
> >   }
> > 
> > function docFormatterFilter(cell, row) {
> >   return cell.docname;
> > }
> > 
> > const columns = [
> >   { dataField: "sno", text: "S.No" },
> >   {
> >     dataField: "doc",
> >     text: "Document Name",
> >     formatter: docFormatter,
> >     filterValue: (cell, row) => docFormatterFilter(cell, row),
> >   },
> > ];
> > ```
> 
> @iamsajithsasi did this actually work for you? If I return any kind of template for my for my formatter, filterValue doesn't work. I have something very similar to this and I can't seem to get it to function properly.

Yup It actually worked for me. the docformatter should show some text/some value,  so that the table could filter it.

**Comment by reppard** [comment]
> Yup It actually worked for me. the docformatter should show some text/some value, so that the table could filter it.

Thanks for the reply @iamsajithsasi.  I have something like the following and a table search just doesn't work.  Am I missing something?
```
function trackingFormatter(cell, row) {
    return (
        <a
            target="_blank" rel="noopener noreferrer"
            href={`https://www.packagetrackr.com/track/${row.tracking}`}>
            {row.tracking}
        </a>
    )
}

function trackingFormatterFilter(cell, row) {
    return row.tracking
}

const columns = [
        {
            dataField: 'tracking',
            text: 'Tracking',
            formatter: trackingFormatter,
            filterValue: (cell, row) => trackingFormatterFilter(cell, row),
            searchable: true,
            ...sharedColumnProps
        }

]
```

**Comment by iamsajithsasi** [comment]
> > Yup It actually worked for me. the docformatter should show some text/some value, so that the table could filter it.
> 
> Thanks for the reply @iamsajithsasi. I have something like the following and a table search just doesn't work. Am I missing something?
> 
> ```
> function trackingFormatter(cell, row) {
>     return (
>         <a
>             target="_blank" rel="noopener noreferrer"
>             href={`https://www.packagetrackr.com/track/${row.tracking}`}>
>             {row.tracking}
>         </a>
>     )
> }
> 
> function trackingFormatterFilter(cell, row) {
>     return row.tracking
> }
> 
> const columns = [
>         {
>             dataField: 'tracking',
>             text: 'Tracking',
>             formatter: trackingFormatter,
>             filterValue: (cell, row) => trackingFormatterFilter(cell, row),
>             searchable: true,
>             ...sharedColumnProps
>         }
> 
> ]
> ```

In the trackingFormatterFilter it should be cell.tracking. You can console log both row and cell and choose your requirement. Console a small table data or might end up in crash of browser. lol..

function trackingFormatterFilter(cell, row) {
    console.log(cell, row)
    return cell.tracking
}
