### ISSUE TITLE
Implement column level filter to hide / show columns based on selection.

### ISSUE THREAD

**Issue by Srikanth4** [react-bootstrap-table/react-bootstrap-table2#151]
This feature is available in multiple grid libraries. Provide filters on Table. One of the filter feature could be column hide / show options. When developer want to hide few columns by default to end user this feature helps.

**Comment by AllenFang** [comment]
HI @Srikanth4 what do you mean for `based on selection` ?

**Comment by Srikanth4** [comment]
@AllenFang So current grid got column level filters. Is there a way I can hide a column from external filters ( table level) and do operations on table like export data / apply filters on displayed columns only ?

**Comment by AllenFang** [comment]
@Srikanth4 "hide column from external filters" just sound like column toggle, we can consider to implement the column toggle.

**Comment by yuri-sakharov** [comment]
Hi, 
I want to do this. Can you please describe more about this feature, what exactly need to do?
Thanks.

**Comment by AllenFang** [comment]
HI @yuri-sakharov `react-bootstrap-table2` just have first drop yesterday, we will consider to implement this featuter, but before that I want to confirm with you guys, what's exactly feature your want? is it really a column toggle feature?!  thanks

**Comment by yuri-sakharov** [comment]
Sorry guys I did'n have time for this implementation.

**Comment by AllenFang** [comment]
@yuri-sakharov never mind :)

**Comment by AllenFang** [comment]
We have new release for fixing this issue: please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/) and upgrade related packages

[this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-column-toggle.html) is docs for column toggle and [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Toggle&selectedStory=Basic%20Column%20Toggle&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is online demo

Please open another issue if you find any bugs, thanks
