### ISSUE TITLE
How to hidden Colum (I need to hidden Id Colum from the view)

### ISSUE THREAD

**Issue by snwijesuriya** [react-bootstrap-table/react-bootstrap-table2#1536]
const columns = [
        {
            dataField: 'id',
            text: 'id'

        },
        {
            dataField: 'name',
            text: 'Product Name'
        },
        {
            dataField: 'price',
            text: 'Product Price'
        },
        {
            dataField: 'Category',
            text: 'Product Category'
        },
    ];

 <BootstrapTable
                        keyField='id'
                        data={list}
                        columns={columns}
                        selectRow={selectRow}

                    />

**Comment by PixelZombie** [comment]
See the Documentation:
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnhidden-bool
```
{
    dataField: 'id',
    text: 'id',
    hidden: true
},

**Comment by snwijesuriya** [comment]
Thank u, Issue resolved
