### ISSUE TITLE
Custom sticky row, unaffected by sort

### ISSUE THREAD

**Issue by HZSamir** [react-bootstrap-table/react-bootstrap-table2#1546]
Hello,
I would like to have a specific row of my data always be at the top of the table, no matter what the table is sorted on.
Something like a sticky header, except this is a sticky row.
I don't think this feature exists and I've been at this for hours but I can't think of a way to implement this cleanly, without having to add a custom sort to all my columns.

Any suggestions would be most helpful.
Thank you.

**Comment by danvc** [comment]
Out of curiosity... did you get this working?

**Comment by HZSamir** [comment]
@danvc I did.
The solution I came up with is appending the specific item to the data array, and pass that data array to the table.
Something like:


```javascript
  const items = React.useMemo(() => {
    if (!data) return [];
    const newId = uuidv4();
    const alwaysOnTop = {
      id: newId,
      utilitySort: "always-on-top", // A utility field that isn't displayed, useful to disallow inline editing on this particular field for example
      name: "Some example",
      createdAt: new Date().toISOString(),
    };
    return [alwaysOnTop].concat(data);
  }, [data]);
```

And then you simply pass data={items} to your table.
I hope it helps.
Also closing this, I completely forgot about this.
