### ISSUE TITLE
Show input/checkbox in Table without clicking to edit

### ISSUE THREAD

**Issue by Exzavierz** [react-bootstrap-table/react-bootstrap-table2#1551]
I want to make my column of checkbox to be shown in table, there is example in the docs/demo but checkboxes are not shown by default, It will be needing to click the column/data to show the checkbox and update the value.

Is there a way to just make the checkboxes to be shown? not the text value but the actual input which is checkbox.

Here is the link of react-bootstrap-table-next demo regarding the editable checkboxes: [Link](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Checkbox%20Editor&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by crimson11** [comment]
Hi Xavier,

I think you should in your case use a combination of **formatter** and **editorRenderer**.
I.e. with column.formatter you control how the checkbox values (true/false) are rendered for values not in edit mode.
With editorRenderer you control the UI item to be used, when you click an element to edit.
So this gives you ALL the flexibility, but you have to write a bit of code.

the formatter could look roughly like this:

```
function boolFormatter(cell, row) {
  return (
    <input type="checkbox" {cell == true ? 'checked' : ''}>
  );
}
```

for the editorRenderer you should check the examples ...

Bye,
Manuel

**Comment by Exzavierz** [comment]
@crimson11 thanks for the help bro! marking this closed :)

**Comment by Gutalala** [comment]
I still don't get this. Combining the editorRenderer and Formatter will force the user to click twice on a checkbox...

**Comment by Gutalala** [comment]
> Hi Xavier,
> 
> I think you should in your case use a combination of **formatter** and **editorRenderer**.
> I.e. with column.formatter you control how the checkbox values (true/false) are rendered for values not in edit mode.
> With editorRenderer you control the UI item to be used, when you click an element to edit.
> So this gives you ALL the flexibility, but you have to write a bit of code.
> 
> the formatter could look roughly like this:
> 
> ```
> function boolFormatter(cell, row) {
>   return (
>     <input type="checkbox" {cell == true ? 'checked' : ''}>
>   );
> }
> ```
> 
> for the editorRenderer you should check the examples ...
> 
> Bye,
> Manuel

I still don't get this. Combining the editorRenderer and Formatter will force the user to click twice on a checkbox...
