### ISSUE TITLE
is it support resize or drag column for change width?

### ISSUE THREAD

**Issue by LoveWaguan** [react-bootstrap-table/react-bootstrap-table2#1561]

**Comment by LoveWaguan** [comment]
i use my way to resolve this problem, using mousedown,mouseup,mousemove functions ,it work very perfect .

**Comment by vladAvanite** [comment]
> i use my way to resolve this problem, using mousedown,mouseup,mousemove functions ,it work very perfect .

hey, can you pls show your code?

**Comment by LoveWaguan** [comment]
yeah,I'm very please share with you; when the table be inited, revoke this function like this,you can adjust code for your  project。
 
/**
 *  resize table columns 
 */
function colResizable(){
  var tTD;
  var tables = $("#list table");
  var table0 = tables[0];
  var table1 = tables[1];
  for (var i =0; i< table0.rows[0].cells.length;i++){
      table0.rows[0].cells[i].onmousedown  = function (){
          tTD = this;
          if(event.offsetX > tTD.offsetWidth - 10){
              tTD.mouseDown = true;
              tTD.oldX = event.x;
              tTD.oldWidth = tTD.offsetWidth;
              tTD.classList.remove('sort-column');
          }
      }
      table0.rows[0].cells[i].onmouseup = function(){
          if(tTD === undefined) tTD = this;
          tTD.mouseDown = false;
          tTD.style.cursor = 'default';
          tTD.classList.add('sort-column');
      }
      table0.rows[0].cells[i].onmousemove = function () {
        if(event.offsetX > this.offsetWidth - 10){
            this.style.cursor = 'col-resize';
        }else{
            this.style.cursor = 'default';
        }
        if(tTD === undefined) tTD = this;
        if(tTD.mouseDown != null &&  tTD.mouseDown === true){
            tTD.style.cursor = 'default';
            if(tTD.oldWidth + (event.x - tTD.oldX) > 0){
                tTD.width = tTD.oldWidth + (event.x - tTD.oldX);
            }
            //tTD.style.width = tTD.width;
            tTD.parentElement.parentElement.previousElementSibling.childNodes[tTD.cellIndex].style.width = tTD.width + 'px';
            tTD.style.cursor = 'col-resize';
            for(var j = 0; j < table1.rows.length; j++){
                table1.rows[j].cells[tTD.cellIndex].parentElement.parentElement.previousElementSibling.childNodes[tTD.cellIndex].style.width = tTD.width + 'px';
            }
            isChangeColWidth = true;
        }
      }
  }
}
