### ISSUE TITLE
Dynamic render json data in react bootstrap table

### ISSUE THREAD

**Issue by Rekha-B** [react-bootstrap-table/react-bootstrap-table2#159]
I am retrieving json response by making API call, I want the json to be rendered in table dynamically with key and values.

When referred few other sites, I came across that we can club all column names into an array and render columns in <TableHeaderColumn> but I am not aware of what  key values are present in my json.

**Comment by AllenFang** [comment]
@Rekha-B it's sorry for lately reply, busy lift :P 

About your question, I think we can't change a truth: we need a key for `react-bootstrap-table`.

I usually suggest use to doing a quick transformation or something then feed the new data into table. Don't think about that you can just put any format data into table, a tiny transformation is necessary and it's not too hard to implement.

Let me know if you still got any questions,  thanks, Please look forward to `react-bootstrap-table2`, we will have first drop in this month.
