### ISSUE TITLE
Searching in object array 

### ISSUE THREAD

**Issue by MudulOzan** [react-bootstrap-table/react-bootstrap-table2#1591]
**Question**
Hi, I have an object array like this
` [{name:"name1, id:0},{name:"name2",id:1}]
`
My data is like
```
[
{Id:0,Title:"test",User:[{name:"name1, id:0},{name:"name2",id:1}], 
Id:1,Title:"test2",User:[]
]
```
And I use a formatter
```
{
    dataField: 'User.name',
    text: 'User', 
    sort: true, 
    formatter: (cell, row) => this.userFormatter(cell, row) 
} 
```
And my formatter
```
userFormatter = (cell, row) => {
    return row["User"] && row.User.map((item, index) => {
        return (
            <div key={index} >
                {item.Name}
            </div>
        );
   )) 
} 
```
When I try to search I am unable to get result depending on this field
I used searchFormatted but it didn't work
I looked at other commits but couldn't find one fitting my issue, how to achieve this? (sorry currently on phone right now and it was bugging my mind, forgive me if I miss wrote something) 

**Screenshots**
N/A

**codesandbox**
N/A

**Comment by jklingen92** [comment]
@MudulOzan 
> My data is like

> 
> [
> {Id:0,Title:"test",User:[{name:"name1, id:0},{name:"name2",id:1}], 
> Id:1,Title:"test2",User:[]
> ]

Your data looks like garbage. You have unclosed curly brace. Either you copied it badly or it shouldn't even run.

As for your formatter, 

> userFormatter = (cell, row) => {
>     return row["User"] && row.User.map((item, index) => {
>         return (
>             <div key={index} >
>                 {item.Name}
>             </div>
>         );
>    )) 
> } 

This line:
```return row["User"] && row.User.map((item, index) => {```
is returning a true or false. The `&&` operator will evaluate true or false. You need to debug your code.

**Comment by MudulOzan** [comment]
sorry, I was on phone back then, never thought I'll get a response, I applied a workaround for that. thanks for your time though
