### ISSUE TITLE
Pagination info translation

### ISSUE THREAD

**Issue by hellogbg** [react-bootstrap-table/react-bootstrap-table2#1621]
Is there a way to translate pagination info at the bottom, i.e:  Showing rows 1 to 10 of 81

**Comment by amoledo** [comment]
Yes, with **paginationTotalRenderer** function.
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationpaginationtotalrenderer-function

**Comment by amoledo** [comment]
Yes, with **paginationTotalRenderer**.
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationpaginationtotalrenderer-function

**Comment by hellogbg** [comment]
Great help. Thank you!!
