### ISSUE TITLE
Jump to Page 1 if not enough data is there after filter remotely

### ISSUE THREAD

**Issue by boilerdev** [react-bootstrap-table/react-bootstrap-table2#1634]
Hi all,
I've implemented a fully remote table using the latest and greatest hooks appoach with pagination and a search/filter box generating the filter requests on all rows. Here comes the issue:
Let's say I've 10 pages and I'm going to page 5, then I search for a term which has exactly one result, I will get an empty table and pagination will show page 1 not selected, it looks like I'm still on page 5. So the question is: How can I jump to page 1 automatically if there are not enough results?
I've tried to update page variable in pagination options on my own but it looks like this is not working.
Are there any other approaches to jump tp page 1?
Thanks and Best 
Mario

**Comment by boilerdev** [comment]
I will close this issue, it is possible by using the page property in pagination options and implementing onPageChange to set the page accordingly. In code the page can be set by using the same property.

**Comment by nguyentanvinh7a** [comment]
Hi, " In code the page can be set by using the same property." - Can you tell me more about this approach?

**Comment by donkeyDau** [comment]
Couldn't get it work. But should be something like:

```javascript
import BootstrapTable from 'react-bootstrap-table-next';
import paginationFactory, {
  PaginationProvider,
} from 'react-bootstrap-table2-paginator';

const paginationOptions = {
  alwaysShowAllBtns: true,
  paginationSize: 4,
  showTotal: true,
};

export default (columns, rows, rowKey) => (
  <PaginationProvider pagination={paginationFactory(paginationOptions)}>
    {({ paginationProps, paginationTableProps }) => (
      <>
        <BootstrapTable
          bootstrap4
          columns={columns}
          keyField={rowKey}
          data={rows}
          striped
          hover
          condensed
          {...paginationTableProps}
        />
        <button
          onClick={() => {
            paginationProps.onPageChange(3);
          }}
        >
          Go to page 3!
        </button>
      </>
    )}
  </PaginationProvider>
);
```
