### ISSUE TITLE
KeyField auto increment

### ISSUE THREAD

**Issue by AdrienDuchemin** [react-bootstrap-table/react-bootstrap-table2#166]
Hi @AllenFang, Thank you first for your work, I am using react-bootstrap-table a lot in my current project and can't wait to upgrade to react-bootstrap-table2!
I was thinking about the possibility to have the KeyField attribute not required. In that case, the key will be auto incremented for each rows (like an index). I say that because there are cases where you don't use the table in a CRUD environment and don't have ids. 
Another scenario (if you still want KeyField required) would be to have the possibility to give KeyField a format like KeyField="column1-column2" so a combination of columns makes the key unique.

**Comment by AllenFang** [comment]
@AdrienDuchemin  it's sorry for lately reply, this issue already discuss before. Actually, I still insist to have the keyField, if your data doesn't contain any id, generate one by simple sequence number then feed into the table.


Regards,
Allen

**Comment by sidhujaspreet** [comment]
@AllenFang Even Thanks for the amazing work you have done.
Coming to issue, I am also in a situation where I just need to show data, not perform CRUD over it. I prefer not to perform extra iteration over data just to add an unique key to it. I deeply feel that keyField should be optional and handled inside react-bootstrap-table2 code by generating key using map > index in ./body.js.

**Comment by turkus** [comment]
@AdrienDuchemin please take a look at https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/688#issuecomment-512295351 maybe would be helpful in this case.
