### ISSUE TITLE
Two carats are appearing for pagination dropdown

### ISSUE THREAD

**Issue by abhishek84** [react-bootstrap-table/react-bootstrap-table2#168]
<img width="833" alt="screen shot 2018-01-16 at 3 00 15 pm" src="https://user-images.githubusercontent.com/6415265/34981537-c46cf00e-facd-11e7-8200-1667921a93ba.png">
<img width="833" alt="screen shot 2018-01-16 at 3 00 15 pm" src="https://user-images.githubusercontent.com/6415265/34981546-cddc8802-facd-11e7-8cc2-ae04bcf02c11.png">

**Comment by AllenFang** [comment]
@abhishek84 this is `react-bootstrap-table2`, but we still not release yet? I think you use `react-bootstrap-table`?
