### ISSUE TITLE
key field in cell should not be cell value

### ISSUE THREAD

**Issue by Sathras** [react-bootstrap-table/react-bootstrap-table2#172]
i am struggling with the autogenerated key field for columns which seams to be a stringified version of the cell value. This causes conflicts when two different columns for an object display the same value (e.g. you wanna display 2 boolean columns).

```
Warning: Encountered two children with the same key, `false`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
I have submitted a pull request for review: #173 

Alternatively, is there a way to manually set the key value for columns?

**Comment by AllenFang** [comment]
wow, you are so fast to use `react-bootstrap-table2` :)

Anyway, react doesn't suggest to use sequence number as `key`, I think we can combine the `content` and `index`?!  You can patch your PR :)



> Alternatively, is there a way to manually set the key value for columns?

i think it's possible, however, what's benefit for you?

**Comment by Sathras** [comment]
your work is pure awesomeness so of course Ill use it.
as far as i can see in your code  the key has no specific purpose on the cell rather than identifying it among its siblings. therefore i do not see any advantage in allowing a custom key to be set if it can be uniquly generated with the information given.

`index-content` sounds fine as long as its not content on its own.

```
key  = {`${index}-${content}`}
```

**Comment by dandonahoe** [comment]
Ahhh, thanks for bringing this up. My console is spewing React errors about this. @AllenFang Any idea when this might be merged? 

Thanks for the project BTW!

**Comment by AllenFang** [comment]
@dandonahoe next patch will fix it

**Comment by AllenFang** [comment]
Fixed on `react-bootstrap-table-next@0.1.2`, check release note: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/02/02/version-bump.html

**Comment by hungdev** [comment]
i don't understand why I still get the same error with "react-bootstrap-table-next": "^1.2.0"
@AllenFang

**Comment by stolenfather** [comment]
I am also getting these errors :grimacing:

**Comment by Bopzor** [comment]
Same using `"react-bootstrap-table-next": "^3.1.7"`but only if the column if the one used for `keyField`. So it's seems logic.
But how can I manage a unique `keyField` if I don't have any unique column ?
Thanks :)

**Comment by Pierre-Gilles** [comment]
There is still a problem with the current approach, as a cell key is = `${content}-${index}` :

**When using :** 

- a formatter function
- a column selector

if two cells in the same row have the same values but are formatted differently (in my case, a count = 0 + a progress bar at 0%), when enabling a new column with the column selector (switching hidden = true to hidden = false), then the first column is not re-rendered because its cells key didn't change, but the content should change because the formatting of the cell is different !  

Maybe the cell key should be `${dataField}-${content}-${index}`  ?
