### ISSUE TITLE
using react-bootstrap-table2 with react-beautiful-dnd

### ISSUE THREAD

**Issue by vaibhav135** [react-bootstrap-table/react-bootstrap-table2#1727]
**Question**

Hi,
I am new to react-bootstrap-table2 and want to use [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) with react-bootstrap-table2. I would like to know:
-  If it is even possible?
-  If it is, can you give me some sense of direction as to how I can do it?

**Things I am not sure about**
I am not sure how I can wrap the row-list with Droppable and Draggable as done [here](https://codesandbox.io/s/zqwz5n5p9x?file=/src/index.js:113-190).
Thank you

**Comment by duartefpereira** [comment]
Hi, @vaibhav135 are there new updates on this?
