### ISSUE TITLE
Custom the Sort Caret

### ISSUE THREAD

**Issue by iamandrewluca** [react-bootstrap-table/react-bootstrap-table2#177]
Any updates on this?
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-sort.html#custom-the-sort-caret
I may give a try to implement this in next weekend maybe.

**Comment by AllenFang** [comment]
@iamandrewluca in the next few sprint, I will focus on filter implementation, any PR is welcome, but please open PR to `develop` branch, remember to write the test code 👍

**Comment by iamandrewluca** [comment]
> I may give a try to implement this in next weekend maybe. ( on Jan 23 ) 🙃

After some investigation and code browsing  

https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/8d62261983968529583cc6102c7bfcf26ff685a2/packages/react-bootstrap-table2/src/header-cell.js#L103  

I found that I can custom the sort caret using `headerFormatter` on column

```js
const columns = [{
  dataField: 'id',
  text: 'Product ID',
  sort: true,
  headerFormatter: (column, index, { sortElement, filterElement }) => {
    const { order = 'x' } = sortElement.props;
    return (
      <div>
        {column.text} {order}
      </div>
    );
  }
}
```

![image](https://user-images.githubusercontent.com/1881266/44814731-4a2b9c80-abe6-11e8-92f4-5555043b7858.png) ![image](https://user-images.githubusercontent.com/1881266/44814750-531c6e00-abe6-11e8-9745-f8b34334e787.png) ![image](https://user-images.githubusercontent.com/1881266/44814768-59124f00-abe6-11e8-81f8-6f5d6d333a93.png)


I will close this issue for now.
Thanks!

**Comment by sinisbad123** [comment]
@iamandrewluca when you pass 'x' as the `order` props of the `sortElement`, you are actually modifying the class associated to the caret and not the character itself.

See below

![screen shot 2018-10-05 at 10 40 22 am](https://user-images.githubusercontent.com/1787177/46513455-20236500-c88b-11e8-865e-d5ade1bc3558.png)

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/07/version-bump.html)

Please upgrade to `react-bootstrap-table-next@1.2.1`

[ONLINE DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Sort%20Table&selectedStory=Custom%20Sort%20Caret&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

[DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnsortcaret-function)
