### ISSUE TITLE
Double check select row event

### ISSUE THREAD

**Issue by matteoventuri7** [react-bootstrap-table/react-bootstrap-table2#180]
Hi.
selectRow={{
          mode: 'checkbox',
          clickToSelect: true,
          classes: 'selection-table-row',
          onSelect: (rowKey, checked, rowIndex) => {
            debugger;
          },
          onSelectAll: (option) => {
            debugger;
          }
        }}
If i single check checkbox row then onSelect event start twice.

**Comment by AllenFang** [comment]
@matteoventuri7 sure, it seems like a bug, I'll fix it soon, thank you

**Comment by AllenFang** [comment]
Fixed on `react-bootstrap-table-next@0.1.2`
