### ISSUE TITLE
Select row checkbox error

### ISSUE THREAD

**Issue by matteoventuri7** [react-bootstrap-table/react-bootstrap-table2#181]
This is my configuration:
selectRow={{
          mode: 'checkbox',
          clickToSelect: true,
          classes: 'selection-table-row',
          onSelect: (rowKey, checked, rowIndex) => {
            debugger;
          },
          onSelectAll: (option) => {
            debugger;
          }
        }}

Error is:
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by CheckBox)
    in CheckBox (created by SelectionHeaderCell)
    in th (created by SelectionHeaderCell)
    in SelectionHeaderCell (created by Header)
    in tr (created by Header)
    in thead (created by Header)
    in Header (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by PaginationWrapper)
    in PaginationWrapper (created by SortWrapper)
    in SortWrapper (created by CellEditWrapper)
    in CellEditWrapper (created by RowSelectionWrapper)
    in RowSelectionWrapper (created by BootstrapTableContainer)
    in BootstrapTableContainer (created by Users)
    in div (created by Users)
    in Users (created by Route)
    in Route (created by Full)
    in Switch (created by Full)
    in div (created by Container)
    in Container (created by Full)
    in main (created by Full)
    in div (created by Full)
    in div (created by Full)
    in Full (created by Route)
    in Route (created by IsLoggedInSwitch)
    in Switch (created by IsLoggedInSwitch)
    in IsLoggedInSwitch
    in Switch
    in Router (created by HashRouter)
    in HashRouter
    in div

**Comment by AllenFang** [comment]
@matteoventuri7 ok, I'll check this later, thank you

**Comment by AllenFang** [comment]
@matteoventuri7 I cant reproduce this issue, did I miss something?

**Comment by matteoventuri7** [comment]
Now i don't use checkbox and receive this warning:
Warning: TextFilter contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components

**Comment by matteoventuri7** [comment]
This my versions:
"react": "16.2.0",
    "react-bootstrap-table-next": "^0.1.2",
    "react-bootstrap-table2-editor": "^0.1.1",
    "react-bootstrap-table2-filter": "^0.1.2",
    "react-bootstrap-table2-paginator": "^0.1.1",

**Comment by AllenFang** [comment]
@matteoventuri7 update to `react-bootstrap-table2-filter@0.1.3`

**Comment by EnriqueAbricot** [comment]
Hi, i using react-bootstrap-table2-filter@0.1.3 and still get the warning for uncontrolled component... only when set mode to checkbox, if change to radio the warning gone away...

**Comment by Northshoot** [comment]
had the same issue until I added

` selected: false,`

in the

```
  const selectRowLinks = {
    mode: 'checkbox',
    clickToSelect: true,
    clickToEdit: true,
    selected: false,
.....
  };
```

**Comment by CDimonaco** [comment]
Having the same issue, when the table is paginated, if you select rows with checkboxes, between pages, at page change you will get this error.

I think the problem is in the implementation of checked state in rows.

**Comment by cbfrank** [comment]
I get the same error: 
Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`

The warning shows:
in input (created by CheckBox)
    in CheckBox (created by SelectionHeaderCell)
    in th (created by SelectionHeaderCell)
    in SelectionHeaderCell (created by Header)
    in tr (created by Header)
    in thead (created by Header)
    in Header (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by CellEditWrapper)
    in CellEditWrapper (created by RowSelectionWrapper)
    in RowSelectionWrapper (created by Table)
    in Table (created by Table)
    in Table (created by AppDefaultTable)
    in div (created by AppDefaultTable)
    in AppDefaultTable (created by Table)
    in Table (created by Page)
    in div (created by Row)
    in div (created by Row)
    in div (created by Row)
    in article (created by Row)
    in div (created by Row)
    in Row (created by Page)
    in section (created by PageLayout)
    in PageLayout (created by Page)
    in Page (created by Connect(Page))
    in Connect(Page) (created by Route)
    in Route (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in Provider (created by App)
    in App

**Comment by sisodiakaran** [comment]
Exactly same warning:
```
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by CheckBox)
    in CheckBox (created by SelectionHeaderCell)
    in th (created by SelectionHeaderCell)
    in SelectionHeaderCell (created by Header)
    in tr (created by Header)
    in thead (created by Header)
    in Header (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by PaginationWrapper)
    in PaginationWrapper (created by SortWrapper)
    in SortWrapper (created by CellEditWrapper)
    in CellEditWrapper (created by RowSelectionWrapper)
    in RowSelectionWrapper (created by BootstrapTableContainer)
    in BootstrapTableContainer (created by GraphView)
    in div (created by GraphView)
    in GraphView (created by ProjectDetail)
    in div (created by Col)
    in Col (created by ProjectDetail)
    in div (created by Row)
    in Row (created by ProjectDetail)
    in div (created by TabPane)
    in TabPane (created by ProjectDetail)
    in div (created by TabContent)
    in TabContent (created by ProjectDetail)
    in div (created by CardBody)
    in CardBody (created by ProjectDetail)
    in div (created by Card)
    in Card (created by ProjectDetail)
    in div (created by ProjectDetail)
    in ProjectDetail (created by Route)
    in Route (created by Projects)
    in Switch (created by Projects)
    in div (created by Container)
    in Container (created by Projects)
    in main (created by Projects)
    in div (created by Projects)
    in div (created by Projects)
    in Projects (created by Route)
    in Route
    in Switch
    in Router (created by BrowserRouter)
    in BrowserRouter
```

My app is having following versions:
```
node@v6.10.2

"react": "16.2.0",
"react-bootstrap-table-next": "^0.1.14",
"react-bootstrap-table2-editor": "^0.2.1",
"react-bootstrap-table2-filter": "^0.3.0",
"react-bootstrap-table2-paginator": "^0.1.5",
```
