### ISSUE TITLE
Dropdown perpage size unselectable

### ISSUE THREAD

**Issue by matteoventuri7** [react-bootstrap-table/react-bootstrap-table2#182]
I can not open perpage size dropdown menu. My config is:
pagination={ paginationFactory({
.......
sizePerPageList: [15,25,50,100],
.....
}
)}

**Comment by Chun-MingChen** [comment]
Hi @matteoventuri7 

According to [README#pagination](https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/docs/README.md#pagination---object),  `numeric array` is acceptable and it also works fine for me. Could you offer more information or check syntax and lint again please. Thanks.

**Comment by AllenFang** [comment]
I will open up until we got the response or someone can prove this is a bug.  thanks

**Comment by zsh1313** [comment]
I got same issue with using bootstrap 4

**Comment by AllenFang** [comment]
@zsh1313  please read [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html), we will support bootstrap 4 in near future, thanks
