### ISSUE TITLE
Why the move away from TableHeaderColumn 

### ISSUE THREAD

**Issue by waynebrantley** [react-bootstrap-table/react-bootstrap-table2#184]
Kind of liked the ``TableHeaderColumn ``, just curious why the move to an array instead of react child components?

**Comment by AllenFang** [comment]
@waynebrantley it's much easy to control the react element internally. Not too much benefit but just easy to implement.   Any concern here?

**Comment by waynebrantley** [comment]
@AllenFang 
No real concern, just had hopes of making different kinds of 'column' components that did things automatically.  Really cannot do that easily with the array, etc.

just wondered why the design change
