### ISSUE TITLE
noDataIndication: doesn't account for hidden columns

### ISSUE THREAD

**Issue by Sathras** [react-bootstrap-table/react-bootstrap-table2#185]
A small visual inconsistency I found:

when a table is empty the default row with class 'react-bs-table-no-data' has a colspan for the total number of columns. 
it should actually be the total number of columns _minus hidden fields_. 

this solves some visual inconsistencies with column headers displaying incorrectly. 
hope I don't get annoying :)

**Comment by AllenFang** [comment]
@Sathras oh not annoying :)

so in this case you mention, you will see the wrong colspan size on table, right?

**Comment by AllenFang** [comment]
I see, that's a bug lol

**Comment by AllenFang** [comment]
@Sathras  fixed on `react-bootstrap-table-next@0.1.2`, check release note: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/02/02/version-bump.html
