### ISSUE TITLE
Empty <Caption /> element

### ISSUE THREAD

**Issue by prajapati-parth** [react-bootstrap-table/react-bootstrap-table2#186]
For tables not using captions, i guess and empty `<Caption></Caption>` should not be rendered. 
Currently empty Caption element is available in all the examples of storybook.

Reference: https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/09fadeb02b5aed6c95467ffef34b68cb5d927685/packages/react-bootstrap-table2/src/bootstrap-table.js#L76

Congratulations @AllenFang for react-bootstrap-table2! 🌟

**Comment by AllenFang** [comment]
Thank you, I'll check this out 👍

**Comment by AllenFang** [comment]
Fixed on `react-bootstrap-table-next@0.1.4`, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/03/06/version-bump.html), thank!
