### ISSUE TITLE
Add case insensitive matching to text filter

### ISSUE THREAD

**Issue by makenova** [react-bootstrap-table/react-bootstrap-table2#189]
As a user, I would like text filter to work in a case insensitive manner.
e.g. `item` match `Feature Items`

**Comment by AllenFang** [comment]
New Release: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/02/14/version-bump.html

For this issue, check this > https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2-example/examples/column-filter/text-filter-caseSensitive.js

Let me know if the problem still remain, thanks
