### ISSUE TITLE
Server-Side Data Filtering

### ISSUE THREAD

**Issue by anikakalbrun** [react-bootstrap-table/react-bootstrap-table2#191]
Is there any way to get Server-Side Data Filtering working?
I tried to pass a callback to onFilter but this does not work.
```
this.columns = [
            {
                text: 'Name',
                dataField: 'name',
                filter: textFilter({
                    delay: 1000,
                    onFilter: myCallback
                })
            }
]
```

**Comment by AllenFang** [comment]
HI @anikakalbrun the remote filter is totally different from `react-bootstrap-table`, you can check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-remote.html) firstly, and check [this](https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2-example/examples/remote/remote-filter.js) to see a remote filter example.

Let me know if you still get any questions, thank you

**Comment by anikakalbrun** [comment]
I don't know how I could miss the remote filter example...

Thanks a lot Allen.
