### ISSUE TITLE
there is not enough subscription for the sort click event

### ISSUE THREAD

**Issue by massmediagroup-28** [react-bootstrap-table/react-bootstrap-table2#196]
I need to subscribe on sort click event in header column when you click it for table sort. After reading docs i found that hook headerEvents: onClick triggered on such header columns where - sort: false.

**Comment by AllenFang** [comment]
@massmediagroup-28 sorry for lately reply, we must implement this feature in Q1. Right now, I can promise when I can finish it, maybe this ned of month or beginning of next month, I'll mention herea again when we finish it, thanks

**Comment by AllenFang** [comment]
New Release: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/02/14/version-bump.html

For this issue, check this > https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2-example/examples/sort/sort-events.js#L18

Let me know if theres any problem, thanks
