### ISSUE TITLE
There is no way to customize the header tr class

### ISSUE THREAD

**Issue by danielzk** [react-bootstrap-table/react-bootstrap-table2#197]
There is no way to customize the header `<tr>` class?

**Comment by AllenFang** [comment]
Hey, please check this: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-row.html

**Comment by danielzk** [comment]
That's just for the header cell (<th>).

**Comment by danielzk** [comment]
As I can see in the source code the `<tr>` is not customizable. It would be a good feature to add. I think it would also be a good feature to be able to pass custom props to the components.

**Comment by AllenFang** [comment]
@danielzk yes, there're some people ask this feature, I'll handle it ASAP, https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/212
