### ISSUE TITLE
Uncaught Error: PaginationWrapper.render()

### ISSUE THREAD

**Issue by aminrasouli** [react-bootstrap-table/react-bootstrap-table2#198]
i got an error when i was add pagination:
`Uncaught Error: PaginationWrapper.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

`import BootstrapTable from 'react-bootstrap-table-next';
import paginationFactory from 'react-bootstrap-table2-paginator';`

`<BootstrapTable keyField="id"
                                                data={[...this.state.orders]}
                                                columns={this.columns()}
                                                pagination={ paginationFactory() }
    />`

when i remove pagination everything is ok

**Comment by AllenFang** [comment]
@aminrasouli what's the version of your react js?

**Comment by aminrasouli** [comment]
"react": "^15.6.1",
"react-dom": "^15.6.1",

**Comment by AllenFang** [comment]
@aminrasouli `react-bootstrap-table2` need the react 16, it's already add as peerdenpendency, so you should see some warning when you were install. Please upgrade your react, thanks
