### ISSUE TITLE
Summary row or custom footer

### ISSUE THREAD

**Issue by epsyan** [react-bootstrap-table/react-bootstrap-table2#2]
Hi! Cool, that you decide to make a 2nd version of this table component!

Not sure if it implemented in the last version of react-bootstrap-table, but it would be cool to have a summary row as the last row of the table. And(or) a custom footer component for a table. 

Thanks!

**Comment by AllenFang** [comment]
> Not sure if it implemented in the last version of react-bootstrap-table, but it would be cool to have a summary row as the last row of the table. And(or) a custom footer component for a table.

yes~ those feature must be implemented in `react-bootstrap-table2` 👍

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/20/version-bump.html

release on `react-bootstrap-table-next@2.1.0`
check [these](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Footer&selectedStory=Simple%20Footer&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) examples

**Comment by DrogoNevets** [comment]
When you dynamically add a row to the table data, the footer function doesnt recalculate
