### ISSUE TITLE
How do you access multiple values in single cell?

### ISSUE THREAD

**Issue by seanpaulkelley** [react-bootstrap-table/react-bootstrap-table2#203]
I am using formatter to create a button in a cell which uses the collection's id and payor_id attributes.  How do I get the payor_id attribute into the formatter?

```
  renderButtons(cell, row) {
    return (
      <span>
        <Link
          to={{
            pathname: `/user/${cell}/record/new`,
            state: { payor_id: payor_id }
          }}
          className="btn btn btn-primary btn-sm"
          type="button"
          data-toggle="tooltip"
          title="Add Person Record"
          recordable_id={cell}
        >
          <i className="fa fa-plus" aria-hidden="true" /> Record
        </Link>
      </span>
    );
  }

  renderUsersTable(users) {
    const columns = [
      {
        dataField: 'id',
        formatter: this.renderButtons,
        text: '',
        headerTitle: false
      }
    ];
    
    return (
      <BootstrapTable
        keyField="id"
        data={users}
        columns={columns}
        striped
        hover
      />
    );
  }
```

**Comment by AllenFang** [comment]
@seanpaulkelley https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatextradata-any . 

[example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter%20with%20Custom%20Data&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Let me know if you still have any other questions, thank you!!

**Comment by seanpaulkelley** [comment]
I thought formatExtraData might be useful but it appears from the example like you are formatting based on the dataField value 'rank'.  It looks like up and down are possible values of rank.  I am trying to use a different collection attribute.  The following example does not appear to pass anything along to formatter

```
renderButtons(cell, row, rowIndex, formatExtraData) {
    return (
      <span>
        payor_id= {formatExtraData[cell]}
        <Link
          to={{
            pathname: `/user/${cell}/record/new`,
            state: { payor_id: `${formatExtraData[cell]}` }
          }}
          className="btn btn btn-primary btn-sm"
          type="button"
        >
         Record
        </Link>
      </span>
    );
  }

  renderUsersTable(users) {
    const columns = [
      {
        dataField: 'id',
        formatter: this.renderButtons,
        formatExtraData: {
          payor_id: 'payor_id'
        },
        text: '',
        headerTitle: false
      }
    ];
```

**Comment by sidthekidder** [comment]
Hi, this doesn't seem to work now? I am trying to access data from 2 different columns in a single column, like seanpaulkelley was, but formatExtraData doesn't seem to pick up the dataField from other columns. It just passed the string directly. The 1st arg doesn't contain the other variables of the row, the 2nd arg is an index, the 3rd arg is an object with sortElement and filterElement keys(I am wrapping the table in ToolkitProvider for searching) and the 4th arg is undefined

My formatter code is this - 
```
let columns = [{
      dataField: 'Product.official_id',
      text: 'Name',
      headerFormatter: productFormatter,
      formatExtraData: {
        name: 'Product.name',
        name: 'Product.image_url',
      }
    }, {
      dataField: 'Product.price',
      text: 'Price',
      sort: true
    }]

function productFormatter(cell, row, rowIndex, formatExtraData) {
    console.log("In productformatter")
    console.log(cell)
    console.log(row)
    console.log(rowIndex)
    console.log(formatExtraData)

    return (
      <h5><strong>{ cell.text }</strong></h5>
    )
  }
```

And I get this in the console - 
<img width="711" alt="scc" src="https://user-images.githubusercontent.com/3611800/80320321-5d3ba900-87db-11ea-825f-9bc785387106.png">

**Comment by hunterxxx** [comment]
@sidthekidder use formatter

```
const columns = [
        {
            dataField: 'Product.name',
            formatter: (value, row) => {
                return value + " " + Product.image_url
            },
            text: 'Price',
        }
```

**Comment by bhavanasachi** [comment]
Hi, I want to merge values of two columns in to one.
Eg: {
         'firstName': 'name',
         'lastName': 'lastname'
    }

I want name = firstName + lastName
columns = [{
    dataField: 'firstName + lastName',
    text: "name",
    sort: true,
}];
