### ISSUE TITLE
TextFilter contains an input of type text with both value and defaultValue prop

### ISSUE THREAD

**Issue by Ar2r** [react-bootstrap-table/react-bootstrap-table2#205]
When i add 'textFilter()' in columns array i got warning in console:
`proxyConsole.js:56 Warning: TextFilter contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components`

Code:
```
    const columns = [
      {
        dataField: 'phone',
        text: localize.phoneNumber,
        filter: textFilter()
      },
    ];

    return (
      <BootstrapTable
        keyField="registrationFilterId"
        data={list}
        columns={columns}
        filter={filterFactory()}
        hover
        striped
      />
    );
```

```
Versions:
    "react": "^16.1.1",
    "react-bootstrap-table-next": "^0.1.2",
    "react-bootstrap-table2-filter": "^0.1.2",
```

**Comment by AllenFang** [comment]
@Ar2r this issue fixed on `react-bootstrap-table2-filter@0.1.3`  https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/195
