### ISSUE TITLE
Client-side/UMD version

### ISSUE THREAD

**Issue by KamyarP** [react-bootstrap-table/react-bootstrap-table2#208]
Hi,
I'm working on a project in .NET Core and wouldn't want to add node.js layer to it for now.
Could you please let me know if there is a client-side ready version like the previous version of this module which can be used just by referencing the .js file in html (without requiring node.js)?

Thank you

**Comment by AllenFang** [comment]
@KamyarP  sure, we already build the UMD version and include it in `dist` folder in the node modules. we didn't provide a public place to download those umd version but I think there's workaround for you is you can try to `npm install react-bootstrap-table-next` in somewhere

then go to `node_modules/react-bootstrap-table-next/dist`, you can find following files
`react-bootstrap-table2.css`
`react-bootstrap-table2.js`
`react-bootstrap-table2.js.map`
`react-bootstrap-table2.min.css`
`react-bootstrap-table2.min.js`

Above *.js files is all UMD version, so right now, you can copy the UMD files to your application.

I'll find some place to puts those UMD files, thanks!!

L4t me know if you got any questions, thanks

**Comment by prajapati-parth** [comment]
We can try using cdnjs(https://cdnjs.com) to host these files. I'm not sure
about how to get those hosted, but it's worth giving a try. I'll try to dig
in more and share my findings soon.

**Comment by prajapati-parth** [comment]
So to add these files to cdnjs we'll just need to create a PR containing directories with name as library version like this example https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/aframe. The PR has to follow this contributing guidelines https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-pull-request.

**Comment by KamyarP** [comment]
@AllenFang Thanks for guidance. However, I'm still having problems and get the following error:
`React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

I tried to initialize the table with minimum complexity:

    const columns = [{ dataField: 'id', text: 'id' }, { dataField: 'name', text: 'name' }];
    var data = [{id: 1,name: "kamyar"},{id: 2,name: "john"}];
    return (<ReactBootstrapTable keyField='id' data={data} columns={columns}/>);

I'm using react 16.2.0

**Comment by AllenFang** [comment]
@prajapati-parth thanks your sharing, I will have a look on it :)

> Also, would you please let me know if I have to include Bootstrap Table (https://github.com/wenzhixin/bootstrap-table) js/css files separately or are they embedded in your code?

Definitly no

**Comment by AllenFang** [comment]
> React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

it's wired..  could you please open an issue, and let's focus on it if the problem is still remain, thanks

**Comment by KamyarP** [comment]
@AllenFang I have created a new issue at [https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/220](url)
Thanks.

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html#umd
