### ISSUE TITLE
onHover event

### ISSUE THREAD

**Issue by abonec** [react-bootstrap-table/react-bootstrap-table2#213]
I need to get id of row in on hover, right now I can achieve it using:
```
    const rowEvents = {
      onMouseEnter: (e) => this.onSelect(+e.target.parentNode.firstChild.textContent),
      onMouseLeave: (e) => this.onSelect(+e.target.parentNode.firstChild.textContent),
    };
```
Because of this event handler got only `event` argument I can get row id only in this curly way. Obviosly it will be more handy if this callbacks would receive row argument as `onClick`.

**Comment by AllenFang** [comment]
@abonec sorry for lately fixing, this requirement is fixed on `react-bootstrap-table-next@0.1.4`, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/03/06/version-bump.html)
