### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by siamak** [react-bootstrap-table/react-bootstrap-table2#214]
When I send `data` as props I have error for iterator `key`.
![image](https://user-images.githubusercontent.com/3109082/36355128-c84a9286-14f3-11e8-9f62-1b38a67731a5.png)

Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `Body`. See https://fb.me/react-warning-keys for more information.
    in Row (created by Body)
    in Body (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by PaginationWrapper)
    in PaginationWrapper (created by SortWrapper)
    in SortWrapper (created by BootstrapTableContainer)
    in BootstrapTableContainer (at RemotePagination.js:66)
    in RemotePagination (created by Connect(RemotePagination))
    in Connect(RemotePagination) (at Merchants.js:178)
    in div (at Merchants.js:166)
    in section (created by styled.section)
    in styled.section (at Merchants.js:165)
    in div (at Merchants.js:164)
    in div (at Merchants.js:163)
    in Merchants (created by Connect(Merchants))
    in Connect(Merchants) (created by Route)
    in Route (at DashboardLayout.js:39)
    in Switch (at DashboardLayout.js:37)
    in main (at DashboardLayout.js:35)
    in div (at DashboardLayout.js:33)
    in div (at DashboardLayout.js:32)
    in section (created by styled.section)
    in styled.section (at DashboardLayout.js:30)
    in AuthorizedLayout (at requireAuth.js:27)
    in Authenticate (created by Connect(Authenticate))
    in Connect(Authenticate) (created by Route)
    in Route (at routes.js:34)
    in Switch (at routes.js:20)
    in div (at routes.js:17)
    in Router (created by BrowserRouter)
    in BrowserRouter (at routes.js:16)
    in Routes (created by Connect(Routes))
    in Connect(Routes) (at index.js:42)
    in Provider (at index.js:41)

**Comment by prajapati-parth** [comment]
@siamak Please post the code that you've tried. Thanks.

**Comment by AllenFang** [comment]
also post your data @siamak

**Comment by siamak** [comment]
It's a bug in my code. Thanks.

**Comment by wallena3** [comment]
same problem...here is data&code, confusing...

![image](https://user-images.githubusercontent.com/11361768/41756990-e462d56c-7611-11e8-99e1-bc76f3dd3dd6.png)
![image](https://user-images.githubusercontent.com/11361768/41756998-ee906108-7611-11e8-8932-f7811182f864.png)
![image](https://user-images.githubusercontent.com/11361768/41757005-f69918ea-7611-11e8-9790-37f684b17b53.png)

**Comment by wallena3** [comment]
@AllenFang could you have a look at this? Many thanks

**Comment by hellriser4** [comment]
The row object in the version 2 of bootstrapTable does not affect a key property in its rendering. This is why this error happens. There is probably a .map in the body rendering and it is missing it.

**Comment by rmartin58** [comment]
Is there a fix for this? Though not fatal, the warning is annoying.

**Comment by hellriser4** [comment]
I don't know!

**Comment by hellriser4** [comment]
It seems the warning is gone, anybody still with it? I guess it got fixed... react-bootstrap-table-next 1.2.0

**Comment by do-diegoortiz** [comment]
> It seems the warning is gone, anybody still with it?

I have version 1.3.1 and it's still happening to me, but only when my BootstrapTable is inside a ToolkitProvider :sweat:

**Comment by JediYozh** [comment]
I have the same problem...

**Comment by anuragb26** [comment]
I am facing same issues in 1.4.2
`export const INSTANCE_DATASET_COLUMNS = [
  {
    dataField: 'id',
    text: 'required',
    hidden: true
  },
  {
    dataField: 'instance_id',
    text: 'Instance ID',
    headerClasses: 'instance-dataset-table__header-cell',
    classes: 'data-cell--first instance-dataset-table__data-cell'
  },
  {
    dataField: 'dataset',
    text: 'Dataset Name',
    headerClasses: 'instance-dataset-table__header-cell',
    classes: 'instance-dataset-table__data-cell'
  },
  {
    dataField: 'last_modified',
    text: 'Last modified date',
    headerClasses: 'instance-dataset-table__header-cell',
    classes: 'instance-dataset-table__data-cell'
  }
]`

**Comment by nononocat** [comment]
I have the same issues in 2.0.0....

**Comment by nononocat** [comment]
it seems like <BootstrapTable /> use keyField as the unique key prop. if the value of the "keyFiled" is not unique in your code, you will see that error message.....

**Comment by dotpegaso** [comment]
> it seems like use keyField as the unique key prop. if the value of the "keyFiled" is not unique in your code, you will see that error message.....

My `keyField` value is unique and I'm facing the same error... using version `3.3.3`, there's no solution for that yet?

**Comment by khanh-nguyen** [comment]
Make sure **keyField** is one of your columns' dataField and it is unique. Otherwise, you get the warning message.

Would be nice to have unique ids generated if `keyField` is not provided in case the table has no unique data, @AllenFang ?

**Comment by jerryjayce** [comment]
Also make sure that the function is not anonymous, that is do not save the function to a variable. Put the function outside your render method. then hook it to the formatter using "this.yourFunctionName".

**Comment by vitvitskyi** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#keyfield-required-string
