### ISSUE TITLE
TextFilter

### ISSUE THREAD

**Issue by micaelsampaio** [react-bootstrap-table/react-bootstrap-table2#217]
Hello, when i put textFilter in my columns, it apears this Warning, even in example story book has the same Warning.

```
import filterFactory, {textFilter} from 'react-bootstrap-table2-filter';
...
filter: textFilter()
```

`Warning: TextFilter contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info:`

**Comment by AllenFang** [comment]
@micaelsampaio update `react-bootstrap-table2-filter` and `react-bootstrap-table-next` to newest should solve this issue  https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/02/14/version-bump.html
