### ISSUE TITLE
UMD version error: React.createElement: type is invalid 

### ISSUE THREAD

**Issue by KamyarP** [react-bootstrap-table/react-bootstrap-table2#220]
I'm trying to use the client-ready version of the component. However I'm facing the following error:
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`
I have attached a bare-bones version of what I'm trying to achieve. 
[sample.zip](https://github.com/react-bootstrap-table/react-bootstrap-table2/files/1743134/sample.zip)

**Comment by prajapati-parth** [comment]
@KamyarP This is not an issue related to react-bootstrap-table2, you'll need babel and other packages to make your index.html file render React components. Thanks.

**Comment by KamyarP** [comment]
The React script references are umd version so there's no need for a Babel compiler. 
Also, I have compiled my `SampleApp.jsx` with Babel 6.7.7 and included the compiled version `SampleApp.js` in my `index.html` So my component has already been compiled.
I have used `React.createElement` to render my component in `index.html` so it also does not need any compilation: `ReactDOM.render(React.createElement(SampleApp, null, null), document.getElementById("reactContainer"));`
I have already successfully rendered other components using this approach.

**Comment by prajapati-parth** [comment]
@KamyarP Okay. I see I missed that. I'll check it out.

**Comment by AllenFang** [comment]
I'll also check this if you got time. I think maybe we need support the UMD version should solve this issue probably.

**Comment by AllenFang** [comment]
@KamyarP try https://unpkg.com/react-bootstrap-table-next@0.1.3/lib/index.js instead of the bundled file from `dist`

**Comment by AllenFang** [comment]
Maybe I do something wrong for the those UMD bundled in `dist`, I'll also double check

**Comment by AllenFang** [comment]
@KamyarP try:


```js
const BootstrapTable = ReactBootstrapTable.default;
render() {
   return<BootstrapTable  .../>; 
}
```

and let me know if the problem is still remain and open this issue again, thanks

I will improve the UMD system in future

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html#umd
