### ISSUE TITLE
Failed prop type: The prop `defaultValue` is marked as required in `TextEditor`, but its value is `null`.

### ISSUE THREAD

**Issue by srikar237** [react-bootstrap-table/react-bootstrap-table2#221]
HI Team,

I came across with this library recently and it's very easy to integrate. Thanks.

Can you please help me with below issues/requirements, thanks.

1.  When i try to edit a row on an empty cell it gives below Warning.  Can you please let me know how/where to pass defaultValue prop..?
       Failed prop type: The prop `defaultValue` is marked as required in `TextEditor`, but its value is `null`.

2.  I would like to have the width of the column based on the length of the data in the cell. tried to width in the column prop like below but its not taking it.
            { dataField: 'affiliateUrl', text: "affiliateUrl", style: {width: '100px'  }, sort: true, 
                 filter: textFilter(), },

![image](https://user-images.githubusercontent.com/18105996/36503532-670026ce-171b-11e8-8b78-002b300657d1.png)

3.   i would like to have the grid within given width, right now my code is like below. but its not working with this code.
            <div style={{width:'600px', height: '600px'}}>
                <BootstrapTable 
                    keyField='id' 
                    data={ rows } 
                    columns={ columns } 
                    noDataIndication="Table is Empty" 
                    cellEdit={ cellEditFactory({
                        mode: 'dbclick',
                        blurToSave: true
                    }) }
                    filter={ filterFactory() }
                    pagination={ paginationFactory() }
                    // pagination={ paginationFactory(options) }
                    hover
                />
            </div>

**Comment by AllenFang** [comment]
HI @srikar237 sorry for lately reply,

> When i try to edit a row on an empty cell it gives below Warning. Can you please let me know how/where to pass defaultValue prop..?
Failed prop type: The prop defaultValue is marked as required in TextEditor, but its value is null.

I'll fixed it soon

> I would like to have the width of the column based on the length of the data in the cell. tried to width in the column prop like below but its not taking it.

Good point, for the width on bootstrap table, it's a challange actually, in the legacy `react-bootstrap-table` we paid a lots of efforts on it, for now, I didn't integrate column width, but you an tried to set the height on [`column.headerStyle`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnheaderstyle-object-function) instead of `column.style`, I guess it should be work

> i would like to have the grid within given width, right now my code is like below. but its not working with this code.

For the bootstrap style, I will suggest you to define a panel/block to contain your table which have your expected width/height.


Please let me know your any feedback, thanks :)

**Comment by srikar237** [comment]
Thanks for your reply Allen,

tried below with column.headerStyle   but couldn't get it working... 

headerStyle: () => { width: '100px'  },  
headerStyle: {width: '100px'}

and i have one more observation,  Whenever i try to pass columns dynamically ( get column data from an asynchronous call) , i get "Uncaught Error: No any visible columns detect".  is there any work around for that..?

**Comment by AllenFang** [comment]
@srikar237 for the dynamic columns, is there any chance that table receive empty `columns` array ?!

**Comment by AllenFang** [comment]
Fixed on `react-bootstrap-table-next@0.1.4`

**Comment by AllenFang** [comment]
Release note: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/03/06/version-bump.html

**Comment by srikar237** [comment]
Thanks for the quick fix Allen...
