### ISSUE TITLE
Default row selection not working

### ISSUE THREAD

**Issue by aaj5956** [react-bootstrap-table/react-bootstrap-table2#224]
Hey, I am trying to specify the default selected row but it does not work for me:

```
let selectRow = {
            mode: 'checkbox',
            clickToSelect: true,
            selected: [1],
            onSelect: this.onExistingContactRowSelect
        }
```

Even though I have an entry in my table with the row key = 1, the entry is not selected by default on initial render.

**Comment by AllenFang** [comment]
@aaj5956 your row key is `1` or `"1"` ?!  I think it's not a bug in `react-bootstrap-table2`. could you please share your raw data and minimal code? thanks

**Comment by aaj5956** [comment]
I may be doing some things incorrectly but I don't understand what the issue is. The key is definitely `1` and not `"1"`. Here is the code:
```
let selectRow = {
    mode: 'checkbox',
    clickToSelect: true,
    selected: [1],
    onSelect: this.onExistingContactRowSelect
}

let columns = [{
    dataField: 'id',
    text: 'ID',
    sort: true,
    hidden: true
}, {
    dataField: 'name',
    text: 'Name',
    sort: true
}, {
    dataField: 'title',
    text: 'Title',
    sort: true
}, {
    dataField: 'type',
    text: 'Type',
    sort: true
}, {
    dataField: 'email',
    text: 'Email',
    sort: true
}, {
    dataField: 'deskphone',
    text: 'Desk Phone',
    sort: true
}, {
    dataField: 'cell',
    text: 'Cell',
    sort: true
}]

let products = [{
    id: 1,
    name: 'Brian Cranston',
    title: 'lord of medicines',
    type: 'internal',
    email: 'iamtheonewhoknocks@brbd.com',
    deskphone: 12341234,
    cell: 2342134
}, {
    id: 2,
    name: 'James Smith',
    title: 'random guy',
    type: 'external',
    email: 'james@smith.com',
    deskphone: 122352344,
    cell: 2323454
}, {
    id: 3,
    name: 'Jane Doe',
    title: 'random lady',
    type: 'internal',
    email: 'jane@doe.com',
    deskphone: 1234234,
    cell: 234263454
}]
```

and then finally
```
<BootstrapTable keyField='id' data={ products } columns={ columns } striped hover selectRow={ selectRow } noDataIndication={'No products'} />

```

**Comment by AllenFang** [comment]
@aaj5956 it's sorry that we don't support the default select currently, we will implement this feature ASAP.

**Comment by aaj5956** [comment]
No problem. @AllenFang Thanks.

**Comment by AllenFang** [comment]
@aaj5956 we support default selection, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/03/06/version-bump.html)

check [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Default%20Select&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Let me know if you have any questions, thanks
