### ISSUE TITLE
Sort order lost on state change

### ISSUE THREAD

**Issue by thimo1** [react-bootstrap-table/react-bootstrap-table2#225]
If you perform a client sort, sorting works fine. If state is refreshed sort order gets lost. Caret stays at state, sort order not.

Is that an known issue?

**Comment by AllenFang** [comment]
@thimo1 yes, we still lack on sorting management, duplicated with #210

**Comment by AllenFang** [comment]
Fixed on `react-bootstrap-table-next@0.1.4`, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/03/06/version-bump.html), thank!
