### ISSUE TITLE
When I change the data prop, the table is not being re-rendered

### ISSUE THREAD

**Issue by RajeevSiewnath** [react-bootstrap-table/react-bootstrap-table2#227]
My table uses an array of objects for the data parameter. When that data gets updated I have to manually sort the table to see the newly entered data.

**Comment by AllenFang** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/210

**Comment by AllenFang** [comment]
Fixed on `react-bootstrap-table-next@0.1.4`, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/03/06/version-bump.html), thank!
