### ISSUE TITLE
Table disregards sort column after re-rendering

### ISSUE THREAD

**Issue by KamyarP** [react-bootstrap-table/react-bootstrap-table2#229]
I have been able to use UMD version thanks to @AllenFang 's guide at #220 
However, upon updating table data, the sort column is disregarded.
I have attached a sample that updates the state every 1 second. If I click on a column for sorting, it is only valid before my component's `render` method is called again. 
Should I render the table in another way to make sort column regarded after updating table's data?

[sample.zip](https://github.com/react-bootstrap-table/react-bootstrap-table2/files/1757793/sample.zip)

**Comment by KamyarP** [comment]
Just saw you have already discussed this at #210

**Comment by AllenFang** [comment]
Fixed on `react-bootstrap-table-next@0.1.4`, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/03/06/version-bump.html), thank!
