### ISSUE TITLE
Support className on BootstrapTable

### ISSUE THREAD

**Issue by waynebrantley** [react-bootstrap-table/react-bootstrap-table2#235]
The styling on this version is much better than the first one is much better!

However, I have to wrap every ``BootstrapTable`` in a <div/> so I can target your classes. (using code based classes, not stylesheet ones).

It would be nice if you let me pass className into ``BootstrapTable`` and you add whatever is passed in to the outer div.  This would let me get rid of this extra div.

**Comment by jtheberge** [comment]
This would be great in addition to adding support for id's as well.

**Comment by AllenFang** [comment]
@waynebrantley sure, added it in next sprint.

**Comment by AllenFang** [comment]
hey all, we fixed on `react-bootstrap-table-next@0.1.5`, please let me know if this issue still remain, thank.  check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Basic%20Table&selectedStory=Customized%20id%20and%20class%20table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example and let me know if this patch is not match your requirement , thanks!
