### ISSUE TITLE
Hidden columns still render

### ISSUE THREAD

**Issue by waynebrantley** [react-bootstrap-table/react-bootstrap-table2#237]
In the previous version of your component, if I did not want to render a column, I would simply do 
```
{this.state.someCondition && <TableHeaderColumn dataField="someField">Some Caption</TableHeaderColumn>}
```
I thought I would just use the new ``hidden`` property in the columns array to accomplish this same thing:
```
...
{ dataField: "someField", text: "Some Caption", hidden:!this.state.someCondition }
...
```
This 'works', but the column is still rendered to the browser - is just wrapped with ``display:none``.  Can you just not render hidden columns at all??

Without the above, I could accomplish with "if statements" around ``push``, etc.

**Comment by waynebrantley** [comment]
Additionally, hidden columns crash when used with a pager.
``Uncaught TypeError: Cannot assign to read only property 'display' of object '#<Object>'``
header-cell.js:83
```
  if (hidden) {
    cellStyle.display = 'none';
  }

```

The above error occurred in the <HeaderCell> component:
    in HeaderCell (created by Header)
    in tr (created by Header)
    in thead (created by Header)
    in Header (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)

**Comment by AllenFang** [comment]
@waynebrantley thanks this feedback, I'll fix it ASAP
