### ISSUE TITLE
Pagination is missing 'total' feature

### ISSUE THREAD

**Issue by waynebrantley** [react-bootstrap-table/react-bootstrap-table2#238]
In the prior version, the pagination component would show something like:
```
1 - 12 of 616 items
```

And that could be customized with a ``paginationShowsTotal`` rendering function.
I know this new version is a work in progress and not all features are ported yet - wondering if this was just missed or if it is coming.  Currently no work around to get this done that I can see.

Thoughts?

**Comment by waynebrantley** [comment]
@AllenFang Is this in the next release - or would you accept a pull request?

**Comment by AllenFang** [comment]
@waynebrantley sorry lately reply, crazy busy lol
it's welcome to accept PR, but if you want to open a PR, please let me know to avoid other contributors is also working on it

Thanks :)

**Comment by AllenFang** [comment]
@waynebrantley this was fixed on `react-bootstrap-table-paginator@0.1.2`, check https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html#paginationshowtotal-bool
