### ISSUE TITLE
Are we gonna have 'search' feature soon?

### ISSUE THREAD

**Issue by zhm12359** [react-bootstrap-table/react-bootstrap-table2#239]

**Comment by Chun-MingChen** [comment]
Hi @zhm12359 

It's the [roadmap](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/01/24/release-plan.html#032) for the upcoming features but it was a little delayed. We will implement the **search** ASAP. Thanks.

**Comment by AllenFang** [comment]
Implement on `react-bootstrap-table-next@1.0.0` and `react-bootstrap-table2-toolkit@1.0.0`

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-search.html
