### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by pr4deep94** [react-bootstrap-table/react-bootstrap-table2#241]
PaginationWrapper.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

**Comment by damonmiller** [comment]
I am seeing the same error when attempting to use pagination.

**Comment by victor95pc** [comment]
same, PaginationWrapper is returning an Array

**Comment by AllenFang** [comment]
hey all, what react version you use? `react-bootstrap-table-next` need `react@16.0.0`, please confirm the your react version, thanks

Please let me know if this issue still remain?

**Comment by victor95pc** [comment]
my react version is 16.2.0

**Comment by AllenFang** [comment]
HI @victor95pc  could you post your code and show us how to reproduce it, thanks

**Comment by AllenFang** [comment]
@victor95pc hello the issue still there?

thanks

**Comment by EugeneTsarenko** [comment]
I have the same issue, I use gatsby standart layout

**Comment by AllenFang** [comment]
@EugeneTsarenko could you please give a repo or something? before that, please make sure u use `react@16`. thanks

**Comment by vinhlevinhle** [comment]
I am still having exact error. 
@AllenFang , I did make sure I have latest react 16+ version 

I am desperate please help.

I am using VS2017 and typescript.
It worked fine when I did not include the Pagnination prop for the table.

**Comment by luqiwang** [comment]
Same error, my react version is 15. Is there any approach to solve this problem without upgrading react to 16? Thanks a lot!

**Comment by vinhlevinhle** [comment]
No it still happened even with later react 16+ version in VS2017 typescript.
Other components like Bootstrap table next (table ver2) worked perfectly though.
As soon as pagination feature added you just get the error.

Note however, if you use the same thing but compile using purely node Js for example in Fiddler, there is no error with pagination component.

I now have lost 5+ days fighting this.
Given up to use react-table npm now.

G luck,
Vinh
