### ISSUE TITLE
Export To CSV functionality missing.

### ISSUE THREAD

**Issue by andela-mekwenugo** [react-bootstrap-table/react-bootstrap-table2#244]
Just like in the "react-bootstrap-table" where you can add this exportCSV={ true } to the BootstrapTable Component and get the export to csv functionality, it would be great to have that here as well.

**Comment by AllenFang** [comment]
@andela-mekwenugo very sorry for lately reply, busy on my crazy job....

I think `react-bootstrap-table2` already delay a lots, I will focus on recover all the feature in legacy `react-bootstrap-table` on the beginning of April

**Comment by AllenFang** [comment]
Support on `react-bootstrap-table-n3xt@1.0.0` and `react-bootstrap-table2-toolkit@1.0.01

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-export-csv.html
