### ISSUE TITLE
"search" functionality

### ISSUE THREAD

**Issue by andela-mekwenugo** [react-bootstrap-table/react-bootstrap-table2#245]
Being able to search keywords on the table. Just like the other react-bootstrap-table where you only need to add "search" in the BootstrapTable component.

**Comment by Chun-MingChen** [comment]
Hi @andela-mekwenugo:

This is the [roadmap](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/01/24/release-plan.html#032) for the upcoming feature but it was a little delayed. We will implement the **search** ASAP. Thanks.

**Comment by AllenFang** [comment]
duplicated with #239

**Comment by AllenFang** [comment]
Implement on `react-bootstrap-table-next@1.0.0` and `react-bootstrap-table2-toolkit@1.0.0`

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-search.html
