### ISSUE TITLE
this.store is not defined on the RowSelectionWrapper

### ISSUE THREAD

**Issue by grogi** [react-bootstrap-table/react-bootstrap-table2#248]
The `this.store` is not defined. It seems the `store` is part of the properties of the RowSelectionWrapper, not the object itself.

https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/4011cae18e8e8bf632671647ad950e8b3209e2c1/packages/react-bootstrap-table2/src/row-selection/wrapper.js#L31-L38

**Comment by Chun-MingChen** [comment]
Hi @grogi 
Exactly. It's the root cause of #246. Thanks for your information and we will fix it ASAP.

**Comment by AllenFang** [comment]
Duplicated with #246

**Comment by AllenFang** [comment]
@grogi  It's very sorry that we don't fix this critical issue in time, right now we fixed on `react-bootstrap-table-next@0.1.5`, please let me know if this issue still remain, thank
