### ISSUE TITLE
dataField does not support dot notation

### ISSUE THREAD

**Issue by anikakalbrun** [react-bootstrap-table/react-bootstrap-table2#250]
```
const columns = [
    {
        text: 'Claimed By',
        dataField: 'claimBy.name',
        filter
    }
]
```
The BootstrapTable does not show records in the Claimed By column when the dataFields value is a string with dot notation. This does not allow me to build a proper url and use the onTableChange method to make an HTTP request to get filtered table data from the server.

When I change the data passed to the table and the columns value to:
```
const columns = [
    {
        text: 'Claimed By',
        dataField: 'claimBy',
        filter
    }
]
```
then the BootstrapTable shows proper records in the Claimed By column.

I am using:
"react-bootstrap-table-next": "^0.1.4",
"react-bootstrap-table2-filter": "^0.1.3",
"react-bootstrap-table2-paginator": "^0.1.1",

**Comment by AllenFang** [comment]
@anikakalbrun sorry for lately reply, can I check your raw data? I think nested field is support from the starting of `react-bootstrap-table2`, thanks

**Comment by anikakalbrun** [comment]
Hi Allen,

Thanks a lot for getting back to me.

This code is not working for me:

`
const columns = [
    {
        text: 'Claimed By',
        dataField: 'claimBy.name'
    },
    {
        text: 'Expenses',
        dataField: 'totalExpenses',
        formatter: amountFormatter
    },
    {
        text: 'Millage',
        dataField: 'totalMillage',
        formatter: amountFormatter
    },
    {
        text: 'Subsistence',
        dataField: 'totalSubsistence',
        formatter: amountFormatter
    },
    {
        text: 'Total',
        dataField: 'total',
        formatter: amountFormatter
    },
    {
        text: 'Period',
        dataField: 'timesheetPeriodStart',
        formatter: TablePeriodFormatter
    },
];

class ExpensesTable extends Component {

    render() {
        const {data} = this.props;
        return (
            <BootstrapTable keyField='id'
                            data={data}
                            columns={columns}
                            hover
            />
        )
    }
}

function mapStateToProps() {
    return {
        data: [
            {
                "id": "4ca067bd-39f5-4fee-b23e-eaea2f5e033e",
                "claimBy.name": "Diane Diaz",
                "totalExpenses": 1124.39,
                "totalMillage": 230.98,
                "totalSubsistence": 1344.4,
                "total": 2699.77,
                "timesheetPeriodStart": {
                    "start": "2017-07-01",
                    "end": "2017-07-31"
                }
            }
        ]
    };
}

export default connect(mapStateToProps)(ExpensesTable);
`
The first column stays empty.

**Comment by AllenFang** [comment]
@anikakalbrun sorry, your data should be following:

```js
{
  id: "4ca067bd-39f5-4fee-b23e-eaea2f5e033e",
  claimBy: { .name: 'Diane Diaz' },
  totalExpenses: 1124.39
}
```

[docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columndatafield-required-string)

**Comment by Vasanth-Indix** [comment]
Hey @AllenFang, Is there a way to disable to disable the processing of dot notation as a nested object?  I would like to retain the column as 
> "claimBy.name": "Diane Diaz"
