### ISSUE TITLE
pagination dropdown is not closing after selecting an Option.

### ISSUE THREAD

**Issue by telltokichu** [react-bootstrap-table/react-bootstrap-table2#251]
clicking on the sizeperpage pagination dropdown is working but after selecting no of records to be shown in a page for example 5,10,25. the Dropdown is not closing.

**Comment by Chun-MingChen** [comment]
Hi @telltokichu:

I didn't get your point. Could you describe in more detail or share the source code please. Thanks :)

**Comment by telltokichu** [comment]
Hi @Chun-MingChen 
I have zipped a video, please check out.
Thanks in advance.

[rbtp2_issue.zip](https://github.com/react-bootstrap-table/react-bootstrap-table2/files/1823760/rbtp2_issue.zip)

**Comment by AllenFang** [comment]
@telltokichu I think there's a little different in your video? can I confirm following items?

1. What bootstrap version you use
2. Do you really use `react-bootstrap-table-next` or legacy `react-bootstrap-table`?

The different I saw is the page option is an anchor(link) instead of a normal selection option, you can check [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example, you will understand what I means

**Comment by telltokichu** [comment]
@AllenFang  
I am using Bootstrap version 4.0.0 and react-bootstrap-table-next.

**Comment by AllenFang** [comment]
@telltokichu understand, please check https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html#add-css

Wee are not support bootstrap@4, it's sorry about that but we are already working on it, I will mention here when we finish it, thanks!

**Comment by telltokichu** [comment]
@AllenFang 
Here mentioned like Compatible for Bootstrap 3 and 4 that's why I used but no issues I got the answer.
Thanks.
<img width="1280" alt="screen shot 2018-03-20 at 10 04 27 pm" src="https://user-images.githubusercontent.com/25656723/37668547-cbe9f072-2c8a-11e8-8280-13298f41b110.png">

**Comment by AllenFang** [comment]
@telltokichu understand, sorry for this kind of wrong information, we will implement it ASAP, thanks

**Comment by LuisUrrutia** [comment]
@AllenFang I had a similar issue with BS4 and I used this package 'cause the website says that is BS4 compatible, but isn't.
However, how can I contribute to BS4 implementation?

**Comment by Thebarda** [comment]
It's maybe too late but you can use this code to manually close that dropdown menu ;) :
```javascript
onSizePerPageChange: () => { 
  document.getElementsByClassName('dropdown-menu show')[0].classList.remove('show')
},
```

**Comment by jrotoni** [comment]
@Thebarda where to add that lines of code? Thank you!

**Comment by Thebarda** [comment]
@jrotoni Here is the doc ;)
[https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html)

**Comment by jrotoni** [comment]
@Thebarda I'm still encountering error such as "Cannot read property 'classList' of undefined". Thank you anyway :)

**Comment by Thebarda** [comment]
@jrotoni I guess there is no 'dropdown-menu show' class attribute inside your DOM. Please, could verify that by navigating inside your HTML page :)

**Comment by AllenFang** [comment]
Support from `react-bootstrap-table-next@1.0.0`: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/bootstrap4.html
