### ISSUE TITLE
Storybook example Column Event Header Column

### ISSUE THREAD

**Issue by saracarlile** [react-bootstrap-table/react-bootstrap-table2#253]
In the Storybook online demo, the code in the Work on Header Columns > Column Event appears to be wrong.  
It says events: {onClick()...  
when it looks like this should say *headerEvents*: {  onClick()....

**Comment by Chun-MingChen** [comment]
Hi @saracarlile 

Thanks for your information. That's a typo and we'll correct this in the next release :)

**Comment by Chun-MingChen** [comment]
Fix in [#3ed4d87b29049a2437e8f5a745d53202d2e37a28](https://github.com/react-bootstrap-table/react-bootstrap-table2/commit/3ed4d87b29049a2437e8f5a745d53202d2e37a28).

**Comment by AllenFang** [comment]
thanks @Chun-MingChen
