### ISSUE TITLE
table handling remote cellEdits and pagination not working when handling table changes

### ISSUE THREAD

**Issue by aaveen** [react-bootstrap-table/react-bootstrap-table2#256]
Hi I am having problem when using pagination to go to next page, error below 
MyContainer.js:116 Uncaught TypeError: Cannot read property 'rowId' of undefined

and here is the definition for my  table change handler
handleTableChange = (type, { page, sizePerPage, filters, cellEdit: {rowId, dataField, newValue }  }) => {
at MyContainer._this.handleTableChange (MyContainer.js:116)

if am only using the pagination on the table, it seems the handleTableChange to expect passing values for cellEdit { .. } 
am not sure if there is way around it, your example of remote-all, includes filtering and pagination but not cellEdit , so am not sure what am trying to do is possible or not!
thanks
Aveen

**Comment by aaveen** [comment]
please ignore , i solved it, just read on paginationsProps docs that we can't do remote when pagination is enabled, so I had to explicitly set it as 
   remote={{pagination: true, cellEdit: false, filter: false}}

**Comment by AllenFang** [comment]
hi @aaveen sorry for lately reply, it might be not a bug but I need to clearify this issue firstly, 

Could you please explain the reproduce steps and I saw your error message is from your code instead of `react-bootstrap-table2`. so it will be good to show me your code but please keep it simple and minimal

Regards
Thanks

**Comment by aaveen** [comment]
Hi Allen 
Thanks for getting back to me, 
here is the code I managed to combine from the examples in the repo the remoteAll and just the setup for cellEdit, it uses same productGenerator you have in repo.
and I just hooked that into my create-react-app , and after I edit a cell then i try to change the page to page 2 for example , i get this error 

Thanks for helping
Aveen

error: 
Container.js:71 Uncaught TypeError: Cannot read property 'rowId' of undefined
    at Container._this2.handleTableChange (Container.js:71)
    at PaginationWrapper.handleRemotePageChange (remote-resolver.js:79)
    at PaginationWrapper.handleChangePage (wrapper.js:142)
    at Pagination.handleChangePage (pagination.js:138)
    at PageButton.handleClick (page-button.js:47)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at Object.invokeGuardedCallback (react-dom.development.js:438)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:452)
    at executeDispatch (react-dom.development.js:836)
    at executeDispatchesInOrder (react-dom.development.js:858)
    at executeDispatchesAndRelease (react-dom.development.js:956)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:967)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (react-dom.development.js:935)
    at processEventQueue (react-dom.development.js:1112)
    at runEventQueueInBatch (react-dom.development.js:3607)
    at handleTopLevel (react-dom.development.js:3616)
    at handleTopLevelImpl (react-dom.development.js:3347)
    at batchedUpdates (react-dom.development.js:11082)
    at batchedUpdates (react-dom.development.js:2330)
    at dispatchEvent (react-dom.development.js:3421)


code for Container.js
/* eslint guard-for-in: 0 */
/* eslint no-restricted-syntax: 0 */
import React from 'react';
import PropTypes from 'prop-types';
import BootstrapTable from 'react-bootstrap-table-next';
import paginationFactory from 'react-bootstrap-table2-paginator';
import filterFactory, { textFilter, Comparator } from 'react-bootstrap-table2-filter';
import cellEditFactory from 'react-bootstrap-table2-editor';
import { productsGenerator } from './common.js';

const products = productsGenerator(87);

const columns = [{
  dataField: 'id',
  text: 'Product ID'
}, {
  dataField: 'name',
  text: 'Product Name',
  filter: textFilter()
}, {
  dataField: 'price',
  text: 'Product Price',
  filter: textFilter()
}];

const cellEdit = {
  mode: 'click'
};

const RemoteAll = ({ data, page, sizePerPage, onTableChange , totalSize }) => (

  <div>
    <h3>When <code>remote.pagination</code> is enabled, the filtering,
      sorting and searching will also change to remote mode automatically</h3>
    <BootstrapTable  
      remote={ { pagination: true, cellEdit: true} }
      keyField="id"
      data={ data }
      columns={ columns }
      filter={ filterFactory() }
      cellEdit={ cellEditFactory(cellEdit) }
      pagination={ paginationFactory({ page, sizePerPage, totalSize }) }
      onTableChange={ onTableChange }
    />

  </div>
);

RemoteAll.propTypes = {
  data: PropTypes.array.isRequired,
  page: PropTypes.number.isRequired,
  totalSize: PropTypes.number.isRequired,
  sizePerPage: PropTypes.number.isRequired,
  onTableChange: PropTypes.func.isRequired
};

class Container extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      page: 1,
      data: products.slice(0, 10),
      totalSize: products.length,
      sizePerPage: 10
    };
    this.handleTableChange = this.handleTableChange.bind(this);
  }



  handleTableChange  = (type, { page, sizePerPage, filters, cellEdit: { rowId, dataField, newValue }}) => {
    console.log('rowID ', rowId);
    const currentIndex = (page - 1) * sizePerPage;
    setTimeout(() => {
      const result = products.filter((row) => {
        let valid = true;
        for (const dataField in filters) {
          const { filterVal, filterType, comparator } = filters[dataField];

          if (filterType === 'TEXT') {
            if (comparator === Comparator.LIKE) {
              valid = row[dataField].toString().indexOf(filterVal) > -1;
            } else {
              valid = row[dataField] === filterVal;
            }
          }
          if (!valid) break;
        }
        return valid;
      });
      this.setState(() => ({
        page,
        data: result.slice(currentIndex, currentIndex + sizePerPage),
        totalSize: result.length,
        sizePerPage
      }));
    }, 2000);
  }

  render() {
    const { data, sizePerPage, page } = this.state;
    return (
      <RemoteAll
        data={ data }
        page={ page }
        sizePerPage={ sizePerPage }
        totalSize={ this.state.totalSize }
        onTableChange={ this.handleTableChange }
      />
    );
  }
}

export default Container;

**Comment by aaveen** [comment]
Hi I know you guys are really busy, however am really stuck and not sure what I done wrong, am new to frontend development so an example of remoteAll with cellEditing added could help me, or check if this is the correct way of passing the cellEdit param in my handler **handleTableChange = (type, { page, sizePerPage, filters, cellEdit: { rowId, dataField, newValue }}) => {** 
Again this works for cellEditing but pagination breaks as i mentioned in my first post!! 

Thanks
Aveen

**Comment by aaveen** [comment]
i fixed it , changed  param to  handleTableChange  = (type, { page, sizePerPage, filters, cellEdit})
