### ISSUE TITLE
Custom styling of edited cells

### ISSUE THREAD

**Issue by philohelp** [react-bootstrap-table/react-bootstrap-table2#258]
Hello all,
Thanks for the wonderful job, I love the new API.  I was wondering how I could customize the style of the inside of an edited cell - for example the font-size, which appears to be very small with too much padding. I cant even find the correct className here...
Thank you for your answers !

**Comment by AllenFang** [comment]
@philohelp you mean the customization for the `input` element or the outer `td` element

**Comment by philohelp** [comment]
It's for the inner input element.

**Comment by AllenFang** [comment]
@philohelp understand, I will handle it soon 👍

**Comment by AllenFang** [comment]
HI @philohelp 

@mrqcmc Fixed on `react-bootstrap-table-next@0.1.6` and `react-bootstrap-table-editor@0.1.4`, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/04/01/version-bump.html), and check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-celledit.html#editor) for custom editor style/class.

let me know if you still have any issues, thanks

**Comment by AllenFang** [comment]
@philohelp 

sorry, I made some mistake, please upgrade again:

react-bootstrap-table2-editor@0.1.5
react-bootstrap-table2-filter@0.1.5
react-bootstrap-table-next@0.1.7

and let me know if the issue still remain, thanks

**Comment by philohelp** [comment]
I will give a look, so many thanks !!!
