### ISSUE TITLE
Exporting data to files

### ISSUE THREAD

**Issue by Northshoot** [react-bootstrap-table/react-bootstrap-table2#259]
Hi, thank you and great job!

I wonder if it on the roadmap to add export functionality to various formats such as pdf, cvs, excel? Similarly, to what datatables provide.

**Comment by Chun-MingChen** [comment]
Hi @Northshoot:

Yes, we do. We've planned the feature of [export csv] in (https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/01/24/release-plan.html#031) but it was a little delayed. For other formats, we will discuss further and thanks for your advice :)

**Comment by AllenFang** [comment]
Duplicated with #244 so that close it

**Comment by Northshoot** [comment]
Any progress on this feature?

**Comment by GauravAjmera25** [comment]
@Chun-MingChen @AllenFang Any progress on this feature?

**Comment by AllenFang** [comment]
Support on `react-bootstrap-table-n3xt@1.0.0` and `react-bootstrap-table2-toolkit@1.0.01

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-export-csv.html
