### ISSUE TITLE
empty table is missing the last cell

### ISSUE THREAD

**Issue by patrickomeara** [react-bootstrap-table/react-bootstrap-table2#264]
most likely not including the select cell in the count

<img width="881" alt="image" src="https://user-images.githubusercontent.com/571773/37574018-cdec663a-2b71-11e8-8a20-e50f85bfa3a3.png">

**Comment by AllenFang** [comment]
@patrickomeara btw, what version you used it now?

**Comment by patrickomeara** [comment]
@AllenFang I pulled the latest and branched off master

**Comment by AllenFang** [comment]
@patrickomeara understand, thank!!

**Comment by AllenFang** [comment]
@patrickomeara  Fixed on `react-bootstrap-table-next@0.1.6`, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/04/01/version-bump.html).

let me know if you still have any issues, thanks
