### ISSUE TITLE
Use react-moment to change dates displayed in rows

### ISSUE THREAD

**Issue by a2441918** [react-bootstrap-table/react-bootstrap-table2#271]
Trying to use react-moment to render dates in a different manner.

I want  to convert 14-Mar-2018 08:23:17 to 03/14/2018 08:23:17
{
    dataField: 'date',
    text: 'Date',
    formatter: dateFormatter,
  }

const dateFormatter = (cell, row) => (
  <Moment parse="dd-MMM-YYYY HH:mm:ss" format="MM/DD/YYYY HH:mm:ss">
    {cell}
  </Moment>
);

When I use cell or row, it returns invalid date. Should I  use formatExtraData parameter?

**Comment by Chun-MingChen** [comment]
Hi @a2441918:

If you wanna customize your cell format, you could take refer to [LiveDemo#ColumnFormatter](http://localhost:6006/?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and the [document](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function). `JSX` is acceptable for the return value of callback of `formatter`. You could convert whatever you want or wrapped with `react-moment` directly.

**Comment by a2441918** [comment]
That worked man. Thanks.

**Comment by AllenFang** [comment]
@Chun-MingChen thanks!
