### ISSUE TITLE
Get data_field of column header clicked

### ISSUE THREAD

**Issue by a2441918** [react-bootstrap-table/react-bootstrap-table2#272]
Hi, how do I get the value of data_field of the column header being clicked?

This is my column.

    {
        dataField: 'data_id',
        text: 'Data ID',
        headerEvents: {
        onClick: () => columnClick(),
        },
     }

    const columnClick = (cell, row, rowIndex) => {
          console.log('cell', cell);
          console.log('row', row);
          console.log('rowIndex', rowIndex);
    };

Everything returns undefined. How do I get the value being clicked?

**Comment by Chun-MingChen** [comment]
Hi @a2441918 

So far we have no plan to support the access for column attributes when clicking the `headerCell`. However, if it's bothering, you could access the `dataField ` by some trick like `HOF`.

```js
const columns = {
    dataField: 'data_id',
    text: 'Data ID',
    headerEvents: {
      onClick: columnClick('data_id')
    },
 }

const columnClick = dataField => (event) => {
  // you could access dataField once you clicked the header
}
```
