### ISSUE TITLE
Column Text Extends Past Width

### ISSUE THREAD

**Issue by marc-dworkin** [react-bootstrap-table/react-bootstrap-table2#277]
Hi,

Is there a way to auto-truncate the value in a column to fit to column width.  With maybe a tooltip to see full value?

Thanks!

**Comment by AllenFang** [comment]
@marc-dworkin we dont have this feature, but you can very easy to custom

check https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnstyle-object-function
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnclasses-string-function

you can check [this](https://www.w3schools.com/cssref/css3_pr_text-overflow.asp) to learn how to truncate the text

for the tooltips, you can define title attribute via [title](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columntitle-bool-function)

**Comment by tfcb93** [comment]
For header column tooltips just use [headerTitle](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnheadertitle-bool-function) and create a function returning a string, like this:
```JS
{
//omit...
headerTitle: () => "my tooltip text"
}
```
After that, the column element on the table will have a tooltip if you hover over it.
![image](https://user-images.githubusercontent.com/6901304/59762789-65978f00-926e-11e9-9cbd-4f5aa8d75ec4.png)

I guess it's the same thing for the title property.
