### ISSUE TITLE
Get selected rows?

### ISSUE THREAD

**Issue by nskiro** [react-bootstrap-table/react-bootstrap-table2#279]
Hi @AllenFang 
How can I get selected rows?

**Comment by AllenFang** [comment]
In the `react-bootstrap-table2` we still not support a exposed API to client to get the selection data. we will support this feature ASAP.

Currently, you can use [`selectRow.onSelect`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowonselect-function) to listen any rows is select or deselect and manage the selection rows in you code

**Comment by a2441918** [comment]
U can use a callback function on onSelect and pass in that values. I use a redux action to achieve that.

**Comment by FishyStacy** [comment]
Do you have a timeline for implementing this feature?
Thank you!

**Comment by AllenFang** [comment]
try this: react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html#get-current-selected-rows

**Comment by AdamRogersDev** [comment]
@AllenFang Where would be the best place to call this.node.selectionContext.selected to allow passing up the prop with the most up to date selection. I've tried in selectRow, rowEvents but they all return with the array before updating with the latest selection.

Are there any actions that run after the selection has took place?
