### ISSUE TITLE
How to change default sorting direction for all columns?

### ISSUE THREAD

**Issue by mrqcmc** [react-bootstrap-table/react-bootstrap-table2#281]
Descending is the default sort direction for all columns when a user first clicks on a header.  How can that be changed to ascending?  Any suggestions?

**Comment by leon-jasper** [comment]
hey! 
I think you could try this: [reverted sorting](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Sort%20Table&selectedStory=Custom%20Sort%20Fuction&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by AllenFang** [comment]
@mrqcmc I'll implement this feature, thanks

**Comment by AllenFang** [comment]
@mrqcmc Fixed on `react-bootstrap-table-next@0.1.6`, check [release note](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/04/01/version-bump.html), and check [defaultSortDirection](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#defaultSortDirection-string).

let me know if you still have any issues, thanks

**Comment by AllenFang** [comment]
@mrqcmc  

sorry, I made some mistake, please upgrade again:

react-bootstrap-table2-editor@0.1.5
react-bootstrap-table2-filter@0.1.5
react-bootstrap-table-next@0.1.7

and let me know if the issue still remain, thanks

**Comment by mrqcmc** [comment]
Works great! Thanks, @AllenFang
