### ISSUE TITLE
Selecting a single rows selects all rows

### ISSUE THREAD

**Issue by a2441918** [react-bootstrap-table/react-bootstrap-table2#283]
Hi I am trying to select a row, but every row gets selected. 

I am using this code.

export const selectRow = {
  mode: 'checkbox',
  onSelect: (row, isSelect, rowIndex) => {
    console.log("row", row);
    console.log("isSelect", isSelect);
    console.log("rowIndex", rowIndex);
  }
};

I am importing the method in my parent and passing it as props to the table.

Please help.  Any idea to debug why this is happening?

**Comment by AllenFang** [comment]
@a2441918 I can't reproduce this issue in newest version: check [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Multiple%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

What version you used and would you please give me more information?  thanks!!

**Comment by a2441918** [comment]
I use version 0.1.5. 

**This is the function.**
	export const selectRow = {
	  mode: 'checkbox',
	  onSelect: (row, isSelect, rowIndex) => {
	    console.log("row", row);
	    console.log("isSelect", isSelect);
	    console.log("rowIndex", rowIndex);
	  }
	};

**This is my parent.**
	import {selectRow} from "../../components/DataTable/selectRow";

	<DataTable
	    keyField={ 'app_id' }
	    columns={ this.child.columns }
	    data={ this.props.data }
	    totalRows={ this.props.totalRows }
	    placeholder={ 'Application ID' }
	    showStatus={ false }
	    showClassification={ false }
	    selectRow={ selectRow }
	/>

**This is the child.**
	<BootstrapTable
	    keyField={ this.props.keyField }
	    data={ this.props.data }
	    columns={ this.props.columns }
	    rowStyle={ centeredStyle }
	    rowClasses={ this.props.rowClasses }
	    striped
	    hover
	    condensed
	    bordered={ this.props.bordered }
	    noDataIndication={ indication }
	    selectRow={ this.props.selectRow }
	/>

When I select one row every row gets selected but console.log(row) gives me only the first row data and not the one I select.

**Comment by a2441918** [comment]
I upgraded to the latest version. Removed my node modules and reinstalled them. Still the same issue.

**Comment by AllenFang** [comment]
@a2441918  give me a repo I can help to check but please remember show me how to setup your repo, thanks

**Comment by AllenFang** [comment]
Close it due to no response since from one month ago

**Comment by cvhong** [comment]
This also happen to me, select single row, but all row's checkbox is checked.

**Comment by eveseli-ritech** [comment]
I'm having the same issue. Any solution to this problem? Thanks in advance.

**Comment by AllenFang** [comment]
@eveseli-ritech please share how to reproduce. thanks

**Comment by raghubedi2004** [comment]
@eveseli-ritech make sure that in all your rows, the TableHeaderColumn which holds the value of key property (with isKey attribute), is not same. If this value is same, then selecting on one will select all of them.

**Comment by dacevedo12** [comment]
> @eveseli-ritech make sure that in all your rows, the TableHeaderColumn which holds the value of key property (with isKey attribute), is not same. If this value is same, then selecting on one will select all of them.

Thank you! I was just having the same issue but after reading your comment i realized there was no key column assigned in my table. Works like a charm.

**Comment by greygatch** [comment]
What are these isKey or TableHeaderColumn values? They're not in the documentation.

**Comment by kartikgandhii** [comment]
> @eveseli-ritech make sure that in all your rows, the TableHeaderColumn which holds the value of key property (with isKey attribute), is not same. If this value is same, then selecting on one will select all of them.

It worked, thanks

**Comment by kartikgandhii** [comment]
> What are these isKey or TableHeaderColumn values? They're not in the documentation.

You will find the key attribute in the BootstrapTable Tag.
