### ISSUE TITLE
0.1.6 npm differences with releases?

### ISSUE THREAD

**Issue by NixonK** [react-bootstrap-table/react-bootstrap-table2#289]
Hi, this is regarding recent merged fixes #274. I saw that 0.1.6 has been pushed to npm but I am seeing that the npm install of version 0.1.6 does not include the changes seen in the github 0.1.6 releases. 

Below are screenshots of the file `wrapper.js` which seem to be inconsistent on 0.1.6; sorry in advance if instead I am looking at completely different files (I am not familiar with the npm release process) and if i should make changes elsewhere. 

This also seems the case for `\node_modules\react-bootstrap-table2-filter\lib\src\filter.js` and the changes pushed to version `react-bootstrap-table2-filter@0.1.4`.

---

The following image is with a fresh install of `npm install react-bootstrap-table-next --save
` (and confirming the version number of 0.1.6 with `npm list`) and with file:
- `\node_modules\react-bootstrap-table-next\lib\src\sort\wrapper.js`

![image](https://user-images.githubusercontent.com/11034937/38172444-789f1a98-3561-11e8-8635-bececaac43cc.png)

The following image is from the GitHub releases .zip file at [react-bootstrap-table-next@0.1.6](https://github.com/react-bootstrap-table/react-bootstrap-table2/releases/tag/react-bootstrap-table-next%400.1.6) with file:
- `\packages\react-bootstrap-table2\src\sort\wrapper.js`

![image](https://user-images.githubusercontent.com/11034937/38172451-8d40c276-3561-11e8-8a10-22ffd5c0e027.png)

**Comment by AllenFang** [comment]
@NixonK sorry, I made some mistake, please upgrade again:

react-bootstrap-table2-editor@0.1.5
react-bootstrap-table2-filter@0.1.5
react-bootstrap-table-next@0.1.7

and let me know if the issue still remain, thanks
