### ISSUE TITLE
Table with cells containing checkboxes and selectRow 

### ISSUE THREAD

**Issue by aaveen** [react-bootstrap-table/react-bootstrap-table2#293]
Hi am hoping someone can help, 
I have dataField of type boolean, and want to display it in the table as an editable checkbox. But at same time my table allows row selection for deletion functionality.

I managed to get my react-bootstrap-table  with editable checkboxes, but the main problem is the selectRow on the table is also getting triggered everytime I check/uncheck the checkbox , not sure how i can stop that from happening!

The way I implemented the checkboxes is without the usage of the table's cellEdit functionality as it just didn't work, not sure if there is way of implementing this with that react-bootstrap-table cellEdit ! 

this is how I done the formatter to display the checkboxes and for any onClick action a handler function is called which sets the new row data state with the updated checkbox value

here is a snippet of the column formatter 

   `    checkboxFormatter(is_checked, row) {
        if (is_checked) {
            return (
                    <input  type="checkbox" defaultChecked 
                        onClick={(e) => this.handleCheckboxChange(e, is_checked, row)}/>
            );
        }else{
            return (
                    <input  type="checkbox" checked={false} 
                    onClick={(e) => this.handleCheckboxChange(e, is_checked, row)}/>
            );
        }
    }`

    getColumns () { 
        return [ {dataField: 'ID' , text:'ID', filter: textFilter({ comparator: Comparator.EQ, caseSensitive: false }) ,isKey: true},
             {dataField: 'tax', text:'Tax', formatter: this.checkboxFormatter}];
    }`

Any help would be great !

Thanks

**Comment by aaveen** [comment]
@AllenFang am using the react-bootstrap-table2 and wondering if there is a better way of editing a checkbox cell in a table
Thanks
Aveen

**Comment by AllenFang** [comment]
@aaveen we will have custom/defalut cell editor in `react-bootstrap-table2`, just same as `react-bootstrap-table`. I'm very sorry that I have big delay for this project due to quite busy job lol.

Anyway, I'll be back for this project in next weeks :)

**Comment by AllenFang** [comment]
@aaveen please check [rich editoris](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-celledit.html#rich-editors) and [custom editor](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-celledit.html#customize-editor)

Upgrade to `react-bootstrap-table2-editor@0.2.0`, thanks
