### ISSUE TITLE
Configuration to show pagination buttons above table rather than below the table.

### ISSUE THREAD

**Issue by karanbajaj2209** [react-bootstrap-table/react-bootstrap-table2#299]
Is there any configuration which allows displaying pagination buttons above table rather than below the table.

**Comment by AllenFang** [comment]
HI @karanbajaj2209 right now, we don't have this kind of configuration, will implement it, thanks

**Comment by cbfrank** [comment]
can we add more custom options such as the container css class?

**Comment by nilaynanavati** [comment]
I am still looking for this. How do I show pagination on top of the table? I was using react-bootstrap-table and it has property to show top of the table but with new table2, it's not there. Can you please help?

**Comment by AllenFang** [comment]
check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20Pagination%20List&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example and document https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#advance-customization
