### ISSUE TITLE
Require 'react bootstrap table' via cdn

### ISSUE THREAD

**Issue by hc1skalyanasundaram** [react-bootstrap-table/react-bootstrap-table2#300]
I'm trying to require react bootstrap table via cdn like this:

require.config( {
	paths: {
'react': 'https://unpkg.com/react@16/umd/react.development',
        'react-dom': 'https://unpkg.com/react-dom@16/umd/react-dom.development',
        'reactbootstraptable' : 'https://unpkg.com/react-bootstrap-table-next@0.1.7/dist/react-bootstrap-table2.min'
})

and in my component I require like this:

define(['react',
        'reactbootstraptable'],
    function(React, ReactBsTable) {
class App extends React.Component {

render() {
                const BootstrapTable = ReactBsTable.BootstrapTable;
                return (
                        <BootstrapTable keyField='id' data={ this.state.products } columns={ this.state.columns } />
                    </div>
                );
            }
}

return App;
});

However when I run this, I get an exception : react-dom.development.js:66 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Any help on how to require the bootstrap table via cdn is much appreciated. Because I'm trying to integrate this with a project, using npm is not an option for now. if I can make it work with require, would be great. Thanks 

Note: I got this to work with old version of react bootstrap table via this cdn
https://cdnjs.cloudflare.com/ajax/libs/react-bootstrap-table/4.3.1/react-bootstrap-table.min

**Comment by AllenFang** [comment]
@hc1skalyanasundaram after next version, we will build a correct UMD version.

https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/228

**Comment by AllenFang** [comment]
BTW, for now, I plan to upload this project to CDN, but there's some limitation, like: github stars and download counts, right now this project is not enough for that. Currently, we will build the UMD version inside the `dist` folder. u can install our repo by `npm` then copy all the file you need inside the `dist` dir.

**Comment by AllenFang** [comment]
@hc1skalyanasundaram check https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html#umd
