### ISSUE TITLE
Support bootstrap 4

### ISSUE THREAD

**Issue by Chun-MingChen** [react-bootstrap-table/react-bootstrap-table2#305]
Hi @AllenFang:

I'm trying to support `bootstrap 4` and I'll take a look on how it was implemented in `react-bootstrap-table`. It would be take refer to but won't be the same. If there's any concern or advices, please let me know. Thanks a lot :)

**Comment by Chun-MingChen** [comment]
@AllenFang

Ok got it. Currently I'm trying to come up with a new way to not use a flag as `react-bootstrap-table` did. Unless there's no better solution, I will pick up the same way.

```js
const isBootstrap4 = Util.isBootstrap4(this.props.version);
```

**Comment by AllenFang** [comment]
@Chun-MingChen sure, that's a good idea!!

**Comment by coommark** [comment]
Hello @Chun-MingChen, good job! Please what is the status of this? Can we start using Bootstrap 4?

**Comment by AllenFang** [comment]
@coommark it does need some time, we will support it ASAP, thanks!!

**Comment by ssorallen** [comment]
Also the `table-condensed` class changed to [`table-sm`](https://getbootstrap.com/docs/4.1/content/tables/#small-table). The `condensed` prop for ReactBootstrapTable2 adds the incorrect class name right now and has no effect. You can get around it by using `classes="table-sm"` right now.

**Comment by kurt-o-sys** [comment]
just wondering (since I'm about to finish a project, and I'm still doubting if I should revert to the react-bootstrap-table or not): any ETA for bootstrap4 support?

**Comment by AllenFang** [comment]
@kurt-o-sys I think before July or middle of June :)

**Comment by kurt-o-sys** [comment]
:+1:

**Comment by mattrei** [comment]
see also #321

**Comment by nthgol** [comment]
thanks @ssorallen

**Comment by jrotoni** [comment]
Works like a charm! Thank you so much @ssorallen and thank you too @AllenFang

**Comment by ynijs** [comment]
Any update on the move to BS4? I'm still facing issues with the pagination component that is causing an overflow and thus a horizontal scrollbar. I could fix the pagination dropdown with a fix mentioned here on the forums.

**Comment by AllenFang** [comment]
Support from `react-bootstrap-table-next@1.0.0`: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/bootstrap4.html
