### ISSUE TITLE
Sorting hooks in react-bootstrap-table 1&2

### ISSUE THREAD

**Issue by jvlinton** [react-bootstrap-table/react-bootstrap-table2#307]
If you could please provide how I might hook into the before sorting event (before the comparator is hit, or if there is a way to "game" the comparator to do something more universal).

My challenge is I have a multi-level expander I have custom-coded into your table (as it does not appear to support multi-tree expansion) and I need to prevent sorting when it's expanded.  If the sort goes through with sub-rows expanded, it will create a jumble :( hence my need to short-circuit sort before it goes through.

If this is not easy, a faster way may be for me to disable sorting buttons when expander logic is opened.  (Maybe you have a quick suggestion on this instead?)  Thanks.

**Comment by jvlinton** [comment]
Particularly in bs-table I if possible since I'm now using that due to its support for a footer row.  Thanks.

**Comment by AllenFang** [comment]
@jvlinton I see, we don't have footer support right now, but we must implement it in the future.

**Comment by AllenFang** [comment]
HI @jvlinton sorry, I totally forget that we already have a hooks you can use, please check https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnonsort-function. Do let me know if there's any question, thanks :)

**Comment by jvlinton** [comment]
Let me ask this in another way:  Can I manually add buttons in the top row of the table, then manually write my own sort routine based on which column button is pushed and whether it's up or down?  (If you can show me how to hook into doing this, I can write my own sort logic that uses other information than just the per-field override).  In other words, I would not use dataSort={true}, but manually draw in my own buttons and write my own sort.
