### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `UDLRecordTable`.

### ISSUE THREAD

**Issue by rajbtece** [react-bootstrap-table/react-bootstrap-table2#308]
Hi,

I'm trying to integrated react-bootstrap-table-next in my project, but getting the above mentioned error, and the component could not be rendered.

Note: I'm trying to use both react-bootstrap-table (is working fine) as well as react-bootstrap-table-next, But table-2 is not getting rendered. Attached code below.

=============
BootstrapTable keyField='id' columns={columns} data={products} 
=============

Package.json:

"react-bootstrap-table": "^4.3.1",
"react-bootstrap-table-next": "^0.1.8",

'use strict';

var React = require('react');
var createReactClass = require('create-react-class');

const { BootstrapTable } = require('react-bootstrap-table-next');

const columns = [{
    dataField: 'id',
    text: 'Product ID'
}, {
    dataField: 'name',
    text: 'Product Name'
}, {
    dataField: 'price',
    text: 'Product Price'
}];

const products = [{
    "id": 1,
    "name": 'Product 1',
    'price': "10 INR"
}, {
    "id": 2,
    "name": 'Product 2',
    'price': "15 INR"
}];

var UDLRecordTable = createReactClass({
    render: function render() {
        return (
            <BootstrapTable keyField='id' columns={columns} data={products} />

// BootstrapTable element code mentioned above in block
        );
    }
});

module.exports = UDLRecordTable;

**Comment by rajbtece** [comment]
1# I tried by removing **react-bootstrap-table** but no luck.

2# 
What is the react version you used ?
I'm using **react@15**, seems that is the problem.

**Comment by LanDeQuHuXi** [comment]
@rajbtece Having this same problem, have you figured out?

**Comment by AllenFang** [comment]
@rajbtece correct, `react-bootstrap-table-next` need react@16, please upgrade react firstly, thanks!!

Let me know if you have more question about `react-bootstrap-table2`
