### ISSUE TITLE
onDoubleClick support in rowEvents

### ISSUE THREAD

**Issue by OneCyrus** [react-bootstrap-table/react-bootstrap-table2#309]
it would be very helpful if the rowEvents would support onDoubleClick the same way like onClick. Currently setting onDoubleClick works as it triggers the method but it doesn't pass the row and rowIndex parameters.

**Comment by AllenFang** [comment]
@OneCyrus  sure~

**Comment by AllenFang** [comment]
@OneCyrus this was fixed on `react-bootstrap-table-next@0.1.9`, thanks
