### ISSUE TITLE
CSS import

### ISSUE THREAD

**Issue by peckpeck20** [react-bootstrap-table/react-bootstrap-table2#310]
After installing the package ,where should I be adding the CSS ?

`import "react-bootstrap-table-next/dist/react-bootstrap-table2.min.css";   `

Tried adding it to Index.js - App.js  - and my component but I still can't seem to get it working

**Comment by AllenFang** [comment]
@peckpeck20 yes, that's right, if it doesn't work, please make sure you have the bootstrap css. we don't bundle the bootstrap css.

**Comment by kakodali** [comment]
@peckpeck20 I have bootstrap CDN  in my index.html and its working fine for me without any extra styling.
you can place it in the head of your index file

**Comment by Pratiktarade** [comment]
error - ./node_modules/react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .react-bootstrap-table-page-btns-ul{float:right;margin-top:0!important}.react-bootstrap-table-pagination-list-hidden{display:none}
