### ISSUE TITLE
Add Image/Thumbnails to Column of Table

### ISSUE THREAD

**Issue by rsgoss** [react-bootstrap-table/react-bootstrap-table2#315]
Is it possible to add a thumbnail image in the cells of a certain column? I was looking at this and thought a *possible* way would be through the column.classes but I am not quite sure... 
{
  classes: function callback(cell, row, rowIndex, colIndex) { ... }
}
Is it possible to take image data and render in cells of a table?

Thanks!!

**Comment by waynebrantley** [comment]
Just code a custom column formatter, you can render anything you like.
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by rsgoss** [comment]
Thanks!!

**Comment by AllenFang** [comment]
Thanks @waynebrantley

**Comment by s-tags** [comment]
Thanks!

**Comment by DeepakGathwal** [comment]
I don't get it... where we have to declare img link..
on my table only link shown as text field
