### ISSUE TITLE
Wrong NPM Installation Instruction

### ISSUE THREAD

**Issue by coommark** [react-bootstrap-table/react-bootstrap-table2#318]
Hello! Awesome job always. 

I noticed that on the NPM page for [Paginator](https://www.npmjs.com/package/react-bootstrap-table2-paginator) the instructions say `$ npm install react-bootstrap-table2-pagination --save`

But the correct thing should be `npm i react-bootstrap-table2-paginator`

Just a little spelling mistake to correct. Thank you

**Comment by AllenFang** [comment]
@coommark Fixed, thank you :)
