### ISSUE TITLE
Embed html in data fields?

### ISSUE THREAD

**Issue by StephieX** [react-bootstrap-table/react-bootstrap-table2#320]
Hi, is there a way to embed html in data fields?  I'd like to do things like display images and have clickable links inside cells.  Something like:

const data = [{id: 'id1', picture: '<img src="img.png"/>', link1: '<a href="/link1.html">l1</a>'}];

I don't know how to turn Markdown off.  The picture is an img source and the link is an href.  

Thanks.

**Comment by kakodali** [comment]
@StephieX  this is not an issue, its how you are using this component.

Please refer to this [example ](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)and i hope this answers your question.
In this example we are returning custom data -  in your case, you can use your data attributes

**Comment by StephieX** [comment]
@kakodali that worked.  Thanks.
