### ISSUE TITLE
Is "expandableRow" supported by react-bootstrap-table2 ?

### ISSUE THREAD

**Issue by northernbird** [react-bootstrap-table/react-bootstrap-table2#332]
Hi

I read that react-bootstrap-table (obsolete version) supports expandableRow & expandComponent properties so that new child table will be shown if row is clicked.
Example : http://allenfang.github.io/react-bootstrap-table/example.html#expand
Is this function not implemented in react-bootstrap-table2 ?

expandableRow is really useful and I would love to use! 
It would be great if you can let me know the current development status for that.

Thanks a lot for your help in advance.
Rie

**Comment by AllenFang** [comment]
@northernbird it's sorry, we not implement it yet, I think it can be done in Jun

**Comment by northernbird** [comment]
Hi

Thanks a lot for your reply.
If it’s ok for you, I can extend and implement then send pull request to
you.

Allen <notifications@github.com> schrieb am Sa. 12. Mai 2018 um 14:38:

**Comment by bvn13** [comment]
I badly need row expanding... When do you plan to update release?

**Comment by WaqarMobeen** [comment]
Hey @AllenFang ,

First of all awesome work on this plugin, Since I am a very old user of react-bootstrap-table I was migrating to the version and was searching for the row expanding, and you mentioned your plan was to release in june, any idea when we will be able to consume that?

Thanks once again.

Cheers

**Comment by northernbird** [comment]
Hi Allen, 

can we help for the implementation?
I will contribute gladly if I can..

Von meinem iPod gesendet

**Comment by AllenFang** [comment]
Support on `react-bootstrap-table-next@1.0.0` and `react-bootstrap-table2-toolkit@1.0.0`

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-row-expand.html

**Comment by dpramani** [comment]
@AllenFang . Thanks for the updated feature. But currently where ever I click, the row expands , is there a way, when I will click only a button for example a get info button inside a row element, the row expands ? Thanks.

**Comment by AllenFang** [comment]
@dpramani we will support this feature in near future. thanks

**Comment by Raphaww** [comment]
Im sorry but it seems this is not yet implemented, expandableRow should receive a function

`isExpandableRow(row) {
    if (row.id < 2) return true;
    else return false;
  }`

The closes thing we have now is the nonExpandable array

`nonExpandable: [1, 3]`

but its not the same. Am I missing something? I think its not so different from other attributes already implemented like: className or parentClassName

Thanks
