### ISSUE TITLE
Clear more than one column at a time works in a weird way

### ISSUE THREAD

**Issue by agarciaffdc** [react-bootstrap-table/react-bootstrap-table2#334]
First of all, thanks @AllenFang for this amazing work. It is helping us a lot.

I'm working with version _"react-bootstrap-table2-filter": "0.1.6"_ and trying to create a clear button to filter all values on my table. Looking at [this example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Text%20Filter%20&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) I decided to follow it and set empty value instead of 0 in order to clear the filter and it worked!!  

But when I tried to applied same logic to all my columns, I got an error. My second try was to create a new variable so that every column would have its own method that clear the filter. That worked better. My clear button was cleaning both text boxes, and the last column was cleaned. However the first one showed the values of the filters without any filter at the top. 

I must also say that even if the table shows a weird status, first column with the values of the filter without having a value at the top, if I try to filter by another value, it works.

Here is part of my code:

```
let nameFilter,orgFilter;
const clearInfo = () => {
	nameFilter('');
	orgFilter('');
};

const columns = [{
	dataField: 'Value1',
	text: 'Value1',
	sort: true,
	filter: textFilter({
		getFilter: (filter) => {
			nameFilter = filter;
		}
	})
},{
	dataField: 'Value2',
	text: 'Value2',
	sort: true,
	filter: textFilter({
		getFilter: (filter) => {
			orgFilter = filter;
		}
	})
}

//more columns I need to be cleared too

];

//more code .....
<Button bsStyle="primary" bsSize="small" onClick={ clearInfo }>Clear Filters</Button>
```
Thanks!!

**Comment by AllenFang** [comment]
hello @agarciaffdc sorry I still have some confuse on your question, but I saw a bug is that when I clean all the text filter with empty string, the table seems like doesn't have reflect, I mean table should show all the data instead of filtered data.  is that your issue?

**Comment by agarciaffdc** [comment]
Yes, exactly. If I apply the clear filter on one column it works fine. On my previous code, just the _nameFilter_ piece. Once I try to apply it on 2 columns it is when the action clear the text on both columns but the table doesn't reflect it.
Thanks!!

**Comment by AllenFang** [comment]
upgrade to `react-bootstrap-table2-filter@0.1.7` and try again, thanks

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/05/13/version-bump.html

**Comment by agarciaffdc** [comment]
Thanks @AllenFang !! This new version works!! 

In order to help others, let you also know that my code only worked locally. I made few changes in order to make it work on our production enviroment.

```
class Subscriber extends Component {

	constructor(props) {
		super(props);
		this.state = {
			column1Filter: '',
			column2Filter: '',
		};
	}

	// ...

	render() {
		
		const clearInfo = () => {
			this.setState.column1Filter('');
			this.setState.column2Filter('');
		};

		const columns = [{
			dataField: 'Value1',
			text: 'Value1',
			sort: true,
			filter: textFilter({
				getFilter: (filter) => {
					this.setState.column1Filter = filter;
				}
			})
		},{
			dataField: 'Value2',
			text: 'Value2',
			sort: true,
			filter: textFilter({
				getFilter: (filter) => {
					this.setState.column2Filter = filter;
				}
			})
		}

		//more columns I need to be cleared too

		];

		//....

		<Button bsStyle="primary" bsSize="small" onClick={ clearInfo }>Clear Filters</Button>	

		// ...
	}

	//....
}
```



Thanks!!
