### ISSUE TITLE
Checkbox doesn't work when using handler

### ISSUE THREAD

**Issue by heyjaypray** [react-bootstrap-table/react-bootstrap-table2#337]
I'm trying to create a delete row handler.  But for some reason its not showing the check in the checkbox when i click on it.  it is selecting it correctly - but just not displaying the check.

```
const deleteRowWood = {
      mode: 'checkbox',
      clickToSelect: true,
      selected: this.state.woodtypeSelected,
      onSelect: this.handleWoodSelectDelete,
    };
```

```
handleWoodSelectDelete = (row, isSelect) => {

    if (isSelect) {

      this.setState(() => ({
        woodtypeSelected: [...this.state.woodtypeSelected, row]
      }));
    } else {
      this.setState(() => ({
        woodtypeSelected: this.state.woodtypeSelected.filter(x => x !== row)
      }));
    }

  }
```

```
 <BootstrapTable
       keyField="name"
       data={this.state.woodtype}
       columns={woodtypeColumns}
      selectRow={deleteRowWood}
            />

```

**Comment by sisodiakaran** [comment]
@heyjaypray Facing exactly same issue. Did you found any clue, why this is happening?

**Comment by heyjaypray** [comment]
I dont remember what my fix was since this issue is about two months old - but heres my code if you see the fix.

```
handleSelect = (row, isSelect) => {
        if (isSelect) {
            this.setState(() => ({
                selected: [...this.state.selected, row]
            }));
        } else {
            this.setState(() => ({
                selected: this.state.selected.filter(x => x !== row)
            }));
        }
    }

handleDelete = (row, isSelect) => {
        if (isSelect) {
            this.setState(() => ({
                selected: [...this.state.selected, row._id]
            }));
        } else {
            this.setState(() => ({
                selected: this.state.selected.filter(x => x !== row._id)
            }));
        }
    }
```

```
const selectRow = {
            mode: 'checkbox',
            clickToSelect: true,
            clickToEdit: true,
            selected: this.state.selected,
            onSelect: this.handleSelect,
            hideSelectColumn: true
        };
```

        const deleteRow = {
            mode: 'checkbox',
            clickToSelect: true,
            selected: this.state.selected,
            onSelect: this.handleDelete,
        };

        const cellEdit = {
            mode: 'click'
        };

                             <BootstrapTable
                                        keyField="_id"
                                        data={this.state.data}
                                        columns={columns}
                                        cellEdit={cellEditFactory({ mode: 'click' })}
                                        selectRow={selectRow}
                                    />`
