### ISSUE TITLE
Cell Editing(Dropdown): Can't read property 'SELECT' of undefined

### ISSUE THREAD

**Issue by 530** [react-bootstrap-table/react-bootstrap-table2#339]
When using any of the cell editing types inside editor I receive an TypeError of undefined. I followed the docs on how to implement exactly. Prior to this I was able to use click editing and edit just fine. Not sure if it's just something I'm doing wrong or if this is an issue for others as well.

Currently using "react-bootstrap-table-next": "^0.1.11", "react-bootstrap-table2-editor": "^0.1.5"
**Import**
`import cellEditFactory, { Type } from 'react-bootstrap-table2-editor';`

**Inside my Columns**:
`		{
			dataField: 'type',
			text: 'Priority',
			editor: {
				type: Type.SELECT,
				options: [{
					value: 'high',
					label: 'high'
				}, {
					value: 'medium',
					label: 'medium'
				}, {
					value: 'low',
					label: 'low'
				}]
			}
		}`
**What my Table2 component looks like**:
`		
const cellEdit = cellEditFactory ({
			mode: 'click',
			blurToSave: true,
			afterSaveCell: this.onAfterSaveCell
		});`

    return (
      <div >
			<Header />

			<BootstrapTable keyField='id' data={ this.state.bugs }  columns={ this.state.columns } 
			pagination={paginationFactory()} cellEdit={cellEdit} insertRow={true} selectRow={ selectRow }
      filter={filterFactory()}/>`

**Comment by AllenFang** [comment]
@530 please upgrade to `react-bootstrap-table2-editor@0.2.1` and `react-bootstrap-table-next@0.1.11`, thanks
