### ISSUE TITLE
Is it possible make CRUD operations?

### ISSUE THREAD

**Issue by Nahuel92** [react-bootstrap-table/react-bootstrap-table2#343]
Hi everyone! I moved from React Bootstrap Table to this version and since then I lost a lot of functionality like CRUD operations.
I found nothing on demos nor documentation.
Can you help me please?

PD : Yes, I opened 2 more issues but because I think this way is clearer than put all in just one issue.

**Comment by AllenFang** [comment]
@Nahuel92 Right not, the insert/delete/search still not implement yet. Only cell edit was implemented.  We will support it ASAP, thanks
