### ISSUE TITLE
Select All and Pagination

### ISSUE THREAD

**Issue by Josh123321** [react-bootstrap-table/react-bootstrap-table2#347]
I am trying to select all the rows only on the current page(10 rows),but I will get the whole table's rows.(100 rows)
Is there any way to accomplish this?

thx

**Comment by AllenFang** [comment]
@Josh123321 I will fixed this in the near future, anyway, in the future, the select all only work on current page!!

**Comment by AllenFang** [comment]
@Josh123321 upgrade all of the `react-bootstrap-table` related packages to `1.0.0`. Please open another issue if this problem still remain.

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/04/version-bump.html

**Comment by ududsha** [comment]
> @Josh123321 I will fixed this in the near future, anyway, in the future, the select all only work on current page!!

@AllenFang 
I am retrieving the data for each page when we click on the page in the pagination as we have large number of data. Is there a way to keep 'checked' all the rows if we selectAll in the first page.

**Comment by shubuu97** [comment]
In remote mode, if we use selectAll button, it de-selects the old page when we select another page.

**Comment by ZippoLag** [comment]
@AllenFang is there an easy way to make the check-all button select items in all pages? I want to do that instead of selecting only the rows in the current page :smile:

**Comment by arkzky** [comment]
Do we have any update on this? 
Would be cool if we could preserve the selected rows in multiple pages on remote mode!
