### ISSUE TITLE
Add date filter

### ISSUE THREAD

**Issue by mathiaswillburger** [react-bootstrap-table/react-bootstrap-table2#349]
When will date filtering be supported like in react-bootstrap-table to get a date selector and input box?

**Comment by AllenFang** [comment]
@mathiaswillburger I will implement it ASAP. thanks

**Comment by AllenFang** [comment]
@mathiaswillburger https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/06/04/version-bump.html

upgrade to `react-bootstrap-table2-filter@0.2.0` and `react-bootstrap-table-next@0.1.13`.

[This](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Date%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example.

check [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/filter-props.html#dateFilter) for more details, thanks
