### ISSUE TITLE
Paginator error in VS2017 with typescript

### ISSUE THREAD

**Issue by vinhlevinhle** [react-bootstrap-table/react-bootstrap-table2#350]
Hi,
I am using vs2017 react template with typescript.
I am just using the basic table works fine but when i included paginator feature I get typescript compilation error so to get around this I declared an index.t.ts in the @type folder.
eg:
import * as React from "react";
export class paginator extends React.Component<any,any> { }
export default paginator;

But VS2017 typescript compiler still wont understand this when i call paginator()  function inside BootstrapTable as below:

 <BootstrapTable keyField='id' data={this.props.responsesData} columns={this.props.columsDefn} pagination={pagination} />

I suspected my type definition is incorrect for paginator. However, I did the same for BootstrapTable and it worked fine.

I have the latest react 16.1.1

Any help be great.

**Comment by vinhlevinhle** [comment]
when i installed npm for paginator , I notice some warning.
But i can't work out if they are related to my issues.


E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1>npm install react-bootstrap-table2-paginator --save
npm WARN saveError Problems were encountered
npm WARN saveError Please correct and try again.
npm WARN saveError extraneous: undefined E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1\node_modules\@types\react-bootstrap-table-next
npm WARN saveError extraneous: react@16.1.1 E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1\node_modules\react
npm WARN saveError extraneous: fbjs@0.8.16 E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1\node_modules\react\node_modules\fbjs
npm WARN saveError extraneous: prop-types@15.6.1 E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1\node_modules\react\node_modules\prop-types
npm WARN saveError extraneous: react-dom@16.0.0 E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1\node_modules\react-dom
npm WARN saveError extraneous: fbjs@0.8.16 E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1\node_modules\react-dom\node_modules\fbjs
npm WARN saveError extraneous: prop-types@15.6.1 E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1\node_modules\react-dom\node_modules\prop-types
npm WARN saveError peer invalid: react@^15, required by react-router@4.1.1
npm WARN saveError peer invalid: react@^15, required by react-router-dom@4.1.1
npm WARN saveError peer invalid: react@^15, required by react-router-redux@5.0.0-alpha.6
npm WARN saveError peer invalid: react@^0.14.0 || ^15.0.0, required by redbox-react@1.4.2
npm WARN saveError peer invalid: react-dom@^0.14.0 || ^15.0.0, required by redbox-react@1.4.2
WebApplication1_netcore2._1@0.0.0 E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1
+-- UNMET PEER DEPENDENCY react@16.1.1 invalid
`-- react-bootstrap-table2-paginator@0.1.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'E:\Dev-old\Test NodeJS\typescript_project\testcore2.0\WebApplication1_netcore2.1\WebApplication1_netcore2.1\node_modules\@types\react-bootstrap-table-next\package.json'
npm WARN react-router@4.1.1 requires a peer of react@^15 but none was installed.
npm WARN react-router-dom@4.1.1 requires a peer of react@^15 but none was installed.
npm WARN react-router-redux@5.0.0-alpha.6 requires a peer of react@^15 but none was installed.
npm WARN redbox-react@1.4.2 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN redbox-react@1.4.2 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none was installed.

**Comment by vinhlevinhle** [comment]
Hi Allan,
Appreciate your prompt response.
I still have the same issue. I also noted a few people were raising similar issue about this.

I use MS VS 2017 react redux template.
Only when I use pagination that when it is a problem. BootstrapTable next on its own work perfectly.

Cheers,
Vinh

**Comment by AllenFang** [comment]
@vinhlevinhle so if your change the **type**, the problem still there?  As I mentioned above, the `paginator` accept an object like https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2-paginator/index.js#L3-L6

**Comment by AllenFang** [comment]
BTW, I saw your stackoverflow issue: https://stackoverflow.com/questions/50521213/type-definition-error-for-paginator-with-react-bootstraptable-in-vs2017-typescri

`
Error: PaginationWrapper.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
`

I do believe your React is before React@16 or have duplicated react version installed!.  Please check it firstly

**Comment by vinhlevinhle** [comment]
Ok I ll look into if I have duplicated react version.

Vinh
