### ISSUE TITLE
Row Selection Question: Is it possible to add a text header for mode: 'radio' ?

### ISSUE THREAD

**Issue by 530** [react-bootstrap-table/react-bootstrap-table2#351]
I'm looking to add a header above my radio button field, but from tinkering with the code I haven't found a way to do this. Is there a way to have it appear as though it were just another column header?

**Comment by AllenFang** [comment]
@530 right now we dont support the custom selection header cell, I will implement it ASAP

**Comment by AllenFang** [comment]
@530 https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/06/04/version-bump.html

Please upgrade to `react-bootstrap-table-next@0.1.13`, check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowselectionheaderrenderer-function) to see how to custom.

Do let me know if there's any issue and reopen this ticket again, thanks
