### ISSUE TITLE
Is there any way to align column.text across multiple columns?

### ISSUE THREAD

**Issue by pashazz** [react-bootstrap-table/react-bootstrap-table2#355]
In your Storybook example you have the following table:
![image](https://user-images.githubusercontent.com/45922/40624445-6ad32b44-62b5-11e8-8376-a499bc644c7f.png)

How can I align all the column **names** along the same baseline horizontally?
Like this:

![image](https://user-images.githubusercontent.com/45922/40624659-8c54fb66-62b6-11e8-8e56-8b07d9d83d57.png)

 I guess it requires me to customize thead.

**Comment by AllenFang** [comment]
Sorry for lately reply, @pashazz yes, that's right.

This [demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Header%20Columns&selectedStory=Column%20Format%20with%20Filter%20and%20Sort&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) just for showing the ability to custom the header if sort and filter is enable. `react-bootstrap-table` give you a lots of power to let you custom the content of header.
