### ISSUE TITLE
react-bootstrap-table2-overlay does not consider caption height

### ISSUE THREAD

**Issue by mathiaswillburger** [react-bootstrap-table/react-bootstrap-table2#358]
When adding `caption={....}` to ReactBootstrapTable together with `overlay={overlayFactory(...)}` the overlay is not positioned correctly anymore.

The overlay top margin seems to be calculated by `var headerDOM = wrapper.parentElement.querySelector('thead');` and `masker.style.marginTop = window.getComputedStyle(headerDOM).height;` but does not consider the height of a possible `caption` tag.

**Comment by AllenFang** [comment]
@mathiaswillburger thanks, its seems like a bug, I will fix it soon :)

**Comment by AllenFang** [comment]
@mathiaswillburger https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/06/04/version-bump.html

Fixed on `react-bootstrap-table-next@0.1.13` and `react-bootstrap-table-overlay@0.1.2`.

Let me know and reopen this issue again if the problem still remain, thanks
