### ISSUE TITLE
prop type checking fails when using mobx

### ISSUE THREAD

**Issue by mathiaswillburger** [react-bootstrap-table/react-bootstrap-table2#361]
When using mobx for state management the proptype checking fails:

```Warning: Failed prop type: Invalid prop `data` of type `object` supplied to `BootstrapTable`, expected `array`.```

The reason is that the provided property is not a simple array anymore but an ObservableArray:

```
@observable
  data = [...];
```

Any ideas how to solve this without loosing observability of the property?

**Comment by AllenFang** [comment]
Not very familiar with `ObservableArray`, but is it possible to change to native Array before feed into table?  you can just keep it as `ObservableArray`, but only different is you change it to an native array when rendering?  thanks

**Comment by AllenFang** [comment]
https://github.com/mobxjs/mobx-react/issues/107

There's a solution but which means `react-bootstrap-table` need to depends on `mobx-react` but I think this is not a good idea for a open source component.

**Comment by mathiaswillburger** [comment]
True, there would be a mobx dependency. I was thinking about proposing to use

```
import { PropTypes as MobxPropTypes } from 'mobx-react';
import PropTypes from 'prop-types';
...
Component.propTypes = {
  data: MobxPropTypes.arrayOrObservableArray,
}
```

This would ensure mobx compatibility and native arrays. But as you said, it creates a dependency.

Converting back to a native array is unfortunately no option, because that removes the whole benefit of using mobx stores with [observableArrays](https://mobx.js.org/refguide/array.html). I'd rather accept the console warning for now in this case.

**Comment by mathiaswillburger** [comment]
Works like a charm. Solved it by slicing the array before using it:
```
@computed
  get dataSource() {
    return this.data.slice();
  }
```

**Comment by AllenFang** [comment]
👍
