### ISSUE TITLE
clear selected rows

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#362]
Good Morning,
How can I clear the selected rows? I did not find anything in the documentation

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/about.html

I am using the following versions:

    "react-bootstrap-table": "^4.3.1",
    "react-bootstrap-table-next": "^0.1.10",
    "react-bootstrap-table2-filter": "^0.1.6",
    "react-bootstrap-table2-paginator": "^0.1.3",

**Comment by AllenFang** [comment]
Check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

You can set `selectRow.selected` as empty array

**Comment by Denis-String** [comment]
Sorry about the delay, Allen.

The sample code is very different from mine, and after your queries, I was not able to clear the selected line.

My code:

`export default class Banco extends Component {
    constructor() {
        super();
        this.state = {
            listbanco: [],
            banco: '',
            bancoAlterar: '',
            rowSelecionada: false,
        }

    }`

` render() {
        const products = this.state.listbanco;
        const selectRowProp = {
            mode: 'radio',
            bgColor: '#26a69965',
            hideSelectColumn: true,
            clickToSelect: true,

            onSelect: (row, isSelect) => {
                this.setState({ rowSelecionada: isSelect })
                this.setState({ banco: row })
                var bancoAlterar = JSON.parse(JSON.stringify(row)); 
                this.setState({
                    bancoAlterar:bancoAlterar
                })
            }


        };`

` return (
<div className="col-lg-12">
                            <BootstrapTable pagination striped data={products} selectRow={selectRowProp}>
                                <TableHeaderColumn filter={{ type: 'TextFilter', delay: 300 }} id="tableFinanceiro" isKey dataField='id'>ID</TableHeaderColumn>
                                <TableHeaderColumn filter={{ type: 'TextFilter', delay: 300 }} dataField='nome'>Nome:</TableHeaderColumn>
                                <TableHeaderColumn filter={{ type: 'TextFilter', delay: 300 }} dataField='conta'>Conta:</TableHeaderColumn>
                                <TableHeaderColumn filter={{ type: 'TextFilter', delay: 300 }} dataField='codigo'>Codigo:</TableHeaderColumn>
                                <TableHeaderColumn filter={{ type: 'TextFilter', delay: 300 }} dataField='agencia'>Agencia:</TableHeaderColumn>
                                <TableHeaderColumn filter={{ type: 'TextFilter', delay: 300 }} dataField='dv'>DV:</TableHeaderColumn>
                                <TableHeaderColumn filter={{ type: 'TextFilter', delay: 300 }} dataField='ativodesc'>Ativo:</TableHeaderColumn>
                            </BootstrapTable>
                        </div>`


Am I doing something wrong?

I can't unmark the line automatically.
