### ISSUE TITLE
Got a react warning on a SelectionCell

### ISSUE THREAD

**Issue by pragmasoft-ua** [react-bootstrap-table/react-bootstrap-table2#363]
Warning: Failed form propType: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`. Check the render method of `SelectionCell`.

For some reason onClick is set on a td element rather than input element:
```
<td onClick={ this.handleClick }>
        <input
          type={ inputType }
          checked={ selected }
          disabled={ disabled }
        />
</td>
```
moving it to input may fix this warning.

**Comment by AllenFang** [comment]
@pragmasoft-ua thank, I will check this out :)

**Comment by robotanz** [comment]
I have exactly the same issue when using selection checkboxes:

```
Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by CheckBox)
    in CheckBox (created by SelectionHeaderCell)
    in th (created by SelectionHeaderCell)
    in SelectionHeaderCell (created by Header)
    in tr (created by Header)
```

**Comment by cbfrank** [comment]
I have the same error which is similar to the issue #181

**Comment by AllenFang** [comment]
hey guys, we fixed this issue in `react-bootstrap-table-next@1.1.2`, check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/21/version-bump.html)

**Comment by pLavrenov** [comment]
actual 4.0.3
