### ISSUE TITLE
Ability to double click on row.

### ISSUE THREAD

**Issue by hashharvest** [react-bootstrap-table/react-bootstrap-table2#372]
Hello.

I would like the ability to double click on a row (it throw an event on a double click) when I have selectRow options set.  In my case, I am hiding the select column and just catching the onSelect event for now.

Is it possible to double click in current state?

**Comment by AllenFang** [comment]
HI @hashharvest sorry for lately reply, [rowEvents](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-row.html#row-events) support u to listen the double click event. Please do re-open this issue if the problem still remain, thanks

**Comment by Fatal1stZ** [comment]
it actually doesn't work, nothing is happening:
`    rowEvents: {
      onDoubleClick: console.log,
    },
`
Can it be somehow depend on selectRow props?
