### ISSUE TITLE
change color of selected row

### ISSUE THREAD

**Issue by xero88** [react-bootstrap-table/react-bootstrap-table2#373]
How can I change the style of a selected row ? # @

**Comment by AllenFang** [comment]
Hello, you can check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Background%20Color&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example.

Please do let me know if you have any concern/idea or suggestion. thanks

**Comment by xero88** [comment]
@AllenFang thank you for your answer

I forget to precise that i'm not using the selectRow. Because I don't want a checkbox, I want that the user click on the row. For now I'm using  

`rowEvents={{ onClick: (e, row, rowIndex) => this.props.onRowSelected(row) }}`

Can I change the color using this way ?

**Comment by AllenFang** [comment]
@xero88  sorry for lately, there's a workaround is you still enable `selectRow` but give [`selectRow. hideSelectColumn`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowhideselectcolumn-bool) as true and enable `selectRow.clickToSelect`. That will match your requirement.

**Comment by xero88** [comment]
This is still not working

 ```
render() {
        const selectRow = {
            mode: 'radio',
            clickToSelect: true,
            hideSelectColumn: true,
            bgColor: '#00BFFF',
            onSelect: (row, isSelect, rowIndex, e) => {
                console.log(row.id);
                console.log(isSelect);
                console.log(rowIndex);
                console.log(e);
            }
        };

        return (
                <BootstrapTable
                    selectRow={selectRow}
                    keyField='id'
                    data={ this.props.contact }
                    columns={ this.columns }
                />
        );
    }
```

**Comment by xero88** [comment]
@AllenFang thx for your answer, this work.

You know by the way if there is a way to set manualy the selected row index ?

**Comment by AllenFang** [comment]
@xero88 you can check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by vtarelkin-comprehend** [comment]
If someone is here like me we can change the color WITHOUT hiding selection and without selection.
in Bootstrap table enable styles for rows
 rowStyle={ rowStyle }  and 

    const rowStyle = (row, rowIndex) => {
        if (row === clickedRow) {
            return {color: '#FD0303' };
        }
    };

**Comment by wink94** [comment]
I  get this error  for these props

```
  const selectRow = {
    mode: "checkbox",
    clickToSelect: true,
    bgColor: "#00BFFF",
  };
```

`Type '{ mode: string; clickToSelect: boolean; bgColor: string; }' is not assignable to type 'SelectRowProps<any>'.`

**Comment by NguyenTrungMax** [comment]
hello @AllenFang  Can I change bgColor of selected row only ? The example display all selected row, I want display only row when I click,

**Comment by Payel-Dutta28** [comment]
> Hello, you can check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Background%20Color&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example.
> 
> Please do let me know if you have any concern/idea or suggestion. thanks

Hi Allen, 

On using select Row all the rows are getting selected do you have any solution for this?

**Comment by Payel-Dutta28** [comment]
> hello @AllenFang Can I change bgColor of selected row only ? The example display all selected row, I want display only row when I click,

Did you find any solution for this?

**Comment by NguyenTrungMax** [comment]
> > hello @AllenFang Can I change bgColor of selected row only ? The example display all selected row, I want display only row when I click,
> 
> Did you find any solution for this?

oh yes, I set class "active-row" for selected row, first, I remove class then add it only selected row
