### ISSUE TITLE
Table Re-Render Problem

### ISSUE THREAD

**Issue by PatrykMilczarek** [react-bootstrap-table/react-bootstrap-table2#374]
Hello,
I created a table with some data. I also added pagination. However, if i edit a row on a second (or third, fourth etc.) page, the table rerenders and i jump to first page instead of staying on the second page. 
 I want it to re-render on the same page i edited the row. Please help me with this problem :)

**Comment by AllenFang** [comment]
@PatrykMilczarek could you please show some codes?  Do you enable the `remote` mode? What version you used?  thanks

**Comment by PatrykMilczarek** [comment]
I am using react-bootstrap-table v2 and i enabled remote mode for cell editing. I have some trouble with remote mode for pagination. I want to stay on the current page after cell editing. 
`
handleTableChange(type, { data, page, cellEdit: { rowId, dataField, newValue } }) {

      const result = data.map((row) => {

        if (row.id === rowId) {
          let newRow = {...row};
          newRow[dataField] = newValue;

          return newRow;
        }
        return row;
      });

      this.setState(() => ({
        data: data
      }));

  }

  const pagination_options = {
    pageStartIndex: 1,
    prePageText: 'Back',
    nextPageText: 'Next',
    sizePerPageList: [{
      text: '10', value: 10
    }]
  };
  
<BootstrapTable 
data={ this.state.data }
remote={ { cellEdit: true } }
keyField='id' 
columns={ this.state.columns } 
hover
cellEdit={ cellEditFactory({
mode: 'dbclick',
blurToSave: true
}) }
filter={ filterFactory() }
pagination={ paginationFactory(pagination_options) } 
onTableChange={ this.handleTableChange }
/>`

**Comment by machour** [comment]
@PatrykMilczarek could you share how you managed to stay on the same page ?
I have a similar problem, when if you sort by a column, then edit a cell, the sort is reseted

**Comment by AllenFang** [comment]
@PatrykMilczarek sorry for lately reply, I will check this out.

**Comment by AllenFang** [comment]
It's a bug and already have a [PR](https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/371/files) for fixing this issue, will be released in this weekend, sorry for lately fixing ;(

**Comment by PatrykMilczarek** [comment]
@AllenFang  Thank you :)

**Comment by AllenFang** [comment]
@PatrykMilczarek 

[RELEASE NOTES](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/06/24/version-bump.html)

Support on `react-bootstrap-table-next@0.1.14` and `react-bootstrap-table2-paginator@0.1.5`

Please reopen this issue and tag me again if the problem still remain, thanks

**Comment by jzhou2014** [comment]
@AllenFang - Is there a way to apply the fixes to the legacy react-bootstrap-table? Thanks, Jin

**Comment by VladimirBessonov** [comment]
Rrrrr where are working code samples for functional components? 
was issue resolved? or what?
