### ISSUE TITLE
selectRow.bgColor does not work if onSelect is used

### ISSUE THREAD

**Issue by waynebrantley** [react-bootstrap-table/react-bootstrap-table2#378]
Using this example:

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Hide%20Selection%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

If you add an ``onSelect`` handler to it, the handler will be called, but the background color is not set.   Remove the handler and the background color is set.

**Comment by AllenFang** [comment]
Many thanks, @waynebrantley I will handle it 👍

**Comment by AllenFang** [comment]
@waynebrantley it work to me:

```js
const selectRow = {
  mode: 'checkbox',
  clickToSelect: true,
  hideSelectColumn: true,
  bgColor: '#00BFFF',
  onSelect: (row, isSelect, rowIndex, e) => {
    console.log(row.id);
    console.log(isSelect);
    console.log(rowIndex);
    console.log(e);
  }
};
```

**Comment by waynebrantley** [comment]
We were using mode of 'radio'

**Comment by AllenFang** [comment]
@waynebrantley sorry for lately reply, but it's still work to me even i change to single selection. Any more information about this issue? Thanks!

**Comment by AllenFang** [comment]
@waynebrantley I'm not sure if you encounter the same issue: https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/297

**Comment by waynebrantley** [comment]
Dang it...yes that is it.  When they click a row - we update state in component so we can change the screen to reflect the row they clicked.  It works fine - but the backgound color does not update - I guess because your gird did not get a chance to update its state.

We are not looking to manage the state of the selection - but to simply take other actions as the selection happens (we dont pass in selected rows, etc).  So, in this case it would make sense for your grid to update its state first, then call the event handlers.   Now, if someone want to completely handle the selected state management - that would be a different case I suspect.

**Comment by AllenFang** [comment]
> I guess because your gird did not get a chance to update its state.

correct.



> So, in this case it would make sense for your grid to update its state first, then call the event handlers.

yes, but react set state is asynchronize. the only why I can imagine is call the handler in before component update. but it will make some logic more complex. so I think current workaround is I will encourage people to manage selection also if you update the component by calling setState in the handler.

Anyway, I will keep to find if we can have a better solution and any idea is welcome, thank you @waynebrantley  👍

**Comment by AllenFang** [comment]
Close due to duplicate #297. Let discuss on #297

**Comment by AllenFang** [comment]
Sorry for lately fixed.....
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/11/04/version.bump.html)

now you can call `setState` in `selectRow.onSelect` and we support a feature that you can reject the selection, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowonselect-function) and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Advance%20Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is example

**Comment by BlaineBradbury** [comment]
I don't think this is a duplicate issue to #297.  Your new example works, and does update the selected array onSelect, but both bgColor and style do not render if you setState in onSelect.  Can you add logic to your example to show bgcolor or style with backgroundColor if you indeed have it working.  thx
