### ISSUE TITLE
Remote sort not working

### ISSUE THREAD

**Issue by eylonronen** [react-bootstrap-table/react-bootstrap-table2#385]
Hi, I'm using this module configured with remote pagination/sorting.
I want to lazy load the data from server, which means always get the relevant part of the data.
In the onTableChange function I query the server and update the state proprety: "results" from which the table data is made.
Remote pagination worked great and easly for me but for some time I'm stuck with the sorting. After i click on header to sort the server returns sorted results and the table updates accordingly. However the carets at the header dont change. The problem is that i can only sort by descending order because everytime i update the results from the server the sorting "resets". 
When i tried to not update the data(just calling the handler function and print) it works just fine. It must be something about the data update.

Please help me by explaining me what i did wrong, or by fixing this.

**Comment by AllenFang** [comment]
@eylonronen I think it might be a bug probably, I will check this out and get back to you ASAP. thanks!!

**Comment by AllenFang** [comment]
@eylonronen hello, the remote pagination/sorting is work for me, following is my test code:

```js

const RemoteAll = ({ data, page, sizePerPage, onTableChange, totalSize }) => (
  <div>
    <h3>When <code>remote.pagination</code> is enabled, the filtering,
      sorting and searching will also change to remote mode automatically</h3>
    <BootstrapTable
      remote
      keyField="id"
      data={ data }
      columns={ columns }
      pagination={ paginationFactory({ page, sizePerPage, totalSize }) }
      onTableChange={ onTableChange }
    />
    <Code>{ sourceCode }</Code>
  </div>
);

RemoteAll.propTypes = {
  data: PropTypes.array.isRequired,
  page: PropTypes.number.isRequired,
  totalSize: PropTypes.number.isRequired,
  sizePerPage: PropTypes.number.isRequired,
  onTableChange: PropTypes.func.isRequired
};

class Container extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      page: 1,
      data: products.slice(0, 10),
      totalSize: products.length,
      sizePerPage: 10
    };
    this.handleTableChange = this.handleTableChange.bind(this);
  }

  handleTableChange = (type, { page, sizePerPage, sortField, sortOrder }) => {
    const currentIndex = (page - 1) * sizePerPage;
    setTimeout(() => {
      let result;
      // handle sorting 
      if (sortOrder === 'asc') {
        result = products.sort((a, b) => {
          if (a[sortField] > b[sortField]) {
            return 1;
          } else if (b[sortField] > a[sortField]) {
            return -1;
          }
          return 0;
        });
      } else {
        result = products.sort((a, b) => {
          if (a[sortField] > b[sortField]) {
            return -1;
          } else if (b[sortField] > a[sortField]) {
            return 1;
          }
          return 0;
        });
      }
      this.setState(() => ({
        page,
        data: result.slice(currentIndex, currentIndex + sizePerPage),
        totalSize: result.length,
        sizePerPage
      }));
    }, 2000);
  }

  render() {
    const { data, sizePerPage, page } = this.state;
    return (
      <RemoteAll
        data={ data }
        page={ page }
        sizePerPage={ sizePerPage }
        totalSize={ this.state.totalSize }
        onTableChange={ this.handleTableChange }
      />
    );
  }
}
```

I just use `setTimeout` to simulate a api call delay. Did I missing something? or maybe you can show your code, thanks

**Comment by AllenFang** [comment]
BTW, do you use `react-bootstrap-table2-overlay`?

**Comment by AllenFang** [comment]
@eylonronen I see, thank you.

There's a few question is do you unmount the table when fetching API then render table again when you get the response?

Right now, I dont have too much time to write a api to handle this, but just like a lots of open source or even legacy `react-bootstrap-table`, they usually use a async operation to simulate a delay for api call. So I believe there's not critical issues for remote sort and pagination.

**Comment by eylonronen** [comment]
I found my bug!
I checked what you said about unmounting the table and you were right.
Instead of using react-bootstrap-table2-overlay i used a custom loading component and rendered it instead of the table...
Thank you very much for the help.
Now all thats left is expandable rows like react-bootstrap-table and this will be the perfect table component

**Comment by AllenFang** [comment]
@eylonronen nice catch 👍 👍 . BTW, I will suggest you do not use `react-bootstrap-table2-overlay` right now, there's a critical bug still not solved yet.
