### ISSUE TITLE
Can't edit cell - TypeError: "x" is read-only

### ISSUE THREAD

**Issue by ac2-warp** [react-bootstrap-table/react-bootstrap-table2#386]
When editing a cell it returns the following error:

Firefox - TypeError: "x" is read-only
Chrome - Cannot assign to read only property 'x' of object '#<Object>' 

Where x is the dataField of the table. 

I have reduced table to bare minimum with no luck. The tables 'data' field is connected to a state value which recieves information from a GraphQL through Apollo client. I even assigned the data to a seperate var but still throwing error. 

When I create a dummy var array in the render it works fine. 

**ERROR:**
Uncaught TypeError: Cannot assign to read only property 'quantity' of object '#<Object>'
    at utils.js:42
    at Array.reduce (<anonymous>)
    at Object.set (utils.js:33)
    at Store.edit (index.js:41)
    at CellEditWrapper.handleCellUpdate (wrapper.js:105)
    at EditingCell.beforeComplete (editing-cell.js:149)
    at EditingCell.handleKeyDown (editing-cell.js:174)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at Object.invokeGuardedCallback (react-dom.development.js:187)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:201)

**Code**
![image](https://user-images.githubusercontent.com/30796009/41797465-69d14a64-766a-11e8-9751-1b078e30b6be.png)

**Comment by AllenFang** [comment]
> I even assigned the data to a seperate var but still throwing error.

yes, correct, you probably need a deeply copy might be work.

And also make sure the `data` props is JavaScript Array and every row object is plan object.

**Comment by ac2-warp** [comment]
Thanks Allen. If I declare the array as [] first then assign it to the apollo data it works fine. Thanks for your prompt response and your work on this great component.

**Comment by ac2-warp** [comment]
Thanks Allen. I copied the receiving Apollo data using JSON.parse(JSON.stringify(this.props.fetchData)) and assigned it to the table and it's working now. Thanks for your prompt response and keep up the good work.

**Comment by obaid-the-dev** [comment]
> Thanks Allen. I copied the receiving Apollo data using JSON.parse(JSON.stringify(this.props.fetchData)) and assigned it to the table and it's working now. Thanks for your prompt response and keep up the good work.

sir still not working for me

**Comment by obaid-the-dev** [comment]
> Thanks Allen. I copied the receiving Apollo data using JSON.parse(JSON.stringify(this.props.fetchData)) and assigned it to the table and it's working now. Thanks for your prompt response and keep up the good work.

i am fetching the data from api then i am using redux slice to store the data and the pasing the data to the table through props i am passig the data to table
