### ISSUE TITLE
react-bootstrap-table2-paginator not working.

### ISSUE THREAD

**Issue by Sweravi** [react-bootstrap-table/react-bootstrap-table2#387]
Hello,

I get the below error when I try to add pagination functionality to the bootstrap table. Here's what I have - 

```
import * as React from 'react';
import { Component } from 'react';
import BootstrapTable from "react-bootstrap-table-next";
import paginationFactory from 'react-bootstrap-table2-paginator';

export class Queues extends Component<{}, IQueueState> {
	constructor() {
		super({});
		this.state = {
			queues: [{
					"id": "1",
					"name": "Book",
					"price": "18"
				},
				{
					"id": "2",
					"name": "Mobile",
					"price": "400"
				}], loading: true
		};
	}

	public render() {
		const columns = [
			{
				dataField: 'id',
				text: 'Product ID'
			},
			{
				dataField: 'name',
				text: 'Product Name'
			}, {
				dataField: 'price',
				text: 'Product Price'
			}
		];
		return <div>
			       <h2>With Pagination </h2>
			       
                               <BootstrapTable keyField='id'
			                       data={this.state.queues}
			                       columns={columns}
			                       pagination={paginationFactory()} />

		       </div>;
	}

```
And the dependencies that I have currently  - 
```
		"react": "^16.4.1",
		"react-bootstrap-table-next": "^0.1.12",
		"react-bootstrap-table2-paginator": "^0.1.4",
		"react-dom": "^16.4.1"
```

Without pagination property the table renders properly but I get the below error when I add paginator -
```
Uncaught Error: n.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
    at e.exports (vendor.js?v=gWN0dwqp0_yY627VZPL5GJPbGaLm6i9oU_upMHr2BP4:1)
    at l._renderValidatedComponent (vendor.js?v=gWN0dwqp0_yY627VZPL5GJPbGaLm6i9oU_upMHr2BP4:58)
    at l.performInitialMount (vendor.js?v=gWN0dwqp0_yY627VZPL5GJPbGaLm6i9oU_upMHr2BP4:58)
```

Any help here is much appreciated!

**Comment by AllenFang** [comment]
@Sweravi would you please help me to check if there are multiple React was install in your `node_modules`?  thanks

**Comment by AllenFang** [comment]
You can check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example, it work well.

**Comment by Sweravi** [comment]
That's the exact example I have followed. Also I have just one version of react which is `16.4.1`

**Comment by AllenFang** [comment]
Oh, I notice you use typescript?  is it possible to downgrade to `react@16.0.0` and try it again, although I can't believe the problem is about react version lol

**Comment by Genarito** [comment]
I had the same issue, I installed React and React-Dom in their 16.4.1 version and updated dependencies and all worked:

```
npm i react@16.4.1 --save
npm i react-dom@16.4.1 --save
npm update
```

**Comment by Manishku99251** [comment]
@Genarito updating dependencies worked like a charm  Thanks for the fix appreciate it.
