### ISSUE TITLE
custom filter support

### ISSUE THREAD

**Issue by flc** [react-bootstrap-table/react-bootstrap-table2#388]
Hi, similar to the way a custom editor is supported with `editorRenderer`, a custom filter support would also be great. For example to utilize the functionality from https://github.com/JedWatson/react-select

**Comment by AllenFang** [comment]
@flc sure, we will support it :)

**Comment by AllenFang** [comment]
@flc 

@jeznag 

[RELEASE NOTES](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/06/24/version-bump.html)

Support on `react-bootstrap-table-next@0.1.14` and `react-bootstrap-table2-filter@0.3.0`

[demo1](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Custom%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and [demo2](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Advance%20Custom%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) will be a quick example to learn.  In addition, you can also check [docs1](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/filter-props.html#customFilter) and [docs2](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-filter.html#custom-filter)

Please open another issue if you find any bugs, thank you 👍
