### ISSUE TITLE
dataField should have an option for value and label.

### ISSUE THREAD

**Issue by narayanchoudhary** [react-bootstrap-table/react-bootstrap-table2#391]
Basically I have data object like this
`{
     _id: 'k4ri89rieo09d8d',
    item: '10',
    rack: '1',
    party_id: '2e3wert45uyb4d', 
}`

Now in the  table I want to show this data but instead of party_id I want to show the name of the party. I managed to replace the party_id with name  of the party in above object. 
Now the problem is that when the party cell is edited it saves the name of the party instead of the id.
Is it possible to give the  dataField an object of value and label  so that it show the label in the table and when edited it saves the value.
Thanks

**Comment by AllenFang** [comment]
@narayanchoudhary I believe [`formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) is the thing you are looking for.

You can keep to use `party_id` but use `formatter` to show the part name certainly on the cell.
