### ISSUE TITLE
Preventing unnecessary (row / cell) re-renders

### ISSUE THREAD

**Issue by renekliment** [react-bootstrap-table/react-bootstrap-table2#392]
Hi!
First, thank you for this nice library.

I am having a performance issue however, because it seems that there are no checks to prevent unnecessary re-renders (`shouldComponentUpdate`).

I had to implement row hover myself (via row `onMouseEnter`), because I need a callback for the hovered point id and the hovered point id can also come from another component and I need to set it on the right row, which I do via `rowClasses`. The `onMouseEnter` changes the redux state, and I get the hovered point id back, which re-renders the component.

Could there be some smart `shouldComponentUpdate` implemented on the rows?

**Comment by AllenFang** [comment]
@renekliment sure, I will do it 👍

**Comment by AllenFang** [comment]
@renekliment yes, sometime I'm busy but any discuss or PR is welcome :)

**Comment by AllenFang** [comment]
Please upgrade to `react-bootstrap-table-next@1.3.0` and `react-bootstrap-table2-editor@1.2.0` will get significant improvement.
