### ISSUE TITLE
Assign object {row} to state

### ISSUE THREAD

**Issue by denys-correia** [react-bootstrap-table/react-bootstrap-table2#393]
I'm trying to migrate my application which currently uses react-bootstrap-table to react-bootstrap-table-next but I'm having a problem.

**What I am trying to do:**
is to get the object of the selected line.

**My code**
```
const selectRow = {
        mode: 'radio',
        hideSelectColumn: true,
        clickToSelect: true,
        bgColor: 'red',
        onSelect: (row) => {
           console.log(row)
          }
      };

<div className="col-lg-12">
                             <BootstrapTable keyField='id' data={ products } columns={ columns } selectRow={ selectRow }   />
                        </div>
```
**result obtained**
When I click on the line, it assigns the color red and prints the object to the selected line

but when I try to put the object in the state:

```
const selectRow = {
        mode: 'radio',
        hideSelectColumn: true,
        clickToSelect: true,
        bgColor: 'red',
        onSelect: (row) => {
           console.log(row)
           this.setState({banco: row});
          }
      };
```
The selected line object is assigned to {banco} property as expected, but the line does not turn red.

**Comment by AllenFang** [comment]
Sorry for lately fixed.....
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/11/04/version.bump.html)

now you can call `setState` in `selectRow.onSelect` and we support a feature that you can reject the selection, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowonselect-function) and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Advance%20Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is example
