### ISSUE TITLE
Is there way to set class for header row?

### ISSUE THREAD

**Issue by Crescent9723** [react-bootstrap-table/react-bootstrap-table2#394]
I want to set custom class of header row and cannot find any documentation about this

Could anyone give me some information on this?

**Comment by AllenFang** [comment]
@Crescent9723 I will support it soon, thanks :)

**Comment by Crescent9723** [comment]
Thank you!

**Comment by AllenFang** [comment]
@Crescent9723 use this: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#headerClasses-string

[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/), please reopen this issue if the problem still remain, thanks

**Comment by Crescent9723** [comment]
Thank you! Working as expected

**Comment by AllenFang** [comment]
👍
