### ISSUE TITLE
 Radio mode does not work

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#395]
Good afternoon,
I am having some problems migrating from react-bootstrap-table to react-bootstrap-table-next.

When I use the radio option, select only one line. does not work.
Follow the repository with a simulation.

https://github.com/Denis-String/React-Table-Next

If I am doing something wrong, I apologize, but I am trying to follow the examples in the documentation.

**What I want**

When I click on a row, the other one is unmarked and puts the value of the row clicked on the state, I need to get the object not the row ID

**Comment by Flo-Slv** [comment]
Hey @Denis-String  
I have the same problem, have you find the solution?

When i click on a row, all row are selected with 'radio'...+

Thanks!

**Comment by Denis-String** [comment]
I think so, I need to validate if it is a solution or an adaptation.

You need to change the `this.handleOnSelect`

```
    handleOnSelect = (row, isSelect) => {
         const car = row;
        this.setState(() => ({
            selected: [row.id],
            car: car
        }));
    }
```

My Code:
```
        this.state = {
            selected: '',
            car: ''
        }
```

```
    handleOnSelect = (row, isSelect) => {
        var car = row;
        this.setState(() => ({
            selected: [row.id],
            car: car
        }));
    }
```
```
  const columns = [{
            dataField: 'id',
            text: 'id'
        }, {
            dataField: 'nome',
            text: 'Nome:'
        }
        ];
```
```
       const selectRow = {
            mode: 'radio',
            clickToSelect: true,
            selected: this.state.selected,
            onSelect: this.handleOnSelect,
            hideSelectColumn: true,
            bgColor: "#26a69965"
        };
```

` <BootstrapTable keyField='id' data={products} columns={columns} selectRow={selectRow} />`
