### ISSUE TITLE
action Button inside cell

### ISSUE THREAD

**Issue by balabukha** [react-bootstrap-table/react-bootstrap-table2#396]
Hi all!
It would be greate to add an action cb function inti ceils.
on the documentation now it's not available.

any ideas?

**Comment by AllenFang** [comment]
@balabukha I think you can use `column.formatter`, check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function)

You can custom the cell by `formatter`, thanks.

Please reopen this issue if you feel this is not helpful, thanks

**Comment by cnyyk** [comment]
action button group will cause wrapper div.bootstrap-table vertical and horizontal scroll.
