### ISSUE TITLE
 Vertical Rotation

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#397]
Using the `react-bootstrap-table` table, I could determine the size of the table by following the example
`<BootstrapTable version='4' height='400'>`

Is there any way to do this using the `react-bootstrap-table-next`

Or maybe you would have the option to scroll using` bootstrap-table-next`

as there was in the previous version follows example:
`<BootstrapTable scrollTop={'Top'}>`

If the new `react-boostrap-table-next` component does not have this functionality, would you have any tips on how I could do this?

**Comment by AllenFang** [comment]
hello @Denis-String sorry for lately reply. I think right now user can use [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#wrapperclasses-string) to add some class which have following styles:

```css
height: 200px;
overflow-y: scroll;
```

but in the `react-bootstrap-table-next`, we dont support the vertical scroll on the table body. so it will look like different with legacy table.

it's an open issue and you can do any style tweak by yourself.  However, after I recover all the legacy functionality, I will consider to implement this.

**Comment by Denis-String** [comment]
Using RowStyle causes it to decrease or increase the size of the rows, but I would need to resize the table itself.

**Comment by Denis-String** [comment]
Sorry, my fault. His tip worked perfectly. But not with the syntax presented in the documentation.

```
Failed to compile
./src/financeiro/FinanceiroLancamento.js
Syntax error: D:/Denis/Nova pasta/src/financeiro/FinanceiroLancamento.js: Unexpected token, expected , (32:155)

  30 |                         <BootstrapTable
  31 |                             noDataIndication="Nenhum registro encontrado"
> 32 |                             striped keyField='id' data={this.props.data} columns={this.props.columns} selectRow={this.props.selectRow} rowStyle={ {overflow-y:'scroll' } }/>
     |                                                                                                                                                            ^
  33 |                     </div>
  34 |                 </div>
  35 |             </div>

```

So I put it in a CSS file and it worked.

  ```
  .Table{
      height: 400px;       /* Just for the demo          */
      overflow-y: auto;    /* Trigger vertical scroll    */
      overflow-x: hidden;  /* Hide the horizontal scroll */
    }
```
Many thanks for the guidance

**Comment by AllenFang** [comment]
@Denis-String very nice sharing, Thanks a lots :)

**Comment by rahulgupta020** [comment]
> Sorry, my fault. His tip worked perfectly. But not with the syntax presented in the documentation.
> 
> ```
> Failed to compile
> ./src/financeiro/FinanceiroLancamento.js
> Syntax error: D:/Denis/Nova pasta/src/financeiro/FinanceiroLancamento.js: Unexpected token, expected , (32:155)
> 
>   30 |                         <BootstrapTable
>   31 |                             noDataIndication="Nenhum registro encontrado"
> > 32 |                             striped keyField='id' data={this.props.data} columns={this.props.columns} selectRow={this.props.selectRow} rowStyle={ {overflow-y:'scroll' } }/>
>      |                                                                                                                                                            ^
>   33 |                     </div>
>   34 |                 </div>
>   35 |             </div>
> ```
> 
> So I put it in a CSS file and it worked.
> 
> ```
> .Table{
>     height: 400px;       /* Just for the demo          */
>     overflow-y: auto;    /* Trigger vertical scroll    */
>     overflow-x: hidden;  /* Hide the horizontal scroll */
>   }
> ```
> 
> Many thanks for the guidance

How to link with css???
