### ISSUE TITLE
Can columns be grouped?

### ISSUE THREAD

**Issue by devTomek** [react-bootstrap-table/react-bootstrap-table2#398]
Can I do this with columns in  react-bootstrap-table2?
![grouped](https://user-images.githubusercontent.com/19184623/42382870-d5503f40-8135-11e8-9d8e-f2534a8ef7c0.PNG)

**Comment by AllenFang** [comment]
@devTomek we are not support this feature yet.

**Comment by AllenFang** [comment]
duplicated with https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/342
