### ISSUE TITLE
UMD version doesn't work in browser

### ISSUE THREAD

**Issue by Ignalion** [react-bootstrap-table/react-bootstrap-table2#399]
As for now, old version of the package works correctly as just CDN in browser (i.e. there's BootstrapTable in window)
The 2nd version provides only ReactBootstrapTable2 namespace which has only BootstrapTableContainer in default parameter.

Can I use the react-bootstrap-table2 w\o webpack just as inline script in <script> tag in html? At least I didn't find any mention in migration doc for now.

Thanks in advance

**Comment by AllenFang** [comment]
@Ignalion I think [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html#umd) docs can help you. Please let me know if it's not helpful to you and reopen this issue. thank!
