### ISSUE TITLE
Functionality for adding in components/icons in cells

### ISSUE THREAD

**Issue by dakotamaker** [react-bootstrap-table/react-bootstrap-table2#400]
Hello there, 

While working with version 0.1.14 I was trying to add in a checkmark into my cell rather than a data value, however when trying to do so I found that these tables don't support rendering a React Component inside the data object.

I did ask a [Stackoverflow question first](https://stackoverflow.com/questions/51255987/putting-a-react-component-or-element-in-an-object/51256201#51256201) to see if there were any answers, but nothing came to fruiting. I also have a stackblitz for reference, [right here ](https://stackblitz.com/edit/react-table-problem?file=index.js)

**Comment by AllenFang** [comment]
I think [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) can help you. there's a online demo: [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Let me know if above docs is not helpful to you and feel free to reopen this issue again, thanks
