### ISSUE TITLE
I don't have border on react-bootstrap-table-next

### ISSUE THREAD

**Issue by tesicg** [react-bootstrap-table/react-bootstrap-table2#401]
Here's my issue:

https://stackoverflow.com/questions/51257468/i-dont-have-border-on-react-bootstrap-table-next

**Comment by AllenFang** [comment]
@tesicg please add bootstrap css firstly. https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html

**Comment by tesicg** [comment]
As you can see from the code I've exposed, I'd added bootstrap CSS firstly.

**Comment by pranaytanniru** [comment]
did you find the solution to this problem,?
I have added the bootstrap css link but I can't see any borders.
