### ISSUE TITLE
 Contents of the leaving table

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#405]
Good afternoon, I do not know if this is a BUG, ​​or my mistake. But the table content is coming out:
https://ibb.co/mkMcE8

My code:
```
<BootstrapTable
                            noDataIndication="x"
                            striped keyField='id' data={this.props.data} columns={this.props.columns} selectRow={this.props.selectRow}/>
```

**Comment by AllenFang** [comment]
@Denis-String  i think you can tweak the css style to avoid the text overflow. By default, we dont do anything for style on cell and row.
