### ISSUE TITLE
afterSaveCell callback: "props.data"/"state.data" didn't update when editing at the first time

### ISSUE THREAD

**Issue by hectorguo** [react-bootstrap-table/react-bootstrap-table2#406]
There is a weird issue. I am not sure if it is related to this component or React framework itself. 

When I try to update the state after the table has been edited, the state will not be updated in the first time.

Code sample like below:
```js
import BootstrapTable from 'react-bootstrap-table-next';
import cellEditFactory from 'react-bootstrap-table2-editor';

class TestTable extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      data: [{
        id: 1,
        name: 'A'
      }],
      columns: [{
        dataField: 'id',
        text: 'Product ID'
      }, {
        dataField: 'name',
        text: 'Product Name'
      }]
  };

  this.handleChange = this.handleChange.bind(this);
}

render() {
  return <BootstrapTable
    keyField="id"
    data={this.state.data}
    columns={this.state.columns}
    cellEdit={cellEditFactory({ mode: 'click', blurToSave: true, afterSaveCell: this.handleChange })}
  />
}

handleChange(oldValue, newValue, row, column) {
  // edit "name" at the first time, "this.state.data" isn't updated!!!
  console.log(this.state.data);  // still shows the initial data - [{id: 1, name: 'A'}]
  this.setState({data: this.state.data}); // trigger state change for other's use
}
}
```

See the live demo here:
[![Edit ovx9m91ypz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ovx9m91ypz)

Please let me know if it is the correct way to update state for table editing. Tks!

**Comment by AllenFang** [comment]
@hectorguo it's because `setState` is async, https://medium.com/@wereHamster/beware-react-setstate-is-asynchronous-ce87ef1a9cf3

in the `react-bootstrap-table`, we also do the `setState` for change something. 

BTW, we shouldn't change your `state.data`, it's a bug I think but not too many people encounter. Your state should be immutable. 

I will enhance it if I have time.

**Comment by AllenFang** [comment]
BTW, could you tell me what you want to do after editing cell. thanks

**Comment by hectorguo** [comment]
@AllenFang Sometimes, I need to notify its parent component after the cell has been changed. For example, I need to show these table's data in another view.
Since there is no callback func that can let me know whether the state updating is done or not, I have to manually pass the updated data like below.
```js
handleChange(oldValue, newValue, row, column) {
  const updatedData = this.state.data.map(item => {
          // pass the updated row instead of original row in state
          if(item.id === row.id) {
              return row;
          }
          return item;
 });
  this.props.onCellChange && this.props.onCellChange(updatedData);
}
```

Please let me know if there are better solutions than this.
Tks!

**Comment by AllenFang** [comment]
@hectorguo I see, I will do some enhancement on it. Thank you

**Comment by AllenFang** [comment]
@hectorguo 

```js
class Table extends React.Component {
  state = { dummyStatus: 1, products }
  render() {
    /* eslint no-plusplus: 0 */
    console.log(this.state.dummyStatus);
    console.log(this.state.products);
    return (
      <div>
        <BootstrapTable
          keyField="id"
          data={ this.state.products }
          columns={ columns }
          cellEdit={ cellEditFactory({
            mode: 'click',
            afterSaveCell: (oldValue, newValue, row, column) => {
              this.setState({ dummyStatus: ++this.state.dummyStatus });
              console.log(this.state.products);   // the state is actually change here!
            }
          }) }
        />
        <Code>{ sourceCode }</Code>
      </div>
    );
  }
}
```

@hectorguo I think use `afterSaveCell` is ok for your case. Above is an example for me to check if the state already changed after cell saving. I think it's already changed. So please reopen this issue if the problems still remain. BTW, please upgrade to newest version. thanks
