### ISSUE TITLE
When clickToSelect and clickToEdit are true, and select mode is "checkbox", double click to edit will also change the row selection state.

### ISSUE THREAD

**Issue by cbfrank** [react-bootstrap-table/react-bootstrap-table2#421]
Hello
When user double click to edit a cell, the row will also be selected/unselected.
Maybe when uer editing a cell, the table selection should be clear (trigger a onSelect or onSelectAll event?)
Is it possible add an opton for "before cell will be editing" which will be happend just before a cell will being editing?

Thanks

**Comment by AllenFang** [comment]
@cbfrank do you consider to use `dbclicktoEdit`? At before, I usually recommend people to use it when they enable the `clickToSelect`? How do you said?

Actually, when the user click on the cell or row, in the program, you never know what they want(edit or select?)

**Comment by cbfrank** [comment]
@AllenFang Yes, I use **dbclicktoEdit** together with **clickToSelect**, **clickToEdit** and select mode is **checkbox**.
When a row is already **selected**, and user **double click** on a cell, in this case, I think the user do want to just start edit the cell, and yes, the cell is changed to editing mode with the editor is shown, but in additional to this, the **selected** row becomes **unselected**, it is a little strange when user trying to edit a cell while the row becomes **unselected**.

**Comment by AllenFang** [comment]
@cbfrank sorry for lately reply, [there](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Click%20to%20Select%20and%20Edit%20Cell&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example for click to select or edit.

if you enable `dbclick`, try:

```js
<BootstrapTable
      keyField="id"
      data={ products }
      columns={ columns }
      selectRow={ {
         mode: 'checkbox',
         clickToSelect: true,
         clickToEdit: true
       } }
      cellEdit={ cellEditFactory({ mode: 'dbclick' }) }
    />
```

Please reopen this issue if your problem still remain, thanks :)
