### ISSUE TITLE
Adding CSS Styles to pagination buttons

### ISSUE THREAD

**Issue by chaserda** [react-bootstrap-table/react-bootstrap-table2#424]
Is there not a way to add styles to the pagination buttons? Would like to have the background transparent with no hover change and different text color.

**Comment by chaserda** [comment]
Please close. Found under `.pagination>li>a, .pagination>li>span`

**Comment by AllenFang** [comment]
👍

**Comment by casha1995** [comment]
this will change the whole react-table-bootstrap css what if if you want to change it with #id
