### ISSUE TITLE
Calling an onClick event handler from inside a cell formatter. 

### ISSUE THREAD

**Issue by dpramani** [react-bootstrap-table/react-bootstrap-table2#426]
Hi @AllenFang 

![screen shot 2018-07-18 at 11 09 19 am](https://user-images.githubusercontent.com/26373096/42911640-1850539e-8aa9-11e8-9fb5-1787dadea36e.png)

I am using the react bootstrap table version 2 for one of my projects, where I faced a problem. 
I will present a screenshot of my code section which I have problem with. 
Basically, I have a settings icon inside one of my cells, which needs to be handled. 
My problem is I cannot call an external event handler from inside the formatter function. 
Can u please help me in this ?
FYI :
I have tried some of the solutions present on the web, but didn't work for me. 
In the screenshot, pulseName is the formatter function and handleSettings is the external handler that 
I want to trigger on a onClick event. 
I have no errors in my console.

Thanks
By the way, you guys did a wonderful job with the table.

**Comment by AllenFang** [comment]
hey, i"m a little confuse on ur issue
Firstly, `handleSettings` and `pulseName`, both method is in the same class?
Secondly, You mean when u click on icon, `handleSettings` method(At the above of `pulseName`) is never get called

Third, do u enable the row selection or cell edit.

BTW, could you please share full code? thanks

**Comment by dpramani** [comment]
Yes both the methods are in the same class.  
I will share the full code with you. 
In the UI I have a settings icon that will pop up a modal on click. So I need a handler for onClick function. 
And I didn't enable row selection or cell edit.

Thanks Allen.

https://docs.google.com/document/d/1ywkiBxCAc2Te6VI0WHhMtkB-Xrmker9DFir0MmhyA0U/edit

**Comment by dpramani** [comment]
@AllenFang thanks. Its solved  we can close it now. I will share a screen shot of the working code. 

<img width="1164" alt="screen shot 2018-07-19 at 12 09 41 pm" src="https://user-images.githubusercontent.com/26373096/42961731-ea719a38-8b4c-11e8-8d1e-8d9a0cc7017e.png">

Along with this, I kept the handlers just before this.state inside the constructor. 
Thanks.

**Comment by saif55582** [comment]
> @AllenFang thanks. Its solved we can close it now. I will share a screen shot of the working code.
> 
> <img alt="screen shot 2018-07-19 at 12 09 41 pm" width="1164" src="https://user-images.githubusercontent.com/26373096/42961731-ea719a38-8b4c-11e8-8d1e-8d9a0cc7017e.png">
> 
> Along with this, I kept the handlers just before this.state inside the constructor.
> Thanks.

Can you explain the solution a bit more? Thanks
