### ISSUE TITLE
Is there any way to add Badge to a table row?

### ISSUE THREAD

**Issue by pashazz** [react-bootstrap-table/react-bootstrap-table2#434]
For example, to indicate new unseen items.

**Comment by AllenFang** [comment]
@pashazz can I know where's the badge you want to add? one of column, a specify column in the last?

**Comment by pashazz** [comment]
I want to add it at the end of specified column's text

**Comment by michaelwschultz** [comment]
@pashazz you could use the formatter to add an indicator or "badge" right after the text in a specific column.

```
// example column
{
  dataField: 'status',
  text: 'Status',
  formatter: this.formatStatus,
  sort: true
}

// example format function
// imagine this.state.viewed is an array of all the row id's a user has already seen
// in the render; check to see if the current row id is included in the array
// if it isn't, attach the badge
formatStatus(status, row) {
  const { viewed } = this.state

  return (
    <div>
      <span>{status}</span>
      {!viewed.includes(row.id) && <span className='badge'>🔵</span>}
    </div>
  )
}
```

This example doesn't include how to then update state after the user has seen a particular row. But hopefully this is the part you were looking for.

**Comment by AllenFang** [comment]
Good answer by @michaelwschultz 
@pashazz please reopen this issue if you feel above solution is not helpful to u.

Thanks
