### ISSUE TITLE
Can icons be added to table row column value?

### ISSUE THREAD

**Issue by cnav007** [react-bootstrap-table/react-bootstrap-table2#435]
I've been scouring the documentation but I'm still not certain this is feasible, but can an icon be specified in the table data / columns such that I can render generic icons controls along with my normal row text, e.g. trash-o, exclamation-triangle etc?

**Comment by AllenFang** [comment]
@Josh123321 's answer is correct. https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function

**Comment by cnav007** [comment]
thanks guys!

**Comment by lilfrootyloops** [comment]
Is it possible to render icons inside column cells without having any other corresponding text that's coming from the data source? I'm just trying to make a column of right-facing arrows at the end of each row.
