### ISSUE TITLE
The table gets slow or may even fail on large datasets

### ISSUE THREAD

**Issue by peter-sl** [react-bootstrap-table/react-bootstrap-table2#437]
Hi,
The table gets progressively slower when displaying large data and at certain data size it fails with an exception. The reason is the deep copy solution that you use in `src/store/index.js` at line 80:
`JSON.parse(JSON.stringify(data))`
Please consider changing this to a more optimal solution, like `[...data]` for example.

Cheers,
Petar

**Comment by AllenFang** [comment]
after `react-bootstrap-table-next@1.1.1`, we improve the cell level performance. In the next couple release, we will start improve the row level performance enhancement. Just give me some time. thanks

**Comment by AllenFang** [comment]
BTW, after `1.0.0`. We fix `JSON.parse(JSON.stringify(data))`. So closed this issue

**Comment by AllenFang** [comment]
Please upgrade to `react-bootstrap-table-next@1.3.0` and `react-bootstrap-table2-editor@1.2.0` will get significant improvement.

**Comment by F-Adam-B** [comment]
I'm as well using a large data set and running into sluggish rendering issues. @AllenFang will the upgrade to react-bootstrap-table-next@1.3.0 and `react-bootstrap-table2-editor@1.2.0` be able to handle a table with 27 columns with 13000 to 15000 values in each column?

**Comment by imtmh** [comment]
I have a similar scenario like @F-Adam-B , 30+ columns with 5000- 10000 rows. (It includes ExpandedArea too), It's taking around 30+ sec to render. Any help?

**Comment by Pragatigg** [comment]
@F-Adam-B I am also facing same problem, around 40 columns and 100 rows  leads to page slows down. Pagination takes time to respond. Any help?

**Comment by eklavya-raj** [comment]
its still very slow when rendering 10000 items
