### ISSUE TITLE
custom filter function

### ISSUE THREAD

**Issue by narayanchoudhary** [react-bootstrap-table/react-bootstrap-table2#445]
Basically I want to add custom filter logic. Something like below.

columns = {[ ...,
    { dataField: 'name',
    text: 'Product Name',
    filter: textFilter(),
    **customOnFilterCallback**: (column, value) = {
        // filteredColumn = custom filter logic on column data
        return filteredColumn;
    }];
};

**Comment by AllenFang** [comment]
Hello, @narayanchoudhary 

Right now the only workaround is you have to enable the remote on filters

[this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-remote.html) is a quick introduction for remote mode, and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is a remote filtering example.

However, I think I will consider to implement a `onFilter` function just like your idea in near future.

Thanks

**Comment by AllenFang** [comment]
Thanks @narayanchoudhary I also open to accept the donate. However, I'm in Taiwan, but it's not easy to connect paypal with local bank... lol

**Comment by narayanchoudhary** [comment]
Hi @AllenFang 
Currently, The onFilter function filter the columns by like query. I want to use https://github.com/farzher/fuzzysort algorythm. Please check it out.
Thanks

**Comment by AllenFang** [comment]
Fixed, please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/09/version-bump.html)

Check [EXAMPLE](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Implement%20custom%20filter%20logic&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by rudra-sena** [comment]
> 

Hi @AllenFang @narayanchoudhary 
I am a beginner and I am not able to figure how to define a custom filter function for my column?? (how to use onFilter() )
Also, @narayanchoudhary if you have implemented fuzzysort as a filter function can you please share how to do that?
