### ISSUE TITLE
wrapperFactory is not a function

### ISSUE THREAD

**Issue by ali-master** [react-bootstrap-table/react-bootstrap-table2#450]
Hi,

Thank you for developing this library.
I have a problem with that.
When I use the paginationFactory function, that will return the following errors.
![screen shot 2018-08-05 at 1 34 11 pm](https://user-images.githubusercontent.com/9049092/43684400-88543e26-98b4-11e8-8303-bbce1d4f13ca.png)

react-bootstrap-table-next": 1.0.0
react-bootstrap-table2-overlay": 1.0.0
react-bootstrap-table2-paginator": 1.0.0

My config:
![screen shot 2018-08-05 at 1 39 17 pm](https://user-images.githubusercontent.com/9049092/43684425-fd57fc26-98b4-11e8-9d82-afa97547e71a.png)

Please help me.
Thank you in advance.

**Comment by AllenFang** [comment]
@ali-master hello, seems like you use newest releases, what's the version of you React.js ?

**Comment by AllenFang** [comment]
BTW, there's not more `container.js` in `1.0.0`, are u sure you upgrade successfully for `react-bootstrap-table-next`?

**Comment by ali-master** [comment]
Hi @AllenFang,

Yes, I'm sure using the latest version.
![screen shot 2018-08-06 at 12 03 04 pm](https://user-images.githubusercontent.com/9049092/43703011-c86b2062-9970-11e8-8140-531f44c3c74e.png)

**Comment by AllenFang** [comment]
@ali-master yes i understand, but the error message show that `react-bootstrap-table-next` may stay in the legacy version. Could you please remove the `node_modules` and run install again? thanks

**Comment by ali-master** [comment]
Great job.

That's helped me, thanks
The problem was fixed.

**Comment by AllenFang** [comment]
@ali-master Cooool 👍

**Comment by maxvia87** [comment]
Hello, I am getting the same error with the filterFactory function even though I removed " node_modules and run install again".

<img width="418" alt="screen shot 2018-08-07 at 12 37 41" src="https://user-images.githubusercontent.com/34567125/43771212-bf130f4c-9a3e-11e8-881e-74efe197f307.png">

Any idea how I could fix that?

Thank you in advance
<img width="541" alt="screen shot 2018-08-07 at 12 17 55" src="https://user-images.githubusercontent.com/34567125/43771247-dfcf23c4-9a3e-11e8-960a-864122d2f808.png">

**Comment by ali-master** [comment]
Would you share your written code about the table config?

**Comment by maxvia87** [comment]
Of course! You mean the Boostrap-table?

Here it is:

`
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import Routes from './routes';
//import App from './components/landingPage';
import {
  graphql,
  ApolloProvider,
  createNetworkInterface
} from 'react-apollo';
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';
import { ApolloClient } from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory';
import gql from 'graphql-tag';
import BootstrapTable from 'react-bootstrap-table-next';
import filterFactory, { dateFilter } from 'react-bootstrap-table2-filter';



const httpLink = new HttpLink({
  uri: "graphql#execute"
});

let tableQuery = gql`{
  allBookingHotelRooms{
    id
    gettingBookingDate
    gettingHotel
    gettingRoomCategory
    gettingAvailabilityPrice
    gettingNRoomsAvailable
  }
}
`

const cache = new InMemoryCache();

const client = new ApolloClient({
  link: httpLink,
  cache,
});


class App2 extends Component {

  state = {
    products: [],
    columns: [{
      dataField: 'gettingBookingDate',
      text: 'Booking Date',
      //filter: dateFilter()
    },
    {  dataField: 'gettingHotel',
      text: 'Hotel',
    },
    {
      dataField: 'gettingRoomCategory',
      text: 'Room Category'
    }, {
      dataField: 'gettingAvailabilityPrice',
      text: 'Price',
    },
    {
      dataField: 'gettingNRoomsAvailable',
      text: 'Nbre # dispos'
    }
    ]
  }


  render() {
    let { data } = this.props
      if (data.loading) {
        return <div> Loading... </div>
    }

    return (
      <div className="container" style={{ marginTop: 50 }}>
        <BootstrapTable
        striped
        hover
        keyField='id'
        data={ this.props.data.allBookingHotelRooms }
        columns={ this.state.columns }
        //filter={ filterFactory() }
        />
      </div>
    );
  }
}




const TableInfoWithData = graphql(tableQuery, {options: { pollInterval: 20000 },
})(App2);



document.addEventListener('DOMContentLoaded', () => {
  ReactDOM.render(
    <ApolloProvider client={client}>
      <TableInfoWithData
      />
    </ApolloProvider>, document.getElementById('example-app'),
  )
});
`

**Comment by maxvia87** [comment]
everything is working fine until I had `filter={ filterFactory() }` to the `<BootstrapTable />` component

**Comment by maxvia87** [comment]
Hey Ali did you see anything wrong with my code? Thank you for the help anyway

**Comment by ali-master** [comment]
Hi @maxvia87,

apologies for the delay in replying.
It works for me.
<img width="624" alt="screen shot 2018-08-09 at 10 29 26 pm" src="https://user-images.githubusercontent.com/9049092/43916769-c32c2f00-9c23-11e8-8b37-b4225de4c792.png">

What's the version of your React.js?

BR.

**Comment by ali-master** [comment]
If you can, please remove your **node_module** folder and try again with **Yarn** package manager instead of **NPM** because npm has many problems like always for installing packages without caching.

**Comment by paulalcabasa** [comment]
Having the same issue, removed node_modules folder and reinstall using NPM, didnt work. reinstall using YARN , still same issue.

**Comment by ali-master** [comment]
@paulalcabasa Please prevent to duplicate reply
