### ISSUE TITLE
customComponent

### ISSUE THREAD

**Issue by Gi972** [react-bootstrap-table/react-bootstrap-table2#451]
Hello @AllenFang 

In React-bootstrap-table v1  it was possible to custom the checkbox selection row.
[selectRow: customComponent](https://allenfang.github.io/react-bootstrap-table/docs.html#customComponent)
This function is missing in the V2, it's possible to add it please?

Thank you, 
The V2 is awesome thank you for this.

Gi

**Comment by Gi972** [comment]
Sorry @AllenFang 

I just see you have already implement It!! 
so when you can just add un little example in storybook :-)

Thanks

**Comment by AllenFang** [comment]
@Gi972 yes, there's an example: [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Custom%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

👍
