### ISSUE TITLE
paginationTotalRenderer not returning correct values.

### ISSUE THREAD

**Issue by dillobird** [react-bootstrap-table/react-bootstrap-table2#453]
The `to` value passed to the paginationTotalRenderer function is incorrect.

I can reproduce this in my own code, but it's also present in the pagination example:

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Custom%20Pagination&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Specifically:

![image](https://user-images.githubusercontent.com/2361138/43739080-742bed9e-998c-11e8-9ac4-9a7dd4914a46.png)

It shows 1 to 86 when there are 87 entries. Seems like a bug.

**Comment by AllenFang** [comment]
@dillobird ok, I will fix it :) . Thanks 👍

**Comment by AllenFang** [comment]
@dillobird Fixed in `react-bootstrap-table2-paginator@1.0.1`

[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/12/version-bump.html)
