### ISSUE TITLE
debounce bug?

### ISSUE THREAD

**Issue by elmoro666** [react-bootstrap-table/react-bootstrap-table2#455]
Just noticed this in lib/src/utils.js

![image](https://user-images.githubusercontent.com/15340253/43762902-88391e2c-9a29-11e8-8778-14a2ed51b703.png)

Seems like s spelling mistake?

**Comment by AllenFang** [comment]
@elmoro666 I will fix it, thanks :)

**Comment by AllenFang** [comment]
Fixed in `react-bootstrap-table-next@1.1.0`

[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/12/version-bump.html)
