### ISSUE TITLE
Clicking anywhere on the row expands the row, can it be attached to a button inside that row ?

### ISSUE THREAD

**Issue by dpramani** [react-bootstrap-table/react-bootstrap-table2#456]
@AllenFang . Thanks for the updated feature. But currently where ever I click, the row expands , is there a way, when I will click only a button for example a get info button inside a row element, the row expands ? Thanks.

**Comment by AllenFang** [comment]
Currently, We only support click on row to expand. But you can still control the expand by yourself.  Check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Expand%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
