### ISSUE TITLE
When updating to V 1.0.0: Error `TypeError: _react2.default.createContext is not a function`

### ISSUE THREAD

**Issue by ivandurst** [react-bootstrap-table/react-bootstrap-table2#458]
I just updated to V 1.0.0 from V 0.1.15. I updated React and react-dom to 16.3. When I `npm start` I now get this error:

````TypeError: _react2.default.createContext is not a function
Object../node_modules/react-bootstrap-table-next/lib/src/contexts/bootstrap.js
node_modules/react-bootstrap-table-next/lib/src/contexts/bootstrap.js:14
  11 | 
  12 | function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
  13 | 
> 14 | var BootstrapContext = exports.BootstrapContext = _react2.default.createContext({
  15 |   bootstrap4: false
  16 | });
````

Using Create-React-App.

Was working perfectly fine before. Any thoughts?

**Comment by AllenFang** [comment]
Hello @ivandurst after `1.0.0` please upgrade to react@16.3`, when you upgrade `react-bootstrap-table-next`, you are suppose to see some warning about react version

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/#notes
