### ISSUE TITLE
 button returns line information when clicked

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#461]
Good morning, I'm trying to put a button in the column that, when clicked, returns me information from that row.

I'm trying something like:

```
 handleTagClick = (row) => {
        console.log(row);
    }
```
```
    render() {

        const addbutton = (cell, row) => {
            return (
                <Button onClick={this.handleTagClick(row)}>Ola</Button>
            )
        }
```
```
  const columns = [{
            dataField: 'id',
            text: 'ID:',
            hidden: true
        },{
            dataField: 'pessoa.nome',
            text: 'Pessoa:',
            sort: true,
            filter: textFilter()
        }, {
            text: 'Ação:',
            formatter: addbutton,
        }];
```
```
       <BootstrapTable
                                id="tableLancamento"
                                filter={filterFactory()}
                                noDataIndication="X"
                                striped keyField='id' data={data} columns={columns}
                                hover
                                rowStyle={rowStyle}
                            />
```

That way, the button appears in the column, but when clicked, does not print the console log.

As if the method was not being called.

So I removed the parameters.
Stay like this.

```
  handleTagClick = () => {
        console.log("print");
    }
```
```
     const addbutton = (cell, row) => {
            return (
                <Button onClick={this.handleTagClick}>Ola</Button>
            )
        }
```
That way, he printed the console log.

How can I put a button, which returns me line info when clicked?

**Comment by elmoro666** [comment]
Hi

It seems to me that in you first example you are executing the function in onClick:
![image](https://user-images.githubusercontent.com/15340253/43838921-03eef070-9b1d-11e8-8075-797e5aac99fa.png)

That's not going to work as it is executed immediately. You can use an arrow function for example:

<Button onClick={() => this.handleTagClick(row)}>Ola</Button>

There are two other ways of doing it to:

https://stackoverflow.com/questions/29810914/react-js-onclick-cant-pass-value-to-method

**Comment by AllenFang** [comment]
@elmoro666 Good answer.

@Denis-String Please reopen this issue if the problem still remain. thanks
