### ISSUE TITLE
How to customize the components?

### ISSUE THREAD

**Issue by Randore** [react-bootstrap-table/react-bootstrap-table2#462]
Hi,

Is there any way to customize the components - what I mean is, to customize pagination's, button placements and positions as per my design?

example: https://www.extjs-tutorial.com/live-examples/extjs4/Paging-in-Grid/default.htm

My project involves porting from ext to react with the exact match of UI.

**Comment by AllenFang** [comment]
@Randore right now the customization is limited. I will work on it ASAP but it really need some time.

**Comment by AllenFang** [comment]
@mwesthelle we have new release -> [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/12/24/version.bump.html)

Please read this [DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#customization) to learn how to custom pagination component and also check some online [DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) 

Please open a new issue if you get any questions or issues, thanks!
