### ISSUE TITLE
Search results cleared after moving cursor

### ISSUE THREAD

**Issue by gvautour** [react-bootstrap-table/react-bootstrap-table2#465]
I noticed that the Search results get cleared back to it's original dataset after the cursor is moved using arrow keys. Is this the expected behavior? I was hoping to be able to provide a 'clear' button to reset the search results instead.

**Comment by gvautour** [comment]
In addition, I am unable to pass the search value directly to the onSearch function.

Even when I have the following, after onKeyUp, the table should only show records with the string 'test', but it only works on the first keyUp event, resets the dataset for any other keyUp afterwards and search doesn't work thereafter.

    ...
    <InputGroup>
        <Input
            onKeyUp={input => {
                props.searchProps.onSearch('test') // will be coming from the state
            }}
        />
        <InputGroupAddon addonType="append">
            <Button>{labels.buttons.clear[lang]}</Button>
        </InputGroupAddon>
    </InputGroup>
    ...

I think it could be related to my initial observation about the cursor.

**Comment by AllenFang** [comment]
Hello @gvautour I don't think it's a expected behavior.

> but it only works on the first keyUp event, resets the dataset for any other keyUp afterwards and search doesn't work thereafter.

A question, you mean it's doesn't work after first keyup event. so when the second keyup event happen. your callback function get called?

**Comment by AllenFang** [comment]
@gvautour fixed in `react-bootstrap-table-next@1.1.0` and `react-bootstrap-table2-toolkit@1.0.1`

[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/12/version-bump.html)
