### ISSUE TITLE
Change column color

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#466]
Good afternoon,
Thanks for this great library.

I'm changing the color of the line this way.
```
    const rowStyle = (row, rowIndex) => {
            if (row.status === "Closed") {
                return {color: '#FD0303' };
            }
        };
```

Is there any way to change the color of the column? because this changes the color of the entire line

**Comment by AllenFang** [comment]
@Denis-String try > [`column.style`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnstyle-object-function)
