### ISSUE TITLE
Open Modal on Row event

### ISSUE THREAD

**Issue by ipflowss** [react-bootstrap-table/react-bootstrap-table2#475]
Is there some boiler plate that shows how to open a modal based on a row event?

**Comment by AllenFang** [comment]
[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Rows&selectedStory=Row%20Event&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example to show u how to attach a row event, however, we don't have any boilerplate to indicate how to open a modal. But I think it's not  to difficult to implement.
