### ISSUE TITLE
Formatting date and time

### ISSUE THREAD

**Issue by ipflowss** [react-bootstrap-table/react-bootstrap-table2#478]
Hi there,

Ive seen how to format date but how do I format time with date.  Here is my code for formatting date only

          formatter: (cell) => {
            let dateObj = cell;
            if (typeof cell !== 'object') {
              dateObj = new Date(cell);
            }
            if (cell == null) {
              return
            }
            return `${('0' + (dateObj.getMonth() + 1)).slice(-2)}/${('0' + dateObj.getDate()).slice(-2)}/${dateObj.getFullYear()}`;
          },
          editor: {
            type: Type.DATE
          }

**Comment by AllenFang** [comment]
@ipflowss currently, we still not support the date time editor and filter. However, you can custom it by yourself.

Anyway, about formatting date and time, you can find the answer from javascript. It's not the question in `react-bootstrap-table`
