### ISSUE TITLE
Format buttons next to each other

### ISSUE THREAD

**Issue by ipflowss** [react-bootstrap-table/react-bootstrap-table2#479]
Hi there,

I am hoping to format "Add Circuit" and "Export CSV" buttons next to each other on the page but currently they are on separate lines.

Here it is:

                    props => (
                      <div>
                        <SearchBar { ...props.searchProps } />
                        {this.state.showAddButton ?
                          <AddCircuit
                          locations={locations}
                          providers={providers}
                          clearForm={this.clearForm}
                            msgOut={this.props.msgOut}
                            errorOut={this.props.errorOut}
                          /> : null }
                          <MyExportCSV { ...props.csvProps } />
                      </div>

**Comment by AllenFang** [comment]
Bootstrap support a row class: 

https://getbootstrap.com/docs/4.0/layout/grid/
