### ISSUE TITLE
Remote search not firing onTableChange

### ISSUE THREAD

**Issue by jasonaronson** [react-bootstrap-table/react-bootstrap-table2#483]
I recreated the remote search example from the Storybook exactly and cannot get onTableChange to fire when typing in the SearchBar component. The issue appears to be that `remote={ { search: true } }` in the BootstrapTable component does not work. When I add filtering or sorting in the remote object the onTableChange function fires properly so I've narrowed it down to this. I have also tried just entering `remote` and still the SearchBar does not fire onTableChange.

Documentation for the remote object does not show a search variable. Was this removed and the Storybook not updated? Here is the [https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#remote-bool-object](url). 

Thanks in advance for your help!

**Comment by AllenFang** [comment]
@jasonaronson ok, I will check it out, thanks!

**Comment by AllenFang** [comment]
@jasonaronson sorry for lately reply, I think the remote search is work fine. There an online [example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Search&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Can you share your example but please keep it minimal and simple, thank you

**Comment by levantuy** [comment]
please help me!

I  use redux get data from  api.  It not working correctly if not settimeout to methed this.setState({}).

// constructor
constructor(props) {
    super(props);
    this.state = {
      data: []
    };
}
//  filter
handleTableChange = (type, { page, sizePerPage, filters }) => {
    this.props.fetchData(page, sizePerPage); // call api use redux.
    this.setState({
      data: this.props.userState.users
    });
  }
// render()
<RemoteFilter
        data={this.state.data}
        onTableChange={this.handleTableChange}
      />
