### ISSUE TITLE
'underscore'  in utils.js missing from 1.1.0 update

### ISSUE THREAD

**Issue by brendanmurphy** [react-bootstrap-table/react-bootstrap-table2#485]
Failed to compile
./node_modules/react-bootstrap-table-next/lib/src/utils.js

Module not found: Can't resolve 'underscore' in '/Users/brendanmurphy/Projects/PARADIS3/website-2018/node_modules/react-bootstrap-table-next/lib/src'

This error occurred during the build time and cannot be dismissed.

**Comment by brendanmurphy** [comment]
just had to: npm i underscore

**Comment by AllenFang** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/486

@brendanmurphy actually, it's a bug and I think it was fixed in `1.1.1`
