### ISSUE TITLE
Module underscore not found in latest Version

### ISSUE THREAD

**Issue by LiquidSean** [react-bootstrap-table/react-bootstrap-table2#486]
```
./node_modules/react-bootstrap-table-next/lib/src/utils.js
Module not found: Can't resolve 'underscore' in '/Users/''/Documents/Repos/react-software-manager/ClientApp/node_modules/react-bootstrap-table-next/lib/src'
```
##
Ever since updating to [1.0.1](https://github.com/react-bootstrap-table/react-bootstrap-table2/releases/tag/react-bootstrap-table2-toolkit%401.0.1) I can't compile my project because of 'underscore' not being found.

**Comment by AllenFang** [comment]
@LiquidSean  please upgrade to `react-bootstrap-table-next@1.1.1` again, I think it will fix this issue.

**Comment by Rawnak-Siddique** [comment]
index.js:1453 ./node_modules/react-bootstrap-table-next/lib/src/utils.js
Module not found: Can't resolve 'underscore' in 'D:\WebsiteCode\car-dealership-dashboard\node_modules\react-bootstrap-table-next\lib\src' 
I am having this problem continuously and my app keeps crashing
