### ISSUE TITLE
selected line effect when using double-click

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#487]
Good Morning,
When I use a click to select the line, I can make the selected line effect (change the color of the line that was selected)

doing like this:

```
 const selectRow = {
            mode: 'radio',
            clickToSelect: true,
            selected: this.state.selected,
            onSelect: this.handleOnSelect,
            hideSelectColumn: true,
            bgColor: "#f18e3757"
        }
```
```
    handleOnSelect = (row, isSelect) => {
        this.setState(() => ({
            selected: [row.id]
        }));
    }
```
`  <BootstrapTable id="tablePessoa" striped hover keyField='id' data={products} columns={columns} selectRow={selectRow} />`

This works very well, when given a click, applies the selection effect.

But when I try to double-click instead of one, the selection effect does not work.
I'm trying like this:

```
 const selectRow= {
                    mode: 'radio',
                    selected: this.state.selectedPessoa,
                    hideSelectColumn: true,
                    bgColor: "#f18e3757"
                }

```
```
    const rowEventsPessoa = {
                    onDoubleClick: (row) => {
                        this.setState(() => ({
                            selectedPessoa: [row.id],
                            pessoa: row
                        }));
                    }
                }
```
`  <BootstrapTable id="tablePessoa" striped hover keyField='id' data={products} columns={columns} selectRow={selectRow}  rowEvents={rowEventsPessoa } />`

It calls the method, but it is not coloring the selected line when I click twice. Am I doing something wrong?

**Comment by AllenFang** [comment]
@Denis-String i will check this out, probably is a bug

**Comment by AllenFang** [comment]
@Denis-String 

```js
class Table extends React.Component {
  constructor(props) {
    super(props);
    this.state = { selected: [] };
  }
  render() {
    const rowEvents = {
      onDoubleClick: (e, row, rowIndex) => {
        this.setState(() => ({
          selectedPessoa: [row.id]
        }));
      }
    };
    const selectRow = {
      mode: 'radio',
      selected: this.state.selectedPessoa,
      hideSelectColumn: true,
      bgColor: '#f18e3757'
    };

    return (
      <div>
        <h3>Try to click on any rows</h3>
        <BootstrapTable selectRow={ selectRow } keyField="id" data={ products } columns={ columns } rowEvents={ rowEvents } />
        <Code>{ sourceCode }</Code>
      </div>
    );
  }
}
```
this is my demo code for reproduce your issue, but when I db click on row, the selection will trigger. Did I missing something?

**Comment by Denis-String** [comment]
Thanks for the attention, I must have done something wrong, because your example worked perfectly.
