### ISSUE TITLE
Wrong code in example for Clear All filters storybook

### ISSUE THREAD

**Issue by vikhyatprabhu** [react-bootstrap-table/react-bootstrap-table2#491]
![image](https://user-images.githubusercontent.com/26038037/44201588-3ce2cc80-a167-11e8-98ee-a7f5a95fc546.png)
Wrong code in Clear all filters example as shown in pic. Code is for filter columns by 0 while the example is for clearing filters.

**Comment by AllenFang** [comment]
@vikhyatprabhu I will fix it, thank you 👍

**Comment by AllenFang** [comment]
Fixed 👍
