### ISSUE TITLE
Cell edit table 2 version "1.1.1" 

### ISSUE THREAD

**Issue by teaklvs** [react-bootstrap-table/react-bootstrap-table2#494]
Hi, 

I am using react bootstrap table next version "1.1.1" and editor version "0.2.1". Cell edit stopped working after updating the table-next version from "0.1.15". Even a simple edit example like below doesn't seem to render an input field. We cant revert to the pervious version, as it will break the pagination option. Could you please provide me with help for this issue?
Thanks!

import React, {Component} from 'react';
import BootstrapTable from 'react-bootstrap-table-next';
import cellEditFactory from 'react-bootstrap-table2-editor';

const products = [{
    id: 1,
    name: "Item name 1",
    price: 100
  },{
    id: 2,
    name: "Item name 2",
    price: 100
  }];

const columns = [{
    dataField: 'id',
    text: 'Product ID'
  }, {
    dataField: 'name',
    text: 'Product Name'
  }, {
    dataField: 'price',
    text: 'Product Price'
}];

export class TestTable extends Component {

render(){
  return(
    <BootstrapTable
      keyField="id"
      data={ products }
      columns={ columns }
      cellEdit={ cellEditFactory({ mode: 'click' }) }
    />
);}}

**Comment by AllenFang** [comment]
@teaklvs you have to upgrade `react-bootstrap-table2-editor` to `1.0.0`. https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/04/version-bump.html

Kindly reopen this issue if the problem still remain, thank you

**Comment by teaklvs** [comment]
Hi @AllenFang, that helped! Thanks!
