### ISSUE TITLE
Pagination not playing nicely with Toolkit table search bar.

### ISSUE THREAD

**Issue by dillobird** [react-bootstrap-table/react-bootstrap-table2#495]
Looks like there's a bug when using both pagination and the search bar from the toolkit.

To reproduce:

1. Search for something that returns 0 results using a full table search bar.
2. Change the rows per page to something other than the current selection. e.g. from 10 to 20.
3. Clear the search term from the search bar.

It throws the following error and crashes the app:

`TypeError: Cannot read property 'name' of undefined`

... where 'name' is the keyField passed to the ToolkitProvider.

Any ideas what this might be?

**Comment by AllenFang** [comment]
@dillobird ok, I will check this out, sorry for lately reply.

**Comment by AllenFang** [comment]
@dillobird btw, what version u used, list all of the related packages. thanks

**Comment by dillobird** [comment]
@AllenFang No worries mate! Package versions below:

```
"react-bootstrap-table-next": "^1.1.1",
"react-bootstrap-table2-paginator": "^1.0.1",
"react-bootstrap-table2-toolkit": "^1.0.1",
```

**Comment by AllenFang** [comment]
ok, thank you

**Comment by dillobird** [comment]
@AllenFang You’re a gentleman and a scholar. Thank you!

When’s the next release due out?

**Comment by AllenFang** [comment]
@dillobird I think about 8/21 or 22.

**Comment by AllenFang** [comment]
@dillobird we fixed this issue in `react-bootstrap-table-next@1.1.2`, `react-bootstrap-table-toolkit@1.0.2` and `react-bootstrap-table2-paginator@1.0.2`. check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/21/version-bump.html)

**Comment by AllenFang** [comment]
Please reopen this issue if the problem still remain, thanks

**Comment by dillobird** [comment]
Fixed! Thanks again @AllenFang.

**Comment by yzhak** [comment]
@AllenFang I can reproduce the above bug in the latest version:
react-bootstrap-table-next@3.0.0
react-bootstrap-table2-toolkit@1.3.1
react-bootstrap-table2-paginator@2.0.3
react-bootstrap-table2-filter@1.1.5

In addition, I have a related issue.
To reproduce:

1. There are more than 10 rows and sizePerPage is 10. 
2. Search for some "SearchTerm1" in the SearchBar that returns 2 pages of results.
3. Clear the search
4. Go to page 3
5. Search for the same "SearchTerm1"

Like above, it throws the following error and crashes the app:
`Uncaught TypeError: Cannot read property 'name' of undefined`
... where 'name' is the keyField passed to the ToolkitProvider.

I would really appreciate your help with this. And thank you for this library.
