### ISSUE TITLE
Wrong code in example in empty table overlay

### ISSUE THREAD

**Issue by vikhyatprabhu** [react-bootstrap-table/react-bootstrap-table2#498]
![image](https://user-images.githubusercontent.com/26038037/44321249-83d10a80-a464-11e8-9681-f1b57bce91e5.png)
Wrong code for example empty table overlay. No source of NoDataIndication in the example

**Comment by AllenFang** [comment]
@vikhyatprabhu thanks, I will patch in next release.

**Comment by AllenFang** [comment]
Fixed on official document and source code, thank you 👍
