### ISSUE TITLE
clickToExpand 

### ISSUE THREAD

**Issue by Gi972** [react-bootstrap-table/react-bootstrap-table2#507]
Hi @AllenFang,

in previous r-b-t in selectRow option with can choose  clickToExpand for Trigger expand and selection together.

[Link to doc  r-b-t V1](https://allenfang.github.io/react-bootstrap-table/docs.html#clickToExpand)

any plans for implements this ?
because a I migrate in new version and I need it.

thanks

**Comment by AllenFang** [comment]
@Gi972 I will implement it ASAP.

**Comment by AllenFang** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/commit/9dbac4614f0c55efce7c7a913df72cadcc801ed1

**Comment by AllenFang** [comment]
Please upgrade to `react-bootstrap-table-next@1.3.0` and `react-bootstrap-table2-editor@1.2.0`

[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/14/version-bump.html) 

Check [`selectRow.clickToExpand`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowclicktoexpand-bool)

**Comment by Gi972** [comment]
Thank you for this work @AllenFang

**Comment by nati08** [comment]
Hi @AllenFang, still not working

**Comment by nati08** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Row%20Select%20and%20Expand&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
