### ISSUE TITLE
Event for when edit cell opened

### ISSUE THREAD

**Issue by jbcksfrt** [react-bootstrap-table/react-bootstrap-table2#514]
Is there a way to determine or catch the event for when a cell edit box or dropdown is opened?  I see before and after save events, but these both appear to fire when you are leaving the input rather than when you are entering it.

This is important for me because I do not want to Ajax refresh the data while someone is editing a box and have them lose their current edits.

Thanks!

**Comment by jbcksfrt** [comment]
Thanks!  I will test next week.

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/09/03/version-bump.html)

Please upgrade related packages. thanks
