### ISSUE TITLE
bug in onSelectAll

### ISSUE THREAD

**Issue by mahyar33** [react-bootstrap-table/react-bootstrap-table2#524]
hi
in onSelectAll function when I want to setState,checkbox is not checked
pls guide me

**Comment by AllenFang** [comment]
if you did call `setState` in the `onSelectAll` or `onSelect`, please do remember to manage the selection too.

https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/297

It's a workaround currently, Will improve it in future.

**Comment by AllenFang** [comment]
Sorry for lately fixed.....
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/11/04/version.bump.html)

now you can call `setState` in `selectRow.onSelect` and we support a feature that you can reject the selection, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowonselect-function) and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Advance%20Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is example
