### ISSUE TITLE
sort indicator is not shown when using ToolkitProvider bootstrap4

### ISSUE THREAD

**Issue by mtiger2k** [react-bootstrap-table/react-bootstrap-table2#528]
this is reopen issue of [516](https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/516)
the sort example of bootstrap4 is simply using BootstrapTable. Please try use BootstrapTable in ToolkitProvider, the sort indicator is not shown. 

const columns = [{
  dataField: 'id',
  text: 'Product ID'
}, {
  dataField: 'name',
  text: 'Product Name',
  sort: true
}, {
  dataField: 'price',
  text: 'Product Price',
  sort: true
}];

const defaultSorted = [{
  dataField: 'name',
  order: 'desc'
}];
        <ToolkitProvider
          keyField="id"
          data={ products }
          columns={ columns }
          search
          defaultSorted={ defaultSorted }
        >
          {
            props => (
              <div>
                <h3>Input something at below input field:</h3>
                <SearchBar { ...props.searchProps } />
                <hr />
                <BootstrapTable
                  bootstrap4
                  { ...props.baseProps }
                />
              </div>
            )
          }
        </ToolkitProvider>

Thanks.

**Comment by AllenFang** [comment]
@mtiger2k ok, I will look into on it.  thanks

**Comment by AllenFang** [comment]
@mtiger2k sorry, this is a wrong document issue, you have to move the `bootstrap4` prop to `ToolkitProvider`, I will update the document later. thanks!
