### ISSUE TITLE
Examples don't work on windows

### ISSUE THREAD

**Issue by amsterdamharu** [react-bootstrap-table/react-bootstrap-table2#533]
According to the documentation:

```
$ git clone https://github.com/react-bootstrap-table/react-bootstrap-table2.git
$ cd react-bootstrap-table2
$ yarn install
$ yarn storybook
$ Go to localhost:6006
```

Getting compilation errors `error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`

In the browser it shows the same errors.

**Comment by AllenFang** [comment]
ok, I will look into on it. if you really need the story, there's a online version: https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Welcome&selectedStory=react%20bootstrap%20table%202%20&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by amsterdamharu** [comment]
The following did solve it for me:
```
git config --global core.autocrlf true
````

I was using git bash.

**Comment by AllenFang** [comment]
Thanks @amsterdamharu and @whatnick   I'am going to close this issue if you find issue again, please reopen it.  Thanks

**Comment by asifsha** [comment]
rules:{
    "linebreak-style": 0
  }
add above in rules in file .eslintrc
this worked for me for windows
https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style
