### ISSUE TITLE
mask on cellEdit

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#535]
Good morning, thank you for the great work.

I'm trying to put a mask when I use cellEdit, to prevent the user from entering letters, but save the R $ character.

Does anyone have any ideas ? I tried several ways, but I could not.

**Comment by AllenFang** [comment]
@Denis-String sorry for lately reply, the mask you mean disabling the input field?

**Comment by Denis-String** [comment]
Good afternoon, I use the cell edit in a column that the data entry needs to be in currency format (R$ 2,562.75).
So, I just need to allow numbers, but keep the currency format, which uses R $ (.) E (,).

**Comment by Denis-String** [comment]
Good morning, I believe that this is going well, I did this way:

```
 const columnsPagamento = [{
            dataField: 'id',
            text: 'ID:',
            hidden: true
        }, {
            dataField: 'vlLancamento',
            text: 'Valor:',
            editorRenderer:(editorProps, value, row, rowIndex, columnIndex) => (
                <NumberFormat
                className="form-control"
                value={row.vlLancamento}
                onValueChange={(values) => {
                    row.vlLancamento = values.formattedValue;
                }}
                thousandSeparator="."
                decimalSeparator=","
                allowNegative={false}
                prefix="R$ "
            />
              )
        },
```
This works, however, it does not blur the selected input, would you have any ideas?
[GIF Simulation](https://uploaddeimagens.com.br/imagens/exemplo-gif-488fe861-4d29-466f-84fe-6808172a6b1a)

The entry that this type of date, works, when you click outside the field disables, but the money field does not.

**Comment by AllenFang** [comment]
ok, I see, so the only problem is your can not leave your custom editor when you blur the input field, right?

**Comment by diogoaltoe** [comment]
I have the same difficulty as Denis-String.

I'm using the custom editor, but after clicking on enter or clicking on another field, there is always an open input for editing. It does not block editing.
How to solve this?

Thanks!
