### ISSUE TITLE
How do I pass a selectList array to the dropdown option for cell editior

### ISSUE THREAD

**Issue by jbp17** [react-bootstrap-table/react-bootstrap-table2#536]
It works for me when I assigned static array to the options of editors.  But I can't passed in an array object to it.  Here is my code:

const sicSelect = (props) => { return this.props.sic };

const columns =
            [{
                dataField: 'id',
                text: 'Employer ID',
                filter: textFilter(),
                sort: true
            }, {
                dataField: 'standardIndustrialClassCode',
                text: 'SIC',
                attrs: { title: 'Standard Industrial Class Code' },
                filter: textFilter(),
                sort: true,
                editor: {
                    type: Type.SELECT,
                    options: sicSelect
                }
            }];

I am getting the following error: 
Warning: Failed prop type: Invalid prop `options` supplied to `DropDownEditor`.
    in DropDownEditor (created by EditingCell)
    in EditingCell (created by Row)
    in tr (created by Row)
    in Row (created by Body)
    in tbody (created by Body)
    in Body (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable
    in PaginationProvider
    in SortProvider
    in FilterProvider
    in CellEditProvider
    in DataProvider (created by BootstrapTableContainer)
    in BootstrapTableContainer (created by RemoteFilterCellEdit)
    in div (created by RemoteFilterCellEdit)
    in RemoteFilterCellEdit (created by EmployerList)
    in EmployerList (created by EmployerSearch)
    
I did create the array as the format specified in your documentation.

**Comment by jbp17** [comment]
Never mind.  I figured it out.

**Comment by JeevaRamachandran** [comment]
can you please explain how you have implemented.
