### ISSUE TITLE
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.  Check the render method of `BootstrapTableContainer`.

### ISSUE THREAD

**Issue by abinashdatta** [react-bootstrap-table/react-bootstrap-table2#540]
Hi,

 Getting subject error during rendering of BootstrapTable 2.

**Comment by abinashdatta** [comment]
@AllenFang Could you please help me out I am struggling since a week after I integrated my components in a different environment..

**Comment by Denis-String** [comment]
Good morning, can you show the code related to BootstraTable 2?

**Comment by AllenFang** [comment]
@abinashdatta what react version you used? thanks and give me your code

**Comment by agarwalankit95** [comment]
I am also facing the same issue, i have followed the docs and example still having this error.
I am on this version of react:
```
"prop-types": "^15.6.2",
"react": "^16.2.0",
"react-dom": "^16.2.0",
"react-router-dom": "^4.2.2",
"bootstrap": "^4.0.0",
"reactstrap": "^5.0.0-beta.3",
```
I am using bootstrap 4 along with reactstrap for bootstrap react components.

Please help.

**Comment by AllenFang** [comment]
@agarwalankit95 please upgrade the `react` and `react-dom` to `16.3.0` at least

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/04/version-bump.html#notes
