### ISSUE TITLE
 buttons on the tables

### ISSUE THREAD

**Issue by Denis-String** [react-bootstrap-table/react-bootstrap-table2#542]
Good afternoon, I had to update the react-bootstrap-table2,

because of this problem: 
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/530#event-1828208046

In the previous version, it was this:
```
    "react-bootstrap-table-next": "^0.1.14",
    "react-bootstrap-table2-editor": "^1.0.1",
    "react-bootstrap-table2-filter": "^0.3.0",

```

I was doing this, to process buttons in the table, based on the row property:

```
      const addButtonLancamento = (cell, row) => {
         if (row.status === "Aberto") {
                return (
                    <div>
                        <Button size="sm" floating color="white" onClick={() => this.acaoLancamento(row)}><Fa className="green-text" icon="check"></Fa></Button>                   
                    </div>
                )
            } 
           if (row.status === "Baixado") {
                return (
                    <div>
                        <Button size="sm" floating color="white" onClick={() => this.acaoLancamento(row)}><Fa className="orange-text" icon="rotate-left"></Fa></Button>
                    </div>
                )
            }

        }
```
```
  const columnsPagamento = [
    {
            dataField: 'dtemis',
            text: 'Emissao:',
            sort: true,
        },
        {
            dataField: 'dtvcto',
            text: 'Vencimento:',
            sort: true,
        },
        {
            dataField: 'vlfinal',
            text: 'Valor:',
            sort: true,
        },
        {
            text: 'Pagar:',
            dataField: 'Pagar',
            formatter: addButtonLancamento,
            editable: false 
        }];

```

This had the following result:
[Gif Result](https://uploaddeimagens.com.br/imagens/exemple-gif)

However, now that I have upgraded to the latest version, it has stopped working.

How can I have the same result in this new version?

**Comment by AllenFang** [comment]
@Denis-String 

Sorry, I am not very clear what the problem you face via your gif..

However, in the newest version, we did some cell performance tuning.  So would you please describe your cases and the problems? thanks

BTW.....  you can check this issue: https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/504

I think after `react-bootstrap-table-next@1.1.4`, we support dummy column via enable `column.isDummyField`. It's useful for your `Pager` column which is just action or component without any data etc.

[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Dummy%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an online demo probably like your case

Please reopen this issue and mention me again if above information can not help u.

**Comment by AllenFang** [comment]
BTW, please read [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) again, the formatter function should not use external data because it will effect `react-bootstrap-table` determine if a cell should be updated.
