### ISSUE TITLE
Programmatically filter hidden columns

### ISSUE THREAD

**Issue by paulalcabasa** [react-bootstrap-table/react-bootstrap-table2#550]
Is it possible to filter hidden columns?

**Comment by AllenFang** [comment]
@paulalcabasa we don't support this feature but you can implement it by yourself, just control the `colums` props on `BootstrapTable` thanks

**Comment by mkwenzel** [comment]
Hi @paulalcabasa were you able to figure out how to make this work? I'd like to do the same thing in my code!

**Comment by mkwenzel** [comment]
Update for anyone else who might be looking how to do this:

1. Set CSS property "visibility" to "hidden" on the following 3 styles: column, column header, filter. 
2. Set style height for filter to 0px
3. Set style width for column to 0

Works like a charm! See code below for example (places to set CSS are marked with double *).

[Link for more info about CSS visibility](https://allyjs.io/tutorials/hiding-elements.html)

```
{
	dataField: 'hideme',
	text: 'HideMe',
	headerStyle: (column, colIndex) => {
		**return { width: 0 , 'visibility': 'hidden'}**
	},
	filter: multiSelectFilter({
		options: selectHideMeOptions,
		defaultValue: this.state.columnFilter7,
			getFilter: (filter) => {
				this.setState.columnFilter7 = filter
			},
			placeholder: 'Select',
			**style: {'visibility': 'hidden','height':'20px'}**
				}),
	**style: {'visibility': 'hidden'}**
}
```

**Comment by Amritpd** [comment]
Out of the box support for this would be very helpful!

**Comment by ZippoLag** [comment]
Thanks a lot @mkwenzel !

However, I ended up replacing all your styles for simply display: 'none', since I couldn't get bot the header and each cell to be _really_ hidden.

**Comment by alenstdev** [comment]
> EDIT: This does not work as well as I had thought--the programmatic filter remains BUT the column header CSS seems to over-ride the filter CSS and essentially forces the table header height to allow for the "invisible" table sort element. This is visually undesirable, and the added white space is a live area (sorts the table columns if you click in it). I'll keep working to figure out how to fix the CSS on it.
> 
> ![screen shot 2018-11-29 at 4 51 43 pm](https://user-images.githubusercontent.com/37850006/49257194-22bbba00-f3f7-11e8-959a-75b2379c6861.png)
> 
> Update for anyone else who might be looking how to do this:
> 
> 1. Set CSS property "visibility" to "hidden" on the following 3 styles: column, column header, filter.
> 2. Set style height for filter to 0px
> 3. Set style width for column to 0
> 
> Works like a charm! See code below for example (places to set CSS are marked with double *).
> 
> [Link for more info about CSS visibility](https://allyjs.io/tutorials/hiding-elements.html)
> 
> ```
> {
> 	dataField: 'hideme',
> 	text: 'HideMe',
> 	headerStyle: (column, colIndex) => {
> 		**return { width: 0 , 'visibility': 'hidden'}**
> 	},
> 	filter: multiSelectFilter({
> 		options: selectHideMeOptions,
> 		defaultValue: this.state.columnFilter7,
> 			getFilter: (filter) => {
> 				this.setState.columnFilter7 = filter
> 			},
> 			placeholder: 'Select',
> 			**style: {'visibility': 'hidden','height':'20px'}**
> 				}),
> 	**style: {'visibility': 'hidden'}**
> }
> ```

Yes, If you want to display absolutely nothing, you need to set `style` and `headerStyle` options from  `{'visibility': 'hidden'} to {'display': 'none'}`
