### ISSUE TITLE
Bootstrap 4 sorting icon missing

### ISSUE THREAD

**Issue by RaySheikh** [react-bootstrap-table/react-bootstrap-table2#553]
Hi, 
When I enable bootstrap 4 support, the sorting works. however the sorting arrow icons in the table header columns are missing. 
I am using bootstrap table next ver 1.1.4 and Bootstrap 4.1.3.

Thanks!

**Comment by AllenFang** [comment]
@RaySheikh where the `bootstrap4` prop you put?

**Comment by RaySheikh** [comment]
> @RaySheikh where the `bootstrap4` prop you put?

Sorry for the late reply. I'm using bootstrap 4 and I have it setup as: 
```
<BootstrapTable
  bootstrap4
  keyField="id"
  data={ products }
  columns={ columns }
  defaultSorted={ defaultSorted } 
/>
```
it seems to be a bug. It works find with bootstrap 3. 
i'm using Bootstrap 4.1.3
react-bootstrap-table-next 1.1.4.

Thanks!

**Comment by RaySheikh** [comment]
I have also noticed the validation message does not appear in BS4. anyone else seeing the same issue?
I recently updated to 1.2.0 and unable to get the autoSelectText to work.. not sure if it may be related to bs4 also. 

Thanks Allen for all the help and work making this. Appreciate your work!

**Comment by AllenFang** [comment]
@RaySheikh I think in the [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Bootstrap%204&selectedStory=Sort%20table%20with%20bootstrap%204&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) we are also use `bootstrap@4.1.3` but it work fine to me.  Would you please share more about how to reproduce this issue? thanks

for the blank message issue, i will check it out. thanks

**Comment by RaySheikh** [comment]
> @RaySheikh I think in the [online demo](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Bootstrap%204&selectedStory=Sort%20table%20with%20bootstrap%204&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) we are also use `bootstrap@4.1.3` but it work fine to me. Would you please share more about how to reproduce this issue? thanks
> 
> for the blank message issue, i will check it out. thanks

Hi Allen, 
I have attached a link to the sandbox below. clicking on the column headers will sort the data but the icons are missing. I have also reproduced the missing validation message. If you change the price to 6 or higher the validation kicks in but the message is not displayed.

https://codesandbox.io/s/039869q7zv

Thanks!

**Comment by AllenFang** [comment]
@RaySheikh thanks for the demo, but I mean the demo is for the sort icon disappear problem lol .  Because it [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Bootstrap%204&selectedStory=Sort%20table%20with%20bootstrap%204&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) online demo is able to show the sort icon in bootstrap4, so i wanna see how you guy reproduce this issue, thank

**Comment by jakeleventhal** [comment]
I am also having this issue

**Comment by abdulrahman-khankan** [comment]
I solved it by adding `import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';` to the top of my component file.

**Comment by jakeleventhal** [comment]
This doesnt work for me

**Comment by AllenFang** [comment]
@alexspence   The demo from @RaySheikh
 is missing `import "react-bootstrap-table-next/dist/react-bootstrap-table2.min.css"` 

Anyway, if anyone can show me a demo to reproduce, I will start to look into on it. Please check you include the correct bootstrap css and `react-bootstrap-table2` css.

**Comment by AllenFang** [comment]
https://codesandbox.io/s/jj22w8lzvv

**Comment by hunterxxx** [comment]
First,  add this to your component
`import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';`

then, add bootstrap4 in            
```
<BootstrapTable
                bootstrap4
                keyField='id'
                data={products}
                columns={columns}
     />
```

**Comment by Vignesh-Ravi** [comment]
Guys, Here is the solution. I had the same issue I have resolved by adding,

import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';

and  added bootstrap4 props in ToolkitProvider instead of  BootstrapTable

<ToolkitProvider bootstrap4 keyField="id" data={items} columns={columns} size="sm" search
          exportCSV={{ onlyExportFiltered: true, exportAll: false }}>

<BootstrapTable responsive striped hover condensed pagination={paginationFactory()}
                noDataIndication="Table is Empty" selectRow={selectRow} {...props.baseProps} />

![image](https://user-images.githubusercontent.com/36445124/80904900-717a2b80-8d30-11ea-9238-afc217ad7156.png)

Thanks all for your input.

**Comment by Jeadonara** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1301#issuecomment-603049898

**Comment by abilpraju-aot** [comment]
Thanks to your support

**Comment by fareed010** [comment]
How can I move the up and down arrow to the right side?
