### ISSUE TITLE
child to parent callback block selectRowProp

### ISSUE THREAD

**Issue by unkls** [react-bootstrap-table/react-bootstrap-table2#555]
Hello,

First I don't know if that is possible to use this table as child component. I'm passing value (id of the row that is selected) between my child and parent. But when I'm passing value to the parents my row style is not apply.

Do you have idea why I get this problem ?

Thank's in advance !

**Comment by unkls** [comment]
I find that the style is not apply when I `setState` the value return from the child. This is cause of the re-render with the state ?

**Comment by unkls** [comment]
I think's it's more a React issues. 
It's just that I have 3 components (A parents, B child navbar, C child table). When I'm passing value from B->A and then A->C (table using your lib), all my style are not apply. Like when I add color to the selected row it doesn't appear to the screen.

**Comment by unkls** [comment]
No It's a callback for return the row selected to the parent : `this.props.giveData(this.rowSelected)`
I fix this with using `shouldComponentUpdate`. My table only re-render when I send a special value from the parent. So the style of the row don't disappear.
Thank's a lot for your amazing job !

**Comment by AllenFang** [comment]
ok, do let me know if there's any issue. thank u
