### ISSUE TITLE
not really an issue but i was wondering if this is possible with react bootstrap table

### ISSUE THREAD

**Issue by paigeflourin** [react-bootstrap-table/react-bootstrap-table2#557]
I have a table but one cell must contain multiple items like this, and they should be displayed like that and must be editable. users can click x and type in a new item in the field. 

![42310651_274160266752919_2115086683916468224_n](https://user-images.githubusercontent.com/6951524/45811714-695aad00-bd00-11e8-886b-e2bd949b0ef2.png)

i have been reading the docs but i cannot find anything that makes my requirement possible. I highly appreciate any help!

**Comment by AllenFang** [comment]
@paigeflourin if you want to custom the column, please use [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function)

BTW, if your column is just some actions without display data, please check [`column isDummyField`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnisdummyfield-bool)


Please reopen this issue and tag me if above solution can not answer your question
