### ISSUE TITLE
Combine Row Selection and Expand Mode

### ISSUE THREAD

**Issue by Julian4711** [react-bootstrap-table/react-bootstrap-table2#559]
Hi,

is there a way one could use Row Selection and Row Expand at the same time?

When I try to combine the Storybook examples ([selection](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Multiple%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) & [expand](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Basic%20Row%20Expand&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)) as follows, row selection does not work. Instead, even when I click on the checkbox, the row expands and is not selected.

EDIT: Apparently, with the legacy react-bootstrap-table it workes fine: [Example](https://allenfang.github.io/react-bootstrap-table/example.html#expand) (scroll down to "Expand Row with Selection").

Thank you!

  ```
`const selectRow = {
      mode: 'checkbox',
      clickToSelect: true
    };
```

    const expandRow = {
      renderer: row => (
        <div>
          <p>{ 'This Exow is belong to rowKey ${row.id}' }</p>
          <p>You can r anything here, also you can add additional data on every row object</p>
          <p>expandRow.renderer callback will pass the origin row object to you</p>
        </div>
        ),
        showExpandColumn: false
    };

    return (
          <BootstrapTable
            keyField='id'
            data={ products }
            columns={ columns }
            expandRow={ expandRow }
            selectRow={ selectRow }
          />`

**Comment by AllenFang** [comment]
@Julian4711 It's a known issue, I already fixing it, but need some time. Will mention here after release.

**Comment by AllenFang** [comment]
#507

**Comment by AllenFang** [comment]
Please upgrade to `react-bootstrap-table-next@1.3.0` and `react-bootstrap-table2-editor@1.2.0`

[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/14/version-bump.html) 

Check [`selectRow.clickToExpand`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowclicktoexpand-bool)
