### ISSUE TITLE
Select Row with RemotePagination

### ISSUE THREAD

**Issue by AbhinethriRS** [react-bootstrap-table/react-bootstrap-table2#560]
Hi,
I am unable to select the row with the remote pagination.

Kindly suggest the code.

**Comment by AbhinethriRS** [comment]
@AllenFang, Please suggest the solution.

**Comment by AllenFang** [comment]
it's impossible.  
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Pagination&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Above is a remote pagination example, just add selectRow prop on `BootstrapTable` and it works.

Please try it or describe your problem more detail if this can not answer you.  Please reopen this issue and tag me if you still need the help
