### ISSUE TITLE
Could not load css

### ISSUE THREAD

**Issue by fabercs** [react-bootstrap-table/react-bootstrap-table2#562]
Hey,

As indicated in documents I have imported 
`import BootstrapTable from 'react-bootstrap-table-next';`

but could not import 
`import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';`

it pops an error 
> You may need an appropriate loader to handle this file type.

It is some webpack bundling related error I guess according to my research, do you know how to configure my webpack?

I am using stephan grinder's [redux simple starter](https://github.com/StephenGrider/ReduxSimpleStarter) boilerplate btw, and its webpack.config.js as follows;

```
module.exports = {
  entry: ['./src/index.js'],
  output: {
    path: __dirname,
    publicPath: '/',
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
        exclude: /node_modules/,
        loader: 'babel',
        query: {
          presets: ['react', 'es2015', 'stage-1']
        }
      }
    ]
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  devServer: {
    historyApiFallback: true,
    contentBase: './',
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    }
  }
};
```

**Comment by AllenFang** [comment]
@fabercs you need the webpack style loader. I remember your need `style-loader` and `css-loader`
