### ISSUE TITLE
Ability to disable Select All

### ISSUE THREAD

**Issue by tmock12** [react-bootstrap-table/react-bootstrap-table2#563]
I have a use case where I need to disable the ability to select/unselect all. Looking at the code there doesn't appear to be a away to do this as `currSelected` is set no matter what `onSelectAll` does. Am I missing something obvious? Or is this a feature you would consider adding? 

```javascript
    handleAllRowsSelect = (e, isUnSelect) => {
      const {
        data,
        keyField,
        selectRow: {
          onSelectAll,
          nonSelectable
        }
      } = this.props;
      const { selected } = this.state;

      let currSelected;

      if (!isUnSelect) {
        currSelected = selected.concat(dataOperator.selectableKeys(data, keyField, nonSelectable));
      } else {
        currSelected = selected.filter(s => typeof data.find(d => d[keyField] === s) === 'undefined');
      }

      if (onSelectAll) {
        onSelectAll(!isUnSelect, dataOperator.getSelectedRows(data, keyField, currSelected), e);
      }

      this.setState(() => ({ selected: currSelected }));
    }
```

**Comment by AllenFang** [comment]
@tmock12 You can custom the selection column so which mean you can just remove the selection all checkbox, following is an example to show you how to custom the selection column:

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Custom%20Selection&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Please reopen this issue and tag me if above information is not helpful to you.

**Comment by tmock12** [comment]
@AllenFang I tried that as well and it unfortunately doesn't work. You can remove the select all checkbox using `selectionHeaderRenderer` but if you click the cell the `handleCheckBoxClick` is still fired. 

I believe its this code:
https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/6e526f455b68f06705ab862cbe1fa63bf8057682/packages/react-bootstrap-table2/src/row-selection/selection-header-cell.js#L74-L76

**Comment by tmock12** [comment]
@AllenFang you also can't re-open Github issues if a collaborator closes them ☹️
