### ISSUE TITLE
SelectFilter formatter is not working properly

### ISSUE THREAD

**Issue by NadineSch** [react-bootstrap-table/react-bootstrap-table2#565]
By using multiselectFilter or selectFilter like below, the content of column 'Category' isn't displayed and with selecting an option, no row is displayed.

<img width="398" alt="bildschirmfoto 2018-09-26 um 15 05 03" src="https://user-images.githubusercontent.com/33058136/46081794-b37add00-c19d-11e8-9dba-1bfc72d59a74.png">

Here is my code:
```
render() {
  const selectOptions = {
    0: 'A',
    1: 'B',
    2: 'C'
  };
  const columns = [
    {
      dataField: 'id',
      text: 'ID'
    },
    {
      dataField: 'category',
      text: 'Category',
      formatter: cell => selectOptions[cell],
      filter: multiSelectFilter({
        options: selectOptions,
      })
    }
  ];
  return (
    <BootstrapTable
      keyField='id'
      data={data}
      columns={columns}
      filter={filterFactory()}
    />
  );
}
```
[Here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=MultiSelect%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is my source of how to use multiSelectFilter.

If I modify selectOptions to

```
const selectOptions = {
  "A": "A",
  "B": "B",
  "C": "C"
}
```

the filter works fine. 
<img width="399" alt="bildschirmfoto 2018-09-26 um 15 04 42" src="https://user-images.githubusercontent.com/33058136/46081821-bfff3580-c19d-11e8-86ef-57b1cb8ab6af.png">
So I think the formatter is not working as expected and searches for the key instead of the value in the table. 
This is what my json data looks like:

```
[{
  "id": 1,
  "category": "A"
}, {...}, {...}]
```

Do you have any idea how to fix this?
Thanks!

**Comment by AllenFang** [comment]
@NadineSch that is wired, I will check this out.

**Comment by AllenFang** [comment]
@NadineSch if you raw data is 
```
{
  id: 1,
  category: "A"
}
```
I mean without double quotes

**Comment by NadineSch** [comment]
@AllenFang no I receive my data in json format, therefore with double quotes. You think this could be an issue?

**Comment by AllenFang** [comment]
@NadineSch lol

I probably got the problem....

ok, https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=MultiSelect%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

that is example you reference and the `selectOptions` is like below

```js
const selectOptions = {
  0: 'good',
  1: 'Bad',
  2: 'unknown'
};
```

Actually, 0, 1 and 2 is just the column value of Product Quailty but I use `column.formatter` to show it as good, bad or unknow.

so if your raw data is not like above example, you probably don't need the `column.formatter`. I think your data is already A, B, C.


Please do let me know if you still have any question and reopen this issue again, thanks

**Comment by NadineSch** [comment]
@AllenFang 
thanks for your fast reply.
So you're right with the formatter, my raw data is A, B or C and not 0, 1 or 2.
Does that mean it's necessary that the value i'm filtering for (A, B or C) is the key-attribute of the selectOptions-Object? Like:
```
const selectOptions = {
  A: 'Filter by A',
  B: 'Filter by B',
  C: 'Filter by C'
}
```
`[key]`: what I'm looking for in my raw Data
`[value]`: how to name it in my filter-menu (?)

If I'm getting this right I'm clear now, thanks!

**Comment by AllenFang** [comment]
@NadineSch yes, you are right!
