### ISSUE TITLE
Combining two or more object properties to form a single column with all features (sorting, searching)

### ISSUE THREAD

**Issue by JEEVANJGA** [react-bootstrap-table/react-bootstrap-table2#566]
Hi,
Would like to know if it is possible to combine 2 or more Object properties to form a single column.

Consider,
`arrayToBeiterated=[{FirstName : 'Jeevan',MiddleName : 'George', LastName : 'Antony',worksat:'Infosys'},{FirstName : 'SaJeevan',MiddleName : '', LastName : 'Raj',worksat:'Infosys'}]`

Table to be displayed : 
```
*************************************************
*                                   *           *
* Name                              * Worksat   *
*                                   *           *
*************************************************.
*                                   *           *
* Jeevan George Antony              * Infosys   *
*                                   *           *
*************************************************
*                                   *           *
* SaJeevan Raj                      * Infosys   *
*                                   *           *
*************************************************
```

Combining 2 or more object properties to form a new value and bringing it under a single column with all features.

**Comment by AllenFang** [comment]
@JEEVANJGA sure, you can use [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function)

Please reopen this issue if above solution is not helpful to you, thanks
