### ISSUE TITLE
Sorting icon not showing

### ISSUE THREAD

**Issue by EndStatement** [react-bootstrap-table/react-bootstrap-table2#577]
Sorting icon missing

`<BootstrapTable keyField="ID"
                            data={this.state.data}
                            columns={this.state.columns}
                            striped
                            bootstrap4/>`

**Comment by HumbleCarl** [comment]
![image](https://user-images.githubusercontent.com/32160916/46270069-01199000-c578-11e8-80cc-87b3c24304f2.png)

**Comment by AllenFang** [comment]
can you share more?  I think it's work for bootstrap 4 
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Bootstrap%204&selectedStory=Sort%20table%20with%20bootstrap%204&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel


What version u used?

**Comment by HumbleCarl** [comment]
I'm using BS4

**Comment by AllenFang** [comment]
I mean the version of `react-bootstrap-table-next` and I think because it work for me on the above example, would you please give me some reproduce code or env? thanks . Online example will be good

**Comment by AllenFang** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/553#issuecomment-431651293

**Comment by Jeadonara** [comment]
I think there is a problem with webpack, the workaround fix is like here: https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1301#issuecomment-603049898

**Comment by vijaychouhan-rails** [comment]
import following at the top

```
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';
import 'react-bootstrap-table2-filter/dist/react-bootstrap-table2-filter.min.css';
```
