### ISSUE TITLE
Setting a particular row border

### ISSUE THREAD

**Issue by nitrogene** [react-bootstrap-table/react-bootstrap-table2#579]
Hello,

Is it possible to change a whole row border ? I tried something like:
                                <BootstrapTable
                                    ....
                                    rowStyle={rowStyleMetre}
                                    ....
                                </BootstrapTable>

with:
        const rowStyleMetre = (row, rowIndex) => {
            if (row["Pos"] == this.state.currentRow) {
                return { "borderColor": "green", "borderBottomWidth": "thin","borderBottomStyle":"solid" };
                //return { "backgroundColor": "#007ACC"};
            }
            return {};
        };

If i use the commented line instead, the background of the "currentRow" is updated. 

Regards

**Comment by AllenFang** [comment]
I think it's ok to set the row border: 

const rowStyle = { backgroundColor: '#c8e6c9', border: '3px solid red' };

<img width="765" alt="2018-10-02 11 56 31" src="https://user-images.githubusercontent.com/5351390/46360892-f3125f00-c69e-11e8-8bd9-29c8a1f4093f.png">

**Comment by AllenFang** [comment]
I think the style should be render to DOM correctly, you can try to change the `borderBottomWidth` to another value, it should work.

**Comment by nitrogene** [comment]
Using const rowStyle = { backgroundColor: '#c8e6c9', border: '3px solid red' } does the trick. 

Thank you :)
