### ISSUE TITLE
any ways to block the beforeSaveCell function until the user hits OK or Cancel button?

### ISSUE THREAD

**Issue by HiroHara-Nextremer** [react-bootstrap-table/react-bootstrap-table2#583]
Hi Allen, 

I want to implement a confirmation modal, wondering if there is a good way to block 'beforeSaveCall' until yes or no is hit by the user. To be exact, I want the beforeSaveCell function to be terminated if the user enters no, and to proceed with afterSaveCell function if yes.

p.s. 
i just figured my question seems to quite similar to https://github.com/AllenFang/react-bootstrap-table/issues/1245.

**Comment by AllenFang** [comment]
hello @HiroHara-Nextremer yes, your question is similar with #1245, so the patch of #1245 is helpful to your case?  thanks

**Comment by AllenFang** [comment]
@HiroHara-Nextremer I will figure out this feature and find a good solution, thanks

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/29/version-bump.html)

[ONLINE DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Async%20Hook%20Functions&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

[DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/cell-edit-props.html#celleditbeforesavecell-function)

**Comment by HiroHara-Nextremer** [comment]
@AllenFang 
sorry for the late reply.
the new feature you've added worked perfect!!!

THX ^^
