### ISSUE TITLE
How to get currently displayed rows data slice with pagination enabled?

### ISSUE THREAD

**Issue by paolostyle** [react-bootstrap-table/react-bootstrap-table2#585]
I have a table which uses pagination with remote disabled. I need to know which rows are currently displayed in the table, for example when the user is on 3rd page and data is sorted by some column with 50 rows/page I want to get access to an array of these 50 objects that are currently displayed. I'm fairly certain there is no non-ugly way to do that, but surely there must be some way to access it through ref, right?

**Comment by AllenFang** [comment]
@paolostyle currently, we dont have a good way to get the reference, I will fixed it ASAP, thanks

**Comment by AllenFang** [comment]
@paolostyle 👍

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/)

[EXPOSED API](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html)

[ONLINE DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Basic%20Table&selectedStory=Exposed%20API&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
