### ISSUE TITLE
columns not updating in v1.2.0

### ISSUE THREAD

**Issue by TRWGali** [react-bootstrap-table/react-bootstrap-table2#586]
I have a grid component that will take the selected row and pass it as a parameter to my columns.
This was nice as I could render anything I needed in a row based on the row being selected.  This was working in v0.1.15, but appears to not be working in v1.2.0.

Example of v0.1.15: https://codesandbox.io/s/436ppjxrn7
Example of v1.2.0: https://codesandbox.io/s/m4py39vz78

**Comment by AllenFang** [comment]
@TRWGali, after `v1.0.0`([RELEASE NOTES](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/08/12/version-bump.html)), we have a enhancement on cell level, so please check [`column.formatter`] docs again: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function

> **Attention: Don't use any state data or any external data in formatter function, please pass them via formatExtraData. In addition, please make formatter function as pure function as possible as you can.**


If you still can not solve this issue, please reopen this issue and tag me, thanks

**Comment by TRWGali** [comment]
https://codesandbox.io/s/o5z8plm1x9 is the fixed version for anyone looking in the future

**Comment by AllenFang** [comment]
👍
