### ISSUE TITLE
No data shown after search

### ISSUE THREAD

**Issue by ramirog89** [react-bootstrap-table/react-bootstrap-table2#588]
Hi!
I'm using react-bootstrap-table-next and I've implemented the remote pagination successfuly,
and instead of using filters in columns with the filter library, I've implemented a search query in a REST API that looks in all model columns passed in the filters[] query, so when I search for a text value the API returns the data items I need and this works well.

What is happening is that after the component renders, it's really disappointing that the data is shown just for one sec but is removed instantaneously.

I'm not using filters in the code just enable the remote pagination in the <Bootstraptable> component and centralizing all queries in the handleTableChange method.

This is weird because only happen when I look for, Languages.
Languages is a column in my table definition which has no filter enable, and is a relational table in my user model.
When I look for any other field, the table shows the registry well. Its looks like the table is applying a filter rule by itself because it loads the data but then removes it, and I can't see how to disable this.... 

Any thoughts?
Thanks!

Animation Case:
![bootstrap-bug-remote-search](https://user-images.githubusercontent.com/864323/46557113-39460900-c8bf-11e8-9c73-af2e4a5f3ac3.gif)

**Comment by feather-jmalone** [comment]
what you're describing is exactly what i'm experiencing well. i posted about it here: https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/568#issuecomment-425489176, but no one seems to be responding to my theory (that both local and remote searches are being performed simultaneously, and the local search results replace the remote search results). fortunately, the work around is very simple: disable remote search and simply use your own text field and trigger the remote search yourself instead of in an `onTableChange` handler.

**Comment by AllenFang** [comment]
@feather-jmalone your assumption is correct, I will fixed it in next version, thanks

**Comment by ramirog89** [comment]
@feather-jmalone hey!, seems you've been experiencing the same... yea, I will give a try to that approach and let you know!

@AllenFang I've just enable the remote like the docs says:
```javascript
<BootstrapTable
   pagination={paginationFactory({ page, sizePerPage, totalSize: data.count })}
   noDataIndication={() => (<div>No Registers available</div>)}
    onTableChange={this.handleTableChange}
   remote={{
       pagination: true
   }}
   {...props.baseProps}
/>
```

I can see that you've found the case, that's pretty fast, I really appreciate the effort. Thank you!
How often you deploy the new releases? I saw its in QA right now.

**Comment by AllenFang** [comment]
@ramirog89 I will release this patch in SAT or SUN. Actually, this project almost developed and maintained by myself, so I didn't have any idea about when to release. I hope I can release every week but it depends lol   Sometime, I'm busy lol

Anyway, give a star for this repo is most effective way for appreciation to me haha
thanks~

**Comment by feather-jmalone** [comment]
@AllenFang starred, and very much appreciated! it's a great component that keeps getting better, thanks for your dedication!

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/07/version-bump.html)

Please upgrade to `react-bootstrap-table-next@1.2.1`, `react-bootstrap-table2-paginator@1.0.3` and `react-bootstrap-table2-toolkit@1.1.1`
