### ISSUE TITLE
react-bootstrap-table2-paginator 1.0.2 broke remote pagination.paginationTotalRenderer

### ISSUE THREAD

**Issue by dieselhank** [react-bootstrap-table/react-bootstrap-table2#589]
With remote data source and search when the filtered list shrinks below the current page I reset page to 1.
But paginationTotalRenderer receives the original page 'from' value. This works fine in 1.0.1 but doesn't in 1.0.2.

**Comment by AllenFang** [comment]
I will fixed it, thanks

**Comment by AllenFang** [comment]
Similar UI issue from https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/568

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/07/version-bump.html)

Please upgrade to `react-bootstrap-table-next@1.2.1`, `react-bootstrap-table2-paginator@1.0.3` and `react-bootstrap-table2-toolkit@1.1.1`

**Comment by dieselhank** [comment]
Thank you for quick the fix!

**Comment by AllenFang** [comment]
👍

**Comment by nontachaiwebdev** [comment]
Hi guys. Is any update on this issue ? Has anyone fixed it ?
