### ISSUE TITLE
pagination toolbar does not update when calling onPageChange externally

### ISSUE THREAD

**Issue by TRWGali** [react-bootstrap-table/react-bootstrap-table2#590]
The pagination toolbar does not update when I call my pageChange function ( one that is passed down to onPageChange ) externally ( not using one of the page buttons ) on table version 1.2.0 and paginator version 1.0.2. I've created an example using these versions [here](https://codesandbox.io/s/rr03ly306m). To reproduce go to page 2 and search "honeydew" in the search box. The table's data will update, but the page identifier will stay on the current page.

I've made another sandbox for table version 0.1.15 and paginator version 0.1.6 [here](https://codesandbox.io/s/ymxz3x1mv1) where this approach works. 

Is this something that can be fixed? If not, how should I go about doing this now?

**Comment by TRWGali** [comment]
closing this as it seems to be fixed in v1.2.1 and v1.0.3.

**Comment by AllenFang** [comment]
👍
