### ISSUE TITLE
tabindex on td fields

### ISSUE THREAD

**Issue by dominic-otoole** [react-bootstrap-table/react-bootstrap-table2#598]
Is tab index supported on this release ?  

Inspecting the generated td element, I don't see this attribute by default.

It appears in the previous version here: 

https://allenfang.github.io/react-bootstrap-table/example.html#celledit

<td tabindex="2" class="" style="text-align: left;">Item name 0</td>

**Comment by AllenFang** [comment]
@dominic-otoole I will support it, thanks!

**Comment by dominic-otoole** [comment]
Thanks Allen

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/14/version-bump.html) 

Enable [`tableIndexCell`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#tabindexcell-bool) on `BootstrapTable`

[ONLINE DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Basic%20Table&selectedStory=Enable%20tabIndex%20on%20Cell&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Please upgrade to `react-bootstrap-table-next@1.3.0`
