### ISSUE TITLE
Paginator: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by amsterdamharu** [react-bootstrap-table/react-bootstrap-table2#599]
In my container that is using bootstrap-table2 I optionally set pagination:

```
const pagination =
    numPages > 1
        ? paginationFactory({
              page: options.page,
              //other values
          })
        : undefined;
```

However the script [here](https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2-paginator/src/context.js#L59) somehow assumes pagination. 

This will error in `Cannot read property 'options' of undefined` when previously there were 2 pages but deleting the only item on the second page causes no more than one page (so pagination props is undefined).

The following code will reproduce the error:

https://github.com/amsterdamharu/table-bug

Worked around this issue by always setting pagination but if there is only one page it'll be hidden with css:

```
const pagination = paginationFactory({...})
...
<div className={classNames({ ['hide-pagination']: numPages === 1 })}>
  <BootstrapTable
     pagination={pagination}
```

css:

```
div.hide-pagination > div.row.react-bootstrap-table-pagination {
    display: none;
}
```

**Comment by AllenFang** [comment]
I think you can do it:

```js
const tableProps = {
  data: ....,
  columns: .....
};

if(numPages > 1) {
  tableProps.pagination = paginationFactory({
     page: options.page,
     //other values
  });
}

<BootstrapTable { ...tableProps } />

```

**Comment by AllenFang** [comment]
please tag me if above solution is not helpful to you.

**Comment by amsterdamharu** [comment]
@AllenFang Thank you for your reply.

The error will occur when you set pagination in first render and have it undefined in any next render. Easily reproduced here: https://github.com/amsterdamharu/table-bug

**Comment by AllenFang** [comment]
@amsterdamharu 
firstly, your code is wrong so that you will get the error.....  please check my above example......
 
Secondly, currently, `react-bootstrap-table` doesn't check the nextProps for `pagination`, I will fixed it in next version.

**Comment by AllenFang** [comment]
@amsterdamharu please upgrade to `react-bootstrap-table-next@1.3.0`
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/14/version-bump.html)

**Comment by amsterdamharu** [comment]
@AllenFang I can confirm that this solved the problem, there is no longer an error when pagination was set but is undefined in a later render.

Yarn upgrade in the [example](https://github.com/amsterdamharu/table-bug) solved it.

**Comment by AllenFang** [comment]
👍
