### ISSUE TITLE
Property condensed has no effect with bootstrap4

### ISSUE THREAD

**Issue by sedrubal** [react-bootstrap-table/react-bootstrap-table2#600]
Setting `condensed` to `true` or `false` makes no difference when you use `bootstrap4`. The css class `table-condensed` was removed there. Instead you should use `.table-sm`. Additionally it was useful to add `.form-control-sm` on a `condensed` table to all `.form-control`s.

If you want, I can try to make a pull request.

**Comment by AllenFang** [comment]
@sedrubal ok, PR is welcome :)

**Comment by YassienW** [comment]
@AllenFang @sedrubal 
> Additionally it was useful to add .form-control-sm on a condensed table to all .form-controls.

Implemented for bootstrap 3 and 4, will be included in the next PR :)

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/11/10/version-bump.html

Fixed it on newest version.  Thanks @YassienW

**Comment by YassienW** [comment]
@AllenFang Yes, the condensed property was fixed, but didn't add .form-control-sm on condensed table  forms which was the second suggestion:

> Setting condensed to true or false makes no difference when you use bootstrap4. The css class table-condensed was removed there. Instead you should use .table-sm.

>  Additionally it was useful to add .form-control-sm on a condensed table to all .form-controls.

**Comment by sedrubal** [comment]
Nice, thanks. Sorry for not crating a pull request. 
Unfortunately we switched back to bs 3 with our project...

**Comment by hsluoyz** [comment]
This issue is still not fixed in latest 3.3.0. Any solution?
