### ISSUE TITLE
Checkbox should false with empty data

### ISSUE THREAD

**Issue by Gi972** [react-bootstrap-table/react-bootstrap-table2#602]
Hello,

on Storybook,
in Row Selection -> selection without data

When you have empty data the checkbox should be checked=false , disabled or even disappear. 

I think it's not a normal behavior if you don't have data that checkbox was checked.

in the first version of  ReactBtable the chekbox is false.

Could you fix that?

Except if you are disagree with me :-p

Thanks

**Comment by AllenFang** [comment]
I will fixed in next version, thanks @Gi972

**Comment by AllenFang** [comment]
@Gi972 please upgrade to newest version: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/14/version-bump.html

`react-bootstrap-table-next@1.3.0`
`react-bootstrap-table2-editor@1.2.0`
