### ISSUE TITLE
expandrows

### ISSUE THREAD

**Issue by rmartin58** [react-bootstrap-table/react-bootstrap-table2#610]
I am having an issue with expand row; if I click on any row, they all expand. I would like to have only the row clicked to expand. I'm sure this is my issue as the demo code works as I would expect.  Any thoughts / pointers about where I made my mistake?
```
const expandRow = {
    renderer: row => (
      <div>
        <MeetExpand row={row} />
      </div>
    ),
    showExpandColumn: true,
  };
```

**Comment by AllenFang** [comment]
it's wired, could you share what version you used now?  and also the react version. 
In addition, a simple and minimal code to reproduce it will be goood 

Thanks

**Comment by AllenFang** [comment]
close it due to no response
