### ISSUE TITLE
Automatically set column width based on max cell text width?

### ISSUE THREAD

**Issue by mkwenzel** [react-bootstrap-table/react-bootstrap-table2#612]
Has anybody found a way to auto set the column widths?

I would love to see functionality for setting the column widths based on the size of whatever is inside the columns. Setting each column width by pixel is so inefficient to what I need to do, especially since the table size changes based on browser window size.

**Comment by AllenFang** [comment]
@mkwenzel I think you can set the `white-space:nowrap ` on column.

Do let me know if it not work. thanks

**Comment by knowbody** [comment]
I'm also looking for the same feature, I tried setting the style on column to what you suggested but it doesn't seem to work.

**Comment by buianhthang** [comment]
@mkwenzel this one work for me
```
{ dataField: 'id', text: 'Id', style: {'white-space': 'nowrap'} }
```

**Comment by mkwenzel** [comment]
Hi @AllenFang I have still not been able to get this to work!

It occurred to me that maybe I'm wording this incorrectly and that's why people are suggesting that I use "nowrap" when it does not achieve what I want.

When I use 
`{ dataField: 'id', text: 'Id', style: {'white-space': 'nowrap'} }`

It renders and looks like this where the text of the column that I am using "nowrap" on runs over the text in the adjacent column.

![screen shot 2018-12-10 at 4 09 24 pm](https://user-images.githubusercontent.com/37850006/49764779-0987f880-fc96-11e8-84d0-5f321cfa8f79.png)

What I am looking for is the ability to have the text not wrap or bleed into the next column, but also not have to set the width of the column manually via headerstyle.

**Comment by pmogilev** [comment]
Thats not an ideal solution but it worked for me ....            

headerStyle: (colum, colIndex) => {
                return { width: '30%', textAlign: 'left' };
            }

**Comment by borihan-p** [comment]
Removing "table-layout: fixed" in react-bootstrap-table2.scss can stop the bleed. It worked for me.

**Comment by mkwenzel** [comment]
Tried @borihan-p 's recommendation and it did not work for me. Still no solution, I've just been working around it.

**Comment by TheShadow8** [comment]
My solution is I created an css file for BootstrapTable and imported css file to js file. Then you can customize css file to fit your needs. I can customize a lot  by using this method. See my example images below. 

![capture1](https://user-images.githubusercontent.com/35181893/52166966-4abee680-26e2-11e9-94dd-5b6237da2d4c.PNG)
![capture2](https://user-images.githubusercontent.com/35181893/52166969-4db9d700-26e2-11e9-8396-0bd677955e95.PNG)

**Comment by fabriciopirini** [comment]
> Removing "table-layout: fixed" in react-bootstrap-table2.scss can stop the bleed. It worked for me.

This solution worked for me but I found it easier to create the rule on my css file:

`.react-bootstrap-table table {
  table-layout: auto !important;
}`

**Comment by shubham-prasad** [comment]
You can also add class **table-responsive** to _BootstrapTable_ element. This will result in the table becoming scrollable horizontally but there will be no overlap between the columns.

**Comment by rgonca** [comment]
@shubham-prasad Thank you, that is exactly what I was looking for
