### ISSUE TITLE
Search and stateManagement (multi selection)

### ISSUE THREAD

**Issue by Gi972** [react-bootstrap-table/react-bootstrap-table2#613]
Hi, 

When I use the table search with the multiselection  and I select any rows, I lost the selection when I search.

After verification, It's because the props don't pass the "selected" propertie. 

You forgot it or ?

Thanks for your answer

**Comment by Gi972** [comment]
Sorry,  It works I make a mistake
Sorry about that 

I close this issue

**Comment by orenberkovich** [comment]
Hi,

When I use the table search with the multiselection and I select any rows, I lost the selection when I search.

this is happened to me you have any solution for this issue?
