### ISSUE TITLE
After Search data object

### ISSUE THREAD

**Issue by kmb266** [react-bootstrap-table/react-bootstrap-table2#615]
I would like to do something similar to what is mentioned in [this](https://github.com/AllenFang/react-bootstrap-table/issues/514) issue for the original react-bootstrap-table. Really I just want the data object after searching so I can display a row count above the table, but being able to manipulate the data object after a search would be great too.
Is this feature coming soon? Or am I missing something in the documentation?
Thanks in advance for the help.

**Comment by AllenFang** [comment]
@kmb266 https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html

You can use above exposed api to get data or current status.
Please upgrade to newest version for all the related packages.

Please tag me if above information is not helpful to you, thanks!
