### ISSUE TITLE
expandByColumnOnly is not behaving as expected; clicking anywhere row still expands row

### ISSUE THREAD

**Issue by mkwenzel** [react-bootstrap-table/react-bootstrap-table2#616]
expandByColumnOnly is not behaving as expected. I would like for my table rows to only expand my rows when clicking the expand column, and then do some other thing when I double click anywhere else in the row.

I followed documentation (here is the relevant code):

    const expandRow = {
        renderer: (row) => ...,
        showExpandColumn: true,
        expandByColumnOnly: true
    };

But setting "expandByColumnOnly" as boolean 'true' does not cause this behavior to occur, and the row still expands regardless of where I click.

Here is my code:

    renderProjectTab(nonformattedData) {
            var rbtnData = formatProjectTableData(nonformattedData)

            const rowEvents = {
                onDoubleClick: (e, row, rowIndex) => {
                    console.log('double clicked')
                }
            }

            const expandRow = {
                showExpandColumn: true,
                expandByColumnOnly: true,
                expandHeaderColumnRenderer: ({ isAnyExpands }) => {
                    if (isAnyExpands) {
                        return (
                            <Glyphicon glyph="menu-down"/>
                        );
                    }
                    return (
                        <Glyphicon glyph="menu-right"/>
                    );
                },
                expandColumnRenderer: ({ expanded }) => {
                    if (expanded) {
                        return (
                            <Glyphicon glyph="menu-down"/>
                        );
                    }
                    return (
                        <Glyphicon glyph="menu-right"/>
                    );
                },
                renderer: row => (
                    <div>
                        "Div content blah blah blah."
                    </div>
                )
            };

            if (rbtnData.data.length == 0) {
                return (
                    <p>No Projects!</p>
                )
            } else {
                return (
                    <>
                    <div className='project-table-container'>
                        <BootstrapTable 
                            keyField='id' 
                            data={ rbtnData.data } 
                            columns={ rbtnData.columns } 
                            bordered={ false }
                            expandRow={ expandRow }
                            rowEvents={ rowEvents }
                            condensed/>
                    </div>
                    </>
                )
            }
        } else {
            return <p>No projects found.</p>
        }
    }

Thank you for your help and all of the great work that you do on this fantastic project!

**Comment by AllenFang** [comment]
@mkwenzel please upgrade to newest version will fix this issue.
