### ISSUE TITLE
Column Event: How to get row id?

### ISSUE THREAD

**Issue by bjostes** [react-bootstrap-table/react-bootstrap-table2#621]
How do I get the row id, when using column event for clicking on specific cell?
So when I click at a specific cell, I would like to know which Id the row has, the cell belongs to.

_Originally posted by @bjostes in https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/427#issuecomment-430602564_

**Comment by bjostes** [comment]
very nice, thank you!

**Comment by AllenFang** [comment]
I will close this issue and tag you when I fix it, thanks

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/29/version-bump.html)

[ONLINE DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Event&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
