### ISSUE TITLE
Unable to style next, last, previous and first page buttons in pagination.

### ISSUE THREAD

**Issue by amsterdamharu** [react-bootstrap-table/react-bootstrap-table2#624]
All paginate page items are li elements that have class `page-item` with a `page-link` anchor.

Tried styling the next, last, previous and first buttons with css selectors like `first-child` but that doesn't help since I've made them optional (first and previous don't show when on page 1).

Is it possible to add a class to these elements so they can be styled?

**Comment by AllenFang** [comment]
it's still pending, I will handle it ASAP, thanks

**Comment by AllenFang** [comment]
@amsterdamharu  you can custom the these buttons via `firstPageText`, `prePageText`, `nextPageText` and `lastPageText`.  

Check [doc](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/pagination-props.html)

**Comment by AllenFang** [comment]
Please tag me if you still dont know how to customize it, thanks

**Comment by stilllife00** [comment]
@AllenFang the docs says the props accept ANY but when passing a JSX element in the console I get an error that the expected prop should be a String. 

The table renders properly though.

Passing jsx is very useful to put icons instead of text.

**Comment by sammccants** [comment]
@AllenFang I'm having a similar issue to @stilllife00. I'm actually able to supply JSX to these fields, but when actually using the buttons, they duplicate in the list and throw the error:
```
Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
Is there a chance JSX will be supported in these fields in the future, or am I just using it wrong? Is there perhaps another way to achieve this functionality?
