### ISSUE TITLE
Row Selection with cellEdit not working properly

### ISSUE THREAD

**Issue by jpramos123** [react-bootstrap-table/react-bootstrap-table2#626]
Hello, I'm trying to make a cell edit and at the same time to make the row of this cell marked as selected.

This is my selectRow configuration:

```
const selectRow = {
      mode: 'checkbox',
      hideSelectColumn: false,
      clickToSelect: true,
      clickToEdit: true,
      bgColor: 'red',
```

When I make the change in the cell, it's possible to see that the code is passing throw the `selectRow` function, but not changing it's state in the front end.

**Comment by AllenFang** [comment]
> When I make the change in the cell, it's possible to see that the code is passing throw the `selectRow` function, but not changing it's state in the front end

@jpramos123 sorry for lately reply, but I am not clear about your question.  Would you please explain again? thanks

**Comment by jpramos123** [comment]
@AllenFang Thank you for your response!
I mean that, when I click in a cell which is marked as "editable", the row is not marked as "selected" and its color don't change (that is I called "state", my bad).
When debugging, It's possible to see that, when I click in this editable cell, the code pass throw the "selectRow" function of the component.

Thank you!

**Comment by AllenFang** [comment]
@jpramos123 ok, you mean the `bgColor` is not rendered when the row is selected, right?  I think its' a bug, I will fix it, thanks

**Comment by AllenFang** [comment]
```js
const columns = [{
  dataField: 'id',
  text: 'Product ID'
}, {
  dataField: 'name',
  text: 'Product Name'
}, {
  dataField: 'price',
  text: 'Product Price'
}];

const selectRow = {
  mode: 'checkbox',
  clickToSelect: true,
  clickToEdit: true,
  bgColor: 'red'
};

const cellEdit = {
  mode: 'click'
};

<BootstrapTable
  keyField="id"
  data={ products }
  columns={ columns }
  selectRow={ selectRow }
  cellEdit={ cellEditFactory({ mode: 'click' }) }
/>
```

this is my code and when click to select/edit, the color is change correctly.

**Comment by AllenFang** [comment]
Did I missing something? @jpramos123  or maybe you can share your code but please keep it simple and minimal, thanks

**Comment by jpramos123** [comment]
Hello @AllenFang, thanks for helping, follow my code:

 ```
   const selectRow = {
      mode: 'checkbox',
      hideSelectColumn: false,
      clickToSelect: true,
      clickToEdit: true,
      bgColor: '#def3ff',

      },

      // This property select or unselect all rows there are showing in the screen
      onSelectAll: (isSelect, rows, e) => {

        // If the select all button is selected
        // push all rows inside the changeAccounts array
        if (isSelect){
          rows.map(row => {
            this.state.changeAccounts.push(row);
          })
        } 
        // Else remove all items from the array
        else{
          this.state.changeAccounts = []
        }
      } 
    };


   // This function is used to make and log any changes to the table
   const cellEdit = cellEditFactory({ 
     mode: 'click', 
     blurToSave: true, 

    })

<BootstrapTable 
          keyField='idAccount' 
          data={ this.state.accounts } 
          columns={ columns }  striped  hover   
          selectRow={ selectRow } pagination={ paginationFactory()  } 
           filter={ filterFactory()  }   
           cellEdit={ cellEdit }
 />
```

**Comment by AllenFang** [comment]
Sorry for lately fixed.....
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/11/04/version.bump.html)

now you can call `setState` in `selectRow.onSelect`. BTW,  we support a feature that you can reject the selection, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowonselect-function) and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Advance%20Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is example

Please tag me if your issue still remain, thanks
