### ISSUE TITLE
setState in selectRow.onSelect will break the row expand

### ISSUE THREAD

**Issue by CaitlinSweeney** [react-bootstrap-table/react-bootstrap-table2#627]
Not sure if I missed something in the docs, but my rows are only expanding when the `ExpansionHeaderCell` is clicked. When inspecting with my React dev tools, I set my props `expanded: true` and it only changes the `+` to `-`, without expanding the data. It renders fine when the header is clicked. Not sure if I'm just missing a prop somewhere?

```
const columns = [
      {
        dataField: "jobOrderNumber",
        text: "Job #"
      },
      {
        dataField: "profitCenter",
        text: "Profit Center"
      },
      {
        dataField: "customer",
        text: "Customer"
      },
      {
        dataField: "year",
        text: "Year"
      },
      {
        dataField: "make",
        text: "Make"
      },
      {
        dataField: "model",
        text: "Model"
      }
    ];

    const selectRow = {
      mode: "radio",
      clickToSelect: true,
      selected: [this.state.jobOrderValue],
      clickToExpand: true,
      onSelect: (row, isSelect, selected, e) => {
        this.handleOnSelect(row, isSelect, selected, e);
      }
    };
    
    const expandRow = {
      renderer: row => (
        <div>
          <p>{`This Expand row is belong to rowKey ${row.jobOrderNumber}`}</p>
          <p>You can render anything here, also you can add additional data on every row object</p>
          <p>expandRow.renderer callback will pass the origin row object to you</p>         
        </div>
      ),
      showExpandColumn: true
      // expandByColumnOnly: true
    }

<BootstrapTable
	keyField={"jobOrderNumber"}
	data={this.state.matchedJobs}
	columns={columns}
	loading={true}
	bootstrap4={true}
	id={"MultipleJobsTable"}
	hover={true}
        selectRow={selectRow}
       expandRow={ expandRow }
/>
```

**Comment by CaitlinSweeney** [comment]
Sorry for the novel, I just wanted to add: 
I'm currently trying to render the expanded cells as such. Still getting the same results.
When the rows are opened with `ExpansionHeaderCell` and the `ExpandCell` is clicked, it closes all of the cells.
```
    const expandRow = {
      renderer: row => (
        <div>
         {jobMatches.map(job => {
              return <p key={job.jobOrderNumber}>{job.warningMessage}</p>
            })}
        </div>
      ),
      showExpandColumn: true,
    }
    console.log(expandRow)
```
![capture](https://user-images.githubusercontent.com/19299064/47450163-c0312780-d781-11e8-833b-276f4acd5eed.JPG)

**Comment by AllenFang** [comment]
@CaitlinSweeney I will look into on it. But would you please help to do a quick check?

* remove `selectRow.onSelect` or dont call `setState` inside `selectRow.onSelect`.

**Comment by CaitlinSweeney** [comment]
Hey @AllenFang,
Thanks for getting back. I had a feeling that was where the problem is. When I comment out the 
`selectRow={selectRow}` it works fine. I have to `setState` somewhere when it's selected, but I might figured out a workaround if I pull that component out and make it a SLC.

**Comment by AllenFang** [comment]
yeah... I think the issue is you call the setState in `selectRow.onSelect`, In my opinion, I will prefer to find the good way avoid the `setState` to break the internal action inside `react-bootstrap-table`.

Thanks

**Comment by antonvstepanov** [comment]
@CaitlinSweeney, first, sorry for my English, it is because of lack of practice. What about the work-around, you can make your own state controlled selection. That's how I did it.
1. Define a column for checkboxes. Here I also wrapped columns object with a function to provide selection callbacks and state for "select all":
```JavaScript
const Columns = (onSelect, onSelectAll, isAllSelected) => [
        {
            dataField: 'isSelected',
            text: ' ',
            formatter: (cell, row, rowIndex) =>
                <input type="checkbox" className="selection-input-4"
                       checked={cell} onChange={e => onSelect(row, e.target.checked, rowIndex)}/>,
            headerFormatter: (cell, row, rowIndex) =>
                <input type="checkbox" className="selection-input-4"
                       checked={isAllSelected} onChange={e => onSelectAll(e.target.checked)}/>,
            headerStyle: () => { return { width: '30px' } },
        },
        ...
}
```
We will need to inject the data field "isSelected" in our rows later. For styling I just used class names that @AllenFang uses for his built in selection.

2. In our class where we render table I defined states for object with selected items, and all selected flag
```JavaScript
class WorkersList extends Component
{
    state = {
      canRemove: false, isAllSelected: false, selected: {}
    };
    
    handleCanRemove()
    {
        const canRemove = !!this.state.selected && Object.keys(this.state.selected).length > 0;
        if (canRemove !== this.state.canRemove)
        {
            this.setState({canRemove});
        }
    }

    handleSelect = (row, isSelect) =>
    {
        this.setState({selected: TableSelect(row, isSelect, this.state.selected)}, this.handleCanRemove);
    };

    handleSelectAll = (isSelect) =>
    {
        this.setState({selected: TableSelectAll(isSelect, this.props.items), isAllSelected: isSelect}, this.handleCanRemove);
    };

    ...
}
```
canRemove state and handleCanRemove method are not mandatory it just for my business logics.
Here I used helper functions for getting tables selection state:
```JavaScript
export const TableSelect = (row, isSelected, items, idAlias = "id") =>
{
    const result = Object.assign({}, items);
    if (isSelected)
    {
        result[row[idAlias]] = row;
    }
    else
    {
        delete result[row[idAlias]];
    }
    return result;
};

export const TableSelectAll = (isSelected, items) =>
{
    return isSelected ? Object.assign({}, items) : {};
};
```
I should mention that the data source for my table is object with keys not an array.
3. Finally my table definition:
```JavaScript
<BootstrapTable bootstrap4 keyField='id' hover
                                            data={
                                                Object.keys(items).map(key =>
                                                    Object.assign({ isSelected: !!this.state.selected[key] }, items[key])
                                                )
                                            }
                                            columns={Columns(this.handleSelect, this.handleSelectAll, this.state.isAllSelected)}/>
```
Here I inject isSelected into my rows and call Columns function with appropriate callbacks.
The result looks like this:
![screenshot_1](https://user-images.githubusercontent.com/25131672/47933207-f50d4f00-dee4-11e8-9b2d-3444ff6b0e4a.png)
Hope this will help you!

**Comment by AllenFang** [comment]
In next version, I will fix this issue. You guys can free to call `setState` in `selectRow.onSelect`. thanks

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/11/04/version.bump.html)

now you can call `setState` in `selectRow.onSelect` and we support a feature that you can reject the selection, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowonselect-function) and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Advance%20Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is example

**Comment by AllenFang** [comment]
Please tag me if this issue still remain, thanks

**Comment by CaitlinSweeney** [comment]
Hello! Sorry for the delayed response.  @AllenFang, thanks so much for the quick release! I'll work on it shortly. 
Thank-you @antonvstepanov  for your help and code examples as well. Your English is 👍 , don't ever apologize for that. I'm going to pick it apart today as well.

**Comment by antonvstepanov** [comment]
@CaitlinSweeney, we don't need any workarounds for now, since @AllenFang released 1.4.0, It works just out of the box!

**Comment by AllenFang** [comment]
👍   Anyway, sorry for lately fixed...

**Comment by LuisGSandoval** [comment]
Hi everyone.
I just notice that the samething happens to onExpand, when there's a this.setState inside it, it stops working.

Thanks to you all

**Comment by LuisGSandoval** [comment]
Tryed to work my way around it using the events.onClick option in the columns object, but it also breaks the expand.

Please look it it  :cry: we would really apreciated

**Comment by LuisGSandoval** [comment]
While it's beign taken care of, I found a posible solution for everyone out there.

I used:

const expandRow = {
 renderer: row => (...),
 expandColumnRenderer: (row) => {
    if (expanded) {
      return (
        <b onClick={()=> this.handleFunction(row.rowKey) }>-</b>
      );
    }
    return (
      <b onClick={()=> this.handleFunction(row.rowKey) }>...</b>
    );
  }
}

I hope it helps you too.

**Comment by LuisGSandoval** [comment]
I also tried this...

const expandRow = {
renderer: row => (...),
expandColumnRenderer: (row) => {
if (expanded) {
return (
<b onClick={()=> this.handleFunction(row.rowKey) }>-
);
}
return (
<b onClick={()=> this.handleFunction(row.rowKey) }>...
);
}
}

but it didn't work either.

In general it's a great tool though... But I'll have to find another way...
