### ISSUE TITLE
Async Cell Editing and cell validation

### ISSUE THREAD

**Issue by AllenFang** [react-bootstrap-table/react-bootstrap-table2#63]
1. `options.onEditing` should accept a async operation

**Additional**: Support default/auto validation when saving cell

**Comment by AllenFang** [comment]
Remember to add `column.editable` propType defined in `header-cell.js`

**Comment by khaninD** [comment]
@AllenFang Hi! , do you want to add support edit of Header Table???

**Comment by AllenFang** [comment]
@khaninD I don't have this kind of plan currently? In addition, in `react-bootstrap-table`, I don't hear this kind of feature. Most of features on header is customization.
