### ISSUE TITLE
npm install failes

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [react-bootstrap-table/react-bootstrap-table2#631]
npm ERR! Unexpected end of JSON input while parsing near '...":{"benchmark":"^1.0.'

**Comment by AllenFang** [comment]
I guess it's because your `package.json` is a invalid JSON format

**Comment by ShoubhikBanerjee** [comment]
No, its a valid one, I have rechecked it through "https://jsoneditoronline.org/" also...
