### ISSUE TITLE
I need expandable indicator on right side(last column)

### ISSUE THREAD

**Issue by ghanavel** [react-bootstrap-table/react-bootstrap-table2#636]
Please provide  configuration option to show expandable integration on right side(last column)

**Comment by AllenFang** [comment]
it's little priority feature for me, PR is welcome, thx

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/06/version-bump.html)

Please upgrade `react-bootstrap-table-next@2.0.1` and `react-bootstrap-table2-paginator@2.0.1`.

Give [`expandRow.expandColumnPosition`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowexpandcolumnposition-string) as `right` can solve your issue, thanks
