### ISSUE TITLE
Truncated pagination

### ISSUE THREAD

**Issue by mwesthelle** [react-bootstrap-table/react-bootstrap-table2#640]
Hi @AllenFang! I'm migrating an old project to use react-bootstrap-table-next. The old design had truncated pagination, i.e instead of having 'first page' and 'last page' buttons, it showed the first page, dots, a few pages centered around the current page, more dots and then the last page. An image is worth a thousand words:
![truncated_pagination](https://user-images.githubusercontent.com/23220394/47741849-16a6d600-dc5a-11e8-96fe-5d5321e48f01.PNG)

Is there any way to reproduce this currently, or a workaround? Thanks a lot!

**Comment by AllenFang** [comment]
@mwesthelle sorry, we didn't implement this feature yet, it's lower priority currently, I will spend some time to implement, thanks

**Comment by AllenFang** [comment]
PR is welcome also

**Comment by AllenFang** [comment]
@mwesthelle we have new release -> [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/12/24/version.bump.html)

Please read this [DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#customization) to learn how to custom pagination component and also check some online [DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) 

Actually we dont support this feature directly, but you can custom the page list by yourself, Read [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Custom%20Page%20List&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) might be helpful to you

Please open a new issue if you get any questions or issues, thanks!
