### ISSUE TITLE
Sorting filter select options

### ISSUE THREAD

**Issue by jehartzog** [react-bootstrap-table/react-bootstrap-table2#641]
We needed to sort the `<options>` used in selectFilter, but because the existing code uses [`Object.keys()`](https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2-filter/src/components/select.js#L61-L73) to do this there was no way to ensure a sort order.

We also had to create boilerplate code to share options between selectFilter, which took options in the form`{ value: label, ...}` versus the the editor Type.Select which took them as `[ { value, label }, ...]`.

We solved this by extending selectFilter to just use the same method as editor, which preserves the sort order that you create the options with. Here is the file we used to do it:

```js
import React from 'react';
import PropTypes from 'prop-types';
import SelectFilter from 'react-bootstrap-table2-filter/lib/src/components/select';

// Modified version of code to allow for custom sorting
// https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2-filter/src/components/select.js#L61-L73
class SortedSelectFilter extends SelectFilter {
  // We have to modify this one as we changed it
  static propTypes = {
    ...SelectFilter.propTypes,
    options: PropTypes.array.isRequired,
  };

  getOptions() {
    const optionTags = [];
    const { options, placeholder, column, withoutEmptyOption } = this.props;
    if (!withoutEmptyOption) {
      optionTags.push(
        <option key="-1" value="">
          {placeholder || `Select ${column.text}...`}
        </option>,
      );
    }

    options.forEach(({ value, label }) => {
      optionTags.push(
        <option key={value} value={value}>
          {label}
        </option>,
      );
    });

    return optionTags;
  }
}

const sortedSelectFilter = (props = {}) => ({
  Filter: SortedSelectFilter,
  props,
});

export default sortedSelectFilter;
```

**Comment by AllenFang** [comment]
@jehartzog ok, I will use `forEach` to render the options, this is good point for me, thanks!

**Comment by jehartzog** [comment]
@AllenFang the way I coded it was a breaking change since it's not backward compatible with the current API.

You'd need a small amount of additional code to be able to change this behavior without breaking existing versions (assuming you aren't doing a major version update). I'd be happy to send a PR, just confirm that this is change you want to make and I'll put it together.

**Comment by AllenFang** [comment]
oh, yeah, let me think more about this, I forget the `options` is an object....

**Comment by AllenFang** [comment]
The proper way maybe we make the `options` accept an object or an array. If array give, we can promise the order will be the preserve.
