### ISSUE TITLE
Custom Pagination

### ISSUE THREAD

**Issue by unski11ed** [react-bootstrap-table/react-bootstrap-table2#651]
Is there currently a way to make a Custom Paginator in the same matter as you can do Custom Filters, Custom Searches etc.? I need to place it outside of the Table Component.

I have seen some issues about this saying that it is a WIP, is it in development? maybe you need some help? Or am I just missing something? :)

**Comment by AllenFang** [comment]
@unski11ed sorry for lately reply, custom pagination will coming soon.

**Comment by AllenFang** [comment]
@unski11ed we have new release -> [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/12/24/version.bump.html)

Please read this [DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#customization) to learn how to custom pagination component and also check some online [DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) 

Please open a new issue if you get any questions or issues, thanks!
