### ISSUE TITLE
Issue in pagination 'showTotal' - react-bootstrap-table2

### ISSUE THREAD

**Issue by dilushi** [react-bootstrap-table/react-bootstrap-table2#654]
@AllenFang: I have used react-bootstrap-table2 in my data grids & there is an issue in pagination 'showTotal' with 'from, 'to' & 'size' values. It seems only '**to**' value is incorrectly showed in the pagination.
ex: when page size is 10 & total records are 15, it shows as below.
Showing rows 1 to **11** of 15
Showing rows 11 to **16** of 15

And also when no data, it shows as:
Showing rows 0 to 1 of 0

It should show as 1 to 10 & 11 to 15.
I guess this is due to the header row or filtering text boxes row (not sure). 
I changed 'to' value to 'to - 1' just to check if it will change. But no difference.

Is there a way to fix this issue? Appreciate your help on this.
Thank you.

**Comment by JaviVargas** [comment]
Same issue here!

**Comment by AllenFang** [comment]
@dilushi  and @JaviVargas  what version u used? and did you enable the `remote` mode?  thanks
