### ISSUE TITLE
setState does not re-render cell from 1.3.0

### ISSUE THREAD

**Issue by jcrew** [react-bootstrap-table/react-bootstrap-table2#656]
https://codesandbox.io/s/8y95z4wx32

This sample works up to 1.2.1, but regressed after 1.3.0.

Plz take a look. Thanks in advance!

**Comment by waynebrantley** [comment]
@jcrew I agree with you.  If you use 1.4.0, nothing updates...not even the main data column.

However I cannot even get 1.2.1 to work right either
For example, note the menu
https://codesandbox.io/s/5zz8mw6qqk

@AllenFang these grid rendering optimizations are really a bear to get right!

**Comment by AllenFang** [comment]
I'm sorry about that, will look into on it.

**Comment by AllenFang** [comment]
[ONLINE DEMO is work](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Dummy%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by waynebrantley** [comment]
@AllenFang I see your online demo, but unsure what version that is built against.

Here is my example from above forked to use version 1.4.0 and you can see the state does change and the grid will not update at all.  Version 1.2.1 will update the data column but not the calculated one...1.4.0 not at all.

https://codesandbox.io/s/nvv87rx5l

If there is something wrong with the code or column definition, please advise - it appears to be like the sample?

**Comment by depl0y** [comment]
I am having the exact same issue. Reverted back to 1.2.1 and the table began updating again.

**Comment by AllenFang** [comment]
https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/629

**Comment by depl0y** [comment]
@AllenFang As I am seeing it, these are two different problems. This one is about the whole table not rerendering when the data is being updated. I use no state data in my column formatters, but use the state as a datasource for the table itself.

**Comment by waynebrantley** [comment]
@AllenFang Any update on this issue?  Were you able to reproduce it (as your demo works, but the sandbox I attached does not)?

**Comment by AllenFang** [comment]
@waynebrantley sorry i am too busy recently, I will work on this issue today, hope I can fix it ASAP.  Thanks :)

**Comment by AllenFang** [comment]
@waynebrantley just a solution if you replace `toggleInStock` function as below

```js
let gridData = [...this.state.gridData];
    gridData = gridData.map((d) => {
      if (d.id === 13) {
        return {
          ...d,
          inStock: !d.inStock
        };
      }
      return d;
    });
    this.setState(curr => ({ ...curr, gridData }));
```

set a new `gridData` reference will solve this issue.

**Comment by AllenFang** [comment]
Don't try to modify the origin row data, actually, your data will also become a state in table, if you modify the data correctly, will cause we have an incorrect comparison on row data.  Every time, your row data change, please reassign a new array.

https://redux.js.org/recipes/structuringreducers/immutableupdatepatterns#updating-an-item-in-an-array

**Comment by AllenFang** [comment]
After `1.3.0`, I had some changes on how compare the row object, so I believe if you follow redux's Immutable Update Patterns, you won't have this issue again.

Please tag me if you still feel this is an issue from `react-bootstrap-table-next`.

**Comment by AllenFang** [comment]
@depl0y  @jcrew   ⏫ ⬆️

**Comment by waynebrantley** [comment]
@AllenFang thanks for getting to the bottom of this.  Did not realize this pattern needed to be followed.  Suggest you make big notes about this in the docs, this will trip up lots of people at first.

**Comment by AllenFang** [comment]
@waynebrantley ok, Will do this, 👍

**Comment by mjmitoff2290** [comment]
@waynebrantley Did mapping the data into a new object and resetting the state with that object fix the issue for you?  I've tried this approach as well as cloning the object and making the updates and resetting the state and yet I am still getting the same issue.  My code does re-render the table in version 1.2

**Comment by matiaslavista** [comment]
This issue is still happening. I've seen alot of comments going back to 2015, where people talk about umutable state. I just through out the react-bootstrap-table2, and replaced it with react-table an it worked. What was happening to me was the actual underlying numbers were updating but the table wasn't showing the update (i.e. i could see the update through inspection, + it was updated in the footer)

**Comment by Angel-Ponce** [comment]
It steel happening
