### ISSUE TITLE
When I click on a editable cell in a row that is already selected, the row is deselected. 

### ISSUE THREAD

**Issue by jpramos123** [react-bootstrap-table/react-bootstrap-table2#659]
Hi, thank you for the help with this project.

Well as the title say, when I have a selected row, and I click on an editable cell of the same row, the row is deselected. This is not a expected behavior, since I click in something which is editable, it's means that it need to be selected.

This [example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Click%20to%20Select%20and%20Edit%20Cell&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) from the project Storybook, have the same unexpected behavior I'm facing.

Thanks you

**Comment by AllenFang** [comment]
@jpramos123 that is not default behavior, the behavior you faced is we enable the `selectRow. clickToEdit`.  So actually, it's expected behavior.
