### ISSUE TITLE
cellEditFactory, beforeSaveCell hook async, show error message inside cell on done(false)

### ISSUE THREAD

**Issue by deathbird** [react-bootstrap-table/react-bootstrap-table2#664]
Hello, thanks for this excellent component!

I'm using 
    "react-bootstrap-table-next": "^1.3.1",
    "react-bootstrap-table2-editor": "^1.2.1",

to display a datatable of Gettext translations with 2 columns msgid (translation key), msgstr (tranlsation text). 

I use the cellEditFactory beforeSaveCell option to trigger an async request (as in this example https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/cell-edit-props.html#celleditbeforesavecell-function)  to update the translations file on the server. 

I need a way to show a custom error message on the editing cell if the async request fails on done(false). An error message similar to the one that is showed if an async validation fails for example as in displayErrorMessage method in editing-cell.js file in  source code.

Can you give me some guidance on how to achieve it?

**Comment by AllenFang** [comment]
Sorry for lately reply, @deathbird you can check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Async%20Validation&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).  

[RELEASE NOTE)(https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/10/29/version-bump.html)

Please tag me if you still have the question on async validation. thanks
