### ISSUE TITLE
Warning: Failed prop type: The prop `onFilter` is marked as required in `SelectFilter`, but its value is `undefined`.

### ISSUE THREAD

**Issue by jonrandahl** [react-bootstrap-table/react-bootstrap-table2#667]
I'm working on a set of component filters based on the filter examples in the docs and the storybook, namely the select filter examples found here: [Programmatically Select Filter](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Select%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and here: [Programmatically Multi Select Filter](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Multi%20Select%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) with the following code:

```
[omit...]

import BootstrapTable from 'react-bootstrap-table-next';
import paginationFactory from 'react-bootstrap-table2-paginator';
import filterFactory, { textFilter, selectFilter, multiSelectFilter } from 'react-bootstrap-table2-filter';

[omit...]

let filterTypes;

const selectOptions = {
  "fundraiser": 'Fundraiser',
  "donate_button": 'Donate Button',
  "charity_page": 'Charity Page'
};

const columns = [
  [Omit ...]
  {
    dataField: 'Source Name',
    text: 'Type',
    formatter: cell => selectOptions[cell],
    sort: true,
//    filter: textFilter({
//      getFilter: (filter) => {
//        filterTypes = filter;
//      }
//    }),
    filter: selectFilter({
      options: selectOptions,
      getFilter: (filter) => {
        filterTypes = filter;
      }
    }),
//    filter: multiSelectFilter({
//      options: selectOptions,
//      getFilter: (filter) => {
//        filterTypes = filter;
//      }
//    }),
  },

  [Omit...]
//get the same options for the types array
let types = Object.keys(selectOptions).map(key => key: key);

//This works as expected to add and remove from the types array
const handleClick = (e) => {
  const filter =  e.target.value;
  if (types.includes(filter)){
    types = types.filter(item => item !== filter)
  } else {
    types.push(filter);
  }
  filterTypes(types);
};
[Omit ...]
//One of three checkboxes
  <Input className="form-check-input" id="fundraisers-checkbox" type="checkbox" defaultChecked value="fundraiser" onChange={ handleClick } />
<Label className="form-check-label" htmlFor="fundraisers-checkbox">fundraisers</Label>
[Omit ..]

          <BootstrapTable  keyField='id' data={ donations } columns={ columns } pagination={ pagination } defaultSorted={ defaultSort } filters={ filterFactory() } />
];
```
Which renders fine:
![image](https://user-images.githubusercontent.com/39102/48481250-c3f61e00-e804-11e8-9274-4e43483e6a75.png)

However, no matter what filter I code in: text, select, or multiselect, I receive the following error on page load:

> index.js:1452 Warning: Failed prop type: The prop `onFilter` is marked as required in `SelectFilter`, but its value is `undefined`.
    in SelectFilter (created by HeaderCell)
    in HeaderCell (created by Header)
    in tr (created by Header)
    in thead (created by Header)
    in Header (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by Context.Consumer)
    in PaginationProvider (created by Context.Consumer)
    in SortProvider (created by Context.Consumer)
    in DataProvider (created by BootstrapTableContainer)
    in BootstrapTableContainer (at Donations.js:245)
[Omit...]

And when I enter a filter, or choose it from either select field rendered, I receive this error:

> select.js:275 Uncaught TypeError: this.props.onFilter is not a function
    at SelectFilter.filter (select.js:275)
    at HTMLUnknownElement.callCallback (react-dom.development.js:144)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:193)
    at invokeGuardedCallback (react-dom.development.js:243)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:258)
    at executeDispatch (react-dom.development.js:615)
    at executeDispatchesInOrder (react-dom.development.js:640)
    at executeDispatchesAndRelease (react-dom.development.js:740)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:753)
    at forEachAccumulated (react-dom.development.js:720)
    at runEventsInBatch (react-dom.development.js:896)
    at runExtractedEventsInBatch (react-dom.development.js:906)
    at handleTopLevel (react-dom.development.js:5074)
    at batchedUpdates$1 (react-dom.development.js:18374)
    at batchedUpdates (react-dom.development.js:2299)
    at dispatchEvent (react-dom.development.js:5154)

Any help would be greatly appreciated as everything else is working brilliantly with React Bootstrap Table 2!

Cheers!

**Comment by jonrandahl** [comment]
I'm working on a set of component filters based on the filter examples in the docs and the storybook, namely the select filter examples found here: [Programmatically Select Filter](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Select%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and here: [Programmatically Multi Select Filter](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Multi%20Select%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) with the following code:

```
[omit...]

import BootstrapTable from 'react-bootstrap-table-next';
import paginationFactory from 'react-bootstrap-table2-paginator';
import filterFactory, { textFilter, selectFilter, multiSelectFilter } from 'react-bootstrap-table2-filter';

[omit...]

let filterTypes;

const selectOptions = {
  "fundraiser": 'Fundraiser',
  "donate_button": 'Donate Button',
  "charity_page": 'Charity Page'
};

const columns = [
  [Omit ...]
  {
    dataField: 'Source Name',
    text: 'Type',
    formatter: cell => selectOptions[cell],
    sort: true,
//    filter: textFilter({
//      getFilter: (filter) => {
//        filterTypes = filter;
//      }
//    }),
    filter: selectFilter({
      options: selectOptions,
      getFilter: (filter) => {
        filterTypes = filter;
      }
    }),
//    filter: multiSelectFilter({
//      options: selectOptions,
//      getFilter: (filter) => {
//        filterTypes = filter;
//      }
//    }),
  },

  [Omit...]
//get the same options for the types array
let types = Object.keys(selectOptions).map(key => key: key);

//This works as expected to add and remove from the types array
const handleClick = (e) => {
  const filter =  e.target.value;
  if (types.includes(filter)){
    types = types.filter(item => item !== filter)
  } else {
    types.push(filter);
  }
  filterTypes(types);
};
[Omit ...]
//One of three checkboxes
  <Input className="form-check-input" id="fundraisers-checkbox" type="checkbox" defaultChecked value="fundraiser" onChange={ handleClick } />
<Label className="form-check-label" htmlFor="fundraisers-checkbox">fundraisers</Label>
[Omit ..]

          <BootstrapTable  keyField='id' data={ donations } columns={ columns } pagination={ pagination } defaultSorted={ defaultSort } filters={ filterFactory() } />
];
```
Which renders fine:
![image](https://user-images.githubusercontent.com/39102/48481250-c3f61e00-e804-11e8-9274-4e43483e6a75.png)

However, no matter what filter I code in: text, select, or multiselect, I receive the following error on page load:

> index.js:1452 Warning: Failed prop type: The prop `onFilter` is marked as required in `SelectFilter`, but its value is `undefined`.
    in SelectFilter (created by HeaderCell)
    in HeaderCell (created by Header)
    in tr (created by Header)
    in thead (created by Header)
    in Header (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by Context.Consumer)
    in PaginationProvider (created by Context.Consumer)
    in SortProvider (created by Context.Consumer)
    in DataProvider (created by BootstrapTableContainer)
    in BootstrapTableContainer (at Donations.js:245)
[Omit...]

And when I enter a filter, or choose it from either select field rendered, I receive this error:

> select.js:275 Uncaught TypeError: this.props.onFilter is not a function
    at SelectFilter.filter (select.js:275)
    at HTMLUnknownElement.callCallback (react-dom.development.js:144)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:193)
    at invokeGuardedCallback (react-dom.development.js:243)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:258)
    at executeDispatch (react-dom.development.js:615)
    at executeDispatchesInOrder (react-dom.development.js:640)
    at executeDispatchesAndRelease (react-dom.development.js:740)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:753)
    at forEachAccumulated (react-dom.development.js:720)
    at runEventsInBatch (react-dom.development.js:896)
    at runExtractedEventsInBatch (react-dom.development.js:906)
    at handleTopLevel (react-dom.development.js:5074)
    at batchedUpdates$1 (react-dom.development.js:18374)
    at batchedUpdates (react-dom.development.js:2299)
    at dispatchEvent (react-dom.development.js:5154)

Any help would be greatly appreciated as everything else is working brilliantly with React Bootstrap Table 2!

Cheers!

**Comment by AllenFang** [comment]
@do-diegoortiz thanks your answer. 

> I wonder if you can leave that field empty, or how should we deal with this case when we don't need to define the dataField in a column? 🤔

Check [column.isDummyField](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnisdummyfield-bool)

**Comment by jonrandahl** [comment]
Thanks for the feedback @do-diegoortiz and @AllenFang, I really appreciate your time to respond!

I've now tried both of your responses by
1. modifying the key in the json response to not have spaces:
```
      const newData = donations.map(item => ({
        CHARGE_DATE: item["Charge Date"],
        SOURCE_NAME: item["Source Name"],
        NET_PAYOUT_AMOUNT: item["Net Payout Amount"],
        ...item
      }));
```
and using the "new" key in the dataField:
```
  {
    dataField: 'SOURCE_NAME',
    text: 'Type',
    classes: 'text-primary',
    sort: true,
    formatter: cell => selectOptions[cell],
    filter: multiSelectFilter({
      options: selectOptions,
      getFilter: (filter) => {
        filterTypes = filter;
      }
    })
  },
```

which still throws both the load and event errors as noted in the OP so I'm not sure this is not still a bug?

2. Added the `isDUmmyField` prop to the column:
```
  {
    dataField: 'SOURCE_NAME',
    isDummyField: true,
    text: 'Type',
    classes: 'text-primary',
    sort: true,
    formatter: cell => selectOptions[cell],
    filter: multiSelectFilter({
      options: selectOptions,
      getFilter: (filter) => {
        filterTypes = filter;
      }
    })
  },
```
which now causes the field in the table to be empty, which is expected as noted in the docs:
> There's only one different for dummy column than normal column, which is dummy column will compare the whole row value instead of cell value when call shouldComponentUpdate.

Any other thoguhts?

**Comment by AllenFang** [comment]
@jonrandahl would you please create an online example on https://codesandbox.io ?

here is an example: https://codesandbox.io/s/nvv87rx5l

**Comment by do-diegoortiz** [comment]
> [column.isDummyField](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnisdummyfield-bool)

That link solved my problem. :+1: 
@jonrandahl problem seems to be different, so go ahead and config a codesanbox to show your code in "real life" and find the solution you're looking for.

**Comment by jonrandahl** [comment]
@AllenFang thanks for reopening the issue! Here's a codesandbox as requested with the error I'm experiencing!

https://codesandbox.io/s/0qojzjl2qv

Let me know how I can help further and thanks once again for everything!

**Comment by AllenFang** [comment]
@do-diegoortiz  about your question, the sendbox is not create by myself, it's just a developer show me some issue via https://codesandbox.io . However, it's welcome to show your question via https://codesandbox.io.  Sometime, I just feel like it's much easy to understand everyone's question. Thanks

**Comment by AllenFang** [comment]
@jonrandahl I think the issue you face is you have a type:

```
<BootstrapTable keyField='id' data={fundraisers} columns={columns} defaultSorted={defaultSort} filters={filterFactory()} />
```

It should be `filter` instead of `filters`

**Comment by jonrandahl** [comment]
@AllenFang, I can't believe I missed that! 🤔 

It's working perfectly, thank you so much! 👍 

On my dev instance, the external filter checkboxes are working as expected too! 🥇 

If there's any way I can repay you for your time please do not hesitate to ask! 🙏

**Comment by AllenFang** [comment]
Thanks @jonrandahl   a star for this repo is the best reward for me :)

**Comment by jonrandahl** [comment]
@AllenFang I've already starred the repo, let me know if I can help otherwise! I'm still embarrassed that I missed the extra 's' on the filter prop! #lookingatthecodetoolong

**Comment by CrystalCo** [comment]
I would like to add (for newbies like me) that if you're using ToolkitProvider, the filter prop is not considered a baseProp (and neither is selectRow or expandRow from what I experienced).  So I resolved the above issue by moving the filter prop from  ToolkitProvider  to  Bootstrap :

```
<ToolkitProvider
  keyField="id"
  data={ this.props.tracks }
  columns={ columns }
  bootstrap4={true} 
  defaultSorted={ defaultSorted } 
  columnToggle
>
  {
    props => (
      <div>
        <ToggleList { ...props.columnToggleProps } />
        <hr />
        <BootstrapTable 
          { ...props.baseProps } 
          selectRow={ selectRow } 
          expandRow={ expandRow }
          filter={ filterFactory() }
        />
      </div>
    )
  }
</ToolkitProvider>
```

**Comment by prateek-sinha** [comment]
Hi @AllenFang 

Could you please help me filter text in  a dummy column. 
Also, is there a way to have the header of the table fixed/sticky so that it doesn't move on scrolling.

I am a big fan of react-bootstrap-table and really appreciate your promptness always.

Thanks in Advance.
