### ISSUE TITLE
Is there any way to possible save text in a cell in a different format? 

### ISSUE THREAD

**Issue by rohankk2** [react-bootstrap-table/react-bootstrap-table2#668]
Essentially i want to save tags for my rows. I have a column called tags and want to save save text in that column in this format: 
<img width="139" alt="screen shot 2018-11-15 at 2 21 53 pm" src="https://user-images.githubusercontent.com/29401337/48585559-d7c38200-e8e1-11e8-9d87-f846ac144378.png">

**Comment by AllenFang** [comment]
@rohankk2 sure, please check [column.formatter](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function)
