### ISSUE TITLE
Custom selection column

### ISSUE THREAD

**Issue by Mujaddadi** [react-bootstrap-table/react-bootstrap-table2#671]
Hi, 
    Is there anyway to create custom selection column or is there any way to manipulate selection in column formatter. The problem is, I have two columns with JSON data and three columns with custom data created by using column's formatter property. When user click something in one custom column, I need to make the checkbox selected. 

I tried using `selected: [0]` in selectRow by using selected rows as default select but the `selected` is not working. Then I tried using my own custom  row selection checkboxes by removing `selectRow` completely from `react-bootstrap-table-next`  but the table stop rerendering. Probabaly it assumes if there is no selectRow then the table is static. 

Here is the columns and selectRow code

```
const servicesColumns = [
      {
        dataField: 'name',
        text: 'Nimi',
        sort: true,
        headerClasses: styles.servcie_name_header,
      }, {
        dataField: 'price',
        text: 'Price(€)',
        sort: true,
        formatter: this.priceFormatter,
        headerClasses: styles.price_header,
      }, {
        dataField: 'quantity',
        text: 'Quantity',
        formatter: this.quantityFormatter,
        hidden: this.state.hideExtraSmall,
        headerClasses: styles.quantity_header,
      }, {
        dataField: 'total',
        text: 'Total(€)',
        formatter: this.totalFormatter,
        hidden: this.state.hideExtraSmall,
        headerClasses: styles.total_header,
      }, {
        dataField: 'legend',
        text: 'Invoice legend',
        formatter: this.legendFormatter,
        hidden: this.state.hideLarge,
        headerClasses: styles.legend_header,
      },
    ];

    const selectRow = {
      mode: 'checkbox',
      clickToSelect: true,
      selected: [0],
      onSelect: this.handleOnSelect,
    }

``` 
Please let me know if there is anyway to solve this issue. 

Thanks!

**Comment by AllenFang** [comment]
I think there's only one way is `selectRow.selected`.  This accept an "rowkey" array.

for example: following is my row data:

```js
var data = [{
  id: 'A',
  name: 'AAAA'
},{
  id: 'B',
  name: 'fddds'
},{
  id: 'C',
  name: '123'
}]
```

if you wanna make row 'A' and 'C' be selected,  you can do it like that:

```js
selectRow = {
  ....,
selected: ['A', 'C']
}
```

[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an online example to show you how to manage row selection.

**Comment by AllenFang** [comment]
Tag me if you still can not solve this issue.

**Comment by Mujaddadi** [comment]
@AllenFang I don't have `id` field in data, the id is called `serviceId`, which I tried selecting but didn't work. It will be good if we pass the selection handler into any of the call back functions of columns.
