### ISSUE TITLE
I can't use event properties on onSelect's method

### ISSUE THREAD

**Issue by Gi972** [react-bootstrap-table/react-bootstrap-table2#675]
Hello,

When I select a row , I try to have the event.currentTarget, but I can't because I have the following message:

Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `currentTarget` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

Same thing in the event columns properties.

Also It's possible have the columnIndex as parameter on the onSelect method? 
and in selectRow -> classes method . 

Thanks

**Comment by AllenFang** [comment]
@Gi972  I will fix the issue about synthetic event problem.







> Also It's possible have the columnIndex as parameter



> Also It's possible have the columnIndex as parameter on the onSelect method?
> and in selectRow -> classes method .

I think it's impossible in current design.

**Comment by AllenFang** [comment]
@Gi972 fixed on `react-bootstrap-table-next@1.4.2`

**Comment by DrogoNevets** [comment]
should this fix be present in v2.1.0 too?
