### ISSUE TITLE
Is there any way to toggle(show/hide) columns dynamically?

### ISSUE THREAD

**Issue by ashishsable27** [react-bootstrap-table/react-bootstrap-table2#677]
Hello Team,
I am looking for dynamically hiding/showing column which should  allow  user to select which columns they want to be visible.

**Comment by AllenFang** [comment]
currently, we dont support this issue and it's a duplicated issue, I will consider to implement it in the future. thanks @ashishsable27

**Comment by rushtokunal** [comment]
@AllenFang - Toggle column visibility is highly desired so that user can select the columns they are interested in viewing

**Comment by AllenFang** [comment]
We have new release for fixing this issue: please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/) and upgrade related packages

[this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-column-toggle.html) is docs for column toggle and [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Toggle&selectedStory=Basic%20Column%20Toggle&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is online demo

Please open another issue if you find any bugs, thanks
