### ISSUE TITLE
Export only Filtered rows without selection?

### ISSUE THREAD

**Issue by ashishsable27** [react-bootstrap-table/react-bootstrap-table2#678]
Is there any way to export all the filtered rows without select box?

Example:
Total rows in table 10.
I am applying search filter on Name Column.
After applying search filter table shows 2 rows but when I click on export CSV contains all 10 rows.
Is there any way to export only those 2 rows without selection?

**Comment by AllenFang** [comment]
@ashishsable27   check [exportCSV.exportAll](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/export-csv-props.html#exportcsvexportall-bool). 

Please tag me if this issue still remain, thanks
