### ISSUE TITLE
expandColumnRenderer add parameter row

### ISSUE THREAD

**Issue by Gi972** [react-bootstrap-table/react-bootstrap-table2#679]
Hello, 

Sometimes, fews rows must don't to be expand.
It's possible to pass a row like parameter or un prop for determinate if is expandable or not?

On the version 1 the propertie isExpandableRow was used for that.

Thanks

**Comment by AllenFang** [comment]
@Gi972 sorry for lately reply, I think you can try [expandRow.nonExpandable](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrownonexpandable-array).

Please tag me if above solution can not solve your question, thanks!
