### ISSUE TITLE
incorrect story

### ISSUE THREAD

**Issue by waynebrantley** [react-bootstrap-table/react-bootstrap-table2#680]
The data does not have an ``onSale`` property in order to show the styling changes the demo is meant to show.

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Work%20on%20Columns&selectedStory=Column%20Formatter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by AllenFang** [comment]
thanks @waynebrantley I will fix it :)
