### ISSUE TITLE
onFilter(filteredData)

### ISSUE THREAD

**Issue by narayanchoudhary** [react-bootstrap-table/react-bootstrap-table2#682]
I have a table, in this table, there are two columns which display the class and height of the students, Now I want to display the sum of the heights of the students. When I filter the class column the table shows the data of students of the filtered class. Now I also want to show the sum of the height of the filtered students.

Basically, I want a callback function which takes the filtered data. something just like this.

columns = [{
  dataFied: 'class,
  filter: textFilter(),
  onFilter: (filteredData) => {  /* set state here */  }
},
{
  dataFied: 'class,
  filter: textFilter(),
}];

Is there any option available for this? @AllenFang 
Thanks

**Comment by AllenFang** [comment]
@narayanchoudhary currently, we dont support the table sum feature, so you have to do it by yourself.  in the `onFilter` listener, you can get the filtered data so that i think you are able to do more advance calculation, like sum etc.

Please tag me if my answer is not helpful to you, thanks

**Comment by narayanchoudhary** [comment]
Thanks, @AllenFang But I am still unable to figure out how to get the filtered data. Can you please show me a reference in the storybook or somewhere.
Thanks.

**Comment by narayanchoudhary** [comment]
> @narayanchoudhary currently, we dont support the table sum feature, so you have to do it by yourself. in the `onFilter` listener, you can get the filtered data so that i think you are able to do more advance calculation, like sum etc.
> 
> Please tag me if my answer is not helpful to you, thanks

Thanks, @AllenFang But I am still unable to figure out how to get the filtered data. Can you please show me a reference in the storybook or somewhere.
Thanks.

**Comment by AllenFang** [comment]
@narayanchoudhary  you can use exposed API to get current data which displayed on table:
https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html#get-current-display-rows

**Comment by Punithbn** [comment]
I have used bootstrap table and in that table default filter search will be there. 
But i need some customization while filtering the items in search area., such that if user has to type minimum three(3) characters to obtain any search in the table. 


can anyone help me :) in this.... please reply to this comment

**Comment by GabrielNicolasAvellaneda** [comment]
Using the exposed-api, to get the filtered data you should access `this.node.filterContext.data`
