### ISSUE TITLE
[Customize pagination] Ability of setting an icon for Prev/Next buttons

### ISSUE THREAD

**Issue by stsiushkevich** [react-bootstrap-table/react-bootstrap-table2#683]
Hello! At this moment there is no ability to set an icon to Prev Next page buttons. 

![image](https://user-images.githubusercontent.com/12151060/49001016-723a8580-f16c-11e8-8f43-112b5380c772.png)

We can change only a text, but if there is a custom design such ability is useless. Please, could you add an ability to set custom icons into this buttons? Like this: 

![image](https://user-images.githubusercontent.com/12151060/49001143-e1b07500-f16c-11e8-8202-3a0b0b113325.png)

They look prettier.)

**Comment by AllenFang** [comment]
@stsiushkevich I'm working on improving the ability for customization on pagination. it's coming soon :)

**Comment by stsiushkevich** [comment]
> @stsiushkevich I'm working on improving the ability for customization on pagination. it's coming soon :)

I'm looking forward to it!)

**Comment by sgwcollins** [comment]
@AllenFang Hey! any update on the customization of the pagination

**Comment by AllenFang** [comment]
@stsiushkevich It is stil WIP.  Hope I can finish it in the end of this year

**Comment by stsiushkevich** [comment]
> @sgwcollins It is stil WIP. Hope I can finish it in the end of this year

Ok!)

**Comment by AllenFang** [comment]
@chandanaccure we have new release -> [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/12/24/version.bump.html)

Please read this [DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#customization) to learn how to custom pagination component and also check some online [DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) 

I will encourage you to check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Custom%20Page%20Button&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) to see how to custom a page button.

Please open a issue if you get any questions or issues, thanks!
