### ISSUE TITLE
expandRow - Load data in specific columns instead of entire row

### ISSUE THREAD

**Issue by dilushi** [react-bootstrap-table/react-bootstrap-table2#685]
Hi @AllenFang,
This is regarding expand row feature of react-bootstrap-table2.
When expanded a row, currently it shows the data in entire row.
Is it possible to display data in specific columns when expanding the row?

In runtime, expanded row is like this.
<tr class="expanding-row"><td colspan="8">

Is it possible to override this colspan or load data in specific columns?
Appreciate any support on this.

Thank you.

**Comment by AllenFang** [comment]
@dilushi currently, we don't support this feature, so PR is welcome, thanks
