### ISSUE TITLE
Turn on and off the editor dynamically

### ISSUE THREAD

**Issue by jbp17** [react-bootstrap-table/react-bootstrap-table2#692]
I have two access groups, one can view only and the other has full access to edit the table.  Is it possible to use the same table, turn on and off the editor feature based on the access group?  If so, how?

Thanks,

**Comment by AllenFang** [comment]
@jbp17 we support different editable level, you can check it more in [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-celledit.html#editable-cell)

Following is some examples:

[Row level editable](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Row%20Level%20Editable&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
[Column level editable](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Column%20Level%20Editable&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
[Cell level editable](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Cell%20Level%20Editable&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

Please tag me if above solution is not helpful to you, thanks

**Comment by jbp17** [comment]
@AllenFang Thank you for your response.  They won't solve my problem.  What I am looking for is easy way to turn on and off table-level editable or not based on Windows credential or AD group.  Is there any switch to do that?

Thanks,

**Comment by AllenFang** [comment]
@jbp17 we dont support this kind of toggle, but if you wanna turn off the cell editing, just dont give the `cellEdit` prop on `BootstrapTable`
