### ISSUE TITLE
table-layout is fixed

### ISSUE THREAD

**Issue by Mujaddadi** [react-bootstrap-table/react-bootstrap-table2#700]
Any idea why the table layout property is fixed? It made table overgrow the smaller screen size. Although I can overwrite it, just wanted to confirm the purpose of it.  
```
react-bootstrap-table table {
     table-layout: fixed; 
}
```

**Comment by Mujaddadi** [comment]
Fixed by changing some of my styles.

**Comment by jabberwo** [comment]
How did you override it?  I'm not having any luck using the "classes" option to the BootstrapTable object.

**Comment by Bopzor** [comment]
@jabberwo, you can override the `table-layout` of `react-bootstrap-table` css using this selector:
`.react-bootstrap-table table`
