### ISSUE TITLE
expandColumnRenderer not returning rowKey

### ISSUE THREAD

**Issue by sgwcollins** [react-bootstrap-table/react-bootstrap-table2#701]
I hope this is an easy change but can you make the expandColumnRenderer return the rowKey it would help a ton I tried to make a pull request but i didnt have the permission so it might just be easier to open up an issue here is how far i got and it seemed to work
`react-bootstrap-table2/row-expand/expand-cell.js`

` render() {
    const { expanded, expandColumnRenderer, tabIndex,rowIndex } = this.props;
    const attrs = {};
    if (tabIndex !== -1) attrs.tabIndex = tabIndex;

    return (
      <td onClick={ this.handleClick } { ...attrs }>
        {
          expandColumnRenderer ? expandColumnRenderer({
            expanded,
            rowIndex
          }) : (expanded ? '(-)' : '(+)')
        }
      </td>
    );
  }`
@AllenFang

**Comment by sgwcollins** [comment]
@AllenFang

**Comment by AllenFang** [comment]
@sgwcollins   fixed in `react-bootstrap-table-next@1.4.3`

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/12/21/version-bump.html

Check this: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowexpandcolumnrenderer-function
