### ISSUE TITLE
React-bootstrap-table2-toolkit - csvExport - encoding

### ISSUE THREAD

**Issue by roneymaia** [react-bootstrap-table/react-bootstrap-table2#702]
Hi, 
I'm having a problem exporting the csv file. What happens is that the encode of the file is coming as UTF-8 and when opening in excell the characters are inregular form.

Is there any way to specify the encode of the file ?

**Comment by AllenFang** [comment]
@roneymaia  I will try to fix this issue, thanks!

**Comment by AllenFang** [comment]
@roneymaia could you please add [exportCSV.noAutoBOM](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/export-csv-props.html#exportcsvnoautobom-bool) as `false`?  thanks


```js
<ToolkitProvider
      keyField="id"
      data={ products }
      columns={ columns }
      exportCSV={ {
        noAutoBOM: false
      } }
    >
...
</ToolkitProvider>
```

**Comment by roneymaia** [comment]
> @roneymaia could you please add [exportCSV.noAutoBOM](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/export-csv-props.html#exportcsvnoautobom-bool) as `false`? thanks
> 
> ```js
> <ToolkitProvider
>       keyField="id"
>       data={ products }
>       columns={ columns }
>       exportCSV={ {
>         noAutoBOM: false
>       } }
>     >
> ...
> </ToolkitProvider>
> ```

Thanks @AllenFang . I did not know that MS Excel needed the byte order marker with UTF-8.

**Comment by AllenFang** [comment]
Cool @roneymaia, so no auto BOM can save your issue?!

**Comment by roneymaia** [comment]
Yes. Thanks a Lot.

**Comment by lovato-hp** [comment]
@AllenFang This solved my problem too. I had no idea what AutoBOM was, and at the documentation, there is no explanation about what it does.

**Comment by lovato** [comment]
@AllenFang This solved my problem too. I had no idea what AutoBOM was, and at the documentation, there is no explanation about what it does.

**Comment by AllenFang** [comment]
@lovato I'm not very familiar with it, actually, it's a property in https://github.com/eligrey/FileSaver.js

**Comment by jonrandahl** [comment]
@AllenFang just to let you know I'm experiencing this issue again on the current version (toolkit-2.0.1) and I've tried both `noAutoBOM: false` and `noAutoBOM: true` as well as manually passing in the blob type (`'text/plain;charset=utf-8'`) and the characters in Excel are exporting as follows:
![image](https://user-images.githubusercontent.com/39102/63425446-739d9380-c408-11e9-962e-0b5b316f0c87.png)
and the same data in Numbers:
![image](https://user-images.githubusercontent.com/39102/63425506-9b8cf700-c408-11e9-9171-dd6c187578fc.png)
I've checked the changes in the [latest release](https://github.com/react-bootstrap-table/react-bootstrap-table2/compare/react-bootstrap-table2-toolkit%402.0.0...react-bootstrap-table2-toolkit%402.0.1) and can't see where this would be caused but I'm probably not looking in the right place!

Would you like me to open a new ticket to keep things tidier?

**Comment by g-akshay** [comment]
Try setting the blob type to `blobType: "data:text/csv;charset=utf-8,%EF%BB%BF"`

**Comment by yousefshakoury** [comment]
> Try setting the blob type to `blobType: "data:text/csv;charset=utf-8,%EF%BB%BF"`

Thanks for you, so where I do it?

**Comment by iamnamananand996** [comment]
> Try setting the blob type to `blobType: "data:text/csv;charset=utf-8,%EF%BB%BF"`

not worked for me.
