### ISSUE TITLE
Show column in editable mode when select a row

### ISSUE THREAD

**Issue by technomanuj** [react-bootstrap-table/react-bootstrap-table2#704]
Hi,
I have just started using react-bootstrap-table2. This table has a lot of good features. I need help to implement a custom functionality. 

Here is my question.
[1] Is it possible that when select a row, then automatically those columns should be shown in editable mode whose editable property is true? Currently I have to do click or double click on that column to bring it in editable mode, that is also a good feature of this table.

Below given is sample code. The product Name field should be shown as a drop down when I click on a row or select a check box because mode property is checkbox in SelectRow prop.

    import React from 'react';
    import BootstrapTable from 'react-bootstrap-table-next';
    import cellEditFactory, { Type } from 'react-bootstrap-table2-editor';
    import 'react-bootstrap-table-next/dist/react-bootstrap-table2.css';
    import 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min.css';
    import { tablePaging, selectRow} from './Paging';

    export default class ProductGridComponent extends React.Component{
        constructor() {
            super();
            this.state = {
            products: [
                {
                    "id": "1",
                    "name": "Book",
                    "price": "18"
                },
                {
                    "id": "2",
                    "name": "Mobile",
                    "price": "400"
                },
                {
                    "id": "3",
                    "name": "PC",
                    "price": "1000"
                },
                {
                    "id": "4",
                    "name": "PS4",
                    "price": "500"
                },
                {
                    "id": "5",
                    "name": "Chromebook",
                    "price": "500"
                }
            ],
            columns: [{
                dataField: 'id',
                text: 'Product ID',
                editable:false
            },
            {
                dataField: 'name',
                text: 'Product Name',
                editable: true,
                editor: {
                    type: Type.SELECT,
                    options: [{
                        value: 'Book',
                        label: 'Book'
                    }, {
                        value: 'Mobile',
                        label: 'Mobile'
                    }, {
                        value: 'PC',
                        label: 'PC'
                    }, {
                        value: 'PS4',
                        label: 'PS4'
                    }, {
                        value: 'Chromebook',
                        label: 'Chromebook'
                    }]
                }
            },
            {
                dataField: 'price',
                text: 'Product Price',
                sort: true,
                editable: false
            }

            ]
          };
       }

        render() {
            return (
                <div>
                    <BootstrapTable
                        striped
                        hover
                        keyField='id'
                        data={this.state.products}
                        columns={this.state.columns}
                        pagination={tablePaging}
                        selectRow={selectRow}
                        cellEdit={cellEditFactory({ mode: 'click' })}/>
                        </div>
            );
        }
    }

-------
    import paginationFactory from 'react-bootstrap-table2-paginator';

    export const tablePaging = paginationFactory({
        sizePerPage: 5,
        showTotal: true,
        onSizePerPageChange: (sizePerPage, page) => {
            console.log('Size per page change!!!');
            console.log('Newest size per page:' + sizePerPage);
            console.log('Newest page:' + page);
        },
        onPageChange: (page, sizePerPage) => {
            console.log('Page change!!!');
            console.log('Newest size per page:' + sizePerPage);
            console.log('Newest page:' + page);
        }
    });

    export const selectRow = {
        mode: 'checkbox',
        clickToSelect: true,
        clickToEdit: true,
        onSelect: (row, isSelect, rowIndex, e) => {
        return true;
         },
       onSelectAll: (isSelect, rows, e) => {
            return true;
        },
        style: { backgroundColor: '#c8e6c9' }
    };

**Comment by AllenFang** [comment]
I think you already know to use `clickToEdit` which mean when you click on row, the clicking target cell will also become editable if it's editable!. however, we don't support the edit a cell when you click on selection's checkbox or radio button.

I think we will support the external cell edit management, however, it's not in my plan so far.

**Comment by technomanuj** [comment]
Ok Allen , No problem. I will try to find other way to solve my problem.

**Comment by yenicelik** [comment]
@technomanuj any updates on how you solved this?
