### ISSUE TITLE
onSelect and onSelectAll

### ISSUE THREAD

**Issue by patrickmillerson** [react-bootstrap-table/react-bootstrap-table2#706]
I think there should be an unSelect and unSelectAll event in stead of only onSelect and onSelectAll.

**Comment by AllenFang** [comment]
right now, we only implement onSelect and onSelectAll and not much critical issue there, I think your suggestion is make sense but it will be a major change, so i think so far I will do any change on this. thanks 👍

**Comment by shubuu97** [comment]
Hi Allen, i found a issue in react-bootstrap-table that if all rows are selected and if we change the page no then the selectAll button keeps on showing while the values are not selected and also in case of sorting it does not updates the values if we selectAll.

**Comment by vtarelkin-comprehend** [comment]
@shubuu97 did you fix it?
