### ISSUE TITLE
Format Column Date

### ISSUE THREAD

**Issue by vwen01** [react-bootstrap-table/react-bootstrap-table2#707]
Is there a built in way to format the cell data that comes in as a number with a large amount of decimal places to dollar format $.$$, or does this need to be done via javascript?

**Comment by AllenFang** [comment]
@vwen01 we dont have this built in feature but you can customize it by yourself via [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function)
