### ISSUE TITLE
Get  rowIndex  from Cell Button

### ISSUE THREAD

**Issue by OSadd** [react-bootstrap-table/react-bootstrap-table2#710]
I am trying to delete a row of the table using a button in a column. I want to pass the rowindex to delete it, but not sure how to do this?

<Button     onClick={(e) => this.Deleterow(**rowIndex**)}>>
          </Button>

**Comment by AllenFang** [comment]
i think if you use [`column.formatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) to custom you column, the `column.formatter` already pass the `rowIndex` to you:

```js
columns = [..., {
  text: '...',
  dataField: '...',
  formatter: (cell, row, rowIndex) => (<button onClick={ () => this.Deleterow(rowIndex)  }>delete me</button>)
}];
```

**Comment by AllenFang** [comment]
Just take care the `this`

**Comment by AllenFang** [comment]
tag me if you still have any question, thx

**Comment by OSadd** [comment]
Thanks Allen.

To delete a row, I need a reference to the table {data} to update the state, I'm not sure how this would work using formatter?

**Comment by do-diegoortiz** [comment]
I think you can update the state in the function you're calling in the button, in this case, `Deleterow`. Probably the [formatExtraData](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatextradata-any) could be useful for you too

**Comment by OSadd** [comment]
I had columns defined outside the class. Moving inside, allowed the table to be in scope with the formatter callback.
