### ISSUE TITLE
Hide table row

### ISSUE THREAD

**Issue by aniov** [react-bootstrap-table/react-bootstrap-table2#711]
Hello, 
Is there a way I can hide a row? 
I need the data to be inside the table, but some rows I don't want to be displayed 
(for example let's say row % 2 === 0).

Thank you.

**Comment by AllenFang** [comment]
@aniov you dont have this feature, I will implement it ASAP, thanks

**Comment by AllenFang** [comment]
@aniov fixed in `react-bootstrap-table-next@1.4.3`

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/12/21/version-bump.html

Check this: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#hiddenrows-array
