### ISSUE TITLE
Is there a way to add a custom column?

### ISSUE THREAD

**Issue by Jatapiaro** [react-bootstrap-table/react-bootstrap-table2#713]
I need to add an extra column to render some actions for each element in my table. Is there a way to achieve that? I cant find something related to that on the docs.

**Comment by AllenFang** [comment]
@Jatapiaro use dummy column -> [column.isDummyField](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnisdummyfield-bool)

Please tag me if you still have any questions, thanks
