### ISSUE TITLE
Pagination position option not available

### ISSUE THREAD

**Issue by chandanaccure** [react-bootstrap-table/react-bootstrap-table2#714]
Pagination position option not available. by default the pagination always appears at bottom. It should provide a option to select `bottom|top|both`

**Comment by AllenFang** [comment]
@chandanaccure I'm working on improving the customization on pagination, it's coming soon

**Comment by chandanaccure** [comment]
Hi @AllenFang If you want some help in managing this repository let me know. I would like to contribute.

**Comment by AllenFang** [comment]
@chandanaccure sure,  i really need some people can join me for a long time contribution. I can not give you the money but you can get the credit on your contribution board lol

I need a developer who is strong on react/redux and css, if you are good, feel free to join me.  `reacct-bootstrap-table2` has a huge code base, you can try to read it firstly when you are interesting. that's always first step if you want to do some contributions :)

**Comment by AllenFang** [comment]
@chandanaccure we have new release -> [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/12/24/version.bump.html)

Please read this [DOCS](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html#customization) to learn how to custom pagination component and also check some online [DEMO](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Basic%20Pagination%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) 

We dont support the `top|bottom` this kind of props, but you can arrange the component position by yourself. I will encourage you to check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20Pagination%20List&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) and [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20SizePerPage%20Dropdown&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) examples to see how standalone work.

Please open a issue if you get any questions or issues, thanks!
