### ISSUE TITLE
detect filter 

### ISSUE THREAD

**Issue by rohankk2** [react-bootstrap-table/react-bootstrap-table2#715]
Is there any way to detect that a filter has happened in the table ? 
I need to link the current data in the table to another component dynamically. As soon as table data changes the data in the other component should change. 

Thanks,
Rohan

**Comment by AllenFang** [comment]
@rohankk2 current, we didn't support a filter hooks function, so I will implement it soon. if we have a post filter hooks function, you can know there's some filters changes the get the newest data to your another component. 

Thanks

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/06/version-bump.html)

Please upgrade `react-bootstrap-table-next@2.0.1`, `react-bootstrap-table2-paginator@2.0.1` and `react-bootstrap-table2-filter@1.1.1`

Now, every kind filter support `onFilter` hook: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/filter-props.html#textfilteronfilter-function

[Example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Filter%20Hooks&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
