### ISSUE TITLE
How to display text limit in table

### ISSUE THREAD

**Issue by senthilmca90** [react-bootstrap-table/react-bootstrap-table2#716]
Hi, I installed `react-bootstrap-table-next` npm new version. how can i display limited text. because table row lot of unwanted space. anyone can help me.

![image](https://user-images.githubusercontent.com/14997781/50149227-96f3ca00-02e0-11e9-8cdf-7e61d9e97ed3.png)

the output look like this.  
> Angular is a typescript based open source front-end web application framework...

**Comment by AllenFang** [comment]
it's a default behavior, you can try to add some css via [column.style](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnstyle-object-function) or [column.classes](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnclasses-string-function) like:

```
    white-space: nowrap;
    text-overflow: ellipsis;
    overflow: hidden;
```

**Comment by senthilmca90** [comment]
@AllenFang Thanks. It's works fine
