### ISSUE TITLE
Column header hides but not columnBody or columnData

### ISSUE THREAD

**Issue by the-yadu** [react-bootstrap-table/react-bootstrap-table2#719]
Upon storing column info in state and then updating a column's hidden attribute on click of a button  only hides the columnHeader and not the columnData.

The state is mutating properly as the columnHeader is hiding as expected.

```
 state = {
        columns: [{
            dataField: 'eta',
            text: 'Driver ETA',
            hidden: false
        }, {
...
```
 above code shows both columnHeader and columnData correctly but upon mutating hidden to true on click of a button only hides the columnHeader.

**Comment by AllenFang** [comment]
@the-yadu I will check this out, thanks

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/06/version-bump.html)

Please upgrade `react-bootstrap-table-next@2.0.1`

**Comment by Suntikka** [comment]
Having this exact issue with react-bootstrap-table-next@2.1.2.
