### ISSUE TITLE
Search and Sort not working

### ISSUE THREAD

**Issue by amad-aleem123** [react-bootstrap-table/react-bootstrap-table2#720]
A few days ago table search and sorting was working just fine. but now suddenly it stopped to work. IDK why its happening. I tried to reinstall it but still nothing, kindly help. 
Versions using,
        "react-bootstrap-table-next": "^1.4.2",
        "react-bootstrap-table2-toolkit": "^1.1.1"

**Comment by AllenFang** [comment]
Hello @amad-aleem123 you information is not enough for me to reproduce your issue, Itry to reproduce but I can not make it. please write more information and give me a simple or minimal example here or on the codesandbox.io.

I will reopen this issue until you know how to give people enough information, thanks.

**Comment by amad-aleem123** [comment]
I don't have anything else to tell. I just know everything was working absolutely fine, then suddenly it stopped working. Kindly tell me what more information you want so I can elaborate.

**Comment by amad-aleem123** [comment]
If you still don't understand my problem, then let me share my screen with you on Skype.

**Comment by amad-aleem123** [comment]
Hello.
 First of all I implemented two option for this table, Sort and Search. Both were working fine. But i don't know what really happened, they stopped working. When  i search something it doesn't work, same is the case with Sort. when I click on sort icons, it won't sort. below is my code. I am sending data and columns as props in it.
  
```
import React, { Component } from "react";
import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';
import BootstrapTable from 'react-bootstrap-table-next';
import ToolkitProvider, { Search } from 'react-bootstrap-table2-toolkit';
const { SearchBar } = Search;
export default class Table extends Component {
    render() {
        return (
            <ToolkitProvider keyField={this.props.keyField} data={this.props.data} columns={this.props.columns} search bootstrap4>
                {
                    props => (
                        <div>
                            <SearchBar style={{ width: '300px' }} {...props.searchProps} />
                            <hr />
                            <BootstrapTable {...props.baseProps} />
                        </div>
                    )
                }
            </ToolkitProvider >
        );
    }
}
```
