### ISSUE TITLE
Enable Column visibility toggle out of the box

### ISSUE THREAD

**Issue by rushtokunal** [react-bootstrap-table/react-bootstrap-table2#723]
Toggle column visibility is highly desired so that user can select the columns they are interested in viewing. We are also planning to save the user's preference in the database so that in future when they log back in we can give them their preferred view. If this feature is not supported now or is not going to be implemented in near future could you please help with an example to implements it programatically
using the prop: hidden

**Comment by AllenFang** [comment]
I will implement it in the future.

**Comment by rushtokunal** [comment]
Any idea when this feature might be added?

**Comment by AllenFang** [comment]
@rushtokunal I will consider to implement this in next sprint or next two sprint, thanks!

**Comment by rushtokunal** [comment]
@AllenFang  thank you Allen, just a suggestion while implementing this feature, it will be helpful if we have APIs to render the table based(saved preference) on the column selected by the user. I'm actually saving the preference of my user and retrieving that when the same user logs back in to the application so that the user doesnt have to re select the columns again. BTW this is a great component.

**Comment by AllenFang** [comment]
I see, it's a good point, for your suggestion, I think that will be good by following two solution:

First one is built-in solution:
```js
// column definition:

const column = [{
  dataField: 'id',
  text: 'Product ID',
  toggle: false // false will hidden the column 
}, {
  dataField: 'name',
  text: 'Product Name'
}, {
  dataField: 'price',
  text: 'Product Price'
}];
```

Second one is developer actually can easy control the column hide by state control:

const column = [{
  dataField: 'id',
  text: 'Product ID',
  hidden: somestate.hidden // true will hide the column 
}, {
  dataField: 'name',
  text: 'Product Name'
}, {
  dataField: 'price',
  text: 'Product Price'
}];
```

[`column.hidden`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnhidden-bool) already supported

**Comment by rushtokunal** [comment]
@AllenFang Yes i agree with you, once the column visibility is first checked by the user, based on his preference we can use the api to toggle visibility

**Comment by AllenFang** [comment]
We have new release for fixing this issue: please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/) and upgrade related packages

[this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-column-toggle.html) is docs for column toggle and [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Toggle&selectedStory=Basic%20Column%20Toggle&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is online demo

Please open another issue if you find any bugs, thanks

**Comment by rushtokunal** [comment]
@AllenFang thanks a ton for implementing this, will take a look and confirm
