### ISSUE TITLE
expand row fails if nonExpandable key is not present in expandRow

### ISSUE THREAD

**Issue by hirenvadalia** [react-bootstrap-table/react-bootstrap-table2#725]
See https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Basic%20Row%20Expand&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

And click on 0 in Product Id and check Action Logger

Looks like the problem is at https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2/src/contexts/row-expand-context.js#L26

**Comment by AllenFang** [comment]
@hirenvadalia it's a new bug cause by newest release, I will fix it ASAP

**Comment by hirenvadalia** [comment]
Thanks @AllenFang, looking for next release as I am badly blocked by this issue.

**Comment by AllenFang** [comment]
@hirenvadalia fixed in `react-bootstrap-table-next@1.4.4`. Sorry about this accident

**Comment by hirenvadalia** [comment]
Thanks for quick response, much appreciated, please keep it up.
