### ISSUE TITLE
props type mismatch for SizePerPageOption

### ISSUE THREAD

**Issue by hirenvadalia** [react-bootstrap-table/react-bootstrap-table2#729]
I am getting below warning in paginator (2.0.0)
```
Warning: Failed prop type: Invalid prop `page` of type `object` supplied to `SizePerPageOption`, expected `number`.
    in SizePerPageOption (created by Context.Consumer)
    in SizePerPageDropDown (created by SizePerPageDropdownAdapter)
    in SizePerPageDropdownAdapter (created by Pagination)
    in div (created by Pagination)
    in div (created by Pagination)
    in Pagination (created by PaginationHandler)
    in PaginationHandler (created by PaginationDataProvider)
    in PaginationDataProvider (created by Context.Consumer)
    in SortProvider (created by Context.Consumer)
    in DataProvider (created by BootstrapTableContainer)
    in BootstrapTableContainer (created by <removed>)
```
Looks like the problem is at https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2-paginator/src/size-per-page-dropdown.js#L74

I think instead of `{...option}` it should be `page = {option.value}` as SizePerPageOption has only 4 props and while using default option renderer it is passing all 4 props so there is no point of passing full option to SizePerPageOption. It makes sense to pass full option to when the user is using custom option renderer.

Also found same issue #352 but I can't reopen that so creating a new one.

**Comment by AllenFang** [comment]
@hirenvadalia ok, I will handle it, thanks and happy new year lol

**Comment by juancafe4** [comment]
`      sizePerPageList: [
        {
          text: '10',
          value: 10,
        },
        {
          text: '25',
          value: 25,
        },
        {
          text: 'All',
          value: dataTotalSize,
        },
      ],`

I am using Redux and dataTotalSize is 0 in my initial State and then is updated when I fetch data.
When dataTotalSize is 0 I see that error but if you set up that variable greater than 0 error disappears.

**Comment by AllenFang** [comment]
ok, I will also check this, thanks @juancafe4

**Comment by AllenFang** [comment]
@hirenvadalia what sizePerPage data you given?

**Comment by hirenvadalia** [comment]
For me issue is exactly same as what @juancafe4 is facing.

**Comment by AllenFang** [comment]
Thanks

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/06/version-bump.html)

Please upgrade `react-bootstrap-table-next@2.0.1`, `react-bootstrap-table2-paginator@2.0.1`
