### ISSUE TITLE
Custom cell edit doesnt trigger table render

### ISSUE THREAD

**Issue by teaklvs** [react-bootstrap-table/react-bootstrap-table2#735]
Hi, 
I have custom cell editor and applying row style if cell was changed. The status of the cell for the particular is changed in aftersavecell function and therefor appropriate style is applied when rendering. It all worked well until I upgraded the packages to the last versions react-bootstrap-table2-editor@1.2.2 and react-bootstrap-table-next@2.0.0. My previous version were  "react-bootstrap-table-next": "^1.1.1" and "react-bootstrap-table2-editor": "^1.0.0". After upgrading, it seems that the table is not being re-rendered after cell editing. Please advise how can I solve this issue?

Thanks!

**Comment by AllenFang** [comment]
@teaklvs yes, we did some performance tuning. so can you provide me an minimal and simple example to reproduce this issue?  You can put the example on codesandbox.io

[this](https://codesandbox.io/s/0xvw06wxpv) is an example which created by other issue reporter, thanks :)

**Comment by AllenFang** [comment]
BTW, how you custom the row style? thanks

**Comment by YassienW** [comment]
This seems to be happening with formatter too, here is an [example](https://codesandbox.io/s/qv3q2y9ry6)

On initial render, the label is displayed fine. However after clicking the button the data changes but the format isn't applied properly

**Comment by AllenFang** [comment]
@YassienW I will check again for your issue, btw, did you fix it? sorry for lately reply.

**Comment by AllenFang** [comment]
@YassienW I think your case is interesting, your formatter make the `shouldComponentUpdate` return `false` always due to your column filed is `name` but in this column formatter, you reference another field: `alert`.  So internally, the row level is rerender but cell level is not

**Comment by AllenFang** [comment]
@YassienW I fixed your issue: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/24/version-bump.html

**Comment by YassienW** [comment]
Thanks a lot for the quick fix Allen. I did manage to fix it by setting the column to be a dummy field, or using formatExtraData as discussed on #629. I'm not sure if this is intentional though

**Comment by AllenFang** [comment]
@YassienW i think `dummy` field is for a column which is just display a button or something else instead of an actual data field.,  In you example, it's absolutely correct for me.

I encourage developer to use `formatExtraData`  when you need some data which is not belong to the `cell` and `row` value.
