### ISSUE TITLE
don't display table 

### ISSUE THREAD

**Issue by armohammadi56** [react-bootstrap-table/react-bootstrap-table2#737]
![error](https://user-images.githubusercontent.com/34424135/50616297-17c7de00-0efd-11e9-8a80-e6706c0e63f2.png)

`<BootstrapTable
              id="UniversitiesTable"
              name="UniversitiesTable"
              keyField="id"
              pagination={paginationFactory()}
              data={this.props.entities}
              columns={columns}
              filter={filterFactory()}
              selectRow={selectRow}
            />`
"react-bootstrap-table-next": "^1.4.4",
"react-bootstrap-table2-filter": "^1.1.0",
"react-bootstrap-table2-paginator": "^2.0.0",
 "react": "^16.7.0",
"react-dom": "^16.7.0",

**Comment by AllenFang** [comment]
@armohammadi56  please upgrade `react-bootstrap-table-next` to version 2

**Comment by armohammadi56** [comment]
tnx :-)
