### ISSUE TITLE
partial table update

### ISSUE THREAD

**Issue by yandreiy** [react-bootstrap-table/react-bootstrap-table2#739]
Is there a way to update only a specific cell / cells, not the whole table ? 
Currently I'm trying to implement editing of a cell while the table is being updated, and don't see any other APIs for partial update.

**Comment by AllenFang** [comment]
@yandreiy hi, right now we dont have this kind of feature.

**Comment by yandreiy** [comment]
Ok, thanks. Do you have any plans to add this ?

**Comment by AllenFang** [comment]
@yandreiy  so far no,  but PR is welcome :)
