### ISSUE TITLE
ToolkitProvider and PaginationProvider not working together

### ISSUE THREAD

**Issue by AshCorah** [react-bootstrap-table/react-bootstrap-table2#740]
Is it possible to have a fully custom pagination component with the toolkit provider that provides search capabilities?

How do you pass the props for data through to both modules?
Below code shows the two wrapped components. Also I have enabled remote for Pagination, does PaginationProvider currently support remote?
```
    <Row>
          <PaginationProvider
            pagination={paginationFactory({
              custom: true,
              totalSize,
              page,
              sizePerPage,
            })}
            keyField="id"
            columns={columns}
            data={data}
          >
            {
              ({
                paginationProps,
                paginationTableProps,
              }) => (
                <div>
                  <ToolkitProvider
                    bootstrap4
                    search
                    {...paginationTableProps}
                  >
                    {
                      props => (
                        <Col>                     
                          <Row>
                            <SearchBar
                              placeholder="Search customers and invoices..."
                              {...props.searchProps}
                            />
                          </Row>
                          <Row>
                            <BootstrapTable
                              ref={n => this.node = n}
                              noDataIndication="No results!"
                              headerClasses={style.header}
                              rowClasses={style.row}
                              bordered={false}
                              defaultSorted={[{
                                dataField: 'Name',
                                order: 'desc',
                              }]}
                              remote={{
                                filter: true,
                                pagination: true,
                                sort: true,
                              }}
                              selectRow={selectRow}
                              expandRow={expandRow}
                              onTableChange={this.handleTableChange}
                              // pagination={paginationFactory({ page, sizePerPage, totalSize })}
                              {...paginationTableProps}
                              {...props.baseProps}
                            />
                            <PaginationListStandalone
                              {...paginationProps}
                            />
                            <SizePerPageDropdownStandalone
                              {...paginationProps}
                            />
                          </Row>
                        </Col>
                      )
                    }
                  </ToolkitProvider>
                </div>
              )
            }
          </PaginationProvider>
        </Row>
```
`TypeError: _this.props.isRemotePagination is not a function`

**Comment by oitozero** [comment]
👍

**Comment by AllenFang** [comment]
@AshCorah   @oitozero sorry, I didn't provide a example to show how to use remote mode in custom pagination.

Following is an example:

```js
```

**Comment by AllenFang** [comment]
I will also check if there's any issue when use search and pagination, thanks

**Comment by AllenFang** [comment]
BTW please upgrade `react-bootstrap-table-next` to version 2  

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2018/12/24/version.bump.html

If you want to have new pagination customization mechanism, please upgrade below packages to version 2

react-bootstrap-table-next@2.0.0
react-bootstrap-table2-paginator@2.0.0

**Comment by AshCorah** [comment]
Is there any way to get your above example working with ToolkitProvider? I think this is where the issue is

**Comment by AllenFang** [comment]
sorry, I got serious disease, I will look into this issue again in this weekend, thanks

**Comment by eslynunez** [comment]
@AllenFang I am sorry to hear that, I hope you feel better! I came here with the same issue. Is there a work around example?

**Comment by AllenFang** [comment]
@eslynunez you also enable the `remote` mode?  maybe an example will be appreciated 👍

**Comment by AllenFang** [comment]
@eslynunez  @AshCorah i can not reproduce this error, following is my code, hope someone can indicate how to reproduce this issue, thanks

```js
const RemoteFilter = ({
  data,
  totalSize,
  page,
  sizePerPage,
  onTableChange
}) => (
  <div>
    <PaginationProvider
      pagination={ paginationFactory({
        custom: true,
        totalSize,
        page,
        sizePerPage
      }) }
      keyField="id"
      columns={ columns }
      data={ data }
    >
      {
        ({
          paginationProps,
          paginationTableProps
        }) => (
          <ToolkitProvider
            keyField="id"
            columns={ columns }
            data={ data }
            search
          >
            {
              toolkitprops => (
                <SearchBar { ...toolkitprops.searchProps } />
                <BootstrapTable
                  { ...toolkitprops.baseProps }
                  { ...paginationTableProps }
                  remote={ { search: true, pagination: true } }
                  onTableChange={ onTableChange }
                />
                <PaginationListStandalone { ...paginationProps } />
              )
            }
          </ToolkitProvider>
        )
      }
    </PaginationProvider>
  </div>
);
```

**Comment by AshCorah** [comment]
Reproduced with your example:
Following packages:
    "react-bootstrap-table-next": "^2.0.0",
    "react-bootstrap-table2-filter": "^1.1.0",
    "react-bootstrap-table2-paginator": "^2.0.0",
    "react-bootstrap-table2-toolkit": "^1.1.1",

![image](https://user-images.githubusercontent.com/26364927/51541524-534d2c80-1e59-11e9-907f-2c3cafa73b12.png)

**Comment by AllenFang** [comment]
@AshCorah ok, cool. now,,, I dont know how to reproduce this.  any more idea?

**Comment by AllenFang** [comment]
https://codesandbox.io/s/jlol04qrxv  I just create an example on codesandbox, it work well @AshCorah

**Comment by AllenFang** [comment]
I will reopen this issue if anyone can tell me or show me how to reproduce this issue,

**Comment by AshCorah** [comment]
Thanks for this - I'll try and use your example on codesandbox to figure out what is happening here. Could this be anything to do with me using Redux in my application?

**Comment by AllenFang** [comment]
@AshCorah i think `react-bootstrap-table2` is compatible with any state management like Mobx or Redux.

Anyway, I encourage developer to write an example on codesandbox for reproducing issue, here is a basic example to create it:

https://codesandbox.io/s/jlol04qrxv

**Comment by AshCorah** [comment]
Hey Allen, 
![image](https://user-images.githubusercontent.com/26364927/51741139-5719c280-2096-11e9-811a-58d495aa1af3.png)  🎉

Finally sorted this, styled component above - I'm not sure what was wrong, maybe I wasn't passing the correct props but your examples were extremely useful at fixing my problem. 

Thanks a lot!

**Comment by dejongbaba** [comment]
@AshCorah Please how were you able to combine both the ToolkitProvider and PaginationProvider together. Please, can you show your working example?
