### ISSUE TITLE
Reset Table

### ISSUE THREAD

**Issue by juancafe4** [react-bootstrap-table/react-bootstrap-table2#748]
Is there a way to reset the table. I am using React select to filter out data ( remote data), but when data changes or I clear up the filter (data  resets) onTableChange is never being called, so I am not able to set page and number of items to the initial state.

**Comment by AllenFang** [comment]
> but when data changes

how you change the data, re-render table with new data?

> I clear up the filter

How you clear the filter

@juancafe4 sorry for lately reply, I got serious disease from last week.

**Comment by juancafe4** [comment]
not problem I figured it out version 1 had .a reset function when you ref the table. But I manage this by only using onTableChange
