### ISSUE TITLE
Create BasicTable Not Working

### ISSUE THREAD

**Issue by 1112266** [react-bootstrap-table/react-bootstrap-table2#749]
I Run - 

> npm install react-bootstrap-table-next --save

 in my project and add 
boostrap 4 - 

> import 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css';

after I copy from link getstart boostrap 2 :https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/getting-started.html

> import BootstrapTable from 'react-bootstrap-table-next';
> 
> const products = [];
> const columns = [{
>     dataField: 'id',
>     text: 'Product ID'
> }, {
>     dataField: 'name',
>     text: 'Product Name'
> }, {
>     dataField: 'price',
>     text: 'Product Price'
> }];
> 
> export default () =>
>     <BootstrapTable keyField='id' data={products} columns={columns} />
> 

. But running  it's show error 
×

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
> Check the render method of `BootstrapTableContainer`.

You can help me

**Comment by AllenFang** [comment]
@1112266 I guess your react version is too old, please upgrade to newest one(at least react@14.0.0)

**Comment by 1112266** [comment]
{
  "name": "ReactJs01",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@coreui/coreui": "^2.1.4",
    "bootstrap": "^3.3.7",
    "react": "^16.5.2",
    "react-bootstrap": "^0.31.5",
    "react-bootstrap-table-next": "^2.0.1",
    "react-dom": "^16.0.0",
    "react-icons": "^2.2.7",
    "react-image": "^1.5.1",
    "react-redux": "^5.0.6",
    "react-router-bootstrap": "^0.24.4",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.8",
    "react-scripts": "1.0.17",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0",
    "rimraf": "^2.6.2"
  },
  "scripts": {
    "start": "rimraf ./build && react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
sorry . i using react 16.2
