### ISSUE TITLE
Can we get rid of bootstrap?

### ISSUE THREAD

**Issue by thevangelist** [react-bootstrap-table/react-bootstrap-table2#75]
I was wondering can we get rid of bootstrap alltogether, isn't it used only for styling the table to look better?

Bootstrap.min.css at least contains redundant CSS styles for the project. In fact the table should be merely a React-table (well, a better name of course...) IMHO.

**Comment by AllenFang** [comment]
HI, actually, this repo is depend on bootstrap styling,
1. `react-bootstrap-table2` and `react-bootstrap-table` doesn't use `Bootstrap.min.css` directly, it was control by yourself, you can use bootstrap loader or other tool to insert the css you want only.

2. The target of this repo is focus on react table with bootstrap styling,

it's very sorry that we dont drop the bootstrap and thanks your feedback 👍
