### ISSUE TITLE
Cell edit mode doesn't close when value was not changed

### ISSUE THREAD

**Issue by slavaradune** [react-bootstrap-table/react-bootstrap-table2#753]
Hi Allen,
I am looking at the example of Custom Editor for editing cells in the following link:
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Custom%20Editor

and it seems that if I enter the "edit mode", but change nothing, I cannot exit the edit mode by clicking outside the table or on other non-editable cell.
I have a similar issue in my project.
Am I missing some way to get it work?

Thanks!!

**Comment by AllenFang** [comment]
@slavaradune sorry for lately, I got serious disease from last week.

I guess this is element focus issue, I can reproduce it by above example. You can try to do [HTML DOME focus](https://www.w3schools.com/jsref/met_html_focus.asp) on your editor when your custom editor rendered.

Please tag me if the issue still remain, thanks
