### ISSUE TITLE
Question: dynamic data that MAY have nested objects, how to handle?

### ISSUE THREAD

**Issue by Werewoof** [react-bootstrap-table/react-bootstrap-table2#755]
Hi there!

I'm currently using React Bootstrap Table 2 to display data that gets fetched from MSSQL SERVER queries  (SELECT * FROM SomeSchema.SomeTable). I'm just using sample data, AdventureWorks2012. 

I'm returning the data from the query as a JSON object. Sometimes I find that the dataField property gets passed the name of a column which, in the data, is an object. So, an object is attempting to be passed into a cell of the column, at which point the application crashes. Is there a way this component can handle that? Or is there some other way via Javascript?

My code is pretty hairy, but I can post it by request.

Many thanks!
-Jon

**Comment by AllenFang** [comment]
sorry for lately reply, I got serious disease from last week,

`react-bootstrap-table2` allow you to render nest data, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columndatafield-required-string)

but it should be specific, I mean in a column, if you give `user.name`, `react-bootstrap-table2` must get the value from each row by `user.name`.

tag me if you have any question, thanks

**Comment by evanz1996** [comment]
`export const items = [
  {
    uid: '934539c0badfa8fa474e20c524aa0ffe',
    name: 'Burger',
    slug: 'burger',
    description: null,
    availability: null,
    menu: [
      {
        uid: '07a8b791a49c90839ca10a5c606ec0e5',
        name: 'Chicken Burger',
        slug: 'chicken-burger',
        description: null,
        availability: null,
        menu: [
          {
            uid: 'd0ce02aae5a873e3ef1a62990ef10b8a',
            name: 'Beef Burger',
            slug: 'beef-burger',
            description: null,
            availability: null,
            menu: [],
          },
        ],
      },
      {
        uid: '234',
        name: 'Vegetable Burger',
        slug: 'chicken-burger',
        description: null,
        availability: null,
        menu: [
          {
            uid: '12345',
            name: 'Potato Burger',
            slug: 'beef-burger',
            description: null,
            availability: null,
          },
          {
            uid: '2345',
            name: 'Fried Burger',
            slug: 'beef-burger',
            description: null,
            availability: null,
          },
        ],
      },
    ],
  },
  {
    uid: '11',
    name: 'Ice Cream',
    slug: 'icecream',
    description: null,
    availability: null,
    menu: [
      {
        uid: '022',
        name: 'Cold Ice cream',
        slug: 'cold-icecream',
        description: null,
        availability: null,
        menu: [
          {
            uid: '1243',
            name: 'Cheese Ice cream',
            slug: 'cheese-icecream',
            description: null,
            availability: null,
            menu: [
              {
                uid: '888',
                name: 'Avocado Ice cream',
                slug: 'cheese-icecream',
                description: null,
                availability: null,
                menu: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
`
Hello  @AllenFang, I wanted to display each menu of this nested array.  I have to access the menu submenus so that when I filter it, it can be still filter from the deeper level of menu name..
