### ISSUE TITLE
Multiple ExportCSV Buttons

### ISSUE THREAD

**Issue by vwen01** [react-bootstrap-table/react-bootstrap-table2#756]
Is it possible to have one exportCSV button to export all data in the table and the other to export only data that is visible on the same dataset.

Vince

**Comment by AllenFang** [comment]
right now, we didn't have this feature. I will explore if you can use some exposed API. I mean we eventually support one export csv button but if you need a button for exporting specific data, you can custom the button and call the exposed API

**Comment by AllenFang** [comment]
```js

createExportAllHandler = ({ onExport }) => () => {
  onExport(YOUR_ALL_DATAS);
};

<ToolkitProvider
          keyField="id"
          data={ products }
          columns={ columns }
          exportCSV
        >
          {
            props => (
              <div>
                <ExportCSVButton { ...props.csvProps }>Export Visible Rows!!</ExportCSVButton>
                <ExportCSVButton { ...props.csvProps } onClick={ .this.createExportAllHandler(props.csvProps) } >Export All Rows!!</ExportCSVButton>
                <hr />
                <BootstrapTable { ...props.baseProps } ref={ n => this.node = n } />
              </div>
            )
          }
        </ToolkitProvider>
```

@vwen01 if it doesn't work, please tag me

**Comment by brandoncoetzee** [comment]
@AllenFang is there any functionality to export data into different sheets? Or does CSV not allow for that? I want to have half of the data in one sheet in excel and half in another sheet in excel?
