### ISSUE TITLE
Clearing filters don't work on date filters

### ISSUE THREAD

**Issue by lindsejs** [react-bootstrap-table/react-bootstrap-table2#758]
When clearing filters with getFilter function on date column/filter it is not possible to pass empty date, exception is thrown on this line:
this.inputDate.value = dateParser(filterVal.date);

**Comment by AllenFang** [comment]
@lindsejs sorry for lately reply, I got serious disease from last week, Will fix this issue ASAP, thanks

**Comment by AllenFang** [comment]
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/01/20/version-bump.html

Fixed on `react-bootstrap-table2-filter@1.1.2`
