### ISSUE TITLE
Table not updating when specific cell is changed (Via API) but works with new data and delete data

### ISSUE THREAD

**Issue by alex5207** [react-bootstrap-table/react-bootstrap-table2#760]
I use the Bootstrap table2 to display data fetched from my API.
I have a component which receives the data as props.

When I add/delete a row via the API, the table is correctly updating to display the new row or remove the deleted one. However, if I change a field on an already existing row the props of the component is correctly updating but the table is not.

Has anyone experienced this issue? It needs a refresh before the change of the field (E.g a name) is displayed.

**Comment by AllenFang** [comment]
@alex5207 how you update a cell? be careful about immutable issues in React application.

**Comment by DrogoNevets** [comment]
I have a similar problem with the footer, adding a row to datasource works fine, but the footer isnt recalculated

**Comment by AllenFang** [comment]
@DrogoNevets, @alex5207  please give me an reproduce example on codesandbox.io.  thanks 

here is an boilerplate you can based on it to write your example: https://codesandbox.io/s/jlol04qrxv

**Comment by AllenFang** [comment]
btw, I have to say that i really dont have enough time to explore or write an example to reproduce your example, I got so many similar issue everyday, so i think please give an example is a big help for me, thx

**Comment by sidorykp** [comment]
I had a similar issue as @alex5207. I debugged **my** code and my issue had a very simple cause: I was **mutating** row objects that I wanted to get updated in the view. Now after I do not mutate such row objects but rather create a **copy with new values** then I have no such issues.

And I think that creating a copy and mutating this copy should also work fine.

My educated guess is that @alex5207 had the same issue as me. If yes then this issue can be safely closed as non-issue.

**Comment by alex5207** [comment]
@sidorykp you were correct I think! Thanks a lot

I had a `RowEvent` which passed `row` directly to setState.
The issue was solved by copying the object using `const rowCopy = JSON.parse(JSON.stringify(row))`

Great!!
