### ISSUE TITLE
isRemotePagination is not a function

### ISSUE THREAD

**Issue by mpnetto** [react-bootstrap-table/react-bootstrap-table2#762]
Hello,
I'm trying to implement pagination in my bootstrap table but I receive the following issue: 
TypeError: _this.props.isRemotePagination is not a function

I'm trying to implement the basic panigation table, but every time I put  pagination={ paginationFactory() } I receive this error. Anyone could help me?

**Comment by AllenFang** [comment]
@mpnetto please list your version here, I guess the issue you face is version.

`react-bootstrap-table-next@2.0.1`
`react-bootstrap-table2-paginator@2.0.1`

Please tag me if the issue still remain, thanks

**Comment by mm3** [comment]
Issue reproduced for me too

versions:
```
    "react-bootstrap-table-next": "^2.0.1",
    "react-bootstrap-table2-editor": "^1.2.2",
    "react-bootstrap-table2-filter": "^1.1.1",
    "react-bootstrap-table2-paginator": "^2.0.1",

```
props:
```

                <BootstrapTable keyField = 'id'
                                data = { this.props.data }
                                columns = { this.props.columns }
                                loading = { this.props.process }
                                noDataIndication= { this.props.noDataStr }
                                defaultSorted ={ this.props.sorting }
                                cellEdit={ cellEditFactory({mode: 'click'}) }
                                expandRow={ {showExpandColumn: true} }
                                filter={ filterFactory() }
                                remote={ { filter: true, cellEdit: true } }
                                onTableChange={ this.onTableChange }
                                pagination={ paginationFactory({ sizePerPageList: [{text: '100', value: 100}] }) }
                                striped hover condensed />

```

**Comment by dppatel03** [comment]
I am also having the same problem. do any can guide me

**Comment by YashLad05** [comment]
@AllenFang I am facing same issue.
Listing my package versions here
`react-bootstrap-table-next@1.4.4` and `react-bootstrap-table2-paginator@2.1.2`
While uninstalling `react-bootstrap-table2-paginator` , I am getting the following error

![image](https://user-images.githubusercontent.com/84368030/204554982-fe022fef-b114-4da7-a295-4195dc1fd4f2.png)

**Comment by ksvbrother** [comment]
Hi,
I'm in the process of implementing pagination using 'react-bootstrap-table2-paginator,' and I have successfully resolved the issues.
TypeError: _this.props.isRemotePagination is not a function


1. "react-bootstrap-table-next": "^4.0.3",
2. "react-bootstrap-table2-paginator": "^2.1.2",
😊😊😊😊
