### ISSUE TITLE
How do I intialize the PaginationProvider in jsx file? 

### ISSUE THREAD

**Issue by nilaynanavati** [react-bootstrap-table/react-bootstrap-table2#765]
I am able to initialize the BootstrapTable and painationFactory in my jsx file like below.
 const BootstrapTable = ReactBootstrapTable2.default;
 const paginationFactory = ReactBootstrapTable2Paginator.default;  

But couldn't initialize the PaginationProvider. I tried multiple ways like below but didn't work out. 

const { PaginationProvider } = ReactBootstrapTable2Paginator.default;
or
const { PaginationProvider } = ReactBootstrapTable2Paginator.PaginationProvider ;

**Comment by AllenFang** [comment]
@nilaynanavati it should be:
```js
const { PaginationProvider } = ReactBootstrapTable2Paginator;
```
