### ISSUE TITLE
Table not shown on mobile Firefox

### ISSUE THREAD

**Issue by borgdrone7** [react-bootstrap-table/react-bootstrap-table2#767]
Hi,

When I open your demo on Firefox on iPad I see only blank page for all the examples. They work on Chrome on iPad but don’t fit correctly. Is this only issue with storybook or the table actually is not working on Firefox on iPad?

Thanks

**Comment by AllenFang** [comment]
@borgdrone7 I think it should be work, I tested it and it work well.  any idea?
