### ISSUE TITLE
Caption element for table

### ISSUE THREAD

**Issue by thevangelist** [react-bootstrap-table/react-bootstrap-table2#77]
See: https://www.w3schools.com/TAgs/tag_caption.asp

I am thinking that it should allow a React element or a string. With element you could put custom stuff inside it, or for example styling.

See WIP test screenshot:

<img width="457" alt="screen shot 2017-10-04 at 8 40 05" src="https://user-images.githubusercontent.com/3482617/31161426-b0826a32-a8df-11e7-9038-6ebac8e5c3ce.png">

**Comment by AllenFang** [comment]
@thevangelist, ok we will support it, thanks a lots :)
