### ISSUE TITLE
Footer is just a new row

### ISSUE THREAD

**Issue by DrogoNevets** [react-bootstrap-table/react-bootstrap-table2#771]
the new functionality for the footer, should be in `tfoot` tag not just another row.

this would allow custom styling in css alone

**Comment by AllenFang** [comment]
<img width="1202" alt="2019-01-22 10 15 52" src="https://user-images.githubusercontent.com/5351390/51541305-74327380-1e93-11e9-8b8b-9a55e26176c6.png">

I think it's a `tfoot`
