### ISSUE TITLE
PaginationListStandalone not working right with Filter

### ISSUE THREAD

**Issue by jrvaldiviaffdc** [react-bootstrap-table/react-bootstrap-table2#778]
Hi Allen!  I've been trying yo use the Standalone component for the pagination on a Table that is not using the remote mode but I've found that, when used with the filter, it doesn't recognize the prop totalSize automatically as it used to

This is a simple demonstration of what I have
```
import React, { Component } from 'react';
import BootstrapTable from 'react-bootstrap-table-next';
import paginationFactory, { PaginationProvider, PaginationListStandalone } from 'react-bootstrap-table2-paginator';
import cellEditFactory from 'react-bootstrap-table2-editor';
import filterFactory from 'react-bootstrap-table2-filter';

const
	columns = [{
		dataField: 'id',
		text: 'Product ID',
		filter: textFilter({
			placeholder: 'Enter Value',
			getFilter: (filter) => this.addFilter('Identifier', type, filter, '')
		})
	}, {
		dataField: 'name',
		text: 'Product Name',
		filter: textFilter({
			placeholder: 'Enter Value',
			getFilter: (filter) => this.addFilter('IdentifierParent', type, filter, '')
		})
	}],

	products = [{
		Id =1,
		Name ='product 1'
	}, {
		Id =2,
		Name ='product 2'
	}, {
		Id =3,
		Name ='product 3'
	}];

class Table extends Component {
	constructor(props) {
		super(props);
	}

	render() {
		let
			options = {
				custom: true,
				paginationSize: 4,
				pageStartIndex: 1,
				firstPageText: 'First',
				prePageText: 'Back',
				nextPageText: 'Next',
				lastPageText: 'Last',
				nextPageTitle: 'First page',
				prePageTitle: 'Pre page',
				firstPageTitle: 'Next page',
				lastPageTitle: 'Last page',
				showTotal: true,
			}
		contentTable = ({ paginationProps, paginationTableProps }) => {
			return (<div>

				<PaginationListStandalone
					{...paginationProps}
				/>
				<div>
					<div>
						<BootstrapTable
							keyField='Id'
							data={products}
							columns={columns}
							filter={filterFactory()}
							cellEdit={cellEditFactory(this.props.editOptions)}
							striped
							hover
							{...paginationTableProps}
						/>
					</div>
				</div>
				<PaginationListStandalone
					{...paginationProps}
				/>
			</div>);
		};
		return (
			<div>
				<PaginationProvider
					pagination={
						paginationFactory(options)
					}
				>
					{contentTable}
				</PaginationProvider>
			</div >
		);
	}
}

export default Table;

```
Is there a way to fix it or it not support yet? 
Thank you for your hard work!

**Comment by AllenFang** [comment]
Fixed, please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/09/version-bump.html), please remember to upgrade the packages which mention in `RELEASE NOTE` to make sure you have correct patchs

**Comment by agarciaffdc** [comment]
Thank you so much @AllenFang for the fix. @jrvaldiviaffdc is on leave these days but your fix will help us to unblock our task. We will take a look and back to you if we have any question. 

Thanks again

**Comment by AllenFang** [comment]
Please tag me if you guys have any question, thanks @agarciaffdc

**Comment by VarunVaro** [comment]
Hi AllenFang, I am new to react-bootstrap-table-next. I need your input. I have data column named "email" , i am using radio as selection mode for Row. when selection of row new Modal will open with data of selected row, i do change email there in modal and save. the data which i modified in modal it's not change in Table, may i know what's the reason and how to update the table?
