### ISSUE TITLE
Sorting remotely

### ISSUE THREAD

**Issue by neasar** [react-bootstrap-table/react-bootstrap-table2#780]
Hi There,

This tool is awesome and perfect for my project. I just can't see how to sort a Table remotely.

What I want to do:
I have a table with columns/table headers that allow sorting, each row of this table can be expanded. When a row is expanded it reveals a sub table. The main table columns/headers now sort the expanded row's table. I am looking for a way to initiate the sorting of the sub table on click of a different div.

I noticed you had [Manage sorting externally](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-sort.html#manage-sorting-externally) as coming soon, any idea when this might be?

Any ideas on how I can achieve this would be greatly appreciated 😄 

Thanks
Neasa

**Comment by AllenFang** [comment]
@neasar hello, sorry for lately reply, [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Sort&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is a remote sort example :)



> I am looking for a way to initiate the sorting of the sub table on click of a different div.

I think there are two feasible ways:

1. Use [`expandRow.onExpand`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowonexpand-function)
2. Use default sort or manage sort externally


Please open another issue when you still have any question, thanks !
