### ISSUE TITLE
Using a react-redux component in expandRow keeps loading the data indefinitely

### ISSUE THREAD

**Issue by lorenzosjb** [react-bootstrap-table/react-bootstrap-table2#781]
Thanks for reading,

I have a component that renders a react-bootstrap-table2. Each row has a basic expandRow that renders a component. When the user clicks a row, it will load the data (using axios and redux) of the event and show it in a nested table.

The problem that I have, is that component keeps loading the data indefinitely. So this is the order that I load the components.

events.js (sends the parameters for each event)
-> event-details-container.js (loads the data)
--> event-details-component.js (just shows the data)

I do test that event-details-container.js renders correctly separately.
Where the problem can be located? 

Thanks.

**Comment by AllenFang** [comment]
No response for a long time.
