### ISSUE TITLE
Customise global search button

### ISSUE THREAD

**Issue by tester5** [react-bootstrap-table/react-bootstrap-table2#783]
How do I customize the Global Search edit box without adding a button?  I want to:

- Make the Search button right justified like in react-bootstrap v1
- Fire an update when the search edit box changes that updates the route/URL to enable a permalink

Below is what I have (default)

Many thanks in advance.

```
return (
    <div>
      <ToolkitProvider
        keyField="id"
        data={rows}
        columns={envColumns}
        search={{ defaultSearch: '' }}
      >
        {
          props => (
            <div>
              <SearchBar {...props.searchProps} />
              <BootstrapTable {...props.baseProps} filter={filterFactory()} condensed striped hover />
            </div>
          )
        }
      </ToolkitProvider>
    </div>
  )
```

**Comment by AllenFang** [comment]
@tester5 hello, The ability to custom on `SearchBar` component is limited, at least you can update class, style placeholder etc. but if you want to do more advance customization, you can check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Fully%20Custom%20Search&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example.

i think `react-bootstrap-table2` is more customizable than version 1, we already allow developer to rearrange the position of component or even repaint whole the part of search, pagination etc.

Please pin me here or open another issue if you have any question. thanks

**Comment by tester5** [comment]
Hi @AllenFang many thanks for the message above, it was helpful.  Was able to customise the Search bar using this example: https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Fully%20Custom%20Search&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

However I also wish to be able to pass in a filter URL param like so:
```
/view/0?filter=check
```
where "check" would be updated in the input field value.  It actually does this and I am able to update the route by typing into the text box as well as get value updated on page refresh.

However, the filter is not activated on page refresh, and currently you have to hit enter (i.e. activate onKeyPress) to get the filter to apply on initial page refresh.  Any idea how this can be achieved?

This is a snippet of the custom search component I created.

```
const MySearch = (searchProps) => {
    let input
    const handleSearch = () => {
      searchProps.onSearch(input.value)
      props.history.push(`${baseUrl}?filter=${input.value}`)
    }

    return (
      <div>
        {defSearch ? (
          <div style={{ display: 'flex', flexDirection: 'row', marginTop: '1px' }}>
            <input
              id="searchInput"
              className="form-control"
              style={{ backgroundColor: 'white', width: '100%', marginBottom: '1px' }}
              ref={n => input = n}
              type="text"
              autoFocus={true}
              onChange={handleSearch}
              onKeyPress={handleSearch}
              title="Hit any key to filter..."
              value={defSearch}
            />
            <label htmlFor='searchInput' style={{ fontSize: '10px', textAlign: 'center', marginTop: '3px' }}>Auto refresh</label>
            <AutoRefreshButton />
          </div>
        ) : (
            <div style={{ display: 'flex', flexDirection: 'row', marginTop: '1px' }}>
              <input
                id="searchInput"
                className="form-control"
                style={{ backgroundColor: 'white', width: '100%', marginBottom: '1px' }}
                ref={n => input = n}
                type="text"
                autoFocus={true}
                onChange={handleSearch}
                placeholder="Start typing to filter..."
                title="Start typing to filter..."
              />
              <label htmlFor='searchInput' style={{ fontSize: '10px', textAlign: 'center', marginTop: '3px' }}>Auto refresh</label>
              <AutoRefreshButton />
            </div>
          )}
      </div>
    )
  }
```
