### ISSUE TITLE
Text filter search issue

### ISSUE THREAD

**Issue by samashok12005** [react-bootstrap-table/react-bootstrap-table2#786]
Hi,

The text filter is not working properly.
Steps to reproduce.
1. Search randomly using text filter in the table.
2.First couple of searches gives the result properly.
3. Then another search produces some random results in table.

Is there a way to fix it?

Thanks 
Ashok S.

**Comment by samashok12005** [comment]
Fixed this issue using onFilter method. But column filter with pagination not working as expected.

**Comment by AllenFang** [comment]
@samashok12005 would you please show me your code via codesandbox, [here](https://codesandbox.io/s/jlol04qrxv) is an example you can take.

In addition, give me more information as you can, let will easier for me to help you, thanks

**Comment by samashok12005** [comment]
Hi Allen,
Thanks for the reply.
I have more records(700) and it's for specific client. So i can't share everything.But the columns and table and pagination options.
Step1: I have two column text filters.
Step2: I do the search  and finish it.and click on the pagination to page 5 or 6.
Stesp: Search again on column filter. It gives wrong results.

Try with more number of records.


this.scheduleDataColumns = [{
      dataField: [constants.REQ_BODY_CDTYR],
      text: [constants.LABEL_CDT_YEAR],
      headerClasses: [constants.LABEL_THEAD_DESIGN]
    }, {
      dataField: "id.cDT",
      text: [constants.LABEL_CDT],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      style: {
        width: "8%"
      },
      filter: textFilter({
        style: {
          width: "80%",
          fontSize: "11px"
        },
        // comparator: Comparator.EQ,
        onFilter: (value) => {
          value = value.toUpperCase();
          if (value.length === 0) {
            this.setState({ scheduleData: [] });
            this.setState({ scheduleData: this.state.originalScheduleData });
          } else if (value.length > 0) {
            const filterRecords = this.state.originalScheduleData.filter((row) => {
              return row.id.cDT;
            });
            this.setState({ scheduleData: [] });
            this.setState({ scheduleData: filterRecords });
          }
        },
      }),
      events: {
        onClick: (e, column, columnIndex, row, rowIndex) => {
          this.editSchedule(row, rowIndex, e);
        }
      },
      formatter: (cell) => {
        return (
          <a href className="cursorTblPtr">{cell}</a>
        );
      }
    }, {
      dataField: [constants.REQ_BODY_NOMENCLATURE],
      text: [constants.LABEL_NOMENCLATURE],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      filter: textFilter({
        style: {
          width: "80%",
          fontSize: "11px"
        },
        onFilter: (value) => {
          if (value.length === 0) {
            this.setState({ scheduleData: [] });
            this.setState({ scheduleData: this.state.originalScheduleData });
          } else if (value.length > 0) {
            const filterRecords = this.state.originalScheduleData.filter((row) => { return row.nomenclature; });
            this.setState({ scheduleData: [] });
            this.setState({ scheduleData: filterRecords });
          }
        }
      }),
      style: (cell, row, rowIndex, colIndex) => {
        return {
          whiteSpace: "nowrap",
          textOverflow: "ellipsis",
          overflow: "hidden",
          maxWidth: "150px"
        };
      },
      events: {
        onMouseEnter: (e, column, columnIndex, row, rowIndex) => {
          e.target.style.whiteSpace = "normal";
        },
        onMouseLeave: (e, column, columnIndex, row, rowIndex) => {
          e.target.style.whiteSpace = "nowrap";
        }
      }
    }, {
      dataField: [constants.REQ_BODY_CDT_CLASS],
      text: [constants.LABEL_CDT_CLASS],
      headerClasses: [constants.LABEL_THEAD_DESIGN]
    }, {
      dataField: [constants.REQ_BODY_MC],
      text: [constants.LABEL_MC],
      headerClasses: [constants.LABEL_THEAD_DESIGN]
    }, {
      dataField: [constants.REQ_BODY_BENEFIT_LEVEL],
      text: [constants.LABEL_BENEFIT_TIER],
      headerClasses: [constants.LABEL_THEAD_DESIGN]
    }, {
      dataField: "",
      text: [constants.LABEL_COVERAGE],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      formatter: (e, column, columnIndex, row, rowIndex) => {
        return column.coverage === "1" ? "Yes" : "";
      }
    }, {
      dataField: "",
      text: [constants.LABEL_IN_NETWORK_COINS_COPAY],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      style: {
        width: "5%"
      },
      formatter: (e, column, columnIndex, row, rowIndex) => {
        if (productType === constants.COPAY) {
          return (productType === constants.COPAY && column.coPayment != null) ? column.coPayment : "";
        }
        return (productType === constants.COINS && column.coInsurance != null) ? column.coInsurance : "";
      }
    }, {
      dataField: [constants.REQ_BODY_COINSURANCE_ONN],
      text: [constants.LABEL_OON_COINS_COPAY],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      style: {
        maxWidth: "75px"
      }
    }, {
      dataField: [constants.REQ_BODY_CONDITIONAL_LIMIT],
      text: [constants.LABEL_CONDITIONS_LIMITATIONS],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      style: {
        width: "20%"
      },
      formatter: (cell, row) => {
        return (
          <span>{ReactHtmlParser(cell)}</span>
        );
      }
    }, {
      dataField: [constants.REQ_BODY_ADDITIONAL_LIMIT],
      text: [constants.LABEL_ADDITIONAL_LIMIT],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      style: {
        width: "20%"
      },
      formatter: (cell, row) => {
        return (
          <span>{ReactHtmlParser(cell)}</span>
        );
      }
    }, {
      dataField: [constants.REQ_BODY_NOTES],
      text: [constants.LABEL_NOTES],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      style: {
        width: "20%"
      },
      formatter: (cell, row) => {
        return (
          <span>{ReactHtmlParser(cell)}</span>
        );
      }
    }, {
      dataField: [constants.REQ_BODY_ORDER_DC],
      text: [constants.LABEL_ORDER_DC],
      headerClasses: [constants.LABEL_THEAD_DESIGN]
    }, {
      dataField: [constants.REQ_BODY_BENCHMARK],
      text: [constants.LABEL_BENCHMARK],
      headerClasses: [constants.LABEL_THEAD_DESIGN]
    }
    ];
------
export const paginationOptions = {
    paginationSize: 100,
    pageStartIndex: 1,
    firstPageText: "First",
    prePageText: "Back",
    nextPageText: "Next",
    lastPageText: "Last",
    nextPageTitle: "First page",
    prePageTitle: "Pre page",
    firstPageTitle: "Next page",
    lastPageTitle: "Last page",
    showTotal: true,
    sizePerPageList: [{
        text: "100", value: 100
    }, {
        text: "150", value: 150
    }, {
        text: "200", value: 200
    }],
    hidePageListOnlyOnePage: true
};
----
table 

<BootstrapTable keyField='id.cDT' width='100' height='250' noDataIndication={"No data available"} scrollTop={"Bottom"} data={scheduleData} columns={this.scheduleDataColumns}
            filter={filterFactory()} pagination={paginationFactory(utility.paginationOptions)}  striped="true" />

**Comment by AllenFang** [comment]
hello, @samashok12005 you can just extract part of code to codesandbox.. at least a simple and minimal code for me to reproduce your issue, you dont need to create 700 records, just 12 or any numbers are enough for me to reproduce this issue.

if you really can not share a example code to me for reproducing, at least you should show me your configuration for filter, search and pagination. In addition do u enable remote mode?  Please give me enough information so that I can help you.  I will reopen this issue until I can identify this issue is a truly bug. Thanks

**Comment by samashok12005** [comment]
Hi Allen,
Please find the pagination and search configuration.
**Pagination config:**
export const paginationOptions = {
    paginationSize: 100,
    pageStartIndex: 1,
    firstPageText: "First",
    prePageText: "Back",
    nextPageText: "Next",
    lastPageText: "Last",
    nextPageTitle: "First page",
    prePageTitle: "Pre page",
    firstPageTitle: "Next page",
    lastPageTitle: "Last page",
    showTotal: true,
    sizePerPageList: [{
        text: "100", value: 100
    }, {
        text: "150", value: 150
    }, {
        text: "200", value: 200
    }],
    hidePageListOnlyOnePage: true
};

**search config:**{
      dataField: [constants.REQ_BODY_NOMENCLATURE],
      text: [constants.LABEL_NOMENCLATURE],
      headerClasses: [constants.LABEL_THEAD_DESIGN],
      filter: textFilter({
        style: {
          width: "80%",
          fontSize: "11px"
        },
        onFilter: (value) => {
          if (value.length === 0) {
            this.setState({ scheduleData: [] });
            this.setState({ scheduleData: this.state.originalScheduleData });
          } else if (value.length > 0) {
            const filterRecords = this.state.originalScheduleData.filter((row) => { return row.nomenclature; });
            this.setState({ scheduleData: [] });
            this.setState({ scheduleData: filterRecords });
          }
        }
      }),
      style: (cell, row, rowIndex, colIndex) => {
        return {
          whiteSpace: "nowrap",
          textOverflow: "ellipsis",
          overflow: "hidden",
          maxWidth: "150px"
        };
      },
      events: {
        onMouseEnter: (e, column, columnIndex, row, rowIndex) => {
          e.target.style.whiteSpace = "normal";
        },
        onMouseLeave: (e, column, columnIndex, row, rowIndex) => {
          e.target.style.whiteSpace = "nowrap";
        }
      }
    }
**And the table below.**
 <BootstrapTable keyField='id.cDT' width='100' height='250' noDataIndication={"No data available"} scrollTop={"Bottom"} data={scheduleData} columns={this.scheduleDataColumns}
            filter={filterFactory()} pagination={paginationFactory(utility.paginationOptions)}  striped="true" />.

Thanks, Please let me know, if it's sufficient.

**Comment by AllenFang** [comment]
I think there's nothing special for me, I mean you code look good and I can not reproduce any issue in my side. However, i probably will suggest you not to call `setState` in `onFilter` to avoid some side effects.
