### ISSUE TITLE
Footer shifted when with use selectRow

### ISSUE THREAD

**Issue by megos** [react-bootstrap-table/react-bootstrap-table2#788]
I used selectRow and footer both.  
Footer shifted to select row.  
Could I use them same time?

###  Example code or repo (please keep it simple and minimal)

https://codesandbox.io/s/r5wkvv3zro

### Steps to reproduce.
Use selectRow and footer both

### react-bootstrap-table2 version.
2.1.0

**Comment by AllenFang** [comment]
oops, it's bug lol.  thanks your bug report and clear information :)

**Comment by AllenFang** [comment]
@megos 
Fixed in below version:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/16/version-bump.html

Please tag me if the issue still remain, thanks

**Comment by megos** [comment]
@AllenFang   
Thanks! Fixed!!
