### ISSUE TITLE
[0209 REGRESSION ISSUE] props.data is not updated when re-render in a search or filter enabled table

### ISSUE THREAD

**Issue by aliogaili** [react-bootstrap-table/react-bootstrap-table2#791]
**Versions:**
"react-bootstrap-table-next": "2.1.1",
"react-bootstrap-table2-filter": "^1.1.3",
"react-bootstrap-table2-paginator": "^2.0.2",

**Current Behaviour:**
If the TextFilter is used and the initial prop data is empty, then table will be empty as expected. However, once the data is loaded and the props change, then the table will remain empty until a filter string is entered by the user.

**Expected Behaviour:**
The grid should show the populated data once loaded even if the text filter string is empty. This was the behaviour in the previous version as well.

**Reproduction:**
https://codesandbox.io/s/z2oy658yvp

**Comment by rexatgithub** [comment]
i have the same issue 
**Versions:**
"react-bootstrap-table-next": "2.1.1",
"react-bootstrap-table2-filter": "^1.1.3",
"react-bootstrap-table2-paginator": "^2.0.2",

**Comment by melom007** [comment]
Hi, I have the same issue, but I also experience this with tables that have pagination attribute.

**Comment by YassienW** [comment]
This happens in tables without filter too, if you have a search bar only you have to write data into the search bar first, otherwise the table is not populated with anything. The initial state for `<SearchProvider/>` is incorrect

![selection_002](https://user-images.githubusercontent.com/11986226/52657945-7b80f600-2f02-11e9-8aa0-0f7333e8cbdb.png)

**Comment by picasik** [comment]
Same problem. When changing the state of the table is not re-rendered. The workaround was as follows:
`filter: textFilter ({
                 getFilter: (filter) => {this.nameFilter = filter; }
             })`
After receiving data from the server I set the filter to an initial empty value:
`await fetchData();
this.nameFilter ('');`

This decision is temporary until the error is corrected.

**Comment by AllenFang** [comment]
Sorry for lately reply, I think it's not related with pagination, @aliogaili example didn't use pagination.  

BTW, did you guys suffered this from newest packages?

**Comment by AllenFang** [comment]
here, I will fix this issue in this weekend.  The issue you guy suffer is from newest release: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/09/version-bump.html

Please don't upgrade above packages, thanks.  This is a critical regression issue, sorry about that.

**Comment by AllenFang** [comment]
Fixed in below version:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/16/version-bump.html

Please tag me if the issue still remain, thanks

**Comment by aliogaili** [comment]
I can confirm it's resolved now, once again thanks Allen for sharing this great library! great work.

**Comment by YassienW** [comment]
All good, thanks for the quick fix!

**Comment by AllenFang** [comment]
Thank you guys 👍
