### ISSUE TITLE
Remote mode and empty columns

### ISSUE THREAD

**Issue by juancafe4** [react-bootstrap-table/react-bootstrap-table2#792]
I am getting my column labels from my server. Right now, it throws an error when the column is empty an empty array.  Is there a way that the table could accept empty columns?

**Comment by AllenFang** [comment]
@juancafe4 sorry, we dont have empty column table support, if your column and data are all empty, just dont render table.

**Comment by AllenFang** [comment]
Do let me know if you still have any concerns, thank :)
