### ISSUE TITLE
Question: How to add unique ID to table row selection radio button?

### ISSUE THREAD

**Issue by basher** [react-bootstrap-table/react-bootstrap-table2#793]
I've successfully implemented a sortable, paging table.

Here's a snippet of my code showing a custom `selectionRenderer`. 
Is it possible to generate a unique ID for each radio button instance?

```
<BootstrapTable
  keyField="index"
  data={ props.data.map((row, index) => ({...row, index})) }
  columns={ props.columns }
  selectRow={{
    mode: 'radio',
    clickToSelect: true,
    classes: 'is-selected',
    onSelect: props.rowClick,
    selectionRenderer: ({ mode, ...rest }) => (
      <input type={ mode } id={somethingUnique} { ...rest } />
    )
  }}
  hover
/>
```

I can see from React devtools that there's a `rowIndex` prop passed down to `<SelectionCell>` component, but I can't figure out how to expose that via `<BootstrapTable>` props to my `selectionRenderer`?

The docs also say that `selectionRenderer` only accepts 3 props.

**Comment by AllenFang** [comment]
@basher if `rowIndex` is helpful to you, I will add it in next version, thanks

**Comment by basher** [comment]
@AllenFang That would be great. Thanks. 
Any idea when that will be?

**Comment by AllenFang** [comment]
ETA 2/20

**Comment by basher** [comment]
Excellent. Thanks for your prompt fix.

**Comment by AllenFang** [comment]
@basher, We have new release for fixing this issue: please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/) and upgrade related packages

**Comment by basher** [comment]
Thanks @AllenFang 
I'll implement fix asap.

**Comment by AllenFang** [comment]
please tag me if the issue still remain, thanks

**Comment by basher** [comment]
Works a treat, @AllenFang 

Here's a working snippet of the relevant code to add an **ID** to a row selector.
The important bit is `rowIndex`.

```
<BootstrapTable
  selectRow={{
    mode: 'radio',
    selectionRenderer: ({ mode, rowIndex, ...rest }) => (
      <input type={mode} id={`row${rowIndex + 1}`} {...rest} />
    ),
    // other 'selectRow' props...
  }}
  // other 'BootstrapTable' props...
/>
```
