### ISSUE TITLE
How to stop row expanding when clicking a component inside a cell?

### ISSUE THREAD

**Issue by AshCorah** [react-bootstrap-table/react-bootstrap-table2#794]
![image](https://user-images.githubusercontent.com/26364927/52786741-f9a4e000-305b-11e9-8dbc-755362ab61a6.png)

I want the row to expand when I click the row however I don't want it to expand when clicking an element. For example clicking this component for a menu, expands the row - but I want it to only expand when I click the row itself not the components inside the cells.

Anyway to do this?

**Comment by AllenFang** [comment]
@AshCorah for your last column, did you use `formatter` to custom the content, right?

**Comment by AllenFang** [comment]
I think so far I can not control it but I will figure out if there's some way can achieve your requirement, thanks

**Comment by AllenFang** [comment]
btw, there's a `expandRow.expandByColumnOnly` option, you can disable it when you only want to user to expand on clicking the expand columns

**Comment by AllenFang** [comment]
The other solution is you can call `e.stoppropagation()` when your component click

**Comment by AllenFang** [comment]
Let me know if above solutions are not work for you, thanks

**Comment by AshCorah** [comment]
This worked for me, thanks so much :)

**Comment by AllenFang** [comment]
👍

**Comment by lavania-aditya** [comment]
This really helps, Thanks !!

**Comment by LegitOverAll** [comment]
In June 2022 I have the same issue, it works now. You saved my day, thank you !
