### ISSUE TITLE
Custom total is not appearing beside pagination

### ISSUE THREAD

**Issue by kaustyy** [react-bootstrap-table/react-bootstrap-table2#795]
const RemotePagination = ({ data, page, sizePerPage, onTableChange, totalSize, columns, filter, options, sizePerPageOption, pagination }) => (
  <div>
    <PaginationProvider
      pagination={
        paginationFactory({
          custom: true,
          page,
          sizePerPage,
          totalSize,
          showTotal: true,
          sizePerPageList: options.sizePerPageList,
        paginationTotalRenderer: paginationTotal
        })
      }
    >
      {
        ({
          paginationProps,
          paginationTableProps
        }) => (
            <div>
              <BootstrapTable
                remote
                keyField="id.cDT"
                data={data}
                columns={columns}
                filter={filter}
                noDataIndication={"No data available"}
                onTableChange={onTableChange}
                {...paginationTableProps}
              />
              <span style={classConstants.drpdownMenu}> <SizePerPageDropdownStandalone
                {...paginationProps}
              /></span>
              <span><PaginationListStandalone
                {...paginationProps} firstPageText={"First"} firstPageTitle={"First Page"} lastPageText={"Last"} lastPageTitle={"Last Page"}
                nextPageText={"Next"} nextPageTitle={"Next Page"} prePageText={"Back"} prePageTitle={"Pre page"}

              /></span>
              
            </div>
          )
      }
    </PaginationProvider>
  </div>
);

const paginationTotal = (from, to, size) => (
  <span className="react-bootstrap-table-pagination-total">
    Showing {from} to {to} of {size} Results
  </span>
);

const sizePerPageOption = ({
  text,
  page,
  onSizePerPageChange
}) => (
    <li
      key={text}
      role="presentation"
      className="dropdown-item"
    >
      <a
        href="#"
        tabIndex="-1"
        role="menuitem"
        data-page={page}
        onMouseDown={(e) => {
          e.preventDefault();
          onSizePerPageChange(page);
        }}
        style={{ color: "#2a6496" }}
      >
        {text}
      </a>
    </li>
  );
render(){
 <RemotePagination
            data={data}
            page={page}
            columns={this.scheduleDataColumns}
            filter={filterFactory()}
            sizePerPage={sizePerPage}
            options={utility.paginationOptions}
            pagination={paginationTotal}
            onTableChange={this.handleTableChange}
            totalSize={this.filterRecords.length}
            sizePerPageOption={sizePerPageOption}
          />
}

const paginationOptions = {
    paginationSize: 100,
    pageStartIndex: 1,
    firstPageText: "First",
    prePageText: "Back",
    nextPageText: "Next",
    lastPageText: "Last",
    nextPageTitle: "Next page",
    prePageTitle: "Pre page",
    firstPageTitle: "First page",
    lastPageTitle: "Last page",
    showTotal: true,
    sizePerPageList: [{
        text: "100", value: 100
    }, {
        text: "150", value: 150
    }, {
        text: "200", value: 200
    }],
    hidePageListOnlyOnePage: true
};

Hi Allen,

You are doing great job. I had been working on the custom total show beside pagination but it is not showing at all. Please find above code snippet. Please let me know what could be reason behind it.

Thanks in advance!

**Comment by AllenFang** [comment]
@kaustyy that is because you choose to use standalone pagination rendering(`custom = true`). in this mode, everything will lost but you can render your component or standalone components.

However, so far we only support the `PaginationListStandalone` and `SizePerPageDropdownStandalone`, `ShowTotalStandalone` is not implemented yet.  I will implement this ASAP, thanks

**Comment by AllenFang** [comment]
We have new release for fixing this issue: please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/) and upgrade related packages

[this](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-column-toggle.html) is docs for column toggle and [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Toggle&selectedStory=Basic%20Column%20Toggle&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is online demo

Please open another issue if you find any bugs, thanks

**Comment by AllenFang** [comment]
We have new release for fixing this issue: please check [RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/) and upgrade related packages

We support `PaginationTotalStandalone`!!, please check [this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20Pagination%20Total&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) example.

**Comment by kaustyy** [comment]
Thanks Allen for quick release of functionality. Great work.
