### ISSUE TITLE
Help typescript example for  ToolKitProvider

### ISSUE THREAD

**Issue by kittyanalyst** [react-bootstrap-table/react-bootstrap-table2#802]
import * as React from "react";

import { fetchData } from "./../services/ApiClient";

import "./../styles/ReactDataTable.css";
import BootstrapTable from "react-bootstrap-table-next";
import ToolkitProvider, { Search } from "react-bootstrap-table2-toolkit";
import { loanSalesColumns } from "./ReactDataTableComponents";

const { SearchBar } = Search;
export interface Props {
  apiUrl: string;
  onStartRequest: () => void;
  onResultSuccess: () => void;
  onResultFailure: (error: Error) => void;
}

interface State {
  resultData: any;
  recordCount: number;
}

const initialState = { resultData: [], recordCount: 0 };

class ReactDataTable extends React.Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = initialState;
  }

  componentDidMount() {}

  componentDidUpdate(prevProps: any) {
    if (this.props.apiUrl !== prevProps.apiUrl) {
      this.updateData();
    }
  }

  updateData() {
    // See also: https://reactjs.org/docs/faq-ajax.html
    this.props.onStartRequest();
    fetchData(this.props.apiUrl)
      .then(response => {
        this.setState({
          resultData: response[0],
          recordCount: response[1]
        });
        this.props.onResultSuccess();
      })
      .catch((error: Error) => {
        this.props.onResultFailure(error);
      });
  }

  render() {
    return (
      
        <ToolkitProvider
          keyField="salesId"
          data={this.state.resultData}
          columns={loanSalesColumns}
          search
        >
          {({ props }: any) => (
          
              <BootstrapTable {...props.baseProps} />
          
          )}
        </ToolkitProvider>
   
    );
  }
}

export default ReactDataTable;

I am getting  error TypeError: Cannot read property 'searchProps' of undefined

Seems i am missing some thing obvious here. Can some one help me

**Comment by kittyanalyst** [comment]
Actual Error is 
TypeError: Cannot read property 'baseProps' of undefined

**Comment by AllenFang** [comment]
Please read document more detail, I guess there's something wrong in your code:

```js
 <ToolkitProvider
      keyField="salesId"
      data={this.state.resultData}
      columns={loanSalesColumns}
      search
    >
      {(props: any) => ( .  // . <<<here, it should not be ({ props }: any)
          <BootstrapTable {...props.baseProps} />
      )}
    </ToolkitProvider>
```

**Comment by kittyanalyst** [comment]
If I change code to 
{  props => ( .  // . <<<here, it should not be ({ props }: any)
          <BootstrapTable {...props.baseProps} />
      )
this will not compile. Error message props should specify explicit any type.
I am using ES5 type script

**Comment by AllenFang** [comment]
@kittyanalyst  is it doesn't work?

```js
{ (props: any) => ( . // . <<<here, it should not be ({ props }: any)
<BootstrapTable {...props.baseProps} />
)
```
