### ISSUE TITLE
React-bootstrap-table2 multiple tabs support

### ISSUE THREAD

**Issue by jackiechenn** [react-bootstrap-table/react-bootstrap-table2#809]
Hello, would it be possible to support multiple tabs in react-bootstrap-table2? I would like to display different json data to different table tabs.

I.e. Accounting tab, Marketing tab, Finance tab

Backend
JsonData
 String accountingJson <- to be displayed in the 1st table tab
 String markettingJson <- to be displayed in the 2nd table tab
 String financeJson <- to be displayed in the 3rd table tab

Thank you for the great library and support.

**Comment by AllenFang** [comment]
@jackiechenn sorry, I didn't get you, what tab you mean here?

**Comment by jackiechenn** [comment]
@AllenFang  sorry for the late reply, thank you for your response.
I meant the table tab e.g. https://www.w3schools.com/bootstrap/bootstrap_tabs_pills.asp

When we click on menu2 tab, it switches to the different data.

Thank you very much.

**Comment by AllenFang** [comment]
This is table library, we didn't support tab pills. actually, if you want to render different table in different tab, I think it will work well
