### ISSUE TITLE
Custom placeholder contents

### ISSUE THREAD

**Issue by iralution** [react-bootstrap-table/react-bootstrap-table2#81]
The reason for this is i18n. In the v1 for example, you cannot change the placeholder in the column filter.

**Comment by AllenFang** [comment]
@iralution actually, it's able to custom the placeholder:
`<TableHeaderColumn dataField='name' filter={ { type: 'TextFilter', delay: 1000, placeholder: 'something here' } }>Product Name</TableHeaderColumn>`

**Comment by espiralverde** [comment]
Is there a way to modify the placeholder for react-bootstrap-table2?
