### ISSUE TITLE
Filter result cleared after using search

### ISSUE THREAD

**Issue by Stefan-Reimer** [react-bootstrap-table/react-bootstrap-table2#811]
When I filter a table using the filter of a column and use the search afterwards, it will remove the filter of the column and only filter using the text in the search field.

Look at this example: https://stackblitz.com/edit/react-sc5gme?file=index.js

If you search for 'Peter' in the 'First Name' column filter and then search for 'Parker' in the Search Text it will  show 'Lisa Parker' and 'Peter Parker'. But I would actually thing that it would combine both filters and only show 'Peter Parker'.

Used version:
react-bootstrap-table-next: 2.2.0
react-bootstrap-table2-filter: 1.1.4
react-bootstrap-table2-toolkit:  1.3.0

**Comment by AllenFang** [comment]
@Stefan-Reimer I will check this, thanks

**Comment by AllenFang** [comment]
Fixed: https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/24/version-bump.html
