### ISSUE TITLE
disable Select for one column

### ISSUE THREAD

**Issue by armohammadi56** [react-bootstrap-table/react-bootstrap-table2#812]
I need to  clickToSelect true for table and disable select for one column?

**Comment by AllenFang** [comment]
@armohammadi56 so far we dont have this feature and it's minor for me, so PR is welcome, thanks

**Comment by armohammadi56** [comment]
thank you @AllenFang

**Comment by gcko** [comment]
@armohammadi56 What would the use case be for selection disable on a specific column? the row itself would still be selectable, correct?

**Comment by armohammadi56** [comment]
@gcko yes

**Comment by AllenFang** [comment]
@armohammadi56 and @gcko you guys can use [`selectRow.nonSelectable `](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrownonselectable-array)

**Comment by mirl72** [comment]
Hello,

I am in need of the same functionality originally requested in this thread and hope you will still see this even though it has been closed. 

One of the columns in my table contains buttons for the user to interact with. I do not want the clicking of these buttons to trigger the select row, but clicking any other column should. (See image below)

I may be misunderstanding the suggested solution but I can not figure out how I would accomplish this through the nonSelectable property. This property appears to prevent rows from being selectable which is not exactly the functionality requested, at least from my understanding of original posted question.

Thank you in advanced for any additional information you can provide on how I can accomplish this.

Thanks!
p.s. I love your table component and have really been able to use it for ALL of my requirements to this point. Great work and please keep it up!

![rowSelectionByColumn](https://user-images.githubusercontent.com/53577960/62316346-17200780-b44c-11e9-9718-75b7c24929cc.png)
