### ISSUE TITLE
Pagination having no effect

### ISSUE THREAD

**Issue by ronaiza-cardoso** [react-bootstrap-table/react-bootstrap-table2#813]
Pagination having not effect on table. I have one table with state and props and when I change the pagination the data inside is not beem updating.

**Comment by AllenFang** [comment]
@ronaiza-cardoso any more information so that I can reproduce it? what version you are using now?

**Comment by ronmo32992** [comment]
same here.
I tried both of these versions but no longer working:

 "react-bootstrap-table-next": "^2.2.0",
 "react-bootstrap-table2-filter": "^1.1.4",
 "react-bootstrap-table2-paginator": "^2.0.3"

and 

"react-bootstrap-table-next": "^1.4.2",
"react-bootstrap-table2-filter": "^1.1.0",
"react-bootstrap-table2-paginator": "^1.0.4",

**Comment by ronaiza-cardoso** [comment]
When I update for this worked, thanks for the amazing job on table. 

```
    "react-bootstrap-table-next": "^2.1.1",
    "react-bootstrap-table2-paginator": "^2.0.2",
```

**Comment by ronmo32992** [comment]
can you share me the code?

**Comment by AllenFang** [comment]
@ronmo32992 please make sure your upgrade all the relative packages, thanks.  If the issue still remain, please open another issue and attach a simple and minimal code for reproducing bug, thanks
