### ISSUE TITLE
defaultValue not working for filters

### ISSUE THREAD

**Issue by sahilvicesoftware** [react-bootstrap-table/react-bootstrap-table2#814]
Hi @AllenFang 
Thanks for this great library.
Could you help me on how to set default filters.

I used the code as per the docs but default filter is not getting applied.

Code - ```{
          dataField: 'status',
          text: 'STATUS',
          formatter: formatStatusColumnData,
          headerFormatter: getColumnHeaderContentForStatusField,
          filter: selectFilter({
            options: filterOptions,
            placeholder: 'All',
            defaultValue: 2,
          }),
          sort: true,
          headerStyle: { width: 125 },
        }```

Thanks.

**Comment by AllenFang** [comment]
`defaultValue: 2` please make sure your raw data's `status` field is a number like 1, 2 etc.

[online](http://localhost:6006/?selectedKind=Column%20Filter&selectedStory=Select%20Filter%20with%20Default%20Value&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) demo is work, so I believe there's something wrong in your code.

If the issue still remain, please tag me and give me a simple and minimal code for reproducing, thanks!

**Comment by sahilvicesoftware** [comment]
> `defaultValue: 2` please make sure your raw data's `status` field is a number like 1, 2 etc.
> 
> [online](http://localhost:6006/?selectedKind=Column%20Filter&selectedStory=Select%20Filter%20with%20Default%20Value&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) demo is work, so I believe there's something wrong in your code.
> 
> If the issue still remain, please tag me and give me a simple and minimal code for reproducing, thanks!

Updating the package fixed the issue.Thanks @AllenFang .
