### ISSUE TITLE
Question : Add button to edit instead of clicking

### ISSUE THREAD

**Issue by sartaj10** [react-bootstrap-table/react-bootstrap-table2#815]
I was wondering if there is a way to click a button to edit a particular cell instead of just clicking on the cell itself? Is there an example for this anywhere?

Thanks!

**Comment by AllenFang** [comment]
@sartaj10 

```js
class Table extends React.Component {
  handle = () => {
    this.table.cellEditContext.startEditing(0, 1);
  }

  render() {
    return (
      <div>
        <button onClick={ this.handle }>click to edit</button>
        <BootstrapTable
          ref={ x => this.table = x }
          keyField="id"
          data={ products }
          columns={ columns }
          cellEdit={ cellEditFactory({ mode: 'click' }) }
        />
        <Code>{ sourceCode }</Code>
      </div>
    );
  }
}
```

**Comment by AllenFang** [comment]
This issue will be fixed in next version then you can follow the above example to achieve your requirement.

**Comment by AllenFang** [comment]
@sartaj10 fixed in https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/02/24/version-bump.html

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html#trigger-cell-editing
