### ISSUE TITLE
column editorRenderer

### ISSUE THREAD

**Issue by functionsonly** [react-bootstrap-table/react-bootstrap-table2#817]
In the custom editor example: [https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Custom%20Editor&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel](url), when you click on multiple cells to edit, and click on "done", the behavior is abnormal and unmanageable.

Can you add a parameter for the column where if a custom editor has been designated, it can only open one cell at a time?

**Comment by AllenFang** [comment]
@functionsonly I think its not a bug, it just I didn't call `focus()` when editor rendered. I will enhance the example

**Comment by AllenFang** [comment]
```js
class QualityRanger extends React.Component {
  static propTypes = {
    value: PropTypes.number,
    onUpdate: PropTypes.func.isRequired
  }
  static defaultProps = {
    value: 0
  }

  componentDidMount() {
    this.range.focus();  // <<<<<<<<< here
  }

  getValue() {
    return parseInt(this.range.value, 10);
  }
  render() {
    const { value, onUpdate, ...rest } = this.props;
    return [
      <input
        { ...rest }
        key="range"
        ref={ node => this.range = node }
        type="range"
        min="0"
        max="100"
      />,
      <button
        key="submit"
        className="btn btn-default"
        onClick={ () => onUpdate(this.getValue()) }
      >
        done
      </button>
    ];
  }
}
```

**Comment by functionsonly** [comment]
So for one of the columns, I've been using the editorRenderer property to call a component that returns a react-select element.  react-select actually creates a bunch of divs and appears to only use the hidden input type.  I can't seem to close one cell when opening another using react-select, i'm suspecting it's due to the react-select.

https://codesandbox.io/s/88pv3omrn8

**Comment by AllenFang** [comment]
@functionsonly ok, I will check out above case again, thanks!

**Comment by AllenFang** [comment]
@functionsonly this is not about `focus`, it's a bug that cell rendering is abnormal when switch editing cell, I will fix it soon

**Comment by AllenFang** [comment]
Fixed https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/17/version-bump.html

Please upgrade to newest version

**Comment by functionsonly** [comment]
Nice.  Thank you.
