### ISSUE TITLE
Search on filtered data returning results from original data

### ISSUE THREAD

**Issue by sahilvicesoftware** [react-bootstrap-table/react-bootstrap-table2#820]
Hi @AllenFang 
If i search through the table and then apply filters, it works fine.
But if i filter the data first and then search the table, it shows the results from the original data rather than from the filtered data only.

Appreciate your help.

**Comment by AllenFang** [comment]
@sahilvicesoftware I think this issue was fixed https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/811

Please tag me if the issue still remain
