### ISSUE TITLE
dev build stuck in dependency install step

### ISSUE THREAD

**Issue by pritam-patil** [react-bootstrap-table/react-bootstrap-table2#822]
We were using the older version react-bootstrap-table, before migrating we thought of reading the documentation. There are quite a few improvements that could be done, we thought.

So after cloning the repo for development (doc editing) purposes, since last couple of days I'm stuck in dependency install step (yarn OR npm install) .

These are the logs that could help - 

> $ yarn
> yarn install v1.10.1
> [1/4] Resolving packages...
> success Already up-to-date.
> $ lerna bootstrap
> lerna info version 2.8.0
> lerna info versioning independent
> lerna info Bootstrapping 7 packages
> lerna info lifecycle preinstall
> lerna info Installing external dependencies
> [         .........] - install dependencies: verb actions 1 actions, concurrency 4
> [         .........] - install dependencies: verb actions 1 actions, concurrency 4
> [         .........] - install dependencies: verb actions 1 actions, concurrency 4

**Platform Info:**
OS: Ubuntu 17.04 
Node version: 8.10.0
Yarn version: 1.10.1

Any help in getting the storybook running is appreciated.

**Comment by AllenFang** [comment]
@pritam-patil I use the same env but I can not reproduce this. If you really need to check the storybook, you can see the [online version](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html).

**Comment by AllenFang** [comment]
in my local env, I use `node@8`, `yarn@1.12.3` and `lerna@2.8.0` << . you try again by this

**Comment by pritam-patil** [comment]
I did try building it again on clean OS (moved from Ubuntu to Fedora), and after a few hiccups (g++ install and node-sass rebuild) --  'yarn install' is a success and I could build storybook without fail.
You can close this. Thanks.
