### ISSUE TITLE
Setting bordered={false} should draw horizontal lines?

### ISSUE THREAD

**Issue by lovato** [react-bootstrap-table/react-bootstrap-table2#823]
The default example is a good one.

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Basic%20Table&selectedStory=borderless%20table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

I am mainly opening this because it took me a lot of time figuring it out. This was the normal behavior for RBT1 (almost sure). Just checked the same page I am migrating to RBT2, and there is no "table-borderless" class on it, and there are no inner borders. I was not able to find a working example available on a public website and wasn't able to understand why actually my code doesn't render horizontal lines in RBT1 (I am doing the migration changing line per line).

So, when setting bordered to false, I was expecting to get rid of all borders. All of them.

After digging around, I found a class called "table-borderless" inside some CSS file.

Then, did this:
bordered={false}
classes="table-borderless"

Is there an "official" way to do this?

I guess what gets most confusing at the very end is that "table.bordered=false" changes the main table borders **AND** vertical lines and something called "table-borderless" gets rid of horizontal lines as well.

Best,

**Comment by AllenFang** [comment]
@lovato default bootstrap table is borderless, [here](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_table-responsive&stacked=h) is an online example.

in `react-bootstrap-table2`, I hope table should with border as default.  If you disable if, the table style will just like above example. actually, if you didn't disable it, `react-bootstrap-table2` will add a `table-bordered` class on table element. it's all official bootstrap solution.

In above example, you can see the borderless table always have horizontal lines between each rows, so my implementation is just follow the official solution

**Comment by lovato** [comment]
Thanks for the clarification. Once I have found a solution, I am fine.

**Comment by tonkabits** [comment]
Thanks @lovato
