### ISSUE TITLE
Second table does not rerender with updated date after setState called

### ISSUE THREAD

**Issue by functionsonly** [react-bootstrap-table/react-bootstrap-table2#825]
I have two tables. If I refresh an element in one table, the second table doesn't show the update after setState has been called.

https://codesandbox.io/s/1v8znzknm7

Is there a way to force all tables to re-render?

**Comment by AllenFang** [comment]
@functionsonly this is not a bug, you mutate the state directly. Please do not modify the state data.

[here](https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns) is an article to teach how to mutate data in a correct way.

**Comment by functionsonly** [comment]
Updated with a copy of the state data.  Still no render:  https://codesandbox.io/s/73zp4z5jk1

**Comment by functionsonly** [comment]
Nevermind, I see what you're saying!  Thanks.

**Comment by AllenFang** [comment]
👍

**Comment by matteusbarbosa** [comment]
The ones facing same difficulties about the issue, please just follow @AllenFang link provided. It says that you must update the table `data` array using .map . check example below

  ```
updateTableRow(array, target_index, form) {
    return array.map((item, index) => {
      if (index == target_index) {
        // This isn't the item we care about - keep it as-is
        return form;
      }
  
      // Otherwise, this is the one we want - return an updated value
      return item;
    })
  }
```

**Comment by HUANGXUANKUN** [comment]
@matteusbarbosa Oh man.. Should have raised this post up.  It is so helpful for implementing an add, edit or delete button with form like this: 
<img width="1415" alt="Screenshot 2020-07-22 at 7 05 06 PM" src="https://user-images.githubusercontent.com/39436447/88169445-88089280-cc4e-11ea-820b-c73addbb6a64.png">
