### ISSUE TITLE
Pagination show blank/empty row when you're on the last page and delete last item

### ISSUE THREAD

**Issue by nkidmano** [react-bootstrap-table/react-bootstrap-table2#826]
Encounter this problem when I'm on last page and if there's only 1 item in the table and I delete it. Table show empty/blank row. I think it should re-render table or force it back to previous page.

https://codesandbox.io/s/rylnxq7nn

**Comment by AllenFang** [comment]
@nkidmano sorry for lately reply, it's a bug, I will fix it ASAP, thanks

**Comment by AllenFang** [comment]
Fixed in newest version, please upgrade all the related packages listed in below notes:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/10/version-bump.html

@nkidmano

**Comment by sbaruti99** [comment]
Hi @AllenFang, So I am having the same issue now, these are the versions of the packages I use, which I think to be the latest ones. Please can you look at this and maybe let me know a workaround or if you could probably find a solution. Thanks in advance!
```
"react-bootstrap-table-next": "4.0.2",
"react-bootstrap-table2-editor": "^1.4.0",
"react-bootstrap-table2-paginator": "2.1.2",
```
