### ISSUE TITLE
Setting the hidden attribute of a column to false or true dynamically

### ISSUE THREAD

**Issue by ahmarkhan** [react-bootstrap-table/react-bootstrap-table2#827]
When I set the property **hidden** in the following :

 {
            dataField: 'display_name',
            text: 'Product Name',
            sort: true,
            onSort: (field, order) => {
                /* This field can be used to send across to the API for server side calling*/
                console.log('field-->', field, '--order--', order)
            },
            **hidden** : **false**
   }

The column still renders, even through **hidden** gets set to true/false.
Please advise . 
I am passing as props from a reducer into the component like : 
**this.props.tableConfig.columns** , which will have the config for the columns.

**Comment by AllenFang** [comment]
@ahmarkhan sorry for lately reply,

it's work for me:

```js
const columns = [{
  dataField: 'id',
  text: 'Product ID'
}, {
  dataField: 'name',
  text: 'Product Name'
}, {
  dataField: 'price',
  text: 'Product Price',
  hidden: true
}];

class Table extends React.Component {
  state = { columns }

  changeHidden = () => {
    const newColumns = this.state.columns.map((column) => {
      if (column.dataField !== 'price') return column;
      return {
        ...column,
        hidden: !column.hidden
      };
    });
    this.setState({ columns: newColumns });
  }

  render() {
    return (
      <div>
        <BootstrapTable keyField="id" data={ products } columns={ this.state.columns } />
        <button onClick={ this.changeHidden }>change price column visibility</button>
      </div>
    );
  }
}
```

Two things I need to mention:

1. Please mutate state data correctly, if you don't know how to mutate data, please check https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns
2. Please upgrade all the `react-bootstrap-table2` related package to the newest. [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/) is our change log.

**Comment by ahmarkhan** [comment]
Why is changing

{
            dataField: 'parent_categories_names',
            text: 'Category',
            sort: true,
            onSort: (field, order) => {},
            headerClasses: 'show',
            classes: 'showMe',
            style : {display : 'table-cell'}
}

to

{
            dataField: 'parent_categories_names',
            text: 'Category',
            sort: true,
            onSort: (field, order) => {},
            headerClasses: '*hidden*',  //*Hiding the TableHeader*
            classes: '*hidden*', // *Not hiding the td / cell*
            style : {display : '*none*} // *Not even this is getting
changed*
  }


*This is very very strange behavior. The Table is already about to get into
production. Please advise.*

*Thanks*
*Ahmar Khan*
Software Dev Engineer
Yahoo Inc
Sunnyvale, California, USA
Mobile :  +1-(669)-248- <(408)%20647-0391>6465 ( Email first is preferred )
khanmannu2006@gmail.com
