### ISSUE TITLE
Are all Toolkit search={searchProps} being propagated?

### ISSUE THREAD

**Issue by lovato** [react-bootstrap-table/react-bootstrap-table2#828]
In the example, I can find this:

```
<ToolkitProvider
  keyField="id"
  data={ products }
  columns={ columns }
  search={ { defaultSearch: '2101' } }
>
  {
    props => (
      <div>
        <h3>Input something at below input field:</h3>
        <SearchBar { ...props.searchProps } />
        <hr />
        <BootstrapTable
          { ...props.baseProps }
        />
      </div>
    )
  }
</ToolkitProvider>
```

This actually works. 

But this won't work (placeholder will still be 'Search'):
```
search={{ placeholder: "type something..."}}
```
I created this object:

```
    const searchProps = {
      delay: 800,
      placeholder: "type something...",
      defaultSearch: 'anyx'
    };
```
And if I do this:
```
<SearchBar {...props.searchProps} />
```
Only 'anyx' is displayed. If I delete the text inside the displayed component, placeholder is again 'Search', not the one I specified.

To achive this currently, I need to use this way:
```
<SearchBar {...searchProps} {...props.searchProps} />
```
or ignoring any change Toolkit might be doing to searchProps internally:
```
<SearchBar {...searchProps} />
```
because a few of subprops are not being propagated. I checked on packages/react-bootstrap-table2-toolkit/context.js

Am I right?

Best
Lovato

**Comment by AllenFang** [comment]
@lovato firstly, sorry for lately reply. about your issue, we use context to pass some internal function to core table and some search functionality configurations.  about placeholder, style, class for `SearhcBar` component, you can just render component with your custom props directly.

Thanks
