### ISSUE TITLE
selectFilter not working inside PaginationProvider

### ISSUE THREAD

**Issue by rexatgithub** [react-bootstrap-table/react-bootstrap-table2#830]
I'm not sure if there is something I miss here. It was working on the older versions but not on the versions below.  

**Versions:**
 "react-bootstrap-table-next": "^3.0.0",
 "react-bootstrap-table2-filter": "^1.1.5",
"react-bootstrap-table2-paginator": "^2.0.3",

**Current Behaviour:**
SelectFilter works perfectly through BootstrapTable alone however in my case where i want custom pagination, using PaginationProvider filter from SelectFilter doesnt seem to work.

**Expected Behaviour:**
Should be able to filter which item is selected from the column which has selectFilter

**Reproduction:**
https://codesandbox.io/s/xr42o1rrlq

**Comment by AllenFang** [comment]
@rexatgithub it's a regression issue, I will fix it ASAP, thanks

**Comment by AllenFang** [comment]
Fixed in newest version, please upgrade all the related packages listed in below notes:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/10/version-bump.html

@rexatgithub

**Comment by rexatgithub** [comment]
@AllenFang awesome!! thank you very much :)
