### ISSUE TITLE
filtering with custom pagination not working

### ISSUE THREAD

**Issue by nathan-fortier** [react-bootstrap-table/react-bootstrap-table2#831]
**When filtering with custom pagination I receive the following error:**
<img width="1258" alt="screen shot 2019-03-01 at 5 10 27 pm" src="https://user-images.githubusercontent.com/48065276/53669414-053ffb80-3c45-11e9-91e1-d38a900259c9.png">

**Steps to reproduce:**
In the code example I have provided simply set the second columns filter to "a" and then click on the 2nd page

<img width="423" alt="screen shot 2019-03-01 at 5 08 26 pm" src="https://user-images.githubusercontent.com/48065276/53669321-b8f4bb80-3c44-11e9-9ce4-6cf9ac4c93c3.png">

**Code:**
https://codesandbox.io/s/rpr0v789n?fontsize=14

**Comment by AllenFang** [comment]
@nathan-fortier it's an regression issue, I will fix it in this weekend, thanks

**Comment by AllenFang** [comment]
note: familiar issue with https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/830

**Comment by AllenFang** [comment]
Fixed in newest version, please upgrade all the related packages listed in below notes:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/10/version-bump.html

@nathan-fortier
