### ISSUE TITLE
Table only displays one records from MongoDB

### ISSUE THREAD

**Issue by dukesx** [react-bootstrap-table/react-bootstrap-table2#832]
Hi, I am fetching data from MongoDB , the result of which is sent in JSON format. My problem is that i can collect all data in state , this is the form : 

```
state = {
data: [
   {
      id: '1',
      firstName: 'A Name',
    }
]
}
```

but when i tell the table to fetch "Data" , it just shows 1 record. I have looped through all 8 records of data myself and it does have all the records stored in it. Then Why isn't the table showing all the data ?? 

Note : I am using Razzle , an SSR version of create-react-app 

I tried with pre-populated data , that i just made as sample by creating another array of objects , and it worked, but does not work dynamically. I have also tried Remote props but still wont work.

**Comment by AllenFang** [comment]
@dukesx how do you update data to `BootstrapTable` component?  is there any example code? I think `react-bootstrap-table2` allow developer to update data on the fly. so it shouldn't be a problem.  if ok, I will suggest you to create an online demo for me to reproduce this issue, [here](https://codesandbox.io/s/jlol04qrxv) is an example.

I will open this issue if I can reproduce this issue, Thanks
