### ISSUE TITLE
Search bar problem 

### ISSUE THREAD

**Issue by ipetrini** [react-bootstrap-table/react-bootstrap-table2#833]
I'm having this weird problem when combining the Search bar and cell editing.

My code looks like:

Edit: I have problems with posting code here, so here it is:

https://pastebin.com/AH1jyq08

The problem is that when I reload the page where this table is in, and then I try to edit some cell, that cell is not showing the new value, but my state and my database are updating properly.

However, when I use this code without the Search Bar, everything works fine.

[https://pastebin.com/52k4Jwwb](url)

I don't know if there's something wrong with my code or this is a bug.

**Comment by AllenFang** [comment]
@ipetrini did you enable the `remote` mode? I saw you didn‘t enable it, so I'm curious how you update the data after editing a cell.  Would you please put a minimal, simple and dummy example on codesandbox.io?  That will be very helpful for me to reproduce this issue.  [here](https://codesandbox.io/s/jlol04qrxv) is an example you can take it.

**Comment by ipetrini** [comment]
Hi @AllenFang. No, I didn´t enable the remote mode. 
Here is an example that looks similiar to my code [https://codesandbox.io/s/nnrqoox274?fontsize=14](url)

**Comment by AllenFang** [comment]
HI @ipetrini sorry, I can not reproduce your issue. Please give me more information so that I can reproduce it.  btw, how do you update the cell? any information is appreciated.

**Comment by ipetrini** [comment]
@AllenFang well, the cell was updating by default, now I've changed to remote mode and it works perfectly. Sorry for the confusion and thanks!
