### ISSUE TITLE
btnContextual property on SizePerPageDropdownStandalone not passed to SizePerPageDropdown

### ISSUE THREAD

**Issue by paaatrick** [react-bootstrap-table/react-bootstrap-table2#840]
I'm working on upgrading from react-bootstrap-table version 1. Previously I could set the `btnContextual` property on the `SizePerPageDropDown` component. In version 2, it looks like that property still exists on `SizePerPageDropDown`, but it is not passed through when I set it on the `SizePerPageDropdownStandalone` component:

```jsx
<SizePerPageDropdownStandalone {...paginationProps} btnContextual='btn-outline-secondary' />
```

**Comment by AllenFang** [comment]
@paaatrick Fixed in newest version, please upgrade all the related packages listed in below notes:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/10/version-bump.html

**Comment by paaatrick** [comment]
Thank you!
