### ISSUE TITLE
BoostrapTable doesn't re-render using react-bootstrap-table-next@3.0.0,  but does using 0.1.15

### ISSUE THREAD

**Issue by zbitouzakaria** [react-bootstrap-table/react-bootstrap-table2#844]
Hi guys,

Following the related issue https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/444 

Example code https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/444#issuecomment-410495815 (copy below) works with react-bootstrap-table-next at version 0.1.15, but not with 3.0.0

```jsx
class Table extends React.Component {
  constructor(props) {
    super(props);
    this.state = { products };

    this.columns = [{
      dataField: 'id',
      text: 'Product ID'
    }, {
      dataField: 'name',
      text: 'Product Name',
      filter: textFilter(),
      formatter: cell => `% ${cell} %`
    }, {
      dataField: 'price',
      text: 'Product Price',
      formatter: (cell, row) => {
        return (
          <button onClick={ this.handleTagClick(row.id) }>Click</button>
        );
      }
    }];
  }
  /* eslint no-param-reassign: 0 */
  handleTagClick = rowId => () => {
    const newProducts = this.state.products.map((row) => {
      if (row.id === rowId) {
        row.name += row.name;
      }
      return row;
    });
    this.setState({ products: newProducts });
  }

  render() {
    return (
      <div>
        <BootstrapTable
          keyField="id"
          data={ this.state.products }
          columns={ this.columns }
          filter={ filterFactory() }
        />
        <Code>{ sourceCode }</Code>
      </div>
    );
  }
}
```

Am I missing something here ?

Thank you

**Comment by zbitouzakaria** [comment]
I setup an example here: https://codesandbox.io/s/8km0ly74m0

Working:
- 0.1.15

Not working:
>= 1.0.0

**Comment by AllenFang** [comment]
@zbitouzakaria please follow [this](https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns) to update/mutate data in correctly or not you will make `react-bootstrap-table` recognize your data is not change.  Too many people ask the same question. So please I will ask developer to read above doc and figure out how `shouldcomponentupdate` work and why we need `immutable.js` sometime.

ping me if you still dont know how to mutate data, thanks

**Comment by zbitouzakaria** [comment]
Got it, thanks! Here is a working example for those interested:
https://codesandbox.io/s/8km0ly74m0
