### ISSUE TITLE
hidePageListOnlyOnePage not working

### ISSUE THREAD

**Issue by sudravi** [react-bootstrap-table/react-bootstrap-table2#845]
I'm not able to hide the pagination bar for my table when there's only 1 page. I tried setting hidePageListOnlyOnePage to true, but I still see a button below my table that says "1".  I'm testing with 1 row (1 page).

Here are the options for my table:

```
<BootstrapTable
   bootstrap4
   hover
   keyField='id'
   data={users}
   columns={ columns }
   pagination={ paginationFactory({ hidePageListOnlyOnePage:true }) }
   filter={ filterFactory() }
   noDataIndication="No Users to Display"
   selectRow={ selectRow }
/>
```

**Comment by ronaiza-cardoso** [comment]
Mine is not working too

**Comment by Lilian1331** [comment]
I have the same issue too.

**Comment by ronaiza-cardoso** [comment]
@Lilian1331, I solved my problem putting this css 
```
.react-bootstrap-table-pagination-list-hidden {
    display: none;
}
```

**Comment by sudravi** [comment]
Great, that worked!

On a related note, anyone know if there's a way to hide the size per page dropdown if there's only one page? Or would I have to track the currently selected dropdown value (via onSizePerPageChange)  and set hideSizePerPage if the table has fewer items?
