### ISSUE TITLE
react-bootstrap-table2-filter 1.1.6 make remote filter not work

### ISSUE THREAD

**Issue by steven11329** [react-bootstrap-table/react-bootstrap-table2#849]
HI every one
Today I updated my project packages,
And I found my remote filter not work.
I use React Developer Tool to check BootstrapTable's data prop.
It always get empty data array.
So I rollback to 1.1.5 all work fine.

**Comment by AllenFang** [comment]
@steven11329 I will fix this soon, thanks

**Comment by AllenFang** [comment]
Fixed https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/17/version-bump.html

Please upgrade to newest version
