### ISSUE TITLE
Select filter + Pagination + function footer

### ISSUE THREAD

**Issue by KARTHIK5300** [react-bootstrap-table/react-bootstrap-table2#850]
In a table, after filtering the data I'm getting the desired result. when I try to get a sum of the filtered result using function footer I'm getting the sum for the data shown in the table. Since I'm using pagination I get the sum for the page I'm on but I need the sum of all the filtered data how to get that.  

After selecting the filtering  how to access all the filtered data

**Comment by AllenFang** [comment]
@KARTHIK5300 so far the footer design is for current visible data on table, which means it is divided by page.  

But there's a way to get the filtered data:


```js
<BootstrapTable
  ref={ n => this.node = n }
  ...
/>

get filtered data >>>> this.node.filterContext.data
```

Please let me know if you still can not sum the all the filtered data, then I will find the new solution, thanks

**Comment by KARTHIK5300** [comment]
Hi Allen, 

Thanks for the reply. It worked

**Comment by AllenFang** [comment]
👍
