### ISSUE TITLE
Wrong dependency?

### ISSUE THREAD

**Issue by rchaser** [react-bootstrap-table/react-bootstrap-table2#851]
After npm install react-bootstrap-table-2
cannot build my app with next message

./node_modules/react-addons-update/index.js
Module not found: Can't resolve 'react/lib/update' in 'C:\Repos\DDD\WebApp\node_modules\react-addons-update'

react-bootstrap-table2 has dependency on @allenfang/react-toastr that depends on react-addons-update, that is not supported by react starting from 16.0 https://github.com/facebook/react/issues/9207 

Am I able to use react-bootstrap-table-2 in react 16.0+?

**Comment by AllenFang** [comment]
@rchaser `react-bootstrap-table2` hasn't dependency on `@allenfang/react-toastr`,  in addition, `react-bootstrap-table2` need `react@^16.3.0`

https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2/package.json#L45

**Comment by rchaser** [comment]
@AllenFang Oops, I was installing https://www.npmjs.com/package/react-bootstrap-table-2 and I didn't notice that the current project has different name without dash between "table" and "2". Packages' names are confusing. I am sorry.
