### ISSUE TITLE
Default date is 01/01/1970 when editing a cell which was original empty

### ISSUE THREAD

**Issue by jbp17** [react-bootstrap-table/react-bootstrap-table2#857]
I have a table with a "Termination Date" column.  So it is mostly empty.  Users sometimes edit it to put a termination date on it.  But when user double-click it and chooses the calendar dropdown.  The calendar is default to 01/01/1970.  It took too long for user for find current year or the year after current year.  How can I let it default of today's date?

**Comment by AllenFang** [comment]
@jbp17 

```js
editor: {
    type: Type.DATE,
    defaultValue: Date.now()
}
```

I will spend some time to enhance the document, sorry for inconvinece.

**Comment by zoldbogar** [comment]
Hello Allen, I have a similar problem and `defaultValue` only solves it partially: my problem now is that `defaultValue` will show even when I have to edit an existing value. 

F.e. if I have no value then it is ok to default to `defaultValue`, but if there is a value on that cell (like '05/21/2019') then I would prefer to see that value in the editor.

Thanks
