### ISSUE TITLE
shouldUpdateByColumnsForSimpleCheck does not react to columns change

### ISSUE THREAD

**Issue by jfremy** [react-bootstrap-table/react-bootstrap-table2#866]
https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/06d87299a3b08b7e110b78a042da5d6b610fc530/packages/react-bootstrap-table2/src/row/should-updater.js#L25

In my code, I allow a user to add / remove columns to a table but also change the order of the columns.
When changing the order of columns, the header gets updated (so columns title is correct) but the data does not get updated (it still displays the data for the old columns set).

This is because the logic in shouldUpdateByColumnsForSimpleCheck is not correct.
It does not check that the columns definition changed, it just updates if the length of the columns definition changed or if a column hidden state changed.

You probably want to do an object equality test or at least a deep comparison on the columns content. A lot of the changes in the columns definition have some kind of impact on the data display (change in formatter, alignment ...).

**Comment by AllenFang** [comment]
@jfremy ok,  I will fix this, thank you

**Comment by AllenFang** [comment]
> You probably want to do an object equality test or at least a deep comparison on the columns content. A lot of the changes in the columns definition have some kind of impact on the data display (change in formatter, alignment ...).

yes, we actually did it already in different level. This `should-updater` is for row level.

**Comment by AllenFang** [comment]
@jfremy 

this issue is fixed, please at least to upgrade related package listed below to newest version:

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/03/26/version-bump.html

**Comment by jfremy** [comment]
Thanks a lot, it's working fine now!
