### ISSUE TITLE
RemoteCellEdit not rendering

### ISSUE THREAD

**Issue by ipetrini** [react-bootstrap-table/react-bootstrap-table2#869]
I'm having trouble when updating the data of a table using RemoteCellEdit.

Here is an example of the code:
https://codesandbox.io/s/m4ly6y304x

It's clear that when I edit a cell everything works as it should, but when I click the button on top of the screen that changes the state of the products (Name of product with id 1), which is the data of the table, the new value is not showed, but when I click that cell the new value appears. So, the props.data of the table is changing, but the table is not rendering.

**Comment by ipetrini** [comment]
Well, I've just found out that using  "react-bootstrap-table-next": "2.0.1", it works just fine...

**Comment by AllenFang** [comment]
👍

**Comment by ipetrini** [comment]
@AllenFang the problem is that using that older version , I'm probably loosing some new features/bug corrections that were made in the newest version (3.0.2). No way to fix it in that version?

**Comment by AllenFang** [comment]
> No way to fix it in that version?

i think it's impossible, you can not override the content in an existing version. lol
