### ISSUE TITLE
Pagination resets back to page 1 when updating other table

### ISSUE THREAD

**Issue by rexatgithub** [react-bootstrap-table/react-bootstrap-table2#870]
I am using 2 tables, 1 is a custom table(**table1**) under paginationProvider and the other one(**table2**) is plain BootstrapTable. 
table2 list will be loaded when a row from table1 is being selected (through the load button).
However when i try to navigate any pages other than page one then i try to select a row the pagination from table1 resets

**Reproduction:**
https://codesandbox.io/s/101nw1m6o3

**Versions:**
"react-bootstrap-table-next": "^3.0.2",
"react-bootstrap-table2-paginator": "^2.0.4",

**Comment by AllenFang** [comment]
@rexatgithub I think this is not a bug. Everytime you click on "Load" button in Actions column will trigger rerender `DataContainer`, that's why you go back to first page.


the best solution will be: Avoid `StudentList` get rerender when `state.selected_student` change by `shouldComponentUpdate`

**Comment by rexatgithub** [comment]
@AllenFang ow right. Thanks.
