### ISSUE TITLE
Custom Search Bar Without Button?

### ISSUE THREAD

**Issue by Jayboy75** [react-bootstrap-table/react-bootstrap-table2#872]
The default Searchbar has no <label> tag for its input, so it is not accessible to users with disabilities. I am therefore trying to create a custom searchbar component that is otherwise identical to the default, where search text is entered and the table responds without the user having to click a button. The only example in the documentation, however, uses a button. How would I set up a custom search bar so it responds to text input rather than a button click?

**Comment by Jayboy75** [comment]
Answered my own question. For the benefit of others this may help in future, here's how I did it (note disabled lines won't be necessary unless you are using eslint):

`import React from 'react';

const TableSearchBar = (props) => {
  let input;
  const handleChange = () => {
    props.onSearch(input.value); //eslint-disable-line
  };
  return (
    <div>
      <label htmlFor="table-search-bar" className="sr-only">
        Search This Data Table
        <input
          id="table-search-bar"
          className="form-control form-control-sm"
        ref={n => input = n} //eslint-disable-line
          type="text"
          placeholder="Search"
          onChange={handleChange}
        />
      </label>
    </div>
  );
};

export default TableSearchBar;`

**Comment by AllenFang** [comment]
I think `react-bootstrap-table2` already support a lots of way to let developer to custom the search bar, export csv button, pagination etc. [here](react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Fully%20Custom%20Search&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example to show how to completely custom a search component.

**Comment by Jayboy75** [comment]
@AllenFang Any examples on how to do the same with pagination? I didn't see a full customization in the docs.

**Comment by Jayboy75** [comment]
@AllenFang Also the dropdown filters that can be added to table columns - I need a way to customize those so I can add a <label> element to them for accessibility. Is there any way to do that?

**Comment by AllenFang** [comment]
@Jayboy75 
[docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html)
[example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Fully%20Custom%20Pagination&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)


---

use [column.formatter](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function) to custom your column.

**Comment by Jayboy75** [comment]
@AllenFang Thanks for pointing me in the right direction. Is there a way to create a custom filter dropdown so I can add a <label> tag to it? This is a necessity for 508/accessibility and from the docs it doesn't look like I can actually create my own filter with HTML in the same way as with the pagination buttons and search bar.
