### ISSUE TITLE
Reordering columns moves the column header but not the data

### ISSUE THREAD

**Issue by colinwagner** [react-bootstrap-table/react-bootstrap-table2#876]
Changing the order of columns provided to the 'columns' prop moves the table headers appropriately but the data within those columns does not move until some sort of data mutation causes a re-render.

**Comment by AllenFang** [comment]
@colinwagner we already fix in from last week, https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/866

**Comment by colinwagner** [comment]
@AllenFang I am on the latest version and am still experiencing this issue. It seems shouldUpdateByColumnsForSimpleCheck isn't being called?

**Comment by AllenFang** [comment]
@colinwagner I think it should be work, would you please give me an simple and minimal example on codesandbox?  So that I can reproduce it, Thanks
