### ISSUE TITLE
UMD files located in dist not working

### ISSUE THREAD

**Issue by sparkle225** [react-bootstrap-table/react-bootstrap-table2#877]
Attempting to use the umd version of the react-bootstrap-table2. I have attempted with the versions in the dist folder as well as within from unpkg. I am using the sdn version of react and react-dom. I have tried to access the BootstrapTable with the following code with and without the window.

var BootstrapTable = ReactBootstrapTable2.BootstrapTable;
<BootstrapTable
          keyField="id"
            data={data}
            columns={columns}
            striped
            hover
          />

I am receiving the error below. I do see the object in Global window but, doesn't seem to be able to actually create it.

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

<img width="489" alt="Screen Shot 2019-03-27 at 11 41 30 PM" src="https://user-images.githubusercontent.com/11600444/55117536-84610c00-50eb-11e9-9f33-81f6cf24eca2.png">

Would appreciate any guidance.

**Comment by AllenFang** [comment]
@sparkle225 would you please give me an example so that I can reproduce this issue? Please keep it simple and minimal, thank you very much.

**Comment by sparkle225** [comment]
I have a pretty simple example I am working with. See below.

In index.html I have something like below. Additional scripts for jquery, bootstrap and css are also included.
<html>
  <body id="form" class="claro app-loading">
    <div id="root"></div>
    <script defer src="bundle.js"></script>
  </body>
  <script src="js/react-bootstrap-table-next/dist/react-bootstrap-table-next.js"></script>

<html>


import React, { Component } from 'react';
import ReactDOM from "react-dom";


var BootstrapTable = ReactBootstrapTable2.BootstrapTable;

const data=[
  {"eventId":1,"eventType":"cd1","createdat":"03/06/19","mgrs":123456,"desc":"some test data goes here 3"},
  {"eventId":2,"eventType":"cd2","createdat":"03/07/19","mgrs":4562546,"desc":"some test data goes here 2"},
  {"eventId":3,"eventType":"cd3"createdat":"03/09/19","mgrs":245265462,"desc":"some test data goes here 2"}
]

const columns = [{
  dataField: 'eventId',
  text: 'Event Id',
  hidden:true
},{
  dataField: 'eventType',
  text: 'Event Type',
  sort: true
}, {
  dataField: 'mgrs',
  text: 'MGRS'
}, {
  dataField: 'createdat',
  text: 'created date',
  sort: true
}, {
  dataField: 'desc',
  text: 'Description',
}];

export default class TableView extends React.Component {


render(){
  return (
      <div>
      <BootstrapTable
          keyField="id"
            data={data}
            columns={columns}
            striped
            hover
          />
        </div>
  )
  }
}

index.js has something similar to

ReactDOM.render(<TableView/>, document.getElementById('root'));

**Comment by sparkle225** [comment]
Also, I am using webpack. I have react and react-dom setup as externals. This configuration seems to be working with the react-bootstrap cdn module.

**Comment by AllenFang** [comment]
@sparkle225 what react version you used?

**Comment by AllenFang** [comment]
I think there's no issue cause of I can not reproduce this. Please give me a packages which can reproduce this case, thanks
