### ISSUE TITLE
onContextMenu Row Instead Cell

### ISSUE THREAD

**Issue by ronaiza-cardoso** [react-bootstrap-table/react-bootstrap-table2#879]
Hi, first of all, thanks for the awesome work with this!

second: there's a way of getting the row element `onContextMenu` instead of the cell?

**Comment by AllenFang** [comment]
@ronaiza-cardoso you can try to use [`rowEvents`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#rowevents-object)
