### ISSUE TITLE
Can we have a custom button located outside to trigger CSV download ?

### ISSUE THREAD

**Issue by ahmarkhan** [react-bootstrap-table/react-bootstrap-table2#881]
Right now the toolkit provider is allowing us to download as csv. Ours requirements are like to have a separate button to download the table as csv.

Is there a way we can avoid useing toolkit provider for exporting to csv download ?

**Comment by AllenFang** [comment]
@ahmarkhan for custom the export csv button, you only  have to do it by toolkit provider: [example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Export%20CSV&selectedStory=Custom%20CSV%20Button&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).  Thanks
