### ISSUE TITLE
pagination drop down option become anchor(link)

### ISSUE THREAD

**Issue by noeljoaquin30** [react-bootstrap-table/react-bootstrap-table2#882]
Pagination drop down option become anchor(link)instead of a normal selection option. 
I noticed also after i select 25,30 ,50(last)  (it's working) but after i select previous page size(30,25 or 10) my page redirect to home page.

**Comment by AllenFang** [comment]
@noeljoaquin30 pagination dropdown option is always an anchor in bootstrap3 and 4. In addition, the `href` attribute is always `#`, so is it any example can let me reproduce it, 

https://codesandbox.io/s/k5750vzzvv this is an example you can take and give me a simple and minimal case for reproducing, thanks.  I will open this issue when I can reproduce this issue

**Comment by noeljoaquin30** [comment]
@AllenFang  i tried to fork your example and i have added records to test the pagination. And the page size option is not href attribute. Please check example  https://codesandbox.io/s/nro84z60np thank you

**Comment by noeljoaquin30** [comment]
hi @AllenFang  can you re-open the issue? since it is not cleared to me and not yet fixed. thanks

**Comment by AllenFang** [comment]
<img width="719" alt="螢幕快照 2019-04-07 下午3 01 59" src="https://user-images.githubusercontent.com/5351390/55679960-267fc000-5946-11e9-888f-2bd4781b212c.png">

Your example work for me lol

**Comment by noeljoaquin30** [comment]
yes that's right but in my real project the pagination size is an anchor link. how it happened ?

**Comment by sudir81** [comment]
> yes that's right but in my real project the pagination size is an anchor link. how it was happened ?

@noeljoaquin30 i have same issue, the drop down button it self navigating to "/step" page. Is this fixed in your case?
