### ISSUE TITLE
allow select options initialization with empty array

### ISSUE THREAD

**Issue by mathiaswillburger** [react-bootstrap-table/react-bootstrap-table2#885]
When initializing the select filter dropdown values with an empty array and adding entries at a later stage the following error is raised: `TypeError: Cannot read property 'value' of undefined`.

There is a solution for that, but I think it would be more friendly to allow initialization with an empty array in a future version ..... unless I am missing something which is already possible.

Here are the details:

According to the tutorial for [Preserved Option Order on Select Filter](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Preserved%20Option%20Order%20on%20Select%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) the implementation is pretty straightforward, by providing the select options as follows to the component:

```
const selectOptions = [
  { value: 0, label: 'good' },
  { value: 1, label: 'Bad' },
  { value: 2, label: 'unknown' }
];
```

This approach assumes that the select options are known when rendering the component. When however remotely querying the select options via an API, there might be some time delay between rendering the table and the dropdown and the actual data received.

Therefore selectOptions is first initialized with `let selectOptions = [];` and some seconds later filled by the API with actual label/value entries.

This leads to the above mentioned error `TypeError: Cannot read property 'value' of undefined`. indicating that the issue originates in `/react-bootstrap-table2-filter/lib/src/components/select.js` + `optionEquals` in the following line:

```
 if (currOpts[i].value !== prevOpts[i].value || currOpts[i].label !== prevOpts[i].label) {
```

The solution for that is pretty straightforward, by initializing the array with a dummy value like `let selectOptions = [{label: null, value: null}];` therefore not causing any issues in the application.

The side effect however is that for a couple of seconds, depending on the speed of the API, an empty value is shown in the dropdown. 

I would suggest to allow initialization with `let selectOptions = [];` until the values are available.

**Comment by AllenFang** [comment]
@mathiaswillburger agree this point, and this issue was asked before for a long time but just not time to fix it, I want to give a proposal like this:

```js
{
  dataField: 'quality',
  text: 'Product Quailty',
  formatter: cell => selectOptions[cell],
  filter: selectFilter({
    asyncOptions: (setOptions) => {
      // simulate a fake ajax call
      setTimeout(() => {
        setOptions(resultOptions);
      }, 1000);
    }
  })
}
```

`asyncOptions` callback function will be called everytime when rendering select dropdown, 
For developer, you can cache the selction option if they won't change, for example:

```js
{
  dataField: 'quality',
  text: 'Product Quailty',
  formatter: cell => selectOptions[cell],
  filter: selectFilter({
    asyncOptions: (setOptions) => {
      // you can cache resultOptions somewhere
      if (resultOptions) return resultOptions; // sync

      // simulate a fake ajax call
      setTimeout(() => {
        setOptions(resultOptions);
      }, 1000);
    }
  })
}
```

**Comment by AllenFang** [comment]
any idea is welcome, thanks

**Comment by SmaranSingh** [comment]
@AllenFang The function(`optionsEquals`) that checks whether the options in select filter have changed, eventually checks the length of the array of options.
So, instead of checking ```currOpts.length === prevOpts.length``` after iterating through the `currOpts` , if you do the check before the iteration, then the above problem would be resolved.

I've raised a PR #894  with my solution.

**Comment by AllenFang** [comment]
@SmaranSingh agree with you, I will adopt your PR and postpone the above idea for lazy load select option. Thank you very much!

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/04/16/version-bump.html)

Please update related packages listed in above notes, thanks

**Comment by mathiaswillburger** [comment]
Great job, works perfect! Thanks for the quick resolution.
