### ISSUE TITLE
Question: styled-components support in the table

### ISSUE THREAD

**Issue by leonas5555** [react-bootstrap-table/react-bootstrap-table2#887]
### Enhancement request/question: How can I style table row and columns with styled-components?
I saw that in previous version I mean "react-bootstrap-table" there was an option to use styled-components and also one example how to do that. I would like to see this feature here too .

**Comment by leonas5555** [comment]
I want to use styled HOC on table itself and on rows. Do I need somehow to utilize "classes" prop of components ? Like here https://material-ui.com/guides/interoperability/#styled-components

**Comment by AllenFang** [comment]
@leonas5555 sorry for lately reply, I think you can `styled-components`, let me know if you have some issues.



> Do I need somehow to utilize "classes" prop of components

which part you mean? if you were talking about `BootstrapTable`, I think it's yes, you need `classes` to add some custom class name on table element.

**Comment by gauravshankar** [comment]
@AllenFang : I am having issues in using Styled Component with react-bootstrap-table. 
Please have a look at sandbox url : https://codesandbox.io/s/loving-hopper-bn74p

I am trying to set background but not able to do it. (Not able to style via style component.)

**Comment by jofelipe** [comment]
> @AllenFang : I am having issues in using Styled Component with react-bootstrap-table.
> Please have a look at sandbox url : https://codesandbox.io/s/loving-hopper-bn74p
> 
> I am trying to set background but not able to do it. (Not able to style via style component.)
> Could you please reopen this.

did you find any solution? having the same here :(

**Comment by jofelipe** [comment]
Well, I may have a solution for who want to customize BootstrapTable with Styled Components:

I created a wrapper component, and wrapped BootstrapTable component (obviously xD). Sandbox is here: https://codesandbox.io/s/bootstraptable-with-styled-components-pfpw1
