### ISSUE TITLE
How to hook into after search

### ISSUE THREAD

**Issue by KBL9698** [react-bootstrap-table/react-bootstrap-table2#891]
I am new to react . . .  

I am using react-bootstrap-table-next@2.1.2

I would like to hook into after search filtering so I can update row counts.  However, I do not know where to do this. 

I believe I need to use this.node.table.props.data for the data, but do not know where to access it.

The onTableChange appears to be before search filtering - the counts are before the filtering.  I have also tried the onSearchChange, but maybe that is no longer valid in the newest version?

Thank you for your help!  

This is what I have tried :
```js
handleSearchChange=()=>{console.log( handlesearchchange")}

handlechange=(type, newstate)=>{
   console.log("handlechange " + type + " " + newstate)
   if (this.node && this.node.table && this.node.table){
	console.log(this.node.table.props.data.length);
	}
};

render() {
    const options = {
	onSearchChange: this.handleSearchChange
  };

<ToolkitProvider
    keyField="id"
    data={ this.props.data }
    columns={ columns }
    search
    exportCSV
    bootstrap4
    condensed
>
{
props => (
        <div id="bootstrap-table-toolbar" >
            <SearchBar  { ...props.searchProps } />	
            <button type="reset" onClick={ () => props.searchProps.onSearch('') }>
                <FontAwesomeIcon icon={faTimes} />
            </button>
            <ExportCSVButton id="export" className="ml-auto btn mr-2"  { ...props.csvProps }>Export</ExportCSVButton>
        </div>
        <BootstrapTable ref={ n => this.node = n } remote={ { filter: true } } onTableChange={this.handlechange()} options={options} { ...props.baseProps } />
    </div>
    )
}
</ToolkitProvider>
```

**Comment by AllenFang** [comment]
@KBL9698 sorry for lately reply, i can understand this case, I will try to implement a props like `onChange` or something like that and it will be called when data change.

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/04/16/version-bump.html)

Please update related packages listed in above notes, thanks

@KBL9698 in newest version, we have [`onDataSizeChange`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#ondatasizechange-function) prop.

[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Data&selectedStory=Data%20Change%20Listener&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an exmaple

**Comment by KBL9698** [comment]
Thank you!  I just upgraded and implemented!
