### ISSUE TITLE
onFilter not firing when using remote data

### ISSUE THREAD

**Issue by nathan-fortier** [react-bootstrap-table/react-bootstrap-table2#892]
When I am using remote data and trying to filter I want to tap into the onFilter function however it does not fire. Is there another way for me to do this?

This ONLY works if the remote flag for the table is false 
```js
onFilter: value => {
    console.log("FILTERING: ", value);
    //TODO: call api with updated search params
}
```

```
"react-bootstrap-table-next": "^3.0.3",
"react-bootstrap-table2-filter": "^1.1.7",
"react-bootstrap-table2-paginator": "^2.0.5",
```

**Comment by nathan-fortier** [comment]
It looks like I can accomplish what I am trying to do with the onTableChange callback

**Comment by AllenFang** [comment]
👍
