### ISSUE TITLE
Storybook Exposed API crash

### ISSUE THREAD

**Issue by TommyFortin** [react-bootstrap-table/react-bootstrap-table2#893]
The Exposed API example in the storybook crashes when you try to order a column.

Thanks for the package!

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Basic%20Table&selectedStory=Exposed%20API&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by AllenFang** [comment]
@TommyFortin it's a regression issue that caused by newest patch for row expand, I will fix this issue ASAP, thanks for this bug report.

**Comment by rahulpsd18** [comment]
Also, the example for **[Expand Only One Row at The Same Time](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Expand%20Only%20One%20Row%20at%20The%20Same%20Time&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)** in storybook is incorrect and exactly the same as **[Basic Row Expand](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Basic%20Row%20Expand&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)**. It is missing the `onlyOneExpanding: true` option in _expandRow_ object. 
Please update it. Thanks!

**Comment by AllenFang** [comment]
[RELEASE NOTE](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/04/16/version-bump.html)

Please update related packages listed in above notes, thanks

**Comment by AllenFang** [comment]
@rahulpsd18  thanks, I will update in next version!
