### ISSUE TITLE
How add additional column Header (Column Header Span)?

### ISSUE THREAD

**Issue by Menogus** [react-bootstrap-table/react-bootstrap-table2#896]
How add additional column Header like Product/Customer on this screen (like Column Header Span in prev. version):
http://allenfang.github.io/react-bootstrap-table/images/react-bootstrap-table-sample.png

??

**Comment by AllenFang** [comment]
@Menogus so far we dont have column span feature, I will implement it when I get time.

**Comment by AllenFang** [comment]
Close it due to duplicated issue
