### ISSUE TITLE
API change/request

### ISSUE THREAD

**Issue by oneringtorulethemall** [react-bootstrap-table/react-bootstrap-table2#897]
Would you consider adding a injectable service array that I could register for the services
I want to include? 
Something like:
      <BootstrapTable 
                        bootstrap4 
                        keyField='image' 
                        data={ images } 
                        bordered={false}
                        columns={ this.defineColumnList() } 
    
                        services= { [ paginationFactory | custompaginationFunction,
                                            rowSelectionFactory | customRowSelectionFunction,
                                            ...<sorting>,
                                            ...<filtering>...
                                            ]
                                        }
      </Bootstrap>

Also, the Toolkit object seems to have a fair amount of functionality when used in
conjunction with the BootstrapTable object...also seems like the names should be
flipped around...Just a thought!

It's set of tools regardless!
Keep up the good work.
  .jdt.

**Comment by AllenFang** [comment]
I think so far I will not consider this, cause of this is a major change for all of the users, so I will focus on feature enhancement until all the functions done then we can start to figure out how to enhance this. thanks!
