### ISSUE TITLE
Header Style for selectRow

### ISSUE THREAD

**Issue by ALuongIBM** [react-bootstrap-table/react-bootstrap-table2#899]
For column headers, I know you can style like this:

`const columns = [{ headerStyle: { backgroundColor: '#215E95', color: 'white'} }]`

How do I do this for selectRow header column? As far as I can tell, it only has options for the selected row style.

`const selectRow = { mode: 'checkbox', clickToSelect: true, style: { header: 'yellow' } }`

**Comment by AllenFang** [comment]
@ALuongIBM yeah, so far we didn't provide a way to custom the selection header, I will implement this ASAP, thanks

**Comment by ALuongIBM** [comment]
Thank you!

**Comment by rufoot** [comment]
@AllenFang @ALuongIBM 
I am trying to change the text color of the selected row and I am using the code as below.

`const selectRowProp = {
  mode: 'radio',
  style: { color: 'pink' },
  clickToSelect: true,
  hideSelectColumn: true,
  onSelect: onRowSelect,
}`

But it isn't working now. Do you have any idea?

**Comment by AllenFang** [comment]
@rufoot we allow developer to custom the row style or class: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-row.html#row-style-class

So you can use above ways to custom the row, then the only remain thing is how do you know which row is selected. [`selectRow.onSelect`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowonselect-function) will help you

**Comment by AllenFang** [comment]
we fixed this issue, [CHANGELOG](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/04/27/version-bump.html)

Please upgrade the packages which listed above to get newest patch, thanks

@ALuongIBM in your case, please use [`selectRow.headerColumnStyle`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowheadercolumnstyle-object-function) thanks!

**Comment by ALuongIBM** [comment]
Thanks for the quick turnaround! I appreciate you checking the issues so frequently.
