### ISSUE TITLE
Dynamically generated columns

### ISSUE THREAD

**Issue by BharahthyKannan** [react-bootstrap-table/react-bootstrap-table2#902]
@AllenFang  Is there any way to implement the Dynamically generated columns, I receive 30 + columns from the backend and I need to use formatters and other style props of the boot strap table. I saw lot of reference for the previous bootstrap table not for table2. Any pointers.?

**Comment by AllenFang** [comment]
@BharahthyKannan sorry for lately reply, I think dynamically generated column is possible definitely, I'm not very clear which part is the your concerns?

**Comment by BharahthyKannan** [comment]
@AllenFang  I was about to close this issue, Sorry for reaching out to you, the issue is cleared and we missed initially few details so i raised this question. Thanks for your support ! ,  Taking this opportunity as you available, when we expect the release-2019-q1-4 available.?  we need a Sticky header option . Thanks!

**Comment by AllenFang** [comment]
@BharahthyKannan currently, I'm busy on mu job, so I think I dont have enough time to deliver sticky header in near future, sorry~

**Comment by devevignesh** [comment]
@AllenFang @BharahthyKannan Could anyone explain me about dynamically generated columns 
Assume the below code as JSON response 
```
data: [
{
calls: 108,
expired: true,
company: "testCompanyOne"
},
{
calls: 112,
expired: false,
company: "testCompanyTwo"
},
{
calls: 134,
expired: false,
company: "testCompanyThree"
}
]

const columns = [
{
dataField: "calls",
text: "Calls"
}, 
{
... 
},
{
... 
}
]

<BootstrapTable data={data} columns={columns} />
```
Instead of having the raw data, is there any possible to render it from JSON response? Thanks.

**Comment by BharahthyKannan** [comment]
@devevignesh 
We just iterated the JSON response and generated the columns Array( with datefield, text, style and all necessary fields)
let me know if not clear, will try to generate a small sample. Thx

**Comment by devevignesh** [comment]
Hey @BharahthyKannan,

It could be better to understand if you get some example. Thanks for your time.
