### ISSUE TITLE
Boolean value and dropdown

### ISSUE THREAD

**Issue by Chaosbit** [react-bootstrap-table/react-bootstrap-table2#903]
Hi,
I have a column with boolean values that I want to edit.
I can change a cell from false to true, but not the other way around.

The column config looks like this:
```javascript
{
	dataField: 'hasAttribute',
	text: 'Attributes',
	sort: true,
	align: 'left',
	formatter: cell => (
		cell ? 'Yes' : 'No'
	),
	editor: {
		type: Type.SELECT,
		options: [{
			label: 'Yes',
			value: true,
		}, {
			label: 'No',
			value: false,
		}],
	},
}
```

Can you give me a hint what the issue might be?
We are using version 3.0.2

**Comment by AllenFang** [comment]
@Chaosbit I will check this, it might be a bug, thanks

**Comment by AllenFang** [comment]
Hello @Chaosbit I can not reproduce this case, would you please give an online example so that i can help you?

You can use codesandbox and [here](https://codesandbox.io/s/k5750vzzvv) is an example you can take it but just be careful the version of `react-bootstrap-table-next` and so on, thanks
