### ISSUE TITLE
CSV Export doesn't handle double quotes

### ISSUE THREAD

**Issue by CaptainCthulhu** [react-bootstrap-table/react-bootstrap-table2#904]
Currently if there's a double quote in a string during CSV export the text creates new unwanted cell breaks.  To fix, just need to replace line 45 of packages/react-boostrap-table2-toolkit/src/scv/exporter.js with `return "${cellContent}".replace(/"/g, '""');`

Thanks!

**Comment by AllenFang** [comment]
@CaptainCthulhu sorry for lately reply, thanks for your information and I will fix it by this week

**Comment by AllenFang** [comment]
@CaptainCthulhu  we fixed this issue, [CHANGELOG](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/04/27/version-bump.html)

Please upgrade the packages which listed above to get newest patch, thanks
