### ISSUE TITLE
Sorting fails when columns are expandable

### ISSUE THREAD

**Issue by nordicbondpricing** [react-bootstrap-table/react-bootstrap-table2#907]
Hi

When a table is expandable, sorting fails. Edit: See the codesandbox example in next comment

**Comment by nordicbondpricing** [comment]
Hi

Added a codesandbox [example](https://codesandbox.io/s/m7126pv7zy)

**Comment by AllenFang** [comment]
@nordicbondpricing  fixed!

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/04/16/version-bump.html

**Comment by nordicbondpricing** [comment]
thanks!
