### ISSUE TITLE
The `expandRow` does not work with nested `keyField`

### ISSUE THREAD

**Issue by yurii-sorokin** [react-bootstrap-table/react-bootstrap-table2#908]
The `expandRow` option does not work with nested `keyField` (e.g. `keyField="some.deep.id.key"`). 
As I can see it's because of this line:

https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/497bf44192a99a0a6612317200aa940d0f1a12ab/packages/react-bootstrap-table2/src/store/expand.js#L28

**Comment by AllenFang** [comment]
@yurii-sorokin sorry for lately reply, I will fix it by this week, thanks

**Comment by AllenFang** [comment]
@yurii-sorokin I think we fixed this issue, [CHANGELOG](https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/04/27/version-bump.html)

Please upgrade the packages which listed above to get newest patch, thanks
