### ISSUE TITLE
onlyOneExpanding passed true but all rows are getting expanded

### ISSUE THREAD

**Issue by Puneetbh** [react-bootstrap-table/react-bootstrap-table2#909]
I used `onlyOneExpanding` flag in expandRow object as true but all rows are expanding. Below is my expand row object for reference

`const expandRow = {
  renderer: row => (
    <div><p>row name</p></div>
  ),
  showExpandColumn: true,
  onlyOneExpanding: true,
  expandByColumnOnly: true
};`

When i click on single row it is expanding all rows, I am not sure what is missing

**Comment by Puneetbh** [comment]
I got the work around, keyField needs to be unique for table

**Comment by AllenFang** [comment]
@Puneetbh sorry for lately reply and yes the `keyField` is supposed to be unique

**Comment by ThahaShahzad** [comment]
i am still getting this issue with keyField unique 

![image](https://user-images.githubusercontent.com/61521512/82640347-09e92a80-9bd0-11ea-85f3-514e8784f446.png)

**Comment by ThahaShahzad** [comment]
![image](https://user-images.githubusercontent.com/61521512/82640600-7ebc6480-9bd0-11ea-910c-03312b09b590.png)
![image](https://user-images.githubusercontent.com/61521512/82640654-94318e80-9bd0-11ea-8a49-02dba8ee09ec.png)

**Comment by ThahaShahzad** [comment]
nvm sorry just read what keyField actually is its working
