### ISSUE TITLE
React styleguidist 

### ISSUE THREAD

**Issue by prajapati-parth** [react-bootstrap-table/react-bootstrap-table2#91]
@AllenFang I'm aware you've selected storybook for building examples. But as we are still at an early stage in react-bootstrap-table2, would it be possible to use [React styleguidist](https://react-styleguidist.js.org/) compared to storybook?
They offer great configurations and support JSDoc comment transformation to prop tables. [Example](https://react-styleguidist.js.org/docs/documenting.html#code-comments-and-proptypes).

I'd be more than happy to build examples from scratch using react styleguidist. 

Thanks.

**Comment by AllenFang** [comment]
@prajapati-parth nice suggestion. For my opinion, the storybook is better to perform the example and it support to publish your books to website and the other concern is storybook is more popular and active community. After I checked the styleguidist quickly, storybook and styleguidist are easy to config, change styles or create your plugin. But support JSDoc is a nice point for me, I'll investigate it more for this option. thanks your feedback, it's really awesome

**Comment by prajapati-parth** [comment]
Sure @AllenFang. I also did see that storybook has a larger community. :+1:

**Comment by prajapati-parth** [comment]
@AllenFang @Chun-MingChen Checkout prajapati-parth/react-bootstrap-table2@b6ac6d586ee0984b68ec73c5c67c3c3af35044ff. I've added 3 examples using styleguidist and it seems pretty cool. 

Screenshot for quick reference(the code blocks are collapsable and interactive playground for live editing):
Note: The sidebar is broken in screenshot by full page screenshot plugin, else it works perfectly.
![screencapture-192-168-0-102-6060-1508019247638](https://user-images.githubusercontent.com/17194534/31579779-5fb8e0c0-b15b-11e7-8051-56fbbbb19797.png)

**Comment by AllenFang** [comment]
@prajapati-parth thanks, we will consider it. Currently, I think we need a explicit or actual benefit to prove `react-styleguidist` is more better than `react-storybook`, After checked your commit, I think `react-styleguidist` and `react-storybook` still need some configuration but not very hard to config.

So I think I prefer to keep to use  `react-storybook` but let's keep this thread here an if there have more benefit on  `react-styleguidist` then I can toward to use it :)

Thanks 👍

**Comment by prajapati-parth** [comment]
Sure @AllenFang, mean while you can visit [here](https://react-styleguidist.js.org/docs/cookbook.html#whats-the-difference-betweeen-styleguidist-and-storybook) for the differences between `react-storybook` and `react-styleguidist`.

**Comment by AllenFang** [comment]
Great 👍

**Comment by prajapati-parth** [comment]
@AllenFang after more in detail looking into the options, I understand that storybook is better suited for a development environment whereas react-styleguidist is for creating playground/documentation site. And since we are using docusaurus for the documentation site, the question in this issue is out of purpose. Closing this out!
