### ISSUE TITLE
Row expand animation opt out.

### ISSUE THREAD

**Issue by elmoro666** [react-bootstrap-table/react-bootstrap-table2#912]
Hi

It would be useful to be able to remove the animation on row expand. I find the old way to be much better:

[new](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Basic%20Row%20Expand&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

[old](https://allenfang.github.io/react-bootstrap-table/example.html#expand)

The new is slow and the motion is not smooth. I have no experience with pull requests, but I am happy to have a go at it, if you want.

**Comment by elmoro666** [comment]
I just saw there is an issue already on this. sorry about that. closing

**Comment by YassienW** [comment]
@elmoro666 Hello, i'm the guy who wrote the row expand animation. I was just curious about why you think the motion isn't smooth?
I do agree that the animation should be optional though.

**Comment by elmoro666** [comment]
@YassienW  Sorry, maybe that came across a bit harsh. Here is a sandbox [example](https://codesandbox.io/s/1y8zkr7m7) of what I mean. Maybe it is just my eyes, but it seems to start slow, and then it speeds up at the end. It makes it seem not so smooth to my eyes. The main thing for me is that it is too slow. Our users need to drill down into details quickly, and so I prefer it without animation. I 'fixed' it in my project by changing the css.

**Comment by YassienW** [comment]
No problem. Thanks for the snippet! I do notice the visual bug. I didn't really test it on large bodies of text so i didn't realize this visual bug existed, i will surely look into it. The animation is indeed useless if all you care about is speed and not visuals, i'll see if i can add a prop to toggle it on/off as well since the css fix isn't really a fix.

**Comment by elmoro666** [comment]
@YassienW  That would be great. Thanks for looking into this

**Comment by AllenFang** [comment]
Sorry for lately reply due to busy on my work. thanks @YassienW  and any enhancement is welcome 👍

**Comment by YassienW** [comment]
@AllenFang Yeah i'm trying. Very busy on other projects as well :/

**Comment by clmz** [comment]
Any updates on this?

**Comment by adgryz** [comment]
Still no updates ? :/

**Comment by Xenio-Bidchat** [comment]
@AllenFang @YassienW 
 Hi, Is there any updates on this.. even i'm facing the same problem :(.. Please fix this issue. Thanks

**Comment by YassienW** [comment]
Hey folks, i know it's late but i just submitted PR #1289  that fixes the height problem @elmoro666 has, i'd appreciate testing it before/after release. The PR also adds a prop to opt out of animating the expansion.

**Comment by xtrapower** [comment]
```
.react-bootstrap-table .row-expand-slide-exit-active {
  max-height: 0;
  overflow: hidden;
  transition: none !important; }

.react-bootstrap-table .row-expand-slide-appear-active {
  max-height: 1000px;
  transition: none !important; }
```

In the meantime add this CSS to disable the animation

**Comment by tomimarkus991** [comment]
hi, any updates?
