### ISSUE TITLE
row expand gives error of key 'undefined' error 

### ISSUE THREAD

**Issue by my1795** [react-bootstrap-table/react-bootstrap-table2#915]
In below part I have tried to implement a table. Data is retrieved from database before mounting the component. Selectrow is working properly. However if I want to use expandrow prop it gives me the error ; TypeError: Cannot read property 'includes' of undefined:

> exports.default = function (Component) {
  42 |   var renderWithExpansion = function renderWithExpansion(props, expandRow) {
  43 |     var key = props.value;
> 44 |     var expanded = expandRow.expanded.includes(key);
  45 |     var isClosing = expandRow.isClosing.includes(key);
  46 |     var expandable = !expandRow.nonExpandable || !expandRow.nonExpandable.includes(key);
  47 |     return [_react2.default.createElement(Component, _extends({}, props, {

So how can we solve the problem?

`import React, { Component } from 'react';
//import './App.css';
import { Container } from 'react-bootstrap';
import { Button } from 'react-bootstrap';
import { Row } from 'react-bootstrap';

import BootstrapTable from 'react-bootstrap-table-next';
import filterFactory, { textFilter, dateFilter} from 'react-bootstrap-table2-filter';

import paginationFactory from 'react-bootstrap-table2-paginator';
import 'react-bootstrap-table2-filter/dist/react-bootstrap-table2-filter.min.css'

import cellEditFactory, { Type } from 'react-bootstrap-table2-editor';
class SearchPage extends Component {
    constructor(props){
        super(props);
        this.state = {
            show: false,
            columns: [{
                dataField: 'generalinfo_id',
                text: 'Info     ID',
                headerAlign: 'center',
                sort: true,
                filter: textFilter(),
                headerStyle:{ backgroundColor: '#81c784',width:'100px'}
              }, {
                dataField: 'fromcompletedby',
                text: 'Completed By',
                headerAlign: 'center',
                filter: textFilter(),
                headerStyle:{ backgroundColor: '#81c784',width:'100px'}
              }, {
                dataField: 'gpsproduct',
                text: 'Product',
                headerAlign: 'center',
                filter: textFilter(),
                editor: {
                  type: Type.SELECT,
                  options: [{

                    value: 'E',
                    label: 'E'
                  }]
                },
                headerStyle:{ backgroundColor: '#81c784',width:'100px'}
              },
              {
                dataField: 'startdate',
                text: 'Date',
                headerAlign: 'center',
                filter: dateFilter(),
                editable: false,
                headerStyle:{ backgroundColor: '#81c784',width:'100px'}
              },
              {
                dataField: 'caseid',
                text: 'Case        ID',
                sort: true,
                filter: textFilter(),
                headerFormatter: this.caseIDFormatter,
                headerAlign: 'center',
                headerStyle:{ backgroundColor: '#81c784',width:'100px'}
              },
              {
                dataField: 'customername',
                text: 'Customer Name',
                headerAlign: 'center',
                filter: textFilter(),
                headerStyle:{ backgroundColor: '#81c784',width:'100px'}
              },
              {
                dataField: 'description',
                text: 'Description',
                headerAlign: 'center',
                filter: textFilter(),
                editor: {
                  type: Type.TEXTAREA
                },
                headerStyle:{ backgroundColor: '#81c784',width:'250px'}
              },
              {
                dataField: 'pname',
                text: 'Problem     Name',
                headerAlign: 'center',
                filter: textFilter(),
                editor: {
                  type: Type.SELECT,
                  options: [{

                    value: 'E',
                    label: 'E'
                  }]
                },
                headerStyle:{ backgroundColor: '#81c784',width:'100px'}
              }

                         
            ],
          
              selectedRows: [],

              generalinfo: [
               
              ],

            
        }
        this.handleSelected = this.handleSelected.bind(this);
        this.saveChanges = this.saveChanges.bind(this);
        this.deleteRows = this.deleteRows.bind(this);
        this.handleShow = this.handleShow.bind(this);
        this.handleClose = this.handleClose.bind(this);
    }
    handleClose() {
      this.setState({ show: false });
    }
  
    handleShow() {
      this.setState({ show: true });
    }
 
     caseIDFormatter(column, colIndex, { sortElement, filterElement }) {
        return (
          <div style={ { display: 'flex', flexDirection: 'column' } }>
            { filterElement }
            { column.text }
            { sortElement }
          </div>
        );
      }
      handleSelected(){
          console.log(this.state.generalinfo.dataField);
      }
     
    componentWillMount(){
      this.assignGeneralInfo();
      this.assingProductBox();
      this.assignProblemBox();
      }

    deleteRows(){
      for(let row of this.state.selectedRows){
        this.deleteRow(row);
      }
      this.assignGeneralInfo();
      this.forceUpdate();
      
    }
    deleteRow(generalinfo_id){
      const axios = require('axios');
      axios.post(`http://localhost:4000/generalinfo/remove?generalinfo_id=${generalinfo_id}`,{
        headers: {"Content-Type": "text/plain"},
        method: 'POST',
        data: "delete sent"
      })
    .then(function (response) {
      // handle success
      console.log(response.data);
    })
    .catch(function (error) {
      // handle error
      console.log(error);
    })
    .then(function () {

      
    });
      alert("Deleted");

    }
    saveChanges(generalinfo_id,fromcompletedby,gpsproduct,startdate,caseid,customername,description,pname){
      const axios = require('axios');
      axios.post(`http://localhost:4000/generalinfo/update?generalinfo_id=${generalinfo_id}&startdate=${startdate}&caseid=${caseid}
      &gpsproduct=${gpsproduct}&fromcompletedby=${fromcompletedby}&customername=${customername}
      &description=${description}&pname=${pname}`,{
        headers: {"Content-Type": "text/plain"},
        method: 'POST',
        data: "update sent"
      })
    .then(function (response) {
      // handle success
      console.log(response.data);
    })
    .catch(function (error) {
      // handle error
      console.log(error);
    })
    .then(function () {

      
    });
      alert("changes saved");

    }
      assignGeneralInfo(){
        fetch('http://localhost:4000/generalinfo')
        .then(response => response.json())
        .then(({ data }) => {
          this.setState({generalinfo : data})
          
        })
        .catch(err => console.error()
        )
      }
      assingProductBox(){
        let products = [];
        let opt = [];
        fetch('http://localhost:4000/products')
        .then(response => response.json())
        .then(({ data }) => {
          for(var el of data){
            products.push(el.productname);
            console.log(el.productname);
          }
          
        })
        .then( () => {
          for(var k =0; k< products.length; k++){
            opt.push({value: products[k], label: products[k] });
          }
         var copy = this.state.columns.slice();
         copy[2].editor.options = opt;
         this.setState({columns: copy});
          console.log(opt[0]);
        })
        .catch(err => console.error()
        )
      
      
      }
      assignProblemBox(){
        let problems = [];
        let opt = [];
        fetch('http://localhost:4000/problems')
        .then(response => response.json())
        .then(({ data }) => {
          for(var el of data){
            problems.push(el.problemname);
            console.log(el.problemname);
          }
          
        })
        .then( () => {
          for(var k =0; k< problems.length; k++){
            opt.push({value: problems[k], label: problems[k] });
          }
         var copy = this.state.columns.slice();
         copy[7].editor.options = opt;
         this.setState({columns: copy});
        })
        .catch(err => console.error()
        )
      
      
      }

    render() {
      const   expandRow= {
        renderer: row => (
          <div>
            <p>{ `This Expand row is belong to rowKey ${row.generalinfo_id}` }</p>
            <p>You can render anything here, also you can add additional data on every row object</p>
            <p>expandRow.renderer callback will pass the origin row object to you</p>
          </div>
        )
      };

      const selectRow = {
        mode: 'checkbox',
        clickToSelect: true,
        bgColor: (row, rowIndex) => (rowIndex % 2 == 0 ? '#00BFFF' : '#00FFFF'),
        clickToExpand: true,
        clickToEdit: true,
        onSelect: (row, isSelect, rowIndex, e) => {
          if(isSelect === true){
            this.state.selectedRows.push(row.generalinfo_id);
          }
          if(isSelect === false){
            this.state.selectedRows.splice(this.state.selectedRows.indexOf(row.generalinfo_id),1);
          }
         console.log(row.rowKey);
          
        },
        onSelectAll: (isSelect, rows, e) => {
           console.log(isSelect);
           console.log(rows);
           console.log(e);
         if(isSelect === true){
           let copyselected = this.state.selectedRows.slice();
           for(let row of rows){
            copyselected.push(row.generalinfo_id);
           }
           this.setState({selectedRows: copyselected});
           console.log("copy selected will be printed");
           console.log(copyselected);
          
         }
         if(isSelect === false){
          let copyselected = this.state.selectedRows.slice();
          for(let row of rows){
            copyselected.splice(copyselected.indexOf(row.generalinfo_id),1);
            
          }
          this.setState({selectedRows: copyselected});
         
         }
     
         }
      };
      const cellEdit = {
        mode: 'click'
      };

      
      
        return (
          
            <div>
                <Container>
       
                  <Row>
                  <Button  onClick={this.deleteRows}  variant="danger" size="lg" active >
          Delete Selected Rows
         </Button>
         <hr></hr>
         <Button onClick={this.handleShow}    variant="danger" size="lg" active >
          Expand Selected rows 
         </Button>
     
  
                  </Row>
                  <hr></hr>
                  <Row>
                  <BootstrapTable keyField = 'generalinfo_id'  filter={ filterFactory()} selectRow={ selectRow }  
               
                  data = { this.state.generalinfo} columns = { this.state.columns }  
                  striped hover condensed
                expandRow = {expandRow}
                  cellEdit={ cellEditFactory({ mode: 'dbclick',blurToSave: true ,
                  afterSaveCell: (oldValue, newValue, row, column) => {
                  // insert buradan yapılacak database e atılacak delete selected kısmına dikkat.
                  console.log(oldValue);
                  console.log(newValue);
                  console.log(row.generalinfo_id);
                  console.log(row.rowKey);
                  this.saveChanges(row.generalinfo_id,row.fromcompletedby,row.gpsproduct,row.startdate,row.caseid,row.customername,row.description,row.pname)
                 }
                }) } 
                  pagination={ paginationFactory() }
                   >

</BootstrapTable>
                    
                  </Row>
  
                </Container>

            </div>
        );
    }
}

export default SearchPage;
`

**Comment by my1795** [comment]
Also if I would like to print rowKey in rowSelect property. It prints rowkey as undefined but I can use selectrow properly. If there is no row key, I have no idea why I can select the row. I am confused

**Comment by AllenFang** [comment]
@my1795 what's the version of `react-bootstrap-table-next` ?

**Comment by my1795** [comment]
> @my1795 what's the version of `react-bootstrap-table-next` ? i can not reproduce this issue, thanks

Thanks, solved
