### ISSUE TITLE
file-saver IE11 issues

### ISSUE THREAD

**Issue by waynebrantley** [react-bootstrap-table/react-bootstrap-table2#916]
We are having quite a few IE11 issues we traced back to file-saver which react-bootstrap-table2-toolkit uses.

1)  Would it be possible to upgrade to the 2.0 release of file-saver?
2)  Would you consider splitting out the 'file saving' ability to something like `react-bootstrap-table2-saving', etc?  We are not using file-saving, but are using the toolkit for search.

**Comment by AllenFang** [comment]
@waynebrantley so if i upgrade `file-saver` to newest version can solve all of your issues?
because if split the file-saving part, that will be a major change.

**Comment by AllenFang** [comment]
btw, sorry for lately reply, busy on my job lol

**Comment by waynebrantley** [comment]
Cannot be sure if you upgrade it will solve all issues.  I know they solved some IE11 issues when updating to latest version.  Thoughts?

**Comment by AllenFang** [comment]
@waynebrantley anyway, I will try to upgrade. If the issue still remain then I will consider to separate it out.

**Comment by AllenFang** [comment]
@waynebrantley I upgrade file savers and please upgrade below packages to newest:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/05/19/version-bump.html
