### ISSUE TITLE
Invalid prop `tableId` of type `number` supplied to `SearchBar`, expected `string`.

### ISSUE THREAD

**Issue by dkulp23** [react-bootstrap-table/react-bootstrap-table2#917]
Allen, first and foremost thank you for making this excellent library available.
This morning I updated from v3.1.0 `=>` v3.1.1 and noticed this failed propType warning in the console.
I am only using 1 table per view so I have not previously made use of the `id` prop. I attempted to supply this to both the `ToolkitProvider` wrapper as well as to the `BootstrapTable` component with no success.
I cloned and launched the Storybook examples locally and noticed that this warning is also present there running the development build.
I noticed that this prop was added to the `SearchBar` in the most recent updates to improve accessibility but I'm unable to determine from the docs how to set it explicitly.
Any pointers would be greatly appreciated.

<img width="1083" alt="Screen Shot 2019-04-22 at 10 53 14 AM" src="https://user-images.githubusercontent.com/16858580/56515720-69689880-64ed-11e9-8787-6a8212827750.png">

**Comment by dkulp23** [comment]
🤦‍♂️ Just realized that a [PR](https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/914) has already been opened to patch this issue.

**Comment by AllenFang** [comment]
@dkulp23 yeah, I will merge it before end of this week thanks
