### ISSUE TITLE
× Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by rmorgan0076** [react-bootstrap-table/react-bootstrap-table2#918]
I am not sure where this error is being generated but any help would be greatly appreciated.

**Comment by rmorgan0076** [comment]
This is actually coming from the productgenerator.

**Comment by AllenFang** [comment]
@rmorgan0076 sorry, I can not help you without more information, please give me your code or something helpful, thanks
