### ISSUE TITLE
Question: How to get current seleted row?

### ISSUE THREAD

**Issue by azxca1731** [react-bootstrap-table/react-bootstrap-table2#920]
I want to know seleted row. so I enter your storybook. 
I found page Exposed API. but it doesn't work well
[react-bootstrap-table2 storybook](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Basic%20Table&selectedStory=Exposed%20API&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).
when i clicked the button named "get current seleted row", the error come out like this.
![image](https://user-images.githubusercontent.com/28680240/56584344-91075000-6616-11e9-8972-b6cbc1737ad2.png)

How can i get selected row?

**Comment by AllenFang** [comment]
@azxca1731 sorry that I forget to update storybook, but the [doc](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/exposed-api.html#get-current-selected-rows) is the correct way to get the selection. I will update storybook thanks

**Comment by azxca1731** [comment]
@AllenFang Thank you for your attention! Doc is pretty cool

**Comment by AllenFang** [comment]
Issue fixed : https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Basic%20Table&selectedStory=Exposed%20API&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
