### ISSUE TITLE
SearchBar not occupying 100% width

### ISSUE THREAD

**Issue by Mirzamohammad22** [react-bootstrap-table/react-bootstrap-table2#921]
So i have followed the storybook for the react-bootstrap-table2, however for the SearchBar as documented in the storybook it does not take the 100%width of the screen, is there an property i can override to fix this

**Comment by AllenFang** [comment]
I dont see this situation? where did you observer it or which story use followed?

**Comment by Mirzamohammad22** [comment]
this is the story use followed
https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Table%20Search&selectedStory=Basic%20Search%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel.

this is my code:
-----------------------------------------------------------------------------------------------------------
<ToolkitProvider
                    keyField="id"
                    data={ this.state.transcriptionData }
                    columns={ this.columns }
                    search  
                  >
                    {
                      props=> (
                        <div>
                          <SearchBar 
                            placeholder="Search Documents" {...props.searchProps} style={{ width: '385%' }} 
                          />
                          <hr />
                          <BootstrapTable
                           {...props.baseProps} noDataIndication="Data is loading..." bordered={false} striped hover condensed
                          />
                        </div>
                      )
                    }
---------------------------------------------------------------------------------------------------------

Result:
![image](https://user-images.githubusercontent.com/38260994/56667873-a4bac100-66bf-11e9-97f6-19a1cc1bc9ba.png)

**Comment by AllenFang** [comment]
@Mirzamohammad22 did you import the bootstrap css?

**Comment by AllenFang** [comment]
the input is 100% width is due to I use `form-control` and that is from bootstrap's default styling

**Comment by Mirzamohammad22** [comment]
> 
> 
> @Mirzamohammad22 did you import the bootstrap css?

yes i have imported 'react-bootstrap-table-next/dist/react-bootstrap-table2.min.css'

**Comment by Mirzamohammad22** [comment]
> 
> 
> the input is 100% width is due to I use `form-control` and that is from bootstrap's default styling

worked around the width by increasing it to 385%

**Comment by AllenFang** [comment]
@Mirzamohammad22 oh ... import `react-bootstrap-table2.min.css` is not enough,  because `react-bootstrap-table2.min.css` only contain the table specified styling, you should add bootstrap to your project.

I didn't mention people should add bootstrap styling because this is a bootstrap component, so I assume developer should already have the bootstrap in their project. In addition, I also didn't import the bootstrap as a dependency, because just wanna reduce the size and make it more lightweight

**Comment by thebradisrad** [comment]
To solve this issue, go into the folder modules/bootstrap/bootstrap.scss and comment out "@import reboot". Or find the specific part inside that _reboot.scss file and comment it out. It is is a top level styling that overrides other styles.
