### ISSUE TITLE
Question: Programmatically Custom Remote Filter

### ISSUE THREAD

**Issue by rchaser** [react-bootstrap-table/react-bootstrap-table2#922]
Could you please give example how to use all this concepts together?
I have custom filter controls for 3 columns (the custom controls are select inputs that in background load data from server), also in a distinct column I have a button, that should be the only way to call filtering on the server, no filtering should happen when user choose values in all 3 filters. Also I've already used remote paging and sorting.

**Comment by AllenFang** [comment]
@rchaser sorry I still not very clear about your question, I think in the online storybook, we had showed the ppl how to implement a remote filter or a custom filter. Maybe be you can just point me which part you are not clear.

if you can give me an online example and explain more detail that will be great: https://codesandbox.io/s/k5750vzzvv you can take this and remember to change the version.

I will reopen this issue if there's any bug and please tag me if you provide more information, thanks

**Comment by rchaser** [comment]
@AllenFang for now in my application I've done something similar to this example, but I have concerns whether it is good approach or not. 
https://codesandbox.io/s/pjr0242820
In this example I haven't implemented filter with custom component for short, but in my app one of the column filters using custom component
