### ISSUE TITLE
add label before page size dropdown

### ISSUE THREAD

**Issue by udenizdogan** [react-bootstrap-table/react-bootstrap-table2#923]
Is it possible write like this 'Rows per page : ' before than page size dropdown ?

**Comment by AllenFang** [comment]
@udenizdogan please read [pagination](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-pagination.html) docs, here we show you how to custom the pagination.

[this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Pagination&selectedStory=Standalone%20SizePerPage%20Dropdown&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) online demo is might be your top answer.

please tag me if the issue still remain, thanks
