### ISSUE TITLE
Remote Sorting and Custom Filter renderer

### ISSUE THREAD

**Issue by rchaser** [react-bootstrap-table/react-bootstrap-table2#927]
Any time I click inside custom component for filtering (react-select), table fires onTableChange with type:"sort"

https://codesandbox.io/embed/7kky87yv2x

**Comment by AllenFang** [comment]
@rchaser sorry for lately reply, I will track this issue and see if we can fix this issue, thanks!

**Comment by AllenFang** [comment]
@rchaser BTW, is it possible to avoid the click event on custom filter bubble up?  because in `react-bootstrap-table2`, we will listen the click event on header cell and for all the default filter component, we will call the `stopPropagation` to stop event bubble up.

**Comment by muiruri** [comment]
> @rchaser sorry for lately reply, Is it possible to avoid the click event on custom filter bubble up? because in `react-bootstrap-table2`, we will listen the click event on header cell and for all the default filter component, we will call the `stopPropagation` to stop event bubble up.

I achieved the same by having an `onClick` event on my rendered component and calling `stopPropagation` when the event is triggered. Could be wrapped in a `div`

**Comment by AllenFang** [comment]
👍
