### ISSUE TITLE
Add way to place filters outside of table header

### ISSUE THREAD

**Issue by python273** [react-bootstrap-table/react-bootstrap-table2#928]
Currently I do it this way:
```js
    // column
    filter: customFilter({type: FILTER_TYPES.SELECT}),
    filterRenderer: (onFilter, column) => {
      this.onSomethingFilter = onFilter;
      return null;
    },
    // then using this.onSomethingFilter in a custom input
```
but it seems hacky. Is there a better way?

Maybe it can be done via calling `onTableChange` handler? Or it's possible to add prop for filter values that would trigger table change when it's changed

**Comment by Vinaythegreat** [comment]
I too want this feature !!

**Comment by Vinaythegreat** [comment]
@python273 can you share the full code or codesandbox.io as i am anewbie to react and react table ? It will help me to understand it in a better way.

**Comment by python273** [comment]
@Vinaythegreat 
https://stackblitz.com/edit/react-55g1xe?file=index.js

**Comment by Vinaythegreat** [comment]
@python273 That helped me a lot. Thank you so much !!

**Comment by AllenFang** [comment]
@python273 thanks your help 👍

**Comment by python273** [comment]
So is it recommended solution? Seems hacky to me

**Comment by AllenFang** [comment]
@python273 and @Vinaythegreat  use [Programmatically Filter](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-filter.html#programmatically-filter) will be the best solution


[example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=Programmatically%20Text%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)
