### ISSUE TITLE
Support for headerEvents onKeypress (for keyboard Accessibility Support)

### ISSUE THREAD

**Issue by mazhar-nbs** [react-bootstrap-table/react-bootstrap-table2#929]
Hi @AllenFang ,
Thank you for such a useful package and great effort.

Currently headerEvents don't support onKeypress event and I need it for Accessibility Support like on pressing "Enter" key the sorting should apply on the table.

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnevents-object

**Comment by AllenFang** [comment]
hello @mazhar-nbs sorry for lately reply, so far I think table header is not accessible so i will enhance it to make header cell accessible then you can use any event on `headerEvents`.

**Comment by AllenFang** [comment]
Fixed it and please upgrade below packages to newest:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/05/19/version-bump.html
