### ISSUE TITLE
Click on selection checkbox causes row to expand

### ISSUE THREAD

**Issue by stilllife00** [react-bootstrap-table/react-bootstrap-table2#932]
I have configured my table with:

````
{ clickToSelect: false, clickToExpand: true }
````

The table correctly selects and clicking on the row it correctly expands/collapse.
But when I click on the selection checkbox it should NOT expand/collapse. The version 1 of the library was working properly about this.

The usecase is that when a row is expanded and I click the checkbox to select, I don't want the row to collapse. 

So basically the click on checkbox should not bubble up the event on the row.

**Comment by AllenFang** [comment]
@stilllife00 sorry for lately reply, I will enhance this in near future, thanks

**Comment by AllenFang** [comment]
Fixed it and please upgrade below packages to newest:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/05/19/version-bump.html

**Comment by shortwavedave** [comment]
I have the same setup:

{ clickToSelect: false, clickToExpand: true }

but now the onExpand callback doesn't fire and I can't manage the expanded rows through state.
