### ISSUE TITLE
Sort Table is adding the rows instead of refresh

### ISSUE THREAD

**Issue by sridhar-v9** [react-bootstrap-table/react-bootstrap-table2#933]
Team,

  Not sure Its problem in my code or not, When i click on sort on a column the DataTable is appending the new rows to the existing rows. Can you please guide..

 **Page loading**
![image](https://user-images.githubusercontent.com/16562639/57101425-cd0d7580-6ce6-11e9-94e7-31577a31d37c.png)

**After click on sort button of county column**

![image](https://user-images.githubusercontent.com/16562639/57101537-15c52e80-6ce7-11e9-9f16-72d882963b94.png)

The pagination's sizePerPage is limited to '5' records
Thanks in advance

**Comment by zhr1130** [comment]
Is key field unique ? I had similar problem when filtering and it turned out the keyField I used is not unique.

**Comment by sridhar-v9** [comment]
> Is key field unique ? I had similar problem when filtering and it turned out the keyField I used is not unique.

*Sure **Rita Zhao** i will try and let you know the result*

**Comment by sridhar-v9** [comment]
Thank you  **Rita Zhao** tried and its working as expected now ...
