### ISSUE TITLE
Drop down editor :  Display label instead of Value 

### ISSUE THREAD

**Issue by BharahthyKannan** [react-bootstrap-table/react-bootstrap-table2#934]
Hi ,
I am trying the drop down cell editor, giving different Label and Value. but I see the value is displayed on selection and not the Label. 

How i can show selected Label rather than selected Value. Am i missing something here?

render(){

    
    const stocks=[
        {id:1,name:'Books',owner:'Books',type:'E'},
        {id:2,name:'Books',owner:'Books',type:'E'},
        {id:3,name:'Books',owner:'Books',type:'E'},
        {id:4,name:'Books',owner:'Books',type:'E'},
    
            ]
        

    const columns = [{
        dataField: 'id',
        text: 'Job ID'
      }, {
        dataField: 'name',
        text: 'Job Name'
      }, {
        dataField: 'owner',
        text: 'Job Owner'
      }, {
        dataField: 'type',
        text: 'Job Type',
        editor: {
          type: Type.SELECT,
          options: [{
            value: '1',
            label: 'A'
          }, {
            value: '2',
            label: 'B'
          }, {
            value: '3',
            label: 'C'
          }, {
            value: '4',
            label: 'D'
          }, {
            value: '5',
            label: 'E'
          }]
        }
      }];

return (
<div>Value

<BootstrapTable
  keyField="id"
  data={ stocks }
  columns={ columns }
  cellEdit={ cellEditFactory({ mode: 'click', blurToSave: true }) }
/>

</div>

);

}

}

**Comment by AllenFang** [comment]
I think your value and label is reverse, 

https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Dropdown%20Editor&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

**Comment by BharahthyKannan** [comment]
Hi Allen 
Sorry i couldnt get it, in above example if user selects E, i should get the value 5. but the dropdown label also changed to 5 , Kindly check

**Comment by vandz979** [comment]
I am seeing the same issue too! Is there a fix for it?

**Comment by rchaser** [comment]
@AllenFang I have the same issue, could you check it, please?

**Comment by hkar19** [comment]
you guys can check his solution about this [here](https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/1106#issuecomment-536256768).

the idea is you pass a formatter to the the column object's `formatter`, then find picked option and get the label.
