### ISSUE TITLE
Can we use multiple datFeilds in column header and data

### ISSUE THREAD

**Issue by Puneetbh** [react-bootstrap-table/react-bootstrap-table2#938]
Hi @AllenFang,
Can we add multiple dataFields in column header ad data as like mentioned in attached 
snapshot. Data part i can do  with formatting but how to mention 2 fields in header row. Please help

<img width="290" alt="Grid_header" src="https://user-images.githubusercontent.com/5443708/57297997-b3a56880-70ee-11e9-9f06-b860591b8d17.png">

**Comment by AllenFang** [comment]
@Puneetbh no, but you can custom column and header column, in the custom function, we will pass row object to you.

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnformatter-function

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnheaderformatter-function
