### ISSUE TITLE
react-bootstrap-table2-overlay old dependency

### ISSUE THREAD

**Issue by LucaNitti** [react-bootstrap-table/react-bootstrap-table2#940]
The last version of react-bootstrap-table2-overlay 1.0.0 has an old dependecy

 "dependencies": {
    "react-loading-overlay": "0.2.8"
  },

it's possibile to update it?

**Comment by AllenFang** [comment]
@LucaNitti  sure, I will update it ASAP, thanks

**Comment by AllenFang** [comment]
Fixed it and please upgrade below packages to newest:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/05/19/version-bump.html
