### ISSUE TITLE
Including Line Breaks in Headers

### ISSUE THREAD

**Issue by ALuongIBM** [react-bootstrap-table/react-bootstrap-table2#941]
Hi Allen,

When attempting to format the text in my headers, I have tried all the usual methods (\n, HTML break, etc.), but nothing seems to work. I cannot consistently get line breaks I need, and instead have to resort to guess and check on column sizing.

Am I missing something here? Do you know why the header columns ignore line break characters?

**Comment by AllenFang** [comment]
@ALuongIBM because the width of header cell is flexible, the only way you can do is

1. add the width on the specific `th`
2. give `overflow-wrap: break-word;` on that `th`

Let me know if the issue still remain, thanks

**Comment by ALuongIBM** [comment]
Thanks for the quick response!

**Comment by AllenFang** [comment]
@ALuongIBM sorry for lately reply, I think you already know where you should put the break line, the best way to do it so far will be [`column.headerFormatter`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnheaderformatter-function), use it to custom the header content
