### ISSUE TITLE
Expand only specific rows based on a condition

### ISSUE THREAD

**Issue by harikrishnanmurthy** [react-bootstrap-table/react-bootstrap-table2#942]
Hi Allen,

Currently, the expand row functionality seems to be all or one. I was wondering if there is a way we can expand only certain rows based on the values returned from the server for those rows? For instance,

        const expandRow = {
            showExpandColumn: true,
            expandByColumnOnly: false,
            renderer: row => (
                <div className="row-attachments">
                    <input type="checkbox" name={row.attachments} />
                </div>
            ),
        };

I would like to set either the "showExpandColumn" attribute to "false" if row.attachments.length==0 or be able to check if(row.attachments.length==0) within the renderer:row

How do I do this? Any advise would be of great help. Thanks a lot in advance for your time

**Comment by AllenFang** [comment]
@harikrishnanmurthy you an use `nonExpandable`:

[expandRow.nonExpandable](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrownonexpandable-array), [example](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Non%20Expandabled%20Rows&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by harikrishnanmurthy** [comment]
@AllenFang : I tried using nonExpandable but it doesn't seem to honor the attribute. Am still able to expand all rows. 

        const expandRow = {
            showExpandColumn: true,
            renderer: row => (
                <div className="row-attachments" id={"attachments" + row.id}>
                    <input type="checkbox" name={row.attachments} />
                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{row.attachments}</span>
                </div>
            ),
            onExpand: (row, isExpand, rowIndex, e) => {},
            expandByColumnOnly: true,
            nonExpandable: [1, 3 ,5]
        };

Is there an issue with the version of react bootstrap table that am using? Currently its
react-bootstrap-table : 4.3.1
react-bootstrap-table-next : 3.0.2

Please advise. I don't even want to think about using any other library since i feel react bootstrap table next is the best

**Comment by AllenFang** [comment]
@harikrishnanmurthy sorry for lately reply, would you please give me an online demo on codesandbox to reproduce your issue?

[this](https://codesandbox.io/s/k5750vzzvv) is an online example, just remember to change the version to the newest, thanks~

**Comment by majsterkoo** [comment]
Hi, I have similar problem.
I need showExpandColumn based on a condition. I'm returning react component or null (there is a condition) in renderer, and when returning null, I need showExpandColumn false, otherwise true. I need automatic showExpandColumn when renderer is null (empty). In example below, row data are from API and I dont know the data ahead, so I cannot know, whats ids will be nonExpandable... (yes, I can test it in useEffect, but variables from react function aren't in renderer callback function...).

Thanks for reply, sorry for my english :)

`const expandRow = {
        renderer: row => (
            (typeof row.subtable !== typeof undefined) ?
            <React.Fragment>
                <div class="table-offer-second-line"></div>
                <TableEdit
                    data={row.subtable.data}
                    columns={row.subtable.columns}
                />
            </React.Fragment>
            : null
        ),
        showExpandColumn: true,
    }`

**Comment by PalakRajput** [comment]
Hi,
 
Is there any way for expanding the rows based on particular condition. Also the nonExpandable prop is not working like after giving an array of row index in nonExpandable I am still able to expand those rows.

 const expandRow = {
                
                renderer: (row) => (
                    
                    <div>
                        <p>{`This row belongs to ${row.name}`}</p>
                    </div>
                ),
                nonExpandable:[1],
                showExpandColumn: true,
                onExpand:this.handleExpand,
                onlyOneExpanding:true
                
            };
After giving row index 1 in nonExpandable prop i am still able to expand that row.
