### ISSUE TITLE
Cell Editing:DropDown Editor with dynamic value

### ISSUE THREAD

**Issue by noeljoaquin30** [react-bootstrap-table/react-bootstrap-table2#945]
Is there a way to input dynamic values in drop down editor ? instead of below example.
 type: Type.SELECT,
                     options: [{
                      value: 'A',
                       label: 'A'
                     }, {
                      value: 'B',
                      label: 'B'
                      }, {
                      value: 'C',
                      label: 'C'
                     }]

Thank you.

**Comment by AllenFang** [comment]
@noeljoaquin30 so far we dont have this feature. I will consider to implement it in future.

**Comment by AllenFang** [comment]
hi, we already implement this feature, now you can use [`editor.getOption`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-celledit.html#editorgetoptions) to configure it and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Dropdown%20Editor%20with%20Dynamic%20Options&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is the online example

Please upgrade the relevant packages list in below:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/10/version-bump.html

**Comment by rikinshah23** [comment]
@noeljoaquin30 @AllenFang could you please help me with sample mapping of options for dynamic options? 

I dont have much idea on from where to bring options value and how to map here.
 ```
{
            dataField: 'role',
            text: 'Role',
            sort: true,
            editor: {
                type: Type.SELECT,
                getOptions: (setOptions, { row, column }) => {
                    console.log(setOptions)
                  
                }

            }
        },
```
