### ISSUE TITLE
Select row column position 

### ISSUE THREAD

**Issue by stilllife00** [react-bootstrap-table/react-bootstrap-table2#946]
Is it possible to move the selection column all the way on the right instead of the left?

EDIT: I see in `aggregate-row.js` that you do a `childrens.push` for the `expandColumnPosition` but not for the `select column`. 

Will it possible to add this feature ? If yes can you give an approximate timeframe?

**Comment by AllenFang** [comment]
@stilllife00  sorry for lately reply, I will be back to this project after my crazy busy hell. if everything ok, i think I can come back in the mid of Jun.

About your requirement, I think it's not pretty hard to implement, Hope I can implement it soon bit it's hard to give you a timeframe. sorry about this

**Comment by AllenFang** [comment]
hi, we already implement this feature, now you can use [`selectRow.selectColumnPosition`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowselectcolumnposition-string) to custom it and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Selection%20Column%20Position&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is the online example

Please upgrade the relevant packages list in below:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/10/version-bump.html
