### ISSUE TITLE
Style select row column

### ISSUE THREAD

**Issue by stilllife00** [react-bootstrap-table/react-bootstrap-table2#947]
There is the option `selectRow.headerColumnStyle` which styles the header of the select row.
But there is no option to style the select column (the select cell of each row).

This is useful when making the table scrollable via CSS with a fixed header: in this case we need **tbody display:block**, which causes the column to loose their alignment between head and body. So setting for example headerStyle: width XXX works for the header but the body column does not follow it resulting in something like this:

![image](https://user-images.githubusercontent.com/3191603/57917342-c52c0480-7894-11e9-81f1-1d1e319b2dbf.png)

An option like `selectRow.columnStyle` would help solving this

**Comment by AllenFang** [comment]
@stilllife00 understand, I will add it. thanks for this suggestion.

**Comment by AllenFang** [comment]
hi, we already implement this feature, now you can use [`selectRow.selectColumnStyle`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-select-props.html#selectrowselectcolumnstyle-object-function) to custom it and [here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Selection&selectedStory=Custom%20Selection%20Column%20Style&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is the online example

Please upgrade the relevant packages list in below:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/10/version-bump.html
