### ISSUE TITLE
Custom Expand Toggle?

### ISSUE THREAD

**Issue by abepark01** [react-bootstrap-table/react-bootstrap-table2#948]
Hello!

Is it possible to manually trigger the row expand on a row?
I do see that there is a `showExpandColumn` prop, but I was hoping to use a custom button that can expand the row when clicked upon.

For example, I have an edit button that should expand when clicked on.

![custom_toggle](https://user-images.githubusercontent.com/7087312/57947154-f86d9400-7892-11e9-91d5-5ed18f2a4211.png)

**Comment by AllenFang** [comment]
@abepark01 I think the best way to achieve it is use [`expandRow.expanded`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowexpanded-array)
