### ISSUE TITLE
Can not set background color for default selection

### ISSUE THREAD

**Issue by mpeng** [react-bootstrap-table/react-bootstrap-table2#950]
I want to set background color on  default selected rows, But it does not work. I can only set background color with click event. 

.i.e. In the example below,

when "**selected**" is used, then  "**bgColor**" does NOT work. Any idea how I can fix it and if there is a workaround ? Thanks

  selectRow = {
    mode: 'checkbox',
    clickToSelect: true,
    onSelect: this.handleOnSelect,
    hideSelectColumn: true,
    **//selected: this.state.selected,**  
    clickToExpand: true,
    **bgColor**: (row, rowIndex) => {
        return '#00BFFF';  // return a color code
    },
    clickToEdit: true  // Click to edit cell also
  };

**Comment by AllenFang** [comment]
@mpeng it's work for me, would you please give me more information. I think you can write a example online in the codesandbox so that i can reproduce it, thanks

**Comment by mpeng** [comment]
@AllenFang , It works for me too. I must miss something earlier. My bad. Thanks
