### ISSUE TITLE
Box Shadow on tr

### ISSUE THREAD

**Issue by ronaiza-cardoso** [react-bootstrap-table/react-bootstrap-table2#951]
There's a way of add box shadow to one tr? 

https://stackoverflow.com/questions/10874985/box-shadow-on-table-row-not-appearing-on-certain-browsers

**Comment by AllenFang** [comment]
i think you can use `rowClasses` or `rowStyle` . https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/table-props.html#rowclasses-string-function
