### ISSUE TITLE
Custom filter not cooperating with regular filters

### ISSUE THREAD

**Issue by hyvyys** [react-bootstrap-table/react-bootstrap-table2#952]
I implemented a custom filter function like this:

    priceFilter = (filterVals) =>
      this.books
        .filter(product => 
          ((filterVals.min && product.price >= filterVals.min) || !filterVals.min)
          &&
          ((filterVals.max && product.price <= filterVals.max) || !filterVals.max)
        );

The column object looks like this:

    { dataField: 'price', text: 'price',
      filter: customFilter({ onFilter: priceFilter }),
      filterRenderer: (onFilter, column) =>
        <PriceFilter onFilter={ onFilter } column={ column } />
    }

The filterRenderer:

    import React, { Component } from 'react';

    export default class PriceFilter extends Component {
      constructor(props) {
        super(props);
        this.filter = this.filter.bind(this);
        this.getValue = this.getValue.bind(this);
      }
      getValue() {
        return ({
            min: this.min.value,
            max: this.max.value
          });
      }
      handleClick(e) {
        e.stopPropagation();
      }
      filter() {
        this.props.onFilter(this.getValue());
      }
      render() {
        return <div className="price-filter"
                onClick={ this.handleClick }>
              <input
                key="min"
                ref={ node => this.min = node }
                type="number"
                onChange={ this.filter }
              />
              <input
                key="max"
                ref={ node => this.max = node }
                type="number"
                onChange={ this.filter }
              />
            </div>]
      }
    }

The defined filter appears to work on its own, but doesn't cooperate with other filters. Once the results are filtered with the custom filter, all other filters stop working, even after custom filter's inputs are cleared.

What am I doing wrong?

**Comment by hyvyys** [comment]
Should I use remote filter instead?

**Comment by hyvyys** [comment]
I solved my issue by duplicating the column as col_min and col_max, applying regular number filters to them, and calling them programmatically from onChange of inputs in a custom header of the original column that mimicks what filter looks like but has two fields with no dropdowns for comparators. To the original column I didn't add filters.

**Comment by AllenFang** [comment]
sorry for lately reply @hyvyys    I took a look on you code quickly, I think everything is ok.  if the issue still remain, please put your code in the codesandbox so that i can easy to reproduce it, thanks

**Comment by mdrahiem** [comment]
@hyvyys If you have any code, can you please paste here? I am unable to get the solution.

Otherwise, @AllenFang can you please provide codesandbox for this solution? Please let me know.

**Comment by mdrahiem** [comment]
Hi @AllenFang @hyvyys Finally i resolved it. :)

Please find the codesandbox for other peoples' reference.
https://codesandbox.io/s/determined-sky-dggkg

**Comment by hyvyys** [comment]
@mdrahiem Oh, I've just dusted off that old project and was starting to look into it. I was imprecise stating I *solved* the issue — I avoided it by hardcoding two separate regular filters, I think. Nvm.
