### ISSUE TITLE
tabindex on table headers should not be > 0

### ISSUE THREAD

**Issue by wparrott-touchnet** [react-bootstrap-table/react-bootstrap-table2#955]
Setting a tabindex greater than 0 for any element effectively takes it out of the tab order of the rest of the page and bumps it to the top. As a result, the change in a1457dfe5900bc6071d450ab58d60e1fa3bd8133 actually worsens the accessibility of tables rather than enhances it.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

**Comment by AllenFang** [comment]
oh sorry, it' probably my mistake and it should always be zero. I will enhance it soon

**Comment by wparrott-touchnet** [comment]
No worries. I know I've done the same thing before. I can submit a PR if that'll help.

**Comment by AllenFang** [comment]
hi, we already implement this issue. Please upgrade the relevant packages list in below:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/10/version-bump.html

**Comment by soetedja** [comment]
is there any way to remove the tabindex?

**Comment by chimericdream** [comment]
I don't know why you'd want to. The tabindex is there for accessibility purposes. What do you need to remove them for?

**Comment by soetedja** [comment]
I've text filter for each column. I'd like to move to the next filter by pressing Tab once. If the tabindex exist in the table header, it will needs to press Tab button twice..
