### ISSUE TITLE
Disable expandAll but allow individual row expand

### ISSUE THREAD

**Issue by MaxOrelus** [react-bootstrap-table/react-bootstrap-table2#956]
Hi,

I'm using the `expandRow` settings to show a expand column. I like the ability to expand individual rows, but I'm trying to completely disable the expandAll functionality in the column header. Is there a way to do this?

**Comment by AllenFang** [comment]
@MaxOrelus sorry for lately reply, and so far we don't support any toggle to turn off expand all function, but there's a tricky way to close it is via [`expandRow.expandHeaderColumnRenderer`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowexpandheadercolumnrenderer-function), and you can just return null to render nothing on expand column header.

**Comment by mrchess** [comment]
This solution sort of works. Returning null will, while returning no visible interactive UI (like no arrow to click), when you hover over the `<th>`, it still has a cursor, and clicking on it will still trigger an `expandAll`.

**Comment by lidaguang1989** [comment]
I use expandRow.expandHeaderColumnRenderer redener a div element, then stop the propagation. It is works well.
The code as below:
<div onClick={(e) => { e.stopPropagation() }}></div>

**Comment by roee69** [comment]
Hi another option that worked for me (@lidaguang1989's suggestion didn't work for me) is to set showExpandColumn as false (or remove it) which will remove the entire functionality of the collapse all and add the indication arrows with CSS.

**Comment by fffaria** [comment]
> Hi another option that worked for me (@lidaguang1989's suggestion didn't work for me) is to set showExpandColumn as false (or remove it) which will remove the entire functionality of the collapse all and add the indication arrows with CSS.

How did you add the indication arrows with CSS?

**Comment by sivabankapalli** [comment]
Can someone please help on how to disable the ExpandAll indicator in the functional component?

**Comment by sivabankapalli** [comment]
I tried with the below code and able to make it work:

expandHeaderColumnRenderer: (isAnyExpands) => (null )

Update the CSS:

.expand-cell-header  {
  pointer-events: none;
}

**Comment by lehelikes** [comment]
@my-work-sivabankapalli 
Update your code as @daniellidg commented:
```
const expandRow = {
   expandHeaderColumnRenderer: ({ isAnyExpands }) => (
      <div onClick={(e) => { e.stopPropagation() }}>Actions</div>`
    )
}
```

**Comment by Ryota201** [comment]
Hello, the same thing I ask, how can you add the arrows from the css?
