### ISSUE TITLE
Export CSV, opens as blob: instead of csv: on IPad's & IPhones

### ISSUE THREAD

**Issue by enf0rc3** [react-bootstrap-table/react-bootstrap-table2#957]
When exporting as CSV on IPads and IPhones the device treats the exported file as a blob text (big text string) instead of as a csv (nicely formatted table).

Example:
![react-bootstrap-table-blob](https://user-images.githubusercontent.com/751986/58393931-07272880-8095-11e9-90eb-37c79cfeb314.png)

This is because the exporter.js line 61 is exporting as the following:

`new Blob([content], { type: 'text/plain;charset=utf-8' }),`

Instead of:

`new Blob([content], { type: 'text/csv;charset=utf-8' }),`

I would propose either allowing over-riding of the blob's Type, or updating it from text/plain to text/csv since all of these files should be returned as csv.

**Comment by enf0rc3** [comment]
@AllenFang What are your thoughts on this??

I have added a PR, let me know if you need any changes.

**Comment by AllenFang** [comment]
@enf0rc3 sorry for lately reply and thanks for you PR and overall is good but I have some comment in your PR, please check

**Comment by AllenFang** [comment]
hi, we already implement this and please upgrade the relevant packages list in below:
https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/10/version-bump.html
