### ISSUE TITLE
How to trigger a table rerender after cell edit, not row select

### ISSUE THREAD

**Issue by morganldev6** [react-bootstrap-table/react-bootstrap-table2#960]
Thanks so much for this great library!

**Here is my issue:** 
I have a table that combines row selection, cell editing, and a custom footer function. The last column is a list of prices, with a footer function that gives the total sum of the values in that column. Each price is also editable. However, the footer does not update with the new total sum based on the edits until that row has been selected. It seems that row selection triggers a table rerender but cell editing alone does not. My question is, how do I trigger a rerender of the table (so that the footer will update) without having to select the row? 

**Some of my code:**
const columns = [
...
  {
    dataField: 'paymentAmt',
    text: 'Payment Amount',
    footer: footerFormatter,
  },
]

const footerFormatter = columnData =>
  columnData.length
    ? columnData.reduce((acc, item) => {
        return (parseInt(acc, 10) + parseInt(item, 10)).toFixed(2);
      })
    : `$0`;

const selectRow = {
    mode: 'checkbox',
    clickToSelect: false,
    clickToEdit: true,
    onSelect: handleOnSelect,
    onSelectAll: handleOnSelectAll,
  };

...

<BootstrapTable
          keyField="invoiceNum"
          data={invoices}
          columns={columns}
          selectRow={selectRow}
          striped
          hover
          condensed
          pagination={paginationFactory()}
          cellEdit={cellEditFactory({
            mode: 'click',
            blurToSave: true,
          })}
        />

Let me know if you have any questions, or need more details. Thanks!

**Comment by AllenFang** [comment]
@morganldev6 i think you can call `forceUpdate` in [`cellEdit.afterSaveCell`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/cell-edit-props.html#celleditaftersavecell-function)

**Comment by vzherebetskyi** [comment]
Another possible approach is to change the relevant keyfield of the `BootstrapTable`.
At our project every row has unique id which is passed to the BootstrapTable keyfield. Every row is editable, when the Edit button is clicked and we need to re-render the whole row to change cells to inputs the row's id is changed. This informs the bootstrap table the the row shall be rerendered
