### ISSUE TITLE
something wrong with ColumnToggle

### ISSUE THREAD

**Issue by jasonusdid** [react-bootstrap-table/react-bootstrap-table2#962]
Hi experts

Something wrong with the basic ColumnToggle, could you help to take a look please? Thanks a lot.
Put the code in codesandbox. 

https://codesandbox.io/s/reactbootstraptable2-662-b96hm

Thanks.

**Comment by jasonusdid** [comment]
Hi, @AllenFang , could you help to take a look please? Thanks a lot in advance.

**Comment by AllenFang** [comment]
@jasonusdid two thing you did wrong:

1. the prop on `ToolkitProvider` should be `columnToggle` instead of `ColumnToggle`

2. the props which render onto `ToggleList` should be `props.columnToggleProps` instead of `props.ColumnToggleProps`

**Comment by jasonusdid** [comment]
Hi @AllenFang , Thanks a lot. it works now.
