### ISSUE TITLE
implement edit/delete action within a menu of the row

### ISSUE THREAD

**Issue by ArouiniLobna** [react-bootstrap-table/react-bootstrap-table2#963]
Hello Every one,

I am trying to use material-table within my project, however i am stuck with few features that i need and not sure how to do that using this library.

basically i have rows with data, and in each row i got a menu that pop up edit/delete options. Curently they only show next to each other within action column.

Also, another feature i need is: in a cell, if i dont have data, i need to click a button which will allow to enter data in texterea and the menu with edit/delete will be hidden. if i enter some text, then the text will apear and the button will not show again. if the i enter nothing and enter, the button show back.

I attach design for refrence
![Capture](https://user-images.githubusercontent.com/29419606/58776292-4ca3a280-860d-11e9-9328-62bb1f92cb15.PNG)
![Capture1](https://user-images.githubusercontent.com/29419606/58776296-4f9e9300-860d-11e9-86a7-454605b454f8.PNG)

Thank you

**Comment by AllenFang** [comment]
@ArouiniLobna I think it's a irrelevant issue to `react-bootstrap-table2`
