### ISSUE TITLE
setState in expandRow.onExpand will break the row expand

### ISSUE THREAD

**Issue by carchan1** [react-bootstrap-table/react-bootstrap-table2#969]
First of all, thanks @AllenFang for your wonderful work! 🎉 

Would it be possible to apply the same fix as on `selectRow.onSelect` (https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/627) on `expandRow.onExpand`?

I would like to modify cells of an expanded row using `setState`. Actually, I would like to hide everything in the 'main' row so it doesn't repeat what would be in the expanded table.

### Currently: 
![image](https://user-images.githubusercontent.com/28656858/59042868-34b86280-8849-11e9-94a9-32ca0ccc11d0.png)

### What I would like:
![image](https://user-images.githubusercontent.com/28656858/59042938-5580b800-8849-11e9-8f2e-2907780ebb17.png)

**Comment by carchan1** [comment]
Other question:
Is it possible for my filter to also search inside the expanded table?

**Comment by AllenFang** [comment]
hello @carchan1 sorry for lately reply.  I will try to implement this function but so far too many thing I need to do for this project, so there's a workaround is you can still call `setState` to do whatever you want but you need to manage the expand state as well:

[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Expand%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example to show how to manage the expand state.

In your case, you just need to follow above solution but just add more state change for the target row when `onExpand` being called.

**Comment by carchan1** [comment]
It works, thanks @AllenFang

**Comment by AllenFang** [comment]
👍

**Comment by kgrech** [comment]
@AllenFang  It would be very nice if we can have it fixed
