### ISSUE TITLE
lastPageTitle not working, taking value of firsPageTitle

### ISSUE THREAD

**Issue by shhdharmen** [react-bootstrap-table/react-bootstrap-table2#970]
- Description: When we give blank space values to both pagination optios: `firstPageText` and `lastPageText`. `lastPageTitle` takes same value as `firstPageTitle`.

- Example code or repo: https://stackblitz.com/edit/react-v85cxp?file=Hello.js
- Steps to reproduce: Set `firstPageText` and `lastPageText` as blank space, `lastPageTitle` will take same value of `firstPageTitle`
- `react-bootstrap-table2` version: 3.1.3

**Comment by shhdharmen** [comment]
Maybe I have found the reason behind this issue, but not sure how to fix:

https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/60eb47dc9e965854c5a3e50297a7928451f43c37/packages/react-bootstrap-table2-paginator/src/page-resolver.js#L141-L145

So, in above code, for both `firstPageText` and `lastPageText`, it will match conditon of [L141](https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/60eb47dc9e965854c5a3e50297a7928451f43c37/packages/react-bootstrap-table2-paginator/src/page-resolver.js#L141) and it will show `firstPageTitle`.

**Comment by AllenFang** [comment]
hmm..  yeah this is an edge case but can I know why you set the blank text for both of first & last page button?

**Comment by shhdharmen** [comment]
I am trying to set a background image for both through css and don't want any content in it. Anyways, it worked when gave: `<span />` instead of blank space. I am closing it.

**Comment by AllenFang** [comment]
👍

**Comment by shhdharmen** [comment]
Sorry, but if we use jsx element instead of string, it gives compile time errors.

```
Warning: Failed prop type: Invalid prop `firstPageText` of type `object` supplied to `Pagination`, expected `string`.
in Pagination (created by PaginationHandler)
in PaginationHandler (created by PaginationDataProvider)
in PaginationDataProvider (created by Context.Consumer)
in DataProvider (created by BootstrapTableContainer)
in BootstrapTableContainer
in Unknown (created by App)
in div (created by App)
in App
```

Example: https://stackblitz.com/edit/react-wjhzky?file=Hello.js

**Comment by AllenFang** [comment]
Hello @shhdharmen, so far the `firstPageText` only accept a string for customization. I will allow it to accept jsx in next version, thanks

**Comment by AllenFang** [comment]
@shhdharmen hello, this issue was fixed, please upgrade packages to newest version which listed in below:

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/25/version-bump.html

**Comment by shhdharmen** [comment]
Thanks for the updates, but now it's showing a different error. Example at : https://stackblitz.com/edit/react-wjhzky?file=Hello.js

![Screenshot 2019-07-08 at 12 33 58 PM](https://user-images.githubusercontent.com/6831283/60789542-fcc07a00-a17c-11e9-9c75-aa3401da0d2e.png)
