### ISSUE TITLE
MultiSelectFilter breaking IE11

### ISSUE THREAD

**Issue by amirafzali** [react-bootstrap-table/react-bootstrap-table2#971]
Hi,

I'm building an app and need to support IE11. When using multiselectfilters, all browsers render fine except for IE. 
At first I noticed this on my app, but the issue persists on the storyboard example   
(https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Column%20Filter&selectedStory=MultiSelect%20Filter&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)  

`▶error: ["Invalid calling object", "https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/static/preview.8c445459b507f37c44ea.bundle.js", 1, 439788, TypeError]  
▶error: ["Exception thrown and not caught", "https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/static/preview.8c445459b507f37c44ea.bundle.js", 1, 462159, TypeError]  
▶error: [TypeError]
`    

My app yields this error when trying to load the page  

`SCRIPT5022: Exception thrown and not caught
File: bundle.js, Line: 2463, Column: 24`

`The above error occurred in the <MultiSelectFilter> component:
    in MultiSelectFilter (created by HeaderCell)
    in th (created by HeaderCell)
    in HeaderCell (created by Header)
    in tr (created by Header)
    in thead (created by Header)
    in Header (created by BootstrapTable)
    in table (created by BootstrapTable)
    in div (created by BootstrapTable)
    in BootstrapTable (created by Context.Consumer)
    in ColumnManagementProvider (created by Context.Consumer)
    in SelectionProvider (created by Context.Consumer)
    in RowExpandProvider (created by Context.Consumer)
    in PaginationDataProvider (created by Context.Consumer)
    in SortProvider (created by Context.Consumer)
    in FilterProvider (created by Context.Consumer)
    in DataProvider (created by BootstrapTableContainer)
    in BootstrapTableContainer (created by ScopeSelectPage)
    in div (created by ScopeSelectPage)
    in div (created by ScopeSelectPage)
    in ScopeSelectPage (created by App)
    in div (created by App)
    `  

Would appreciate some help. Thanks.

**Comment by AllenFang** [comment]
@amirafzali sorry for lately reply, i will fix it soon

**Comment by AllenFang** [comment]
hello, this issue was fixed, please upgrade packages to newest version which listed in below:

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/25/version-bump.html
