### ISSUE TITLE
Cell Editing(Dropdown): TypeError when using getOptions

### ISSUE THREAD

**Issue by Devkutt** [react-bootstrap-table/react-bootstrap-table2#977]
### Version
- react-bootstrap-table-next: 3.1.4
- react-bootstrap-table2-editor: 1.2.4
### Description
I used the Dropdown editor for cell editing with its `options` props and it worked fine. After that I wanted to use `getOptions` instead, but got the following error:
```
TypeError: options is undefined
    render dropdown-editor.js:148
```
### Code
After getting the error, I tried to use the example from [the docs](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Cell%20Editing&selectedStory=Dropdown%20Editor%20with%20Dynamic%20Options&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel), but it throws the same error.
```
import React from 'react';
import BootstrapTable from 'react-bootstrap-table-next';
import cellEditFactory, { Type } from 'react-bootstrap-table2-editor';

const jobs = [
    {
        id: 'a',
        name: 'name',
        owner: 'owner',
        type: 'A'
    },
    {
        id: 'b',
        name: 'name',
        owner: 'owner',
        type: 'B'
    },
    {
        id: 'c',
        name: 'name',
        owner: 'owner',
        type: 'C'
    }
];

const columns = [{
  dataField: 'id',
  text: 'Job ID'
}, {
  dataField: 'name',
  text: 'Job Name'
}, {
  dataField: 'owner',
  text: 'Job Owner'
}, {
  dataField: 'type',
  text: 'Job Type1',
  editor: {
    type: Type.SELECT,
    getOptions: () => [{
      value: 'A',
      label: 'A'
    }, {
      value: 'B',
      label: 'B'
    }, {
      value: 'C',
      label: 'C'
    }, {
      value: 'D',
      label: 'D'
    }, {
      value: 'E',
      label: 'E'
    }]
  }
}];

export const Testtable = (props: any) => 
<BootstrapTable
  keyField="id"
  data={ jobs }
  columns={ columns }
  cellEdit={ cellEditFactory({ mode: 'click', blurToSave: true }) }
/>;
```

**Comment by AllenFang** [comment]
@Devkutt sorry for lately reply, I can not reproduce your issue, are u sure your dependencies is newest(`react-bootstrap-table-next` and `react-bootstrap-table2-editor`)?.    

If dependencies is newest absolutely, please give me an online example via codesandbox.io so that i can reproduce it.

**Comment by Devkutt** [comment]
@AllenFang I cannot reproduce it online either. After I updated all my dependencies, the error is gone.
But I was on the newest version of both `react-bootstrap-table-next` and `react-bootstrap-table2-editor`, so I guess an older version of one of my other dependencies caused the malfunction.
