### ISSUE TITLE
Column formatter seems to conflict with expandRow.

### ISSUE THREAD

**Issue by zylin1206** [react-bootstrap-table/react-bootstrap-table2#979]
**Version**
react-bootstrap-table-next: 3.1.4

**Description**
I have a column contain a button that will show if the row hovers. To achieve that, I use `rowEvents` to catch the event and `setState` to update the cell through `formatter` (I use `formatExtraData` to pass extra data). It works fine when my table doesn't have `expandRow`.
When I add `expandRow` to my table, the function of `formatter` is just called once time on the page loaded and doesn't update at `setState`.

**Code**
https://repl.it/@zylin1206/React-table

So sorry for my bad English 😅

**Comment by AllenFang** [comment]
@zylin1206 your english is good. I think it might be a bug, I will look into on this, thanks

**Comment by AllenFang** [comment]
similar issue with https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/719

**Comment by goosemondude** [comment]
**Description**
I too am seeing this issue. For me formatExtraData has state information that I pass it in the parent row. It works as expected without expandRow. With the expandRow attribute in use however it seems that state updates don't pass through the formatExtraData property any longer.

**Version** 3.1.4 and 3.1.3 for me.

**Comment by AllenFang** [comment]
hello, this issue was fixed, please upgrade packages to newest version which listed in below:

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/25/version-bump.html

**Comment by goosemondude** [comment]
Thanks so much - you rock!
