### ISSUE TITLE
Using columnClasses causes the page to crash on Internet Explorer 11

### ISSUE THREAD

**Issue by dparasam** [react-bootstrap-table/react-bootstrap-table2#980]
Version: 
react-bootstrap-table-next@3.1.4
Internet Explorer: 11.1884.14393.0

Description:
If I use columnClasses, the table does not render on Internet Explorer.  The error I see is:
> TypeError: Object doesn't support property or method 'includes'
> {
>       [functions]: ,
>       __proto__: { },
>       description: "Object doesn't support property or method 'includes'",
>       message: "Object doesn't support property or method 'includes'",
>       name: "TypeError",
>       number: -2146827850,
>       stack: "TypeError: Object doesn't support property or method 'includes'
>       <-- snip -->
> }

The columnClasses value is set to a function that looks like:
```
columnClasses(cell, row, rowIndex, colIndex) {
    return colIndex === 0 ? 'style1' : 'style2'
}
```

**Comment by AllenFang** [comment]
hello, this issue was fixed, please upgrade packages to newest version which listed in below:

https://react-bootstrap-table.github.io/react-bootstrap-table2/blog/2019/06/25/version-bump.html

**Comment by deepakpn** [comment]
Thank you.

**Comment by dparasam** [comment]
Thank you.
