### ISSUE TITLE
selectColumnStyle is not applied on the header if hideSelectAll: true

### ISSUE THREAD

**Issue by stilllife00** [react-bootstrap-table/react-bootstrap-table2#982]
As per title `selectColumnStyle` is not applied if `selectColumnPosition: 'right'`

**Comment by AllenFang** [comment]
@stilllife00 it work for me:

```js
const selectRow = {
  mode: 'checkbox',
  clickToSelect: true,
  selectColumnPosition: 'right',
  selectColumnStyle: { backgroundColor: '#c8e6c9' }
};
```

any idea?

**Comment by stilllife00** [comment]
Maybe it was not because of the right but because of the "hideSelectAll"? i cannot try right now but if you want to try that meanwhile

**Comment by AllenFang** [comment]
@stilllife00 sorry for lately reply, I am still confusing with this issue, can you just show your `selectRow` config and provide more information?  thanks

**Comment by stilllife00** [comment]
Sorry, I can clarify, the problem is with 'hideSelectAll' AND column style:

If I set:

```
hideSelectAll: true,
selectColumnStyle: {
    width: '3rem',
}
```
the select cell on the rows will get width 3rem BUT NOT THE HEADER (the header stays width 'auto') creating a misalignment between the rows and the header

**Comment by AllenFang** [comment]
@stilllife00 try to apply the width on `headerColumnStyle` as well. so far `selectColumnStyle` is for non header cell and `headerColumnStyle` is for header only.

**Comment by stilllife00** [comment]
@AllenFang setting `headerColumnStyle` does not solve the problem.
The thing is `hideSelectAll: true` is emptying the first `td` of the header and so the styling rules are lost as well. 

And there is no workaround I can see for that because the CSS does not know about the `hideSelectAll`. 

The only workaround is to pass a custom CSS class to the table, but then `hideSelectAll` becomes useless. 

Can this be considered a bug? The headerStyle should be retained even if `hideSelectAll: true`
