### ISSUE TITLE
Expanded Row - How can I remove expand all functionality from header but I need in individual row 

### ISSUE THREAD

**Issue by somilkhandelwalwork** [react-bootstrap-table/react-bootstrap-table2#983]
I am doing something like below
`const expandRow = {
  renderer: row => (
    <div>
      <p>{ `This Expand row is belong to rowKey ${row.id}` }</p>
      <p>You can render anything here, also you can add additional data on every row object</p>
      <p>expandRow.renderer callback will pass the origin row object to you</p>
    </div>
  ),
showExpandColumn: true,
  expandByColumnOnly: true,
  onlyOneExpanding: true,
};`
Now my concern is how to remove the expand all functionality in header 

Screenshot -> 
![image](https://user-images.githubusercontent.com/40453353/59877762-4b6fc500-93c4-11e9-9a84-9bb613912a6f.png)

**Comment by AllenFang** [comment]
@somilkhandelwalwork so for we don't have a toggle props for hiding the expand all indicator, but there's a workaround is via [`expandRow.expandHeaderColumnRenderer`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowexpandheadercolumnrenderer-function) and you can just return null as render nothing

**Comment by somilkhandelwalwork** [comment]
@AllenFang , if I return null, nothing will render but it still has the toggle functionality.

**Comment by anicache08** [comment]
Hi, any updates on this one?

**Comment by somilkhandelwal** [comment]
@anicache08 , no updates on the same.

**Comment by roee69** [comment]
Hi another around that works is to set showExpandColumn as false (or remove it) which will remove the collapse column and the functionality of the "collapse all" with it and then add the indication arrows with CSS.

**Comment by sivabankapalli** [comment]
I tried with the below code and able to make it work:

expandHeaderColumnRenderer: (isAnyExpands) => (null )

Update the CSS:

.expand-cell-header {
pointer-events: none;
}

**Comment by Ryota201** [comment]
hello, how can you add the arrows with css in this library to disable the showExpandColumn or just by chance is there any solution currently to remove the expansion of all header functions?
