### ISSUE TITLE
Question: Exact Match Text Filter

### ISSUE THREAD

**Issue by oscarreyes98** [react-bootstrap-table/react-bootstrap-table2#984]
Is it possible to have a text filter for a table header column that filters only by an exact match.

So for example when filtering a column by "MALE", only "MALE" entries would appear, instead of both "MALE" and "FEMALE" (since "MALE" is a sub-string) ?

If not, are there any workarounds?

Thanks!

**Comment by fahmidamostafa** [comment]
@oscarreyes98 did you find a solution to this?

**Comment by oscarreyes98** [comment]
I did. I simply set the condition to 'eq':

`filter={ { type: 'SelectFilter', condition: 'eq' } }`

**Comment by mendismenon** [comment]
Do you have a sample code? If yes, please share. I am struggling to find a fix for that.

**Comment by fahmidamostafaml** [comment]
Simply like this:

```
<TableHeaderColumn
   filter={{
      type: 'SelectFilter',
      condition: 'eq'
}} />
```
