### ISSUE TITLE
is there a way to hide the next and prev icons

### ISSUE THREAD

**Issue by shorif2000** [react-bootstrap-table/react-bootstrap-table2#988]
i want to hide the next/prev icons in pagination. i can only find how to modify text but no hide/show icons.

my codebase is here https://codesandbox.io/s/plentific-uo68b?eslint=1&fontsize=14

table component is under componenets/table

What i want to do is show the go to 1st and got to last but hide next/prev

**Comment by AllenFang** [comment]
sorry for lately reply and so far we don't provide any solution to hide next and prev button always. However, i check your code and I see you already hide the next and prev button
