### ISSUE TITLE
import BootstrapTable from 'react-bootstrap-table-next' doesnt work

### ISSUE THREAD

**Issue by lilrinchi** [react-bootstrap-table/react-bootstrap-table2#989]
For some reason when I try to import the react-bootstrap-table-next it doesnt work

https://imgur.com/a/eSenDcA

import BootstrapTable from 'react-bootstrap-table-next';

module "/home/rin/sc-deal/client/node_modules/react-bootstrap-table-next/lib/index"
Could not find a declaration file for module 'react-bootstrap-table-next'. '/home/rin/sc-deal/client/node_modules/react-bootstrap-table-next/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-bootstrap-table-next` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-bootstrap-table-next';`ts(7016)

When I try the fix they suggested:

root@ubuntu:/home/rin/sc-deal/client# npm install @types/react-bootstrap-table-next
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-bootstrap-table-next - Not found
npm ERR! 404 
npm ERR! 404  '@types/react-bootstrap-table-next@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-24T12_58_36_545Z-debug.log

**Comment by amirafzali** [comment]
I'm assuming you're using typescript.
The problem might be that there are no type definitions for this package. When you attempt the recommended fix, it tells you that DefinitelyTyped does not have an existing module for this package. In this case you can declare your own typings, or create a module.

More information can be found here:
 https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam

**Comment by AllenFang** [comment]
@amirafzali is correct, I didn't provide the type offical

**Comment by chancesmith** [comment]
Anybody have any types to share to get rolling?

**Comment by chancesmith** [comment]
This helped: https://github.com/react-bootstrap-table/react-bootstrap-table2/issues/384
