### ISSUE TITLE
Migration problem - Table crash - Objects are not valid as a React child

### ISSUE THREAD

**Issue by lilrinchi** [react-bootstrap-table/react-bootstrap-table2#990]
So I'm migrating from react-bootstrap-table to react-bootstrap-table2 and now my code which was working before doesnt work when I try to import certain data into my table. I will provide pictures.

So it works when I get these values marked red:
https://i.imgur.com/kHsCGGo.png

It doesnt work when I attempt to import data marked in blue.

I get error:

Objects are not valid as a React child (found: object with keys {_hex}). If you meant to render a collection of children, use an array instead.

My code:

```
    const columns = [{
      dataField: 'buyerAddr', // with this works normally
      text: 'Product ID'
    },
    {
      dataField: 'invoiceNumber', //with this it crashes
      text: 'Product ID'
    }];   

     <BootstrapTable
          keyField='id'
          data={ this.state.invoices }
          columns={ columns }
        />
```

It crashes here:
```
  addEventListenerInvoiceSent(component) {

    this.state.contractInstance.events.InvoiceSent({fromBlock: 0, toBlock: 'latest'})
    .on('data', async function(event){

      var epochValue = event.returnValues.dateOfInvoice;      
      var d = new Date(epochValue * 1000); // The 0 there is the key, which sets the date to the epoch
      event.returnValues.dateOfInvoice = d.toDateString();   
      
      var newInvoicesArray = component.state.invoices.slice();
      newInvoicesArray.push(event.returnValues)
      newInvoicesArray.sort(function(a,b){
        return parseInt(a.invoiceNumber)  - parseInt(b.invoiceNumber);
       })
      component.setState({ invoices: newInvoicesArray })
    })
    .on('error', console.error);
  }
```

I have to mention that this same code worked normally with react-bootstrap-table

**Comment by AllenFang** [comment]
@lilrinchi I think you probably encounter react version issue, in `react-bootstrap-table2`, we need `react@16.3.0` https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/master/packages/react-bootstrap-table2/package.json#L46
