### ISSUE TITLE
Renderer method in expandRow always render new instance when parent table is update.

### ISSUE THREAD

**Issue by mhnpd** [react-bootstrap-table/react-bootstrap-table2#992]
` const expandRow = {
  renderer: rows => <NetworkGroupDeviceTable key={rows.id} {...rows} />,
  showExpandColumn: true,
  expanded: [0]
};  `

In the above code NetworkGroupDeviceTable component checkbox get reset if any change occur in parent table due to ` renderer: ()=>{}` as render method which return new instance every time. Any solution?

**Comment by mhnpd** [comment]
```
const expandRow = {
  renderer: rows => <NetworkGroupDeviceTable key={rows.id} {...rows} />,
  showExpandColumn: true,
  expanded: [0]
};
```
In the above code NetworkGroupDeviceTable component checkbox get reset if any change occur in parent table due to ()=>{} as render method which return new instance every time. Any solution?

**Comment by AllenFang** [comment]
@mhnpd if you want to keep the current expand state whenever parent component rerender, you should manage the expand state via [`expandRow.expanded`](https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/row-expand-props.html#expandrowexpanded-array)

[here](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Row%20Expand&selectedStory=Expand%20Management&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an online example, though this case is not same as yours, but it just show you a most simple case to manage expand state.
