### ISSUE TITLE
Edit many cells

### ISSUE THREAD

**Issue by lgangas88** [react-bootstrap-table/react-bootstrap-table2#996]
Hello, when I want to edit one cell I'd like to many cells from different rows also change.
I edit the data in cascade (which I use to fill table) on beforeSaveCell and when component renders, only renders the data of one row, the row from the cell I've edited.

beforeSaveCellRangeMaxMin = (oldValue, newValue, row, data) => {
    const nextRow = data[row.indexRow + 1]
    if (nextRow) {
      nextRow.rangeMin = newValue
      data[row.indexRow + 1] = nextRow
      changeMinRowAction([...data])
    }
  }

  render() {
    const { columns, data } = this.props.listSpreads
    return (
      <div className='parent-table'>
        {
          !this.props.listSpreads.empty &&
          <BootstrapTable
            bordered={true}
            bootstrap4={true}
            keyField='id'
            data={data}
            columns={columns}
            tabIndexCell={true}
            cellEdit={cellEditFactory({
              mode: 'click', blurToSave: true, autoSelectText: true,
              beforeSaveCell(oldValue, newValue, row, column) {
                switch (column.indexCol) {
                  case 1:
                    this.beforeSaveCellRangeMaxMin(oldValue, newValue, row, data)
                    break;
                  default:
                }
              },
            })}
          />
        }
      </div>
    )
  }

**Comment by AllenFang** [comment]
@lgangas88 I think your solution can not work. so far I can not find a good workaround for this and we didn't support this feature as well. In my opinion, I will suggest you to enable `remote` mode for `cellEdit` only

https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/basic-remote.html

[this](https://react-bootstrap-table.github.io/react-bootstrap-table2/storybook/index.html?selectedKind=Remote&selectedStory=Remote%20Cell%20Editing&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) is an example to show how to implement a remote cell editing.

In you case, I think you dont need to call any backend api to update data, you just handle any data source change in `handleTableChange` function.
